### ISSUE TITLE
LoadDatasource DataSourceException: Missing connection name in relation

### ISSUE THREAD

**Issue by yefanjiang** [tableau/connector-plugin-sdk#1004]
**About You:**
Name: yefan
Company: Alibaba

**Your question:**
when I run "python3 -m tdvt.tdvt --run tdvt_test --generate", I failed all tests.
And I check the log "test_result_combined.csv", the part of log is like this:
''
Suite,Test Set,TDSName,TestName,TestPath,Passed,Closest Expected,Diff count,Test Case,Test Type,Process Output,Error Msg,Error Type,Query Time (ms),Generated SQL,Actual (100)tuples,Expected (100)tuples
tdvt_test,logical.calcs.tdvt_test,cast_calcs.tdvt_test,BUGS.B1713,/Users/jyf/Library/Python/3.8/lib/python/site-packages/tdvt/logicaltests/setup/calcs/setup.BUGS.B1713.tdvt_test_logical.xml,False,,,,logical,,"LoadDatasource DataSourceException: Missing connection name in relation

No data source specified
","LoadDatasource DataSourceException: Missing connection name in relation

No data source specified
",,,,
tdvt_test,logical.calcs.tdvt_test,cast_calcs.tdvt_test,BUGS.B26728,/Users/jyf/Library/Python/3.8/lib/python/site-packages/tdvt/logicaltests/setup/calcs/setup.BUGS.B26728.tdvt_test_logical.xml,False,,,,logical,,Error.,Error.,,,,
tdvt_test,logical.calcs.tdvt_test,cast_calcs.tdvt_test,BUGS.B27875-asc-nulls-first,/Users/jyf/Library/Python/3.8/lib/python/site-packages/tdvt/logicaltests/setup/calcs/setup.BUGS.B27875-asc-nulls-first.tdvt_test_logical.xml,False,,,,logical,,Error.,Error.,,,,
tdvt_test,logical.calcs.tdvt_test,cast_calcs.tdvt_test,BUGS.B27875-desc-nulls-last,/Users/jyf/Library/Python/3.8/lib/python/site-packages/tdvt/logicaltests/setup/calcs/setup.BUGS.B27875-desc-nulls-last.tdvt_test_logical.xml,False,,,,logical,,Error.,Error.,,,,
tdvt_test,logical.calcs.tdvt_test,cast_calcs.tdvt_test,BUGS.B59740,/Users/jyf/Library/Python/3.8/lib/python/site-packages/tdvt/logicaltests/setup/calcs/setup.BUGS.B59740.tdvt_test_logical.xml,False,,,,logical,,Error.,Error.,,,,
tdvt_test,logical.calcs.tdvt_test,cast_calcs.tdvt_test,BUGS.B641638,/Users/jyf/Library/Python/3.8/lib/python/site-packages/tdvt/logicaltests/setup/calcs/setup.BUGS.B641638.tdvt_test_logical.xml,False,,,,logical,,Error.,Error.,,,,
tdvt_test,logical.calcs.tdvt_test,cast_calcs.tdvt_test,BUGS.TFS660780,/Users/jyf/Library/Python/3.8/lib/python/site-packages/tdvt/logicaltests/setup/calcs/setup.BUGS.TFS660780.tdvt_test_logical.xml,False,,,,logical,,Error.,Error.,,,,
tdvt_test,logical.calcs.tdvt_test,cast_calcs.tdvt_test,Filter.Date_In,/Users/jyf/Library/Python/3.8/lib/python/site-packages/tdvt/logicaltests/setup/calcs/setup.Filter.Date_In.tdvt_test_logical.xml,False,,,,logical,,Error.,Error.,,,,
tdvt_test,logical.calcs.tdvt_test,cast_calcs.tdvt_test,Filter.Exclude-list-not-null,/Users/jyf/Library/Python/3.8/lib/python/site-packages/tdvt/logicaltests/setup/calcs/setup.Filter.Exclude-list-not-null.tdvt_test_logical.xml,False,,,,logical,,Error.,Error.,,,,
tdvt_test,logical.calcs.tdvt_test,cast_calcs.tdvt_test,Filter.Exclude-range-not-null,/Users/jyf/Library/Python/3.8/lib/python/site-packages/tdvt/logicaltests/setup/calcs/setup.Filter.Exclude-range-not-null.tdvt_test_logical.xml,False,,,,logical,,Error.,Error.,,,,
tdvt_test,logical.calcs.tdvt_test,cast_calcs.tdvt_test,Filter.FilterBy-to-no-results,/Users/jyf/Library/Python/3.8/lib/python/site-packages/tdvt/logicaltests/setup/calcs/setup.Filter.FilterBy-to-no-results.tdvt_test_logical.xml,False,,,,logical,,Error.,Error.,,,,
tdvt_test,logical.calcs.tdvt_test,cast_calcs.tdvt_test,Filter.QFilter-NotNull,/Users/jyf/Library/Python/3.8/lib/python/site-packages/tdvt/logicaltests/setup/calcs/setup.Filter.QFilter-NotNull.tdvt_test_logical.xml,False,,,,logical,,Error.,Error.,,,,
tdvt_test,logical.calcs.tdvt_test,cast_calcs.tdvt_test,Filter.QFilter-Null,/Users/jyf/Library/Python/3.8/lib/python/site-packages/tdvt/logicaltests/setup/calcs/setup.Filter.QFilter-Null.tdvt_test_logical.xml,False,,,,logical,,Error.,Error.,,,,
tdvt_test,logical.calcs.tdvt_test,cast_calcs.tdvt_test,Filter.QFilter-max-NotNull,/Users/jyf/Library/Python/3.8/lib/python/site-packages/tdvt/logicaltests/setup/calcs/setup.Filter.QFilter-max-NotNull.tdvt_test_logical.xml,False,,,,logical,,Error.,Error.,,,,
tdvt_test,logical.calcs.tdvt_test,cast_calcs.tdvt_test,Filter.QFilter-max-Null,/Users/jyf/Library/Python/3.8/lib/python/site-packages/tdvt/logicaltests/setup/calcs/setup.Filter.QFilter-max-Null.tdvt_test_logical.xml,False,,,,logical,,Error.,Error.,,,,
tdvt_test,logical.calcs.tdvt_test,cast_calcs.tdvt_test,Filter.QFilter-min-NotNull,/Users/jyf/Library/Python/3.8/lib/python/site-packages/tdvt/logicaltests/setup/calcs/setup.Filter.QFilter-min-NotNull.tdvt_test_logical.xml,False,,,,logical,,Error.,Error.,,,,
tdvt_test,logical.calcs.tdvt_test,cast_calcs.tdvt_test,Filter.QFilter-min-Null,/Users/jyf/Library/Python/3.8/lib/python/site-packages/tdvt/logicaltests/setup/calcs/setup.Filter.QFilter-min-Null.tdvt_test_logical.xml,False,,,,logical,,Error.,Error.,,,,
tdvt_test,logical.calcs.tdvt_test,cast_calcs.tdvt_test,Filter.QFilter-minmax-NotNull,/Users/jyf/Library/Python/3.8/lib/python/site-packages/tdvt/logicaltests/setup/calcs/setup.Filter.QFilter-minmax-NotNull.tdvt_test_logical.xml,False,,,,logical,,Error.,Error.,,,,
tdvt_test,logical.calcs.tdvt_test,cast_calcs.tdvt_test,Filter.QFilter-minmax-Null,/Users/jyf/Library/Python/3.8/lib/python/site-packages/tdvt/logicaltests/setup/calcs/setup.Filter.QFilter-minmax-Null.tdvt_test_logical.xml,False,,,,logical,,Error.,Error.,,,,
tdvt_test,logical.calcs.tdvt_test,cast_calcs.tdvt_test,Filter.TopN-context,/Users/jyf/Library/Python/3.8/lib/python/site-packages/tdvt/logicaltests/setup/calcs/setup.Filter.TopN-context.tdvt_test_logical.xml,False,,,,logical,,Error.,Error.,,,,
tdvt_test,logical.calcs.tdvt_test,cast_calcs.tdvt_test,Filter.datetime_fractional,/Users/jyf/Library/Python/3.8/lib/python/site-packages/tdvt/logicaltests/setup/calcs/setup.Filter.datetime_fractional.tdvt_test_logical.xml,False,,,,logical,,Error.,Error.,,,,
tdvt_test,logical.calcs.tdvt_test,cast_calcs.tdvt_test,Query.Filter.IsNOTNULL,/Users/jyf/Library/Python/3.8/lib/python/site-packages/tdvt/logicaltests/setup/calcs/setup.Query.Filter.IsNOTNULL.tdvt_test_logical.xml,False,,,,logical,,Error.,Error.,,,,
tdvt_test,logical.calcs.tdvt_test,cast_calcs.tdvt_test,Query.Filter.IsNULL,/Users/jyf/Library/Python/3.8/lib/python/site-packages/tdvt/logicaltests/setup/calcs/setup.Query.Filter.IsNULL.tdvt_test_logical.xml,False,,,,logical,,Error.,Error.,,,,
tdvt_test,logical.calcs.tdvt_test,cast_calcs.tdvt_test,Query.Filter.NullAndOne,/Users/jyf/Library/Python/3.8/lib/python/site-packages/tdvt/logicaltests/setup/calcs/setup.Query.Filter.NullAndOne.tdvt_test_logical.xml,False,,,,logical,,Error.,Error.,,,,
tdvt_test,logical.calcs.tdvt_test,cast_calcs.tdvt_test,join.null.bool,/Users/jyf/Library/Python/3.8/lib/python/site-packages/tdvt/logicaltests/setup/calcs/setup.join.null.bool.tdvt_test_logical.xml,False,,,,logical,,Error.,Error.,,,,
tdvt_test,logical.calcs.tdvt_test,cast_calcs.tdvt_test,join.null.date,/Users/jyf/Library/Python/3.8/lib/python/site-packages/tdvt/logicaltests/setup/calcs/setup.join.null.date.tdvt_test_logical.xml,False,,,,logical,,Error.,Error.,,,,
tdvt_test,logical.calcs.tdvt_test,cast_calcs.tdvt_test,join.null.datetime,/Users/jyf/Library/Python/3.8/lib/python/site-packages/tdvt/logicaltests/setup/calcs/setup.join.null.datetime.tdvt_test_logical.xml,False,,,,logical,,Error.,Error.,,,,
tdvt_test,logical.calcs.tdvt_test,cast_calcs.tdvt_test,join.null.int,/Users/jyf/Library/Python/3.8/lib/python/site-packages/tdvt/logicaltests/setup/calcs/setup.join.null.int.tdvt_test_logical.xml,False,,,,logical,,Error.,Error.,,,,
tdvt_test,logical.calcs.tdvt_test,cast_calcs.tdvt_test,join.null.real,/Users/jyf/Library/Python/3.8/lib/python/site-packages/tdvt/logicaltests/setup/calcs/setup.join.null.real.tdvt_test_logical.xml,False,,,,logical,,Error.,Error.,,,,
tdvt_test,logical.calcs.tdvt_test,cast_calcs.tdvt_test,join.null.str,/Users/jyf/Library/Python/3.8/lib/python/site-packages/tdvt/logicaltests/setup/calcs/setup.join.null.str.tdvt_test_logical.xml,False,,,,logical,,Error.,Error.,,,,
tdvt_test,logical.staples.tdvt_test,Staples.tdvt_test,BUGS.B14080,/Users/jyf/Library/Python/3.8/lib/python/site-packages/tdvt/logicaltests/setup/staples/setup.BUGS.B14080.tdvt_test_logical.xml,False,,,,logical,,"LoadDatasource DataSourceException: Missing connection name in relation
''

My .ini named "tdvt_test.int", specifically as follows
''
[Datasource]
Name = tdvt_test
LogicalQueryFormat = tdvt_test_logical
CommandLineOverride = -DConnectPluginsPath=/Users/jyf/Documents/aliyun-maxcompute-tableau-connector-master/plugins

[StandardTests]

[LODTests]

[UnionTest]

[LogicalConfig]
Name = tdvt_test_logical
tablename = $dsName
tablePrefix = [jyf123].
tablenameLower = True
fieldnameLower = True
''

My tds file named "cast_calcs.tdvt_test.tds", as follows:
''
<_.fcp.ObjectModelEncapsulateLegacy.false...relation connection='maxcompute_jdbc.0fahzch1o8gl6q1dhisrk1jjd1ru' name='calcs' table='[jyf123].[calcs]' type='table' />
''

btw, I run the command "python3 -m tdvt.tdvt --list_logical_configs", the part of result is 
''
Name = tdvt_test_logical
Calcs = [jyf123].[Calcs]
Staples = [jyf123].[Staples]
Camel Case = [Camel Case]
bool0 = [bool0]
Date = [Date]
''

So, I don't know why I cannot pass the TDVT test. Why I miss connectition name?

**Comment by rosswbrown** [comment]
Ensure the `add_ds` step has been run to prepare a new tds file. The instructions can be found at https://tableau.github.io/connector-plugin-sdk/docs/tdvt#test-a-new-data-source
