### ISSUE TITLE
[FEATURE] Live only connector example.

### ISSUE THREAD

**Issue by useready-andyv** [tableau/connector-plugin-sdk#1005]
Just like we have an extract only connector sample ([SQLite](https://github.com/tableau/connector-plugin-sdk/tree/master/samples/scenarios/extract_only/sqlite_extract)) , can we get a live only connector example ?

The Live only example would help in cases where we would need to keep authorization in the data store and not have to move it to Tableau Layer as it is dynamic.

Alterative is educating the creators on not using the extract feature and policing the same.

Name: Andy Vadul
Company: USEReady

**Comment by cezhang16** [comment]
Internal tracking id: 1456524

**Comment by pvanderknyff** [comment]
Hi Andy,

Live only connectors are not supported in Tableau, and there are no plans to enable this as a connector-level configuration. If live-only connections are ever supported, it would most likely be as part of the Virtual Connections feature, though there are no current plans there as far as I know.
