### ISSUE TITLE
Tableau Prep Pulling data when process join

### ISSUE THREAD

**Issue by cola-prince** [tableau/connector-plugin-sdk#1006]
**About You:**
Name: Frank
Company:

**Your question:**
I have built a custom connector for Sybase IQ with JDBC driver, when run a prep flow with join step, it will get whole data from DB then join data locally. This will significantly impact the performance.
For example:
select * from TABLE_1
select * from TABLE_2

For built-in Sybase IQ connector with ODBC driver, the SQL generated looks good:
For Example:
select * from TABLE_1 left join TABLE_2 on TABLE_1.column = TABLE_2.column

It will also works good if I use custom connector with custom query to force using the join query.

The custom connector also works good on tableau desktop with data source contains joins.

Is there any capabilities in "connection-customization" to solve this?

**Comment by cezhang16** [comment]
Internal Tracking ID: 1456526

**Comment by cola-prince** [comment]
it seems prep cannot generate a subquery even CAP_QUERY_SUBQUERIES set to 'yes'
tested on 2021.2.2 and 2021.4.3
