### ISSUE TITLE
[FEATURE] Ability to rename Common Fields after connection is created

### ISSUE THREAD

**Issue by useready-andyv** [tableau/connector-plugin-sdk#1007]
When connecting to custom data stores, we would need the ability to call Database, Schema and Tables by different names 
   Ex:  Division for Database,  Snapshot for Schema , View instead of Tables etc. 
 We have the option of rename these fields on the Connection Dialog. After connection dialog completes, the names are reverted back to their original names inside Tableau 

We need a way to persist our renames from Connection Dialog to the Tableau Data Source Pane

Educate the users on what they need to be seeing and how this translates to the Data Store they are used to accessing. 

Name: Andy Vadul
Company: USEReady

**Comment by cezhang16** [comment]
Internal Tracking ID: 1460299

**Comment by rosswbrown** [comment]
The Database, Schema, Table labels are customizable on the Data Source pane as well. The `label` attribute in the `database`, `schema` and `table` elements in the connectionMetadata.xml file controls this value. ([doc](https://tableau.github.io/connector-plugin-sdk/docs/mcd#the-connection-metadata-file), [example](https://tableau.github.io/connector-plugin-sdk/docs/mcd#example))
