### ISSUE TITLE
[FEATURE] DATE as value type while creating fields in Connection Dialog

### ISSUE THREAD

**Issue by SachinS-UR** [tableau/connector-plugin-sdk#1008]
I'm trying to create a field in Connection Dialog which is based on Date selection. But I found it does not support DATE as value type. 

I would like a feature that help in selection of Date as field type in connection dialog.

Current work around here is using String as value type and then validating using Reg Expression but the issue is Date can not be localized. 
Ex: DD/MM/YYYY or MM/DD/YYYY based on location.

Name: Sachin Sehrawat
Company: USEReady

**Comment by lukewrites** [comment]
Internal tracking: W-12315840. 

Hi @SachinS-UR this is something we don't have on the roadmap.
