### ISSUE TITLE
How to make Database selective in meta-data file

### ISSUE THREAD

**Issue by akash-singh478** [tableau/connector-plugin-sdk#1009]
Name: Akash Singh

When we click on our connector inside Tableau, the Sign-in page opens, I want to make the Database field selective like a dropdown will be there for selecting a database.
Is it possible to do that? or any alternative?

**Comment by VasanthiNeelagiri** [comment]
Hi Akshay, 

Unfortunately, this is not supported. Connection dialog does not query the backend server for details. Selecting the Database is something that is done after the connection dialog step on the Data Source pane. Let me know if you have more questions. 

Thanks & Regards,
Vasanthi Neelagiri,
Product Manager, Tableau

**Comment by akash-singh478** [comment]
I need to add new metadata elements other than Database and Schema on the Data Source Pane.

I was trying vendor-defined fields but didn't get any success.

Is there any feature to add a new metadata element on the Data Source Pane between Database and Schema?

**Comment by rosswbrown** [comment]
Answer above: not supported at this time. Follow-up question appears to be tracked in #1013, so closing this issue, thanks.
