### ISSUE TITLE
[BUG] TDVT tds not getting modified to indicate password file

### ISSUE THREAD

**Issue by andysmith-sfdc** [tableau/connector-plugin-sdk#1012]
**Describe the bug**
When adding a datasource to tdvt, e.g. `python.exe -m tdvt.tdvt action --add_ds athena`
I'm prompted to create a password file. After completing that process, tdvt smoke tests fail with a "Missing Password" error
Looking at the tdvt code and tds, it seems that a property `tdvtconnection` should be added to the 'connection' node, but is not. 

I suspect this is down to a faulty or outdated regex in setup_env.py (line 121), 
``` r3 = re.compile('(^\s*<connection .*?)(\s*/>)')```
which doesn't match the 'connection' node

If I add the `tdvtconnection` property manually, then tdvt picks up the password and the test proceeds

**Screenshots**
E.g. in the tds
Expected: <connection class='athena'  tdvtconnection='athena_connection' .....
Actual: <connection class='athena' ....

**Desktop (please complete the following information):**
 - OS: Windows
 - Tableau Version: Latest

**About you:**
 Name: Andy Smith
 Company: Tableau

**Comment by lukewrites** [comment]
Ticket: W-12315835
Assigned to @tabsdavis

**Comment by tabsdavis** [comment]
Created PR: https://github.com/tableau/connector-plugin-sdk/pull/1144
