### ISSUE TITLE
Unable to connect to DB using Custom Connector

### ISSUE THREAD

**Issue by venkatmy** [tableau/connector-plugin-sdk#1026]
Issue :
We created a new custom connector using the Connector SDK  to connect to star rocks DB using the MySQL driver, deployed the connector on Tableau Server, and are only testing over the web. The connector is failing to connect to DB. with the below error : 
The error we are getting is - Can’t connect to Starrocks Live Connector by Airbnb.
Can’t connect to Starrocks Live Connector by Airbnb
Detailed Error Message
Please add the setting native_api.datasource_runas_principal

We have customized the MySQL JDBC Driver to handle the delegation meaning it can run the query as the "tableau server user" using the RunAs Service Account.
The connector SDK is passing two properties to the driver i)  props["user"] = "service_account"; and props["IMPERSONATE_USER"] = tableauServerUser; ( The tableauServerUser parameter is the Viewer ID). The driver takes these parameters and performs.

In addition, I went ahead and tried enabling the Kerberos Delegation on the server and tried to connect to the DB. This time, the error was different.
Can’t connect to Starrocks Live Connector by Airbnb
Detailed Error Message
Unable to obtain a password for the user.
Ideally, we do not want the tableau server to handle the delegation. We need the connector to pass the user names, i.e., the service account and the tableau server user (Viewer), to the driver. The driver is customized to handle the rest. We have a working Presto custom connector doing the same thing. Below is the snippet of the connectionProperties file—e specific details. 

Code in ConnectionProperties

     if (attr[connectionHelper.attributeAuthentication] == "auth-integrated") {
        var tableauServerUser = attr[connectionHelper.attributeTableauServerUser];
       // console.log(attr);
        if (attr[connectionHelper.attributeTableauServerAuthMode]==connectionHelper.valueAuthModeDBImpersonate){
            logging.log("In if statement");
            props["user"] = "service_account";
            props["IMPERSONATE_USER"] = tableauServerUser;
            //props["gsslib"] = "gssapi";  
            //props["jaasLogin"] = "false";
            props["Keytabfile"] = "/opt/tableau/tableau_server/keytab/svc-di-tableau.keytab"
            props["defaultAuthenticationPlugin"] = "authentication_kerberos_client";
    	  	props["applicationNamePrefix"] = "Tableau";

Manifest
<?xml version='1.0' encoding='utf-8' ?>

<connector-plugin class='starrocks' superclass='jdbc' plugin-version='0.0.0' name='Starrocks Live Connector' version='18.1' min-version-tableau='2020.3'>
  <vendor-information>
      <company name="Airbnb"/>
      <support-link url = "https://example.com"/>
  </vendor-information>
  <connection-customization class="starrocks" enabled="true" version="18.1">
    <vendor name="name"/>
    <driver name="driver"/>
    <customizations>
      <customization name='CAP_QUERY_HAVING_REQUIRES_GROUP_BY' value='yes' />
      <customization name='CAP_AUTH_DB_IMPERSONATE' value='yes'/>
    </customizations>
  </connection-customization>
  <connection-fields file="connection-fields.xml"/>
  <connection-metadata file="connection-metadata.xml"/>
  <connection-resolver file="connectionResolver.tdr"/>
  <dialect file="dialect.tdd"/>
</connector-plugin>

**Screenshots**

 - OS: Linux Ubuntu 18.04
 - Tableau Version 2022.1.4

**About you:**
 Name: Venkata Mylavarapu
 Company: Airbnb

**Comment by devanshsoni9** [comment]
I request you to use similar workflow as the Presto custom delegation. This requires publishing from Tableau Desktop using "Impersonate via Server Runas" auth mode as mentioned in the Presto custom delegation document (emailed you). The web auth only workflow hasn't been enabled for this as far as I know.

**Comment by venkatmy** [comment]
Thanks @devanshsoni9 our direction is to use the Web Auth only and not the Tableau Desktop. How can we enable it without having to publish from tableau desktop

**Comment by devanshsoni9** [comment]
I guess that request might have to come through our product team. @VasanthiNeelagiri

**Comment by venkatmy** [comment]
Thank you Devansh. We will follow and test this connector from Tableau Desktop and see it goes.

**Comment by venkatmy** [comment]
@devanshsoni9 I am running into an issue where the tables are not loading in tableau desktop with the new connector. I am able to successfully connect and navigate to the schemas in the database but i do not any tables in the schema. I think this may have to do with either my dialect or the manifest file. I have sent you a detailed email along with the snapshots. Please take a look. Thank you!

**Comment by devanshsoni9** [comment]
Synced offline with @venkatmy . They are able to successfully connect now. Closing this now.
