### ISSUE TITLE
Custom data connector OAuth in Tableau Server v2021.1.18

### ISSUE THREAD

**Issue by chen4119** [tableau/connector-plugin-sdk#1035]
**About You:**
Name: Wan Chun Chen
Company: JP Morgan

**Your question:**
Trying to build a custom data connector with OAuth integration with our internal OIDC provider.  It worked if I run it through Tableau Desktop.  I'm able to get the access token.  When I test the data connector on Tableau Server, I'm seeing this log in vizportal-node log file.

Request received: GET for /v1/auth/request_oauth
INFO com.tableausoftware.domain.content.oauthconnections.OAuthClientService - features.SiteLevelOAuthClient is disabled, request will not be completed
ERROR com.tableausoftware.api.webclient.rest.util.WebClientRestControllerAdvice - OAuthException in WebClientController: (errorCode: 170006)
INFO com.tableausoftware.app.vizportal.LoggingInterceptor - Request completed: /v1/auth/request_oauth with status 400

How do I enable SiteLevelOAuthClient?  Is this the cause of my error?

**Comment by jkoskela** [comment]
We have several docs that explain this, but they are specific to connectors. We will be adding a general docs that would apply to plugins soon. But the steps are basically the same. Here is an example for the Dremio connector.

https://help.tableau.com/current/server/en-us/config_oauth_dremio.htm

See the section for "Configure custom OAuth for a site"

**Comment by chen4119** [comment]
We just upgraded Tableau server to 2022.3.  I also added my OAuth client to the registry as described in the dremio link.  I was able to get further now.  My browser re-directed me to my OIDC provider where I can enter my credential.  I also see from the logs that it called back to Tableau.  I see this.

INFO Request received: GET for /v1/auth/add_oauth_token

Now I'm getting a HTTP 400 Bad Request error when Tableau attempts to exchange authorization code for access token.  From the logs I see

POST https://<valid domain>/token?grant_type=authorization_code&client_id=<valid client>&redirect_uri=<valid redirect>

The URL above didn't include client_secret or code query params as required when making the /token request.  Is this because Tableau didn't include it?  Which would explain the HTTP 400 error but why wouldn't Tableau include it?

Or is it simply that the log excluded those two query params for privacy reasons?

**Comment by jkoskela** [comment]
We won't log the secrets. Client secret is optional for native/local apps because they don't have the same security issues as non-local apps, and also because there is no way to keep the client secret a secret anyways.

**Comment by jkoskela** [comment]
What OIDC provider are you using?

**Comment by jkoskela** [comment]
There is no way to configure TS to authenticate without the client_secret. It will always pass something.

**Comment by chen4119** [comment]
It's an internal OIDC provider.  Is it possible for Tableau Server to support OAuth clients with no secret?  Client secret is optional in the OAuth spec.

https://www.rfc-editor.org/rfc/rfc7591#section-3.2.1

Don't see why Tableau Server need to make it mandatory.

**Comment by jkoskela** [comment]
It's required for confidential clients, which are all clients for Tableau Server (as opposed to Tableau Desktop).
https://oauth.net/2/client-types/

**Comment by jkoskela** [comment]
If this is an internal OIDC provider, can you just make it ignore any client_secrets that may be passed in? Then you can configured some dummy value on TS.

**Comment by jkoskela** [comment]
We will probably make this change, but it may be much faster to fix it on your end.

**Comment by chen4119** [comment]
We have no control over the behavior of the OIDC provider so that's not possible unfortunately.  Also, a confidential client doesn't necessary have to authenticate using client secret.  There are other forms of authentication.  

From https://www.rfc-editor.org/rfc/rfc6749#section-2.1

confidential
      Clients capable of maintaining the confidentiality of their
      credentials (e.g., client implemented on a secure server with
      restricted access to the client credentials), **or capable of secure
      client authentication using other means.**
