### ISSUE TITLE
[BUG] LogicalException: Cannot check the capabilities of a federated connection.

### ISSUE THREAD

**Issue by mmcwhort** [tableau/connector-plugin-sdk#1036]
I’m attempting to run the Validation Pipeline on a new version of our connector, which uses JDBC.  When I receive the spreadsheet of test results, roughly 100 of the tests are listed as FAILED with the following error message:
 
"Error. Previous error message is: Attempting to run query...
LogicalException: Cannot check capabilities of a federated connection.
Error running query"
 
I do not get these errors with the ODBC version of our connector.  I only see them with the JDBC version.  It looks like my validation pipeline might be misconfigured.  Any idea what this message means?

Thank you!

Mike McWhorter
Yellowbrick Data

**Comment by rosswbrown** [comment]
Hi,

Ensure the `add_ds` step has been run to prepare a new tds file. The instructions can be found at https://tableau.github.io/connector-plugin-sdk/docs/tdvt#test-a-new-data-source

There is additional detail in Issue #710 that may answer your question.

**Comment by rosswbrown** [comment]
Please let us know if this should be reactivated, thanks.
