### ISSUE TITLE
Deploying Kerberos Connected Code gives exception in com.tableausoftware.auth.KerberosContext.kerberosLogin() 

### ISSUE THREAD

**Issue by useready-andyv** [tableau/connector-plugin-sdk#1038]
Name: Andy Vadul
Company: USEReady

 We have built a custom connector working with Kerberos Authentication on the Tableau Desktop. The authentication on desktop works as expected and gets the Kerberos TGT and allows us to access the data source.  for dev purpose, the Tableau Desktop is on the same machine where Tableau Server is running.

On deploying tableau data source to Tableau Server, connection to the data source fails with the exception java.net.UnknownHostException. in com.tableausoftware.auth.KerberosContext.kerberoslogin() 
Stack Trace is  
![tgtIssue](https://user-images.githubusercontent.com/16009851/203316157-9a25a19b-1281-411d-9add-153bf9f2d511.png)

The Tableau Server is working with SQL Server using Kerberos Auth for live connections.
 
Is there additional setting we need to do besides the standard Kerberos Configuration as explained in : https://help.tableau.com/current/server/en-us/kerberos_requ.htm ?

**Comment by devanshsoni9** [comment]
Hi @useready-andyv 

Depending on which type of authentication you are trying to do in Tableau Server, mainly these are two types of Kerberos authentication in Tableau Server using JDBC: 
1. [Kerberos Run-as Authentication](https://help.tableau.com/current/server/en-us/kerberos_runas_jdbc.htm).
2. [Kerberos Delegation](https://help.tableau.com/current/server/en-us/kerberos_delegation_jdbc.htm). 

Please go through the above links and make sure you have made the necessary configurations. Feel free to ask any further questions on the same.

**Comment by UR0082** [comment]
Hi,

I am also working on the same issue able to make the connection to the custom connector from tableau desktop. But when I try to deploy the connector to Server, I get an error. The connection with username and password works, but Kerberos run as authentication or delegation both fail. below is the screenshot of my error message

![image](https://user-images.githubusercontent.com/66296528/204389602-1fe8a851-7d8a-44dc-9682-b710bb358171.png)

**Comment by devanshsoni9** [comment]
Hi @useready-andyv and @UR0082, I am not a systems expert. Although it is possible it has to do with your DNS settings. I would suggest try to add the hostname and IP address to the etc/hosts ( C:\Windows\System32\drivers\etc\hosts) file.  Also double check your krb5.ini (C:\Windows\krb5.ini) file for `[realms]` and `[domain_realm]` configurations.

**Comment by devanshsoni9** [comment]
Hi 
will mark this one as resolved in a day, let us know if you still have issues.
