### ISSUE TITLE
How can I get a configurable option for Tableau Desktop

### ISSUE THREAD

**Issue by akash-singh478** [tableau/connector-plugin-sdk#1039]
How can I get a configurable option for tableau desktop which can take input for any property and then use in Connection Builder file, or any alternate option is there for now Connection Builder file takes it directly from desktop UI.

**Comment by pvanderknyff** [comment]
Hi Akash, customers can set configuration options using a JDBC properties files, documented here: https://community.tableau.com/s/question/0D54T00000F339uSAB/customize-jdbc-connections-using-a-properties-file
