### ISSUE TITLE
TDVT - How should I run expression tests for a DB that require custom logical query config

### ISSUE THREAD

**Issue by ishaydahan** [tableau/connector-plugin-sdk#1040]
Name: Ishay Dahan
Company: Salesforce

I'm running TDVT tests on a custom DB that on ingestion, auto reshape column names and table names to a customized format. Therefore I need to use your `Logical query config` feature to define my DB schema.
I works fine for the logical tests, but I understand now that it shouldn't work for the expression tests.
How should I run the TDVT expression tests if my DB require column/table name reshaping?

Thanks!

**Comment by tabBhargav** [comment]
Column renaming only works for Logical tests, as you found out. We are about to merge a new feature that lets you run the expression tests against basically any table. So if your Calcs table looks like _bool0__c_, TDVT will be able to handle that by creating custom tests that replace the hardcoded column names _(like bool)_ with the column from your table that matches. This update is coming up in TDVT v. 2.8.0
