### ISSUE TITLE
TDVT: How to add a SET statement before SELECT in every test

### ISSUE THREAD

**Issue by ImprovingRichard** [tableau/connector-plugin-sdk#1053]
**About You:**
Name: Richard G

**Your question:**
I have a need to execute a 'SET var=value; ' statement before every SELECT being executed by the TDVT tests. I've modified my dialect to add the SET statement in the 'Select' part of format-select:

```xml
    <format-select>
      <part name='Select' value='SET var=value; SELECT %1' />
```
While this works for most tests, many of the calcs expression tests fail with 'For input string: "null"' or 'Unable to fetch date'. Executing the query (with the SET prepended) in my database query console works successfully.

Is format-select the correct place to add the SET statement? Is this functionality supported by TDVT?

**Comment by rosswbrown** [comment]
This doesn't sound like a scenario that is supported today. The expectation is that `format-select` is a single query statement.

Tableau does have the concept of [Initial SQL](https://help.tableau.com/current/pro/desktop/en-us/connect_basic_initialsql.htm) that allows for SQL statements to be run during initial connection. These get persisted in the `.tds` file used by TDVT. This however doesn't seem to match the per-statement requirement above.

**Comment by ImprovingRichard** [comment]
Not the answer I was hoping for, but thanks for the quick reply.
