### ISSUE TITLE
[BUG] setup.BUGS.B140080 does not cover cases where [Order Date] have time part

### ISSUE THREAD

**Issue by xsgao-github** [tableau/connector-plugin-sdk#1063]
**Describe the bug**
All `[Staples].[Order Date]` values don't have a time part, thus some test cases, e.g. `setup.BUGS.B140080,` will still pass even though `datetime - datetime` rewriting formula is incorrect.

Taken the screenshot for an example, `DATETIME('2000-01-02 00:00:01') - DATETIME('2000-01-01 23:59:59')` returns `-1` because the formula was not defined correctly in `dialect.tdd`, but the final results still match expected.

I would suggest to add time part to `[Order Date]` column, and/or change the filter of test case `setup.BUGS.B140080` from `FLOAT([Received Date] - [Order Date]) in (121., 122., ..., 138.)` to `ROUND([Received Date] - [Order Date], 1) in (121., 122., ..., 138.)`.

**Screenshots**
<img width="1290" alt="image" src="https://user-images.githubusercontent.com/39278329/215540656-341dfdf7-2453-4dc7-84af-32e7834a6626.png">

**Desktop (please complete the following information):**
 - OS: Mac
 - Tableau Version: 2022.4

**About you:**
 Name: Song Gao
 Company: Starburst Data

**Comment by lukewrites** [comment]
Hi @xsgao-github we have updated TDVT internally to resolve this. The next quarterly release of TDVT will include the new test cases.

Thanks again for catching this and the suggestion.
