### ISSUE TITLE
[BUG] incorrect help message for TDVT run-pattern 

### ISSUE THREAD

**Issue by xsgao-github** [tableau/connector-plugin-sdk#1069]
**Describe the bug**
Help message when you execute `... tdvt.tdvt run-pattern`

```
usage:
    Run one expression test against many datasources
        run-pattern postgres_odbc --exp exprtests/standard/setup.date.datepart.second*.txt --tdp cast_calcs.*.tds
```

But when you issue this command, you got this error:

```
no matches found: exprtests/standard/setup.date.datepart.second*.txt
```

It turned out that you need to double quote the two parameter values, e.g.

```
        run-pattern postgres_odbc --exp "exprtests/standard/setup.date.datepart.second*.txt" --tdp "cast_calcs.*.tds"
```

**Screenshots**
See 

**Desktop (please complete the following information):**
 - OS: MacOS 13.1
 - Tableau Version: 2022.4

**About you:**
 Name: Song Gao
 Company: Starburst Data

**Comment by lukewrites** [comment]
Hi @xsgao-github, you're right that this will look different depending on what shell you're using. I use zsh and have to escape the `*` character to run commands.

It makes sense to mention this in the help string. Thanks for the feedback.
