### ISSUE TITLE
With Kerberos login when we trying to publish in Tableau server using our Kyvos custom connector we are not able to see "Server Run As account" in Authentication option 

### ISSUE THREAD

**Issue by srinadhkunam** [tableau/connector-plugin-sdk#1080]
**Describe the Bug**
We have our own ODBC based custom Kyvos connector which is listed in Tableau & now we are enhancing the connector to support Kerberos Authentication as well using [connection dialog v2](https://tableau.github.io/connector-plugin-sdk/docs/mcd)

We tested it on Tableau desktop and it is working fine as expected, however when we tried to publish in Tableau server but we are not able to see "Server Run As account" in Authentication options. We are seeing Prompt and Embedded as options. We are expecting to see "Server Run As account" in Authentication options when we are connected using Kerberos. 

We also tried by adding property in manifest file `<customization name="CAP_AUTH_KERBEROS_IMPERSONATE" value="yes"/>` but it didn't work.

**Screenshots**
![image](https://user-images.githubusercontent.com/52819363/221191766-112f6c46-132c-45ee-ac9b-c90db7a03b97.png)

For you reference we are attaching our connector files:
[tableau_connector_sk.zip](https://github.com/tableau/connector-plugin-sdk/files/10824737/tableau_connector_sk.zip)

**About me**
Srinadh Kunam
[Kyvos Insights](https://www.kyvosinsights.com/)

**Comment by devanshsoni9** [comment]
Hi @srinadhkunam 
Is your Tableau Server setup on Linux or Windows ? For Linux machine, you have to additionally run the tsm commands mentioned [here](https://help.tableau.com/current/server-linux/en-us/kerberos_runas_linux.htm).

**Comment by srinadhkunam** [comment]
Hi @devanshsoni9 

We have both Linux and Windows Tableau Servers. We are seeing the issue in both when we tried to publish from desktop.

**Comment by devanshsoni9** [comment]
Hi @srinadhkunam 
I think you might be already doing it but if can you confirm that the tsm commands mentioned [here](https://help.tableau.com/current/server-linux/en-us/kerberos_runas_linux.htm) are being run ?

**Comment by srinadhkunam** [comment]
Hi @devanshsoni9 

I validated again & when we tried to publish using Spark SQL connector, I'm able to see "Server Run As account" as below
![image](https://user-images.githubusercontent.com/52819363/222068284-110b9903-a95e-4758-9478-3e4d87581875.png)

But when I try to publish using Kyvos connector I'm seeing only Prompt & Embedded.

Can we get into a call to resolve the issue ASAP.

@VasanthiNeelagiri @sidwray

**Comment by srinadhkunam** [comment]
Hi @devanshsoni9 any update for me on this issues.

**Comment by devanshsoni9** [comment]
Hi @srinadhkunam 

I looked at the connector files you provided and have the following suggestion based on my testing. 
1. In this file connectionBuilder.js, the `AUTHMECH` for `auth-integrated` should be `3`.This is needed for the Kerberos authentication. 

Let me know if it changes anything, or else we may have to look into the platform code.

**Comment by devanshsoni9** [comment]
@srinadhkunam updated my comment, per spark [docs](https://downloads.datastax.com/odbc/2.6.5.1005/Simba%20Spark%20ODBC%20Install%20and%20Configuration%20Guide.pdf) , In case of Kerberos auth,  the value for AuthMech is `1`

**Comment by srinadhkunam** [comment]
@devanshsoni9 we are using our own ODBC driver, which is developed by Kyvos team and in the driver code for Kerberos AuthMech is set as 2.

**Comment by VasanthiNeelagiri** [comment]
@srinadhkunam - Hi Srinadh, We are still discussing the solutions and timelines to fix the issue. But, before we proceed further, we want to understand a couple of things:
1. What are your plans on this connector update? When do you anticipate this new connector to be released? 
2. Is it just for internal purposes/Do you want Tableau to bundle this connector Vs release on Tableau Exchange? Please note that we are encouraging our partners to use and submit JDBC Connectors going further

Could you please share more details on the above questions and if any customers are requesting for this upgrade

**Comment by srinadhkunam** [comment]
Hi @VasanthiNeelagiri, Thanks for the update. Below are answers for your questions.

1. This issue only blocking for me to release this new version of Kyvos connector and new release of Kyvos ODBC driver.
2. This enhancement we are doing for couple of our join customers requirement. This new version replaces our existing Kyvos connector which is already included in Tableau bundle.

**Comment by VasanthiNeelagiri** [comment]
Thanks for the update Srinadh. To fix this, we need to do a fix on our platform side. Also, we would like to update the connector at the same time. Closing this issue and moving the conversation to email. I will involve our Tech Partner team for updating the connector. 

Thanks & Regards,
Vasanthi Neelagiri,
Product Manager, Salesforce
