### ISSUE TITLE
Question about Trino external authentication and making HTTP calls in Tableau connector

### ISSUE THREAD

**Issue by chen4119** [tableau/connector-plugin-sdk#1084]
**About You:**
Name: Wan Chun Chen
Company: JP Morgan

**Your question:**
1) Trino JDBC driver supports external authentication via OAuth 2.0.  When I tried it from Tableau server using a custom Tableau connector, it didn't work.  Does Tableau server prevents Trino JDBC driver from redirecting to identity provider?

2) Does Tableau connector SDK allow you to make custom HTTP calls in connectionBuilder.js?  For example, if I want to hit another URL to get some credential and add that credential to JDBC string.  Is that possible?  If so, is there any example I can look at?

**Comment by lukewrites** [comment]
Tracked with W-12652932

**Comment by lukewrites** [comment]
Hi,

Thanks for the questions.

1. @sidwray can talk to you directly about identity provider issues.
2. Unfortunately the SDK doesn't allow for this, and it's not something we are planning to support.

**Comment by sidwray** [comment]
Have you reviewed this part of the documentation?  https://tableau.github.io/connector-plugin-sdk/docs/oauth
Our next release builds on the above and includes the platform components to allow you to configure the IDP of your choice through server admin configuration.  Each connector, whether native or plugin would need a minor refactoring to take advantage of it.  I don't believe we have any specific plans related to Trino, but I will add it to the backlog.

**Comment by sidwray** [comment]
2023.1 includes customer configurable IDP support after a connector has been updated.  https://tableau.github.io/connector-plugin-sdk/docs/oauth

**Comment by jkoskela** [comment]
Just wanted to clarify "Does Tableau server prevents Trino JDBC driver from redirecting to identity provider?" That is a desktop only flow. The driver has no way to redirect your browser when running on the server, nor the ability to receive the response. It does say their connector supports OAuth: https://docs.starburst.io/data-consumer/clients/tableau.html
