### ISSUE TITLE
Tableau DataSource Refresh Issue

### ISSUE THREAD

**Issue by akash-singh478** [tableau/connector-plugin-sdk#1085]
When we drag a table in DataSource it shows all the data inside fields like field name, data inside the it but after a refresh all the data like column and table name goes away.
If we have to do a custom implementation for this, can I add custom attribute to preserve state so I can retrieve data while refreshing the tableau DataSource?

**Comment by tabBhargav** [comment]
- Need more information on this
- Need clear steps on how to repro the issue, possibly logs
- Also, if you can identify which partner connector you’re working with
