### ISSUE TITLE
Questions on Tableau Connector for Databricks - dialect and CAP_FAST_METADATA

### ISSUE THREAD

**Issue by yunbodeng-db** [tableau/connector-plugin-sdk#1086]
**About You:**
Name: Yunbo Deng
Company: Databricks

**Your question:**
1. My team owns Tableau connector for Databricks. This is our [repo](https://github.com/databricks/tableau-connector). We would like to update the [dialects](https://github.com/databricks/tableau-connector/blob/master/tableau-databricks/dialect.tdd) but wonder if there is any compatibility issues with the syntax, will Tableau have any fallback mechanism for the old/existing queries?
2. On [CAP_FAST_METADATA](https://tableau.github.io/connector-plugin-sdk/docs/capabilities) capability, our understanding is this is all-or-for-nothing. I wonder if the connector can provide an option or switch that at least we can allow customers to opt-out themselves if they have too many schemas and tables which would slow down their connecting time?

**Comment by lukewrites** [comment]
Tracked internally with ticket W-12652888

**Comment by rosswbrown** [comment]
For question 1, at this time connectors can only define a single dialect definition. There is not any fallback mechanism to retry an unsupported query in a different form if failure is detected. 

Regarding question 2, you are correct that `CAP_FAST_METADATA` is defined at a connector level as a part of the definition. The only way a user could customize this is with a [TDC](https://help.tableau.com/current/pro/desktop/en-us/connect_customize.htm) file in Tableau Desktop. There is no way to customize this for a Tableau Cloud customer.
