### ISSUE TITLE
Sample Kerberos Connector: Publishing with Viewer Credentials does not work? 

### ISSUE THREAD

**Issue by useready-andyv** [tableau/connector-plugin-sdk#1102]
I am trying to get to 'Server Run As Account with  Impersonation' for a Kerberos connector I am building.
Got the Server Credentials to work, but Viewer Credentials fails when publishing from Desktop.
 

I fell back to looking at the Kerberos connector in samples, connecting to postgres, but I see the same issue there
I am not able to get publishing with viewer credentials to work. It does publish the connector but fails on connecting to 
published connector and does not replace on the desktop 

<img width="265" alt="errorScreenshot_1" src="https://user-images.githubusercontent.com/16009851/226787610-46a4b07d-f7b5-4897-8abf-47a33589708f.png">

<img width="319" alt="errorScreenshot_2" src="https://user-images.githubusercontent.com/16009851/226787630-a3b3d2c8-ac18-49e8-935b-ac2017f56ebe.png">

Error on Tableau desktop logs is : 

`
 {"ts":"2023-03-21T21:46:09.081","pid":24624,"tid":"4d60","sev":"warn","req":"-","sess":"-","site":"-","user":"-","k":"msg","v":"HTTPRequestor::DoWork::HTTPException 401 [http://ts2021.acme.com:80/vizportal/api/clientxml/kerberos](http://ts2021.acme.com/vizportal/api/clientxml/kerberos) HTTP/1.1 401 \r\nDate: Wed, 22 Mar 2023 01:46:09 GMT\r\nServer: Tableau\r\nCache-Control: no-store\r\nWWW-Authenticate: Negotiate\r\ntableau_error_source: NeedsClassification\r\ntableau_status_code: 2\r\ntableau_error_code: 0x78902427\r\ntableau_service_name: vizportal\r\nContent-Type: application/xml;charset=UTF-8\r\nX-Tableau: Tableau Server\r\nP3P: CP=\"NON\"\r\nX-UA-Compatible: IE=Edge\r\nX-Content-Type-Options: nosniff\r\nX-XSS-Protection: 1; mode=block\r\nReferrer-Policy: no-referrer-when-downgrade\r\nContent-Security-Policy-Report-Only: connect-src * [https://*.tiles.mapbox.com](https://%2A.tiles.mapbox.com/) [https://api.mapbox.com;](https://api.mapbox.com%3B/) default-src blob:; font-src * data:; frame-src * data: tableau-desktop:; img-src * data: blob:; object-src data:; report-uri /vizql/csp-report; script-src * blob:; style-src * 'unsafe-inline'\r\nKeep-Alive: timeout=8, max=95\r\nConnection: Keep-Alive\r\nTransfer-Encoding: chunked\r\n\r\n<?xml version=\"1.0\" encoding=\"UTF-8\" standalone=\"yes\"?>\n<error xmlns:xsi=\"[http://www.w3.org/2001/XMLSchema-instance\">\n](http://www.w3.org/2001/XMLSchema-instance/%22%3E/n)    <code>43</code>\n    <message>Not authorized</message>\n    <details>Kerberos 401 (errorCode=43)</details>\n</error>\n"}
`

**Comment by jkoskela** [comment]
There isn't enough information here to diagnose this. You probably don't have Tableau Server setup for Kerberos. The [authentication to TS using Kerberos](https://help.tableau.com/current/server/en-us/config_kerberos.htm) is not required for Kerberos connections to the backend. See [here](https://help.tableau.com/current/server/en-us/security_data_connection_auth.htm) for more information.
