### ISSUE TITLE
[BUG] Tableau Desktop (Tabquerytool) Crashes During TDVT Run

### ISSUE THREAD

**Issue by ravjotbrar** [tableau/connector-plugin-sdk#1104]
**Describe the bug**
I'm trying to run TDVT and during the run I get a pop-up saying "Tableau quit unexpectedly." All 920 tests "ran" and 269 fail, but when I dig into those failures I see that most of the expected tuples are null (which I'm assuming has to do with the crash). I also tried to take a look at the logs to see crashdumps, but the crashdumps folder is empty. I'm unable to reproduce this without TDVT; will attach the relevant tdvt logs. 

It appears that the tool is crashing during the run of these tests:
```
Running flight logical.staples.flight 2

EEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEE
Finished flight logical.staples.flight 2

Running flight logical.lod.flight 3

EEEEEEEEEEEEEEEEEEEEEEEEEEE
Finished flight logical.lod.flight 3
```
**Screenshots**
![Screenshot 2023-03-31 at 11 44 55 AM](https://user-images.githubusercontent.com/83892020/229216153-9d86614a-8d48-4e3d-bf27-3c15323a4cfd.png)

**Desktop (please complete the following information):**
 - OS: macOS Ventura 
 - Tableau Version: 2022.3 (2023.1 also had the same issue) 

**About you:**
 Name: Ravjot Brar
 Company: Dremio

** Logs **
[tabquery_logs.zip](https://github.com/tableau/connector-plugin-sdk/files/11125443/tabquery_logs.zip)
[tdvt_log_combined.txt](https://github.com/tableau/connector-plugin-sdk/files/11125470/tdvt_log_combined.txt)

**Comment by lukewrites** [comment]
Hi Ravjot, thanks for the bug report we will take a look.

**Comment by lukewrites** [comment]
@ravjotbrar out of curiosity, are you on an Intel mac or an Apple Silicon mac?

**Comment by ravjotbrar** [comment]
Thanks, Luke. I'm on silicon.

**Comment by ravjotbrar** [comment]
I also tested on a Windows machine and get the same number of failures, with the same behaviour of all but one test having no values in the expected tuples column. I've attached my results below. 
[test_results_combined.csv](https://github.com/tableau/connector-plugin-sdk/files/11141463/test_results_combined.csv)

**Comment by lukewrites** [comment]
@ravjotbrar I'm sorry for how long it's taken to respond. I've been going through your logs this morning - would it be possible to see your logical config for the connector?

**Comment by ravjotbrar** [comment]
No worries, @lukewrites. I managed to find the expected tuples in the log files that outline the diffs and resolve a lot of the failures. Still not sure why the expected tuples were null in the csv though. Unfortunately, I don't have the logical config handy anymore.

**Comment by lukewrites** [comment]
Glad you got it to work. I'll close this out, feel free to reopen if it reoccurs.
