### ISSUE TITLE
[BUG] Tableau intercepts 401 replies to JDBC driver after OAuth authentication

### ISSUE THREAD

**Issue by petroav** [tableau/connector-plugin-sdk#1109]
**Describe the bug**
This specifically relates to the interaction between Trino and its JDBC driver.

Trino and the JDBC driver have a protocol between themselves, wherein at certain times Trino replies with a 401 and a WWW_AUTHENTICATE header. The header contains a URL that the JDBC driver is expected to query in order to get an updated authentication token. This interaction works fine in tools like DBeaver where we use the JDBC driver as well. However, with Tableau something is interfering with the above protocol and the URL returned by Trino is never queried by the driver. This leads me to believe that Tableau may be intercepting 401 replies and isn't forwarding them to the driver.

**Screenshots**

**Desktop (please complete the following information):**
 - OS: Windows 10 Home
 - Tableau Version: 2023.1.0 (20231.23.0310.1044)

**About you:**
 Name: Anton
 Company: Starburst Data

**Comment by lukewrites** [comment]
Internal tracking: W-13546955

**Comment by jkoskela** [comment]
Just saw this. We are not intercepting HTTP requests for the driver. Is this still an issue?

**Comment by jkoskela** [comment]
I have started a conversation about all of these issues in our shared slack channel. If this is still an issue let's discuss it there. Resolving.
