### ISSUE TITLE
Connector with your own OAuth-IdP // Is it possible to hide the option "OAuth authentication" when the user loads the connector in Tableau 2022.4 or older?

### ISSUE THREAD

**Issue by carlossc** [tableau/connector-plugin-sdk#1112]
**About You:**
Name: Carlos Santos Canelles
Company: Denodo Technologies

**Your question:** 

We are improving our connector [Denodo JDBC](https://extensiongallery.tableau.com/products/303) to take advantage of the new feature to "Bring your own IdP" (OAuth) of Tableau.

If users load a connector with this feature in Tableau 2022.4 or older, in the login dialog the drop-down **Authentication** has the option **OAuth authentication** but will not work with our connector.

- Can we hide the option **OAuth authentication** when the connector is loaded in Tableau 2022.4 or older? We did not find anything in the [documentation of the SDK](https://tableau.github.io/connector-plugin-sdk/docs/oauth#how-to-enable-oauth-for-a-plugin-connector) to do it but maybe we did not see it.
- If not, is the expectation that we should add to the documentation, something like this?
> OAuth authentication only works if you load the connector in Tableau 2023.1 or newer.

We worry that displaying an option that does not work may trigger support cases for Tableau and Denodo. Maybe our worries are unfounded.

**Comment by lukewrites** [comment]
Hi, Carlos, sorry I missed this before - will get back to you soon.

**Comment by carlossc** [comment]
Hi @lukewrites have you been able to find an answer to this? Thank you.

**Comment by jkoskela** [comment]
There is no currently no way to hide it. We are investigating other options to improve this in the future.
