### ISSUE TITLE
TDVT Failure for one special test

### ISSUE THREAD

**Issue by eric-wang-1990** [tableau/connector-plugin-sdk#1123]
**About You:**
Name: Eric Wang
Company: Databricks

**Your question:**
There is one logical query test on Staples thrown exception and cause all other tests to fail, I've identity this single test suite is Query.MultipleFilters, it is not even able to generate the query. The error messages are: `Tableau cannot evaluate the query that results from this calculation`, I also saw this in logs: `FederatedQueryOptimizerImpl::DetermineConnForExecution: Could not find connection for evaluating all LogicalExps `, that seems the only tests also invoke hyper since there is a hyperd log as well.
This repros in Tableau Desktop 2022.2, 2022.4, 2023.1. I think the tests used to pass in Tableau 2020.x but I cannot verify now since those cannot be downloaded any more. This repros both in windows and mac so it's not a platform specific issue, I've attached the logs from both platforms as well.
[tabquery_logs_windows.zip](https://github.com/tableau/connector-plugin-sdk/files/11367250/tabquery_logs_windows.zip)
[tabquery_logs_mac.zip](https://github.com/tableau/connector-plugin-sdk/files/11367252/tabquery_logs_mac.zip)

**Comment by lukewrites** [comment]
Thanks @eric-wang-1990 we'll take a look. 

Internal ID: W-13131468

**Comment by rosswbrown** [comment]
Hi Eric,
In the next release after Tableau 2023.3 we've fixed the issue where a single test will cause the remaining tests in the suite to be Aborted.

Unfortunately, I've been unable to reproduce the other issue you're seeing above with `Query.MultipleFilters` internally. I've attached the tdvt config and tds files used. I don't see any meaningful difference between our internal test instance and what was [shared](https://github.com/databricks/tableau-connector/tree/master/tdvt_workspace) in your repo. There are some minor differences in column type, but I don't believe that is the issue: [tdvt_config_databricks.zip](https://github.com/tableau/connector-plugin-sdk/files/13285195/tdvt_config_databricks.zip)

It is possible the `<function group='operator' name='$IN_SET$' return-type='bool'>` [definition](https://github.com/databricks/tableau-connector/blob/master/tableau-databricks/dialect.tdd#L152) might be causing the issue, but internally keeping it or removing it didn't make a difference for the TDVT suite results.

**Comment by tabsdavis** [comment]
Reviewed error and confirmed this has been something seen before which we've had a few suggestions for. See:

https://github.com/tableau/connector-plugin-sdk/issues/1190#issuecomment-1751307057
https://github.com/tableau/connector-plugin-sdk/issues/916#issuecomment-1055648786
However I would look closely here: https://github.com/tableau/connector-plugin-sdk/issues/742#issuecomment-813650391
Recommendation: "...Starting with something like [this example dialect](https://github.com/tableau/connector-plugin-sdk/blob/master/samples/plugins/postgres_odbc/dialect.tdd) and modifying it as necessary"
