### ISSUE TITLE
Connector with your own OAuth-IdP // Question regarding backward compatibility of the new connector with older versions of Tableau

### ISSUE THREAD

**Issue by carlossc** [tableau/connector-plugin-sdk#1126]
**About You:**
Name: Carlos Santos Canelles
Company: Denodo Technologies

**Your question:**

We are improving our connector [Denodo JDBC](https://extensiongallery.tableau.com/products/303) to take advantage of the new feature to "Bring your own IdP" (OAuth) of Tableau. 

We have a question regarding using the connector in older versions of Tableau.

The version that is in the marketplace works with _Tableau 2020.3 and later_ (at the time, we tested it with that version).

We are now testing the new version we are working on (the one with a "Bring your own IdP" - OAuth - capabilities) in several versions:

- Tableau 2020.4: it does not work (the connector does not show up in Tableau Desktop). Should it appear? 
- Tableau 2022.X (I am not sure the exact version): it works showing the OAuth authentication option, even though it will not work (see https://github.com/tableau/connector-plugin-sdk/issues/1112).
- Tableau 2021: we could not get this version so we did not test with this.

I see in [this page](https://www.tableau.com/support/services) of Tableau: 

> For all versions of Tableau Desktop and Tableau Server, maintenance (along with full technical support) is provided for 24 months following the [version release](https://www.tableau.com/support/releases).

So, maybe we do not have to worry about this because Tableau 2020 is unsupported.

**Question**
Considering all this, what do you suggest regarding publishing the new version of the connector?
  -  Is it possible to publish two versions of the connector? Keep the current one, which is compatible with Tableau 2021 and also the new one that includes the "Bring your own IdP" (OAuth) capabilities?
  - Maybe just publish the newest one and in the description add a note saying, if you use Tableau 2021, contact Denodo Support to get the older version of the connector? or something like that?

**Comment by rosswbrown** [comment]
That [page](https://www.tableau.com/support/services) you referenced is correct. You only need to consider the last 24 months following release, which currently would be 2021.2 and newer.

Based on the question in #1112 we have updated the packager to correctly set the min-version-tableau to 2023.1 if multiple embedded OAuth configs are detected.

Currently the Tableau Exchange does not support multiple versions for download of the same connector. We are working on additional guidance for how to message this within the gallery listing for customers. We will refine this with you during the connector review process.
