### ISSUE TITLE
[BUG] redirectUrisDesktop format in https://tableau.github.io/connector-plugin-sdk/docs/oauth

### ISSUE THREAD

**Issue by xsgao-github** [tableau/connector-plugin-sdk#1127]
**Describe the bug**
In this doc: https://tableau.github.io/connector-plugin-sdk/docs/oauth, it says:

> Starting in Tableau 2023.1, You can use any valid loopback address like http://localhost:[portnumber]/Callback, http://127.0.0.1:[portnumber]/Callback(IPv4), http://[::1]:[portnumber]/Callback(IPv6). If you use loopback address other than localhost, enable OAUTH_CAP_SUPPORTS_HTTP_SCHEME_LOOPBACK_REDIRECT_URLS as well.

However, in the OAuth Capabilities table, it says:

> 
OAUTH_CAP_SUPPORTS_HTTP_SCHEME_LOOPBACK_REDIRECT_URLS | Only relevant for desktop apps (Tableau Desktop and Prep). When enabled the desktop app callback will use loopback address instead of “localhost”. If using OAUTH_CAP_FIXED_PORT_IN_CALLBACK_URL, the redirectUri must still specify localhost, but is rewritten. For more info see https://developers.google.com/identity/protocols/oauth2/native-app
-- | --

I think the first statement is accurate and the 2nd should be updated.

**Screenshots**

**Desktop (please complete the following information):**
 - OS: n/a
 - Tableau Version: 2023.1

**About you:**
 Name: Song Gao
 Company: Starburst Data

**Comment by lukewrites** [comment]
Internal tracking: W-13292143

**Comment by jkoskela** [comment]
We fixed that recently, but hadn't updated the docs. I will get those updated. Thanks.
