### ISSUE TITLE
[Question] Issue http request in Javascript file

### ISSUE THREAD

**Issue by xsgao-github** [tableau/connector-plugin-sdk#1128]
**About You:**
Name: Song Gao
Company: Starburst Data

**Your question:**
We published a custom data connector using a JDBC driver. We would like to execute an HTTP request in `connectionProperties.js`, then conditionally assemble the properties based on the HTTP response. I tried `https = require('https')` and other various codes to allocate an HTTP client, but those libraries are not available.

 

Would you please let us know which Javascript libraries are available, and which object we can use to execute HTTP requests?

**Comment by rosswbrown** [comment]
Only simple string manipulation of the incoming arguments is supported and allowed within the the .js file. This is by design.
