### ISSUE TITLE
[BUG] Misleading <redirectUrisDesktop> with dynamic port support

### ISSUE THREAD

**Issue by xsgao-github** [tableau/connector-plugin-sdk#1129]
**Describe the bug**
> If the authorization server supports dynamic port ranges for native applications then that should be used.

This is not clear about what should be used. If I use specify `<redirectUrisDesktop>http://localhost:*/Callback</redirectUrisDesktop>`, Tableau will error out.

It should state that: "If the authorization server supports dynamic port ranges for native applications then `<redirectUrisDesktop>` should not be specified."

**Screenshots**
<img width="1088" alt="image" src="https://github.com/tableau/connector-plugin-sdk/assets/39278329/f543cf6c-6f2c-4aad-9ecf-565bc5447d36">

**Desktop (please complete the following information):**
 - OS: MacOS
 - Tableau Version: 2023.1

**About you:**
 Name: Song Gao
 Company: Starburst Data

**Comment by lukewrites** [comment]
Internal tracking ID: W-13486557

**Comment by jinli-dev** [comment]
The confusing part is removed. Please see the updated doc [here](https://tableau.github.io/connector-plugin-sdk/docs/oauth#oauth-on-tableau-desktoptableau-prep).
