### ISSUE TITLE
Tableau desktop needs administration access when authenticating using custom OAuth connector

### ISSUE THREAD

**Issue by UR0082** [tableau/connector-plugin-sdk#1141]
I am trying to develop a custom OAuth connector using AWS Cognito as my OAuth provider. 

When I open the Tableau desktop as an administrator and try to authenticate the flow works fine. The Tableau desktop opens the Chrome browser and authenticates the user and then the access token is provided back to the driver.

The issue is when I do not run the Tableau desktop as an administrator it is stuck at the screen where it says trying to authenticate via browser and the browser never opens. Below I have attached the screenshots of the issue below. 

I have tried these on a couple of other systems with similar OS and desktop configurations and the issue is consistent. 

![image](https://github.com/tableau/connector-plugin-sdk/assets/66296528/8446384d-9b81-4519-aa18-79f2cb987f2f)

 - OS: windows server 2019 Datacenter
 - Tableau Version: 2023.1.0

 Name: Jayaprakash Sivanandam
 Company: USEReady

**Comment by lukewrites** [comment]
Internal tracking: W-13610807

**Comment by jkoskela** [comment]
When we run a desktop flow we start a small webserver to receive the response from the IDP. It's run as java.exe. It will try and listen on one of the ports specified in the config file. In this case it must be failing because of permissions issues to bind to the port, or to launch the system browser.

**Comment by UR0082** [comment]
Hi,

I am an administrator on the machine, and it still requires that I specify that the users run the tableau as an administrator. I cannot have all end users run tableau as administrator. Why does this issue happen only for the custom connector and not for the other built-in connectors that use oauth?

Regards,
Jayaprakash Sivanandam

**Comment by UR0082** [comment]
I am an administrator on the machine, and it still requires that I specify that the users run the tableau as an administrator. I cannot have all end users run Tableau as administrators. Why does this issue happen only for the custom connector and not for the other built-in connectors that use OAuth?
