### ISSUE TITLE
[BUG] Web Data Connector 3.0 EPS OAuth does not support connection dialog

### ISSUE THREAD

**Issue by chunqinghong** [tableau/connector-plugin-sdk#1142]
**Describe the bug**
Building a connector supporting multiple OAuth configs in Web Data Connector 3.0 running an EPS server throws an error when launching the connection dialog. Any workflow that would launch a Connection Dialog, such as allowing editable fields also throws the same exception.

The error message is: 
Unexpected error
Error: TypeError: Cannot read property 'connectorAppUrl' of undefined

**Screenshots**
![image](https://github.com/tableau/connector-plugin-sdk/assets/2489230/4c53d7d2-4e6e-4d25-b073-b2e1b354ada8)

**Desktop (please complete the following information):**
 - OS: Mac OSX
 - Tableau Version: 2023.2

**About you:**
 Name: Roger Hong
 Company: Visier

**Comment by lukewrites** [comment]
Internal tracking: W-13652623

**Comment by jchen-tab** [comment]
Not sure I follow....the Tableau Connector Plugin SDK and WDC 3.0 SDK are, more or less, completely separate SDKs. There is no concept of multiple oauth configs in WDC 3.0.
