### ISSUE TITLE
setClientInfo capability

### ISSUE THREAD

**Issue by gs-manvig** [tableau/connector-plugin-sdk#1146]
**Question:**
There is a `CAP_JDBC_SET_CLIENT_INFO` capability documented [here](https://tableau.github.io/connector-plugin-sdk/docs/capabilities) which says 'Needs additional configuration see documentation'.

Could you please share documentation on the additional configuration needed? And maybe the github docs could be updated with appropriate links

**About You:**
Name: Vignesh Manickavasagam
Company: Goldman Sachs

**Comment by lukewrites** [comment]
Internal tracking: W-13660186

**Comment by rosswbrown** [comment]
Thanks for the feedback. We've updated the `CAP_JDBC_SET_CLIENT_INFO` documentation to include a link to the [Query Tagging](https://help.tableau.com/current/api/rest_api/en-us/REST/rest_api_how_to_query_tagging.htm) documentation page.
