### ISSUE TITLE
Does OAuth authentication require the offline_access scope?

### ISSUE THREAD

**Issue by joe-chu** [tableau/connector-plugin-sdk#1152]
**About You:**
Name: Joe Chu
Company: Starburst Data

**Your question:**
I've tried configuring a connector with OAuth authentication that uses VMware Workspace One Access as the IdP. When testing I get an error: "Error Code: FF9C14D9  Tableau detected that your OAuth refresh token is expired. Reauthenticate with new credentials."

Workspace One Access can be configured to generate a refresh token, but does not support a scope for offline_access. Without that scope, Tableau will return the above error even though the response to the token request contains a refresh_token field (and mapped accordingly).

I was also to reproduce this error using Okta as the IdP, first using a known working configuration and then just removing the offline_access scope to reproduce the error.

Is there a reason why offline_access scope is required, if that's the case? [RFC 6749](https://datatracker.ietf.org/doc/html/rfc6749#section-1.5) does not indicate any scope needed for requesting a refresh token. I did find a reference to Offline Access in the [OpenID specification](https://openid.net/specs/openid-connect-core-1_0.html#OfflineAccess) but even then it mentions:
"The use of Refresh Tokens is not exclusive to the offline_access use case. The Authorization Server MAY grant Refresh Tokens in other contexts that are beyond the scope of this specification."

**Comment by jkoskela** [comment]
I don't see anything in our code that is relying on offline_access. We aren't doing anything with it but passing it to the IDP. Are you sure about that? How did you test this?

**Comment by xsgao-github** [comment]
Tableau custom data connector requires `refresh_token` to work (`access_token` alone won't work). So the question is not strictly about `offline_access` scope. You need to specify the correct (specific to your IDP) scopes and let your IDP return `refresh_token`.

**Comment by joe-chu** [comment]
I am wrong about this. After reviewing the oauth-service.log, I can see that the error is a result of trying to refresh the access_token using the refresh_token, but with the IdP returning a 401 Unauthorized. I'll continue to investigate from here. Thank you for the quick response to my question.

**Comment by xsgao-github** [comment]
@joe-chu You can take a look at #1148, and there is a [log](https://github.com/tableau/connector-plugin-sdk/files/11887659/token_requests.txt) showing why refreshing token failed.
