### ISSUE TITLE
Access [TableauServerUser] and others variables in custom connector

### ISSUE THREAD

**Issue by xsgao-github** [tableau/connector-plugin-sdk#1153]
**About You:**
Name: Song Gao
Company: Starburst Data

**Your question:**
In the `Initial SQL` input box, users can put runtime variables, e.g. `[TableauServerUser]`. Can custom data connector have access to those variables?

If I can access `[TableauServerUser]`, I can pass it to my JDBC driver to filter/secure data.

**Comment by jkoskela** [comment]
This is called impersonation in the SDK.
Here is an example: [samples/scenarios/templates/db_impersonation](https://github.com/tableau/connector-plugin-sdk/tree/0af4924afacd482fd00575063348883d3eca8ae3/samples/scenarios/templates/db_impersonation).

Important points
- Enable the capability in the [manifest](https://github.com/tableau/connector-plugin-sdk/blob/0af4924afacd482fd00575063348883d3eca8ae3/samples/scenarios/templates/db_impersonation/manifest.xml#L47).
- Pass username to the driver [connectionProperties.js](https://github.com/tableau/connector-plugin-sdk/blob/0af4924afacd482fd00575063348883d3eca8ae3/samples/scenarios/templates/db_impersonation/connectionProperties.js#L22)

However, this is only available when publishing from Tableau Desktop. If the capability is enabled the user will see an option when they publish. The common use case is that data stewards will publish like this and embed a service account credentials in the datasource, which has the ability to impersonate other users.

If you have more questions let's talk on slack.
