### ISSUE TITLE
DOCS: confusing default dialect

### ISSUE THREAD

**Issue by astefan** [tableau/connector-plugin-sdk#118]
I am testing a JDBC connector I'm working on and I get mixed results based on the `base` dialects I'm using in my tests.

According to the documentation [here](https://tableau.github.io/connector-plugin-sdk/docs/dialect):

> 

base | N | Specifies a base dialect to build upon. If a certain property or function isn’t defined in a dialect definition file, the connector will fall back to its base dialect’s behavior if a base is defined, and SQL-92 default behavior if there is no base. Important: This must be a valid, existing dialect. If the specified base does not exist, the connector will fail to load. For a list of bases, see Dialect base classes.
-- | -- | --

My `dialect.tdd` file header is the following (and the rest of the file is empty):

```
<?xml version="1.0" encoding="utf-8"?>
<dialect name='Custom'
         class='custom_jdbc'
         version='18.1'>
		 <!--base='SQL92Dialect'-->
   <function-map>
```

**Having the `dialect.tdd` file without a `base` (as shown above) my tests output:**

```
Total time: 194.51126885414124
Total failed tests 633
Total tests ran 715
```

According to the documentation, if there is a base, that dialect will be used, if there is no base then **SQL-92 default behavior is used**. **My second test was adding as base `SQL92Dialect`**:

```
<?xml version="1.0" encoding="utf-8"?>
<dialect name='Custom'
         class='custom_jdbc'
         base='SQL92Dialect'
         version='18.1'>
		 <!---->
   <function-map>
```

This dialect is not listed [here](https://tableau.github.io/connector-plugin-sdk/docs/design#dialect-base-classes), but the tests ran and they generated a different output, even though I would have assumed (based on the docs) that the same dialect should have been used and, implicitly, the same output should have been generated:

```
Total time: 227.23913717269897
Total failed tests 690
Total tests ran 811
```

As you can see, the number of tests that ran is different, the same can be said about the number of failed tests.

1. is the documentation correct regarding the `base` dialect fallback?
2. is `SQL92Dialect` a valid base dialect? If it is, the statement saying _SQL-92 default behavior is used_ means a different base dialect is used by default?
3. in the samples one can find `full_dialect.tdd` file, but I would be interested in seeing other DBs dialects, for example `PostgreSQL90Dialect`. Are these available somewhere?

Many thanks.

**Comment by lriggs** [comment]
Hi,

Try using 'DefaultSQLDialect' as your base dialect. We recently added that one as a generic customization point. It implements SQL-92 and you can further customize it as needed. I'll update our documentation to reflect this.

I will also open a work item to provide an example of the PostGres dialect. One approach you could take in the meantime is to follow our examples and setup a PostGres database and then run all the tests against it using the native PostGres connector. Then you can inspect the generated SQL for each test case and use that to guide your dialect development.

**Comment by BobSenturus** [comment]
@lriggs Can you tell us which dialect the ODBC connector in Tableau uses?  We're trying the DefaultSQLDialect but it seems like we're seeing different message patterns to the server with our plugin connector than we get with just ODBC.

**Comment by lriggs** [comment]
@BobSenturus The "Default ODBC" connector dynamically configures much of the dialect based on what the driver reports through the ODBC API and some exploratory queries on our side. We have some enhancements in mind to allow you to save a dialect from an existing connector which might help with this. Our "DefaultSQLDialect" is a very plain starting point. You will need to do more work in the dialect file to add any missing functions. If your database is similar to an existing one, then it is probably better to start with that dialect.

**Comment by jsun28** [comment]
DefaultSQLDialect is no longer recommended as base dialect.
