### ISSUE TITLE
Output mismatch between TDVT and Tableau custom SQL

### ISSUE THREAD

**Issue by GumpacG** [tableau/connector-plugin-sdk#1180]
**About You:**
Name: Guian Gumpac
Company: Improving

**Your question:**
Is there a configuration that would create an output mismatch between TDVT and Tableau custom SQL with the same query as TDVT generates?

I am running the test `Query.Top99_ByField` and TDVT generates the query
```
SELECT `Staples`.`Employee Name` AS `Employee Name`,
  AVG(`Staples`.`Employee Salary`) AS `avg_Employee Salary_ok`
FROM `staples` `Staples`
GROUP BY `Employee Name`
ORDER BY `avg_Employee Salary_ok` DESC
LIMIT 99
```

TDVT output:
<img width="454" alt="Screenshot 2023-09-16 at 5 43 10 PM" src="https://github.com/tableau/connector-plugin-sdk/assets/29149268/67bdbd53-967a-4519-bee5-46cdf23901bd">

Tableau custom SQL output:
<img width="753" alt="Screenshot 2023-09-16 at 5 49 00 PM" src="https://github.com/tableau/connector-plugin-sdk/assets/29149268/35f749ef-1fa0-4c2e-b709-e42250900613">

For context, I get the same output in DBVisualizer as the Tableau custom SQL output.

Logs:
[tabquery_logs.zip](https://github.com/tableau/connector-plugin-sdk/files/12641805/tabquery_logs.zip)
[test_results_combined.csv](https://github.com/tableau/connector-plugin-sdk/files/12641807/test_results_combined.csv)
[tdvt_log_combined.txt](https://github.com/tableau/connector-plugin-sdk/files/12641808/tdvt_log_combined.txt)

**Comment by lukewrites** [comment]
Internal tracking: W-14138460

**Comment by rosswbrown** [comment]
I'd recommend reviewing that the connector's `LIMIT` and `ORDER BY` clauses are defined and working as expected. 

For `ORDER BY` the [default](https://github.com/tableau/connector-plugin-sdk/blob/master/samples/components/dialects/SQLDialect.tdd#L209) is `<format-order-by value='DirectionOnly' />`, though in many cases `<format-order-by value='Nulls' />` is correct. Less commonly one of the [other values](https://github.com/tableau/connector-plugin-sdk/blob/master/validation/tdd_latest.xsd#L238) maybe be correct. These [capabilities](https://tableau.github.io/connector-plugin-sdk/docs/design#review-capabilities-list) can also impact the query generated in this test:
- CAP_QUERY_GROUP_BY_DEGREE
- CAP_QUERY_SORT_BY_DEGREE

For `LIMIT` the `<part name='Top' value='LIMIT %1 ' />` order within the `<format-select>` ([default definition](https://github.com/tableau/connector-plugin-sdk/blob/master/samples/components/dialects/SQLDialect.tdd#L214C5-L214C20)) is the determining factor. It appears from your logs this is likely already customized for your data source. 

This is a screenshot of the scenario in Tableau Desktop the test is simulating if that is helpful in diagnosing the issue.

![Query Top99_ByField](https://github.com/tableau/connector-plugin-sdk/assets/6444215/b3b67a20-a47c-48c8-b6c2-90dc59923778)

**Comment by rosswbrown** [comment]
Let us know if you still have questions about this issue. Closing.
