### ISSUE TITLE
Incorrect Expected Tuple in DATEDIFF('week', [date3], [date2], 'monday')

### ISSUE THREAD

**Issue by ravjotbrar** [tableau/connector-plugin-sdk#1181]
**About You:** 
Name: Ravjot Brar
Company: Dremio

**Your question:**
I'm working on some TDVT test failures for our new connector, specifically the test case DATEDIFF('week', [date3], [date2], 'monday'). I noticed one of the tuples involving Friday November 7, 1980 and Sunday April 1, 1979 is expected to be 83 weeks. However, with Monday being the start of the week, we should add an extra week, making it 84 weeks. Am I missing something here?

**Comment by lukewrites** [comment]
Internal tracking: W-14141342

**Comment by ravjotbrar** [comment]
I noticed there are different expected files and I was only focusing on the one in my csv results. After modifying the query I was able to match it to another expected file.

**Comment by rosswbrown** [comment]
I'm glad you were able to resolve your issue. In general when this test fails there are two things to look at in the [dialect definition](https://tableau.github.io/connector-plugin-sdk/docs/dialect#function-map-element).

First check the Custom Start of Week function for `DATEDIFF`:
> To support Tableau’s Custom Start of Week functionality each of the following: DATEDIFF, DATENAME, DATEPART, DATETRUNC need to also have an overloaded form with an additional <argument type='localstr' />.
```
    <date-function name='DATEDIFF' return-type='int'>
      <formula part='week'>DATEDIFF(week,%2,%3)</formula> // example
      <argument type='localstr' />
      <argument type='datetime' />
      <argument type='datetime' />
      <argument type='localstr' />
    </date-function>
```

Second check the `<start-of-week-offset value='...' />` definition. The [default value](https://github.com/tableau/connector-plugin-sdk/blob/master/samples/components/dialects/SQLDialect.tdd#L273) is `0`.

**Comment by ravjotbrar** [comment]
The start-of-week-offset value is really helpful. Thanks @rosswbrown!
