### ISSUE TITLE
Actual results for some TDVT datename.sow and datepart.sow test cases are correct but do not match any expected results

### ISSUE THREAD

**Issue by hab6** [tableau/connector-plugin-sdk#1182]
**About You:**
Name: Michael Habiger
Company: Actian Corporation

**Your question:**
These test cases are returning correct actual results, but do not match any of the expected results.

Test Name | Test Case
--|--
date.datename.sow.week | DATENAME('week', [date2], 'monday')
date.datepart.sow.week | DATEPART('week', [date2], 'monday')

Checking the operations manually using the definition for [ISO week date](https://en.wikipedia.org/wiki/ISO_week_date) and using various ISO 8601 "week of year" calculators on the web indicates that the actual results are correct and that a few of the TDVT expected values are incorrect.

**Environment:**
MS Windows 10 Enterprise
Tableau Desktop 2023.2
Connector SDK [repository](https://github.com/tableau/connector-plugin-sdk) cloned from master branch on Sep 20, 2023
Actian JDBC Tableau Connector (development/testing)
Actian Vector 6.3 on Ubuntu 20.04 LTS

**Request:**
We would like to request that a new expectation file be added (or an existing one be updated?) to match the Actian results.

**Actian TDVT Actual Results:**
[actual.setup.date.datename.sow.week.txt](https://github.com/tableau/connector-plugin-sdk/files/12676643/actual.setup.date.datename.sow.week.txt)
[actual.setup.date.datename.sow.week_diff.txt](https://github.com/tableau/connector-plugin-sdk/files/12676640/actual.setup.date.datename.sow.week_diff.txt)
[actual.setup.date.datepart.sow.week.txt](https://github.com/tableau/connector-plugin-sdk/files/12676641/actual.setup.date.datepart.sow.week.txt)
[actual.setup.date.datepart.sow.week_diff.txt](https://github.com/tableau/connector-plugin-sdk/files/12676642/actual.setup.date.datepart.sow.week_diff.txt)

**Relevant Expected Results Files:**
[expected.setup.date.datename.sow.week.txt](https://github.com/tableau/connector-plugin-sdk/blob/master/tdvt/tdvt/exprtests/standard/expected.setup.date.datename.sow.week.txt)
[expected.setup.date.datename.sow.week.1.txt](https://github.com/tableau/connector-plugin-sdk/blob/master/tdvt/tdvt/exprtests/standard/expected.setup.date.datename.sow.week.1.txt)
[expected.setup.date.datename.sow.week.2.txt](https://github.com/tableau/connector-plugin-sdk/blob/master/tdvt/tdvt/exprtests/standard/expected.setup.date.datename.sow.week.2.txt)
[expected.setup.date.datepart.sow.week.txt](https://github.com/tableau/connector-plugin-sdk/blob/master/tdvt/tdvt/exprtests/standard/expected.setup.date.datepart.sow.week.txt)
[expected.setup.date.datepart.sow.week.1.txt](https://github.com/tableau/connector-plugin-sdk/blob/master/tdvt/tdvt/exprtests/standard/expected.setup.date.datepart.sow.week.1.txt)
[expected.setup.date.datepart.sow.week.2.txt](https://github.com/tableau/connector-plugin-sdk/blob/master/tdvt/tdvt/exprtests/standard/expected.setup.date.datepart.sow.week.2.txt)

**Comment by lukewrites** [comment]
Hi @hab6 could you bring this conversation to your internal repo? Let's continue the conversation there - it looks like the test cases is right and there may be an implementation issue in the dialect file.

**Comment by hab6** [comment]
@lukewrites Issue [2](https://github.com/Tabloids/Actian-Connector/issues/2) in our internal repo has been updated with details.
