### ISSUE TITLE
Disable calculated fields

### ISSUE THREAD

**Issue by aiguofer** [tableau/connector-plugin-sdk#1188]
In our connector, most transformations are defined in our Semantic Layer so it doesn't really make sense to create calculated fields in Tableau. I disabled most functions in the `dialect.tdd` file, but the option to create a calculated field is still available. We'd like to remove this to make sure our users don't run into unexpected errors while attempting to do so. Is there a way to disable this functionality?

**Comment by lukewrites** [comment]
Hi, @aiguofer there is not a way to disable calculated fields.
