### ISSUE TITLE
Unable to fetch continuous year and month by using dialect file.

### ISSUE THREAD

**Issue by akash-singh478** [tableau/connector-plugin-sdk#1199]
Name: Akash Singh

I am unable to get continuous year, month, day, week number on the tableau worksheet having issue while using the formulae -

<formula>CAST(TRUNCATE(%1(%2),1) AS INTEGER)</formula>
<formula part='weekday'>(1 + CAST(DAYOFWEEK(%2) AS INTEGER))</formula>
<formula part="week">CAST(FLOOR((7 + (DAYOFYEAR(%2)) - 1 + (DAYOFWEEK(%2))) / 7) AS INTEGER)</formula>
<formula part='iso-quarter'>TO_DATE(TO_CHAR(%2, &apos;IYYY-&apos;) || (LEAST(CAST((EXTRACT(WEEK FROM %2) - 1) AS BIGINT) / 13, 3) * 13 + 1), &apos;IYYY-IW&apos;)</formula>

<formula part='iso-week'>CAST(TRUNC(EXTRACT(WEEK FROM %2)) AS INTEGER)</formula>
<formula part='iso-weekday'>CAST(TRUNC(EXTRACT(ISODOW FROM %2)) AS INTEGER)</formula>
<formula part='iso-year'>CAST(TRUNCATE(YEAR(%2)) AS INTEGER)</formula>
<argument type='localstr' />
<argument type='datetime' /> 

Could you please help!

**Comment by lukewrites** [comment]
Internal tracking: W-14480389

**Comment by tabsdavis** [comment]
@akash-singh478 Not sure what we are looking at here and need more context. Is this part of a certain function definition in a particular connector plugin’s dialect? I don't see correct syntax for an initial sql excerpt or calculated field. Can you provide the scenario you were using this formulae with?

**Comment by tabsdavis** [comment]
Closing issue. Can be re-opened with more information.
