### ISSUE TITLE
[BUG] Installation using setup.py is deprecated

### ISSUE THREAD

**Issue by kaklakariada** [tableau/connector-plugin-sdk#1203]
**Describe the bug**
Installing the SDK according to the [instructions](https://tableau.github.io/connector-plugin-sdk/docs/package-sign) by executing `python setup.py install` logs the following warning:

```
running install
/path/to/tableau-connector/target/sdk/connector-packager/.venv/lib/python3.11/site-packages/setuptools/_distutils/cmd.py:66: SetuptoolsDeprecationWarning: setup.py install is deprecated.
!!

        ********************************************************************************
        Please avoid running ``setup.py`` directly.
        Instead, use pypa/build, pypa/installer or other
        standards-based tools.

        See https://blog.ganssle.io/articles/2021/10/setup-py-deprecated.html for details.
        ********************************************************************************
```

Please adapt the documentation to describe a non-deprecated way of installing the SDK.

**Desktop (please complete the following information):**
 - OS: macOS 13.6.1
 - Tableau Version: 2023.3

**About you:**
 Name: Christoph Pirkl
 Company: Exasol

**Comment by lukewrites** [comment]
W-14763004
