### ISSUE TITLE
Adding wildcards to string arguments

### ISSUE THREAD

**Issue by cdessanti** [tableau/connector-plugin-sdk#1205]
Name: Candido Dessanti
Company: HEAVY.AI

Is there a method to incorporate wildcards directly into literals without resorting to string functions such as concat? Specifically, in the context of using the "contains" condition, I aim to include '%' before and after the string. However, when I formulate it as (%1 LIKE '%%2%'), the second argument is enclosed in single quotes.

Is there a way to extract the string argument without it being automatically quoted?

I have successfully implemented the formula using string functions, functioning as intended. However, from a performance perspective, achieving this without relying on string manipulation functions would be more optimal.

**Comment by lukewrites** [comment]
Internal tracking: W-14661560

**Comment by lukewrites** [comment]
Hi @cdessanti - is this a question related to a connector you're building, or is it more about general Tableau use?

**Comment by cdessanti** [comment]
My question is related to the connector I updated to make use of the standard tbaleu string functions, and specifically for the contains/start_with and ends_with functions

**Comment by rosswbrown** [comment]
We do not have this level of string literal customization available in [format-string-literal](https://tableau.github.io/connector-plugin-sdk/docs/dialect#string-literal-support)
