### ISSUE TITLE
custom probe query after enabling CAP_FORCE_CONNECTION_VERIFICATION

### ISSUE THREAD

**Issue by xsgao-github** [tableau/connector-plugin-sdk#1207]
**About You:**
Name: Song Gao
Company: Starburst Data

**Your question:**
We are using the Trino JDBC driver and enabled `CAP_FORCE_CONNECTION_VERIFICATION` in our connector per [this doc](https://tableau.github.io/connector-plugin-sdk/docs/capabilities):

CAP_FORCE_CONNECTION_VERIFICATION | Set to ‘yes’ to verify connection status during initial connection by running a probe query. Available in Tableau 2022.2 and newer.
-- | --

Now I see Tableau always sends a query `select version()` during connection.

My questions are: 

1. Where is this probe query defined? 
2. Can I customize this query or even add a function to validate the returned resultset of the probe query?

**Comment by rosswbrown** [comment]
The current design of `CAP_FORCE_CONNECTION_VERIFICATION` does not check the result of the probe query. The probe query should always `SELECT 1` for a connector built from the SDK.

What is your desired use case with a potential customization?

**Comment by xsgao-github** [comment]
My bad.  The probe query is `SELECT 1`.

I would like to add some validation on Tableau connector. For example, if the server does not meet the minimum version of server requirement, error it out.

**Comment by rosswbrown** [comment]
Ok, that makes sense. Please open an issue about your desire to enforce the minimum server version as a part of defining a connector. Anything like this would be decoupled from `CAP_FORCE_CONNECTION_VERIFICATION`.

I'll make sure it gets tagged as a potential enhancement. Thanks.

**Comment by xsgao-github** [comment]
Feature request here https://github.com/tableau/connector-plugin-sdk/issues/1210
