### ISSUE TITLE
[BUG] SPACE(int2) could not catch invalid result when connector returns `space(0) = null`

### ISSUE THREAD

**Issue by xsgao-github** [tableau/connector-plugin-sdk#1211]
**Describe the bug**
We noticed a bug that our custom connector (`Starburst Enterprise by Starburst`) does not return correct value for formula `space(0)`. Instead of empty string (`''`), it returns `null`.

However, tdvt test suite could not capture this error.

In test case `SPACE(int2)`, there is a expected value `<value>&quot;&quot;</value>`. But tdvt did not error out when our connector never returned an empty string.

Furthermore, I think only checking the formula output without corresponding input is a bad idea. Instead of checking `SPACE(int2)` only, we should check `int2, SPACE(int2)`.

**Screenshots**
The screenshot below shows that our connector did not convert the `space(param)` correctly and still passed the test.

<img width="1746" alt="image" src="https://github.com/tableau/connector-plugin-sdk/assets/39278329/e696df37-b4d0-4136-a1a4-766e0a2dad86">

**Desktop (please complete the following information):**
 - OS: macOS
 - Tableau Version: 2023.3

**About you:**
 Name: Song Gao
 Company: Starburst Data

**Comment by rosswbrown** [comment]
Thanks for raising this issue. The existing `string.space` tests do have some ambiguity regarding correctness. Based on your suggestion we've added an explicit `string.space.empty` test case that should catch this issue in the future.
