### ISSUE TITLE
[BUG] GetProductName return Tableauserver for TableauCloud

### ISSUE THREAD

**Issue by eric-wang-1990** [tableau/connector-plugin-sdk#1212]
Thanks for filing a bug report! Please check out our docs on [Filing a Bug with the SDK](https://tableau.github.io/connector-plugin-sdk/docs/bug-artifacts) for guidance on what to include with your report. 

**Describe the bug**
As listed here https://tableau.github.io/connector-plugin-sdk/docs/api-reference.html the GetProductName should return TableauCloud for TableauCloud, but as our tests it just return TableauServer.

**Screenshots**
<img width="554" alt="image" src="https://github.com/tableau/connector-plugin-sdk/assets/115501094/7510f65c-cd0b-445e-bd6c-aae203e7386e">
agent captured:
"thriftUserAgent":"SimbaSparkODBCDriver/2.7.5.1012 Thrift/0.9.0 (C++/THttpClient) TableauServer/2024.1.0"

**Desktop (please complete the following information):**
 - OS:
 - Tableau Version

**About you:**
 Name: Eric Wang
 Company: Databricks

**Comment by lukewrites** [comment]
Nice Issue number, @eric-wang-1990 😄 

Internal tracking: W-14869726

**Comment by pvanderknyff** [comment]
Hi Eric,

Looking in to this, investigation will probably take a while longer since we most likely will need to add some logging to cloud to track this down.

For context, are you always seeing "Tableau Server"? Or do you sometimes see "Tableau Cloud"?

**Comment by eric-wang-1990** [comment]
> Hi Eric,
> 
> Taking a look at this. GetProductName logic looks sound, investigation will probably take a while longer since we most likely will need to add some logging to cloud to track this down.
> 
> For context, are you always seeing "Tableau Server"? Or do you sometimes see "Tableau Cloud"?

We only see Tableau Server, Tableau Desktop, Tableau. We never see Tableau Cloud.

**Comment by pvanderknyff** [comment]
Hi Eric, thanks for your patience. The investigation took longer than expected, your issue uncovered an underlying problem that one process was not correctly being labeled as "Tableau Cloud" on startup. We've fixed this on our end, and GetProductName should be returning the correct value now (or very soon, depending on when the next Cloud update is). Closing this issue as fixed, please reopen if you're still not seeing Tableau Cloud as a result.
