### ISSUE TITLE
While running TDVT test suite getting issue on DataSourceException: No such function $IN_SET$ that takes arguments of type (str, datetime, datetime, datetime).

### ISSUE THREAD

**Issue by Arunbaddipadige** [tableau/connector-plugin-sdk#1220]
Thanks for filing a bug report! Please check out our docs on [Filing a Bug with the SDK](https://tableau.github.io/connector-plugin-sdk/docs/bug-artifacts) for guidance on what to include with your report. 

**Describe the bug**

While running TDVT test suite getting issue on DataSourceException: No such function $IN_SET$ that takes arguments of type (str, datetime, datetime, datetime).
[tabquery_logs.zip](https://github.com/tableau/connector-plugin-sdk/files/14232960/tabquery_logs.zip)
[tdvt_output_combined.json](https://github.com/tableau/connector-plugin-sdk/files/14232961/tdvt_output_combined.json)
[test_results_combined.csv](https://github.com/tableau/connector-plugin-sdk/files/14232962/test_results_combined.csv)

**Screenshots**

**Desktop (please complete the following information):**
 - OS: windows 10
 - Tableau Version :- 2021.4

**About you:**
 Name:ArunKumar
 Company: Trianz

**Comment by lukewrites** [comment]
Internal tracking: W-15024673

**Comment by tabsdavis** [comment]
Reviewed error and confirmed this has been something seen before which we've had a few suggestions for. See:

https://github.com/tableau/connector-plugin-sdk/issues/1190#issuecomment-1751307057
https://github.com/tableau/connector-plugin-sdk/issues/916#issuecomment-1055648786
However I would look closely here: https://github.com/tableau/connector-plugin-sdk/issues/742#issuecomment-813650391
Recommendation: "...Starting with something like [this example dialect](https://github.com/tableau/connector-plugin-sdk/blob/master/samples/plugins/postgres_odbc/dialect.tdd) and modifying it as necessary"

**Comment by tabsdavis** [comment]
Closing issue. Will re-open if the feedback has been attempted and Arunbaddipadige is still looking for a solution.
