### ISSUE TITLE
[Question] Custom String escaping functionality

### ISSUE THREAD

**Issue by BentsiLeviav** [tableau/connector-plugin-sdk#1221]
Hi Tableau team,

I'm trying to run the TDVT tests suite and facing some issues related to string escaping.
Our [connector](https://github.com/ClickHouse/clickhouse-tableau-connector-jdbc/blob/main/clickhouse_jdbc/dialect.tdd) is based on the `PostgreSQL90Dialect` dialect.

When running the `string.contains.regex` test, the generated SQL is escaping the string `"A\"` with an escape string constant of `E` (as it works for Postgres). 
Is there a way to overwrite the escape functionality in my dialect?

**Comment by yurifal** [comment]
Hi @BentsiLeviav, 

It was my decision to set the  `PostgreSQL90Dialect` as the base one, 
mainly for the `ISO-8601` Calendar to be available (in Tableau Desktop / Web Edit).
I guess you may write any other dialect in the TDD as a base, for example `MySQL8Dialect`.

Yours,
Yuri

**Comment by rosswbrown** [comment]
The `E` prefix comes from using `<format-string-literal value='Extended' />`. I would recommend trying to use `<format-string-literal value='Standard' />` as a starting point.

Additional [documentation](https://tableau.github.io/connector-plugin-sdk/docs/dialect#string-literal-support) and [sample](https://github.com/tableau/connector-plugin-sdk/blob/master/samples/components/dialects/SQLDialect.tdd#L244)
