### ISSUE TITLE
Date format `MM/dd/yyyy`

### ISSUE THREAD

**Issue by BentsiLeviav** [tableau/connector-plugin-sdk#1222]
Hello,
This issue might be related to tableau/connector-plugin-sdk#892 which closed.
In my ClickHouse dialect, I have these settings configured:
```
<format-date-literal formula="DATE '%1'" format='yyyy-MM-dd' />
<format-datetime-literal formula="TIMESTAMP '%1'" format='yyyy-MM-dd HH:mm:ss' />
```
In the given test case, the passed date string is not being transformed correctly:

![image](https://github.com/tableau/connector-plugin-sdk/assets/46030906/cf533508-498d-4ae3-a1df-7c98db8b3209)

The test case includes this date `#4/12/2010#` with the format of `MM/dd/yyyy`, but the generated SQL creates the date `2010-12-04` with the format of `yyyy-dd-MM` even though `format-date-literal formula` is set to `'yyyy-MM-dd' `

Could you please advise on this? Did I miss something?

_Originally posted by @BentsiLeviav in https://github.com/tableau/connector-plugin-sdk/issues/892#issuecomment-1970911764_

**Comment by pvanderknyff** [comment]
It looks like from the screenshot the test is passing? I think that means your connector is working as expected. Are you seeing any test failures related to literal date formats?

It's odd that it's transposing the date and month but I can't tell from this context if it's a one-off in a test that is ultimately passing or a widespread issue causing multiple tests to fail.

**Comment by pvanderknyff** [comment]
Closing, please reopen if this is still an issue

**Comment by BentsiLeviav** [comment]
Hi @pvanderknyff,

It is a bit confusing at first look, but if you look closely you will notice the last dates are not equal (`2010-12-04` vs `2010-04-12`).

**Comment by BentsiLeviav** [comment]
I'm unable to reopen. @pvanderknyff / @lukewrites could you please reopen this?
