### ISSUE TITLE
set connection timeout

### ISSUE THREAD

**Issue by xsgao-github** [tableau/connector-plugin-sdk#1238]
**About You:**
Name: Song Gao
Company: Starburst Data Inc.

**Your question:**
If our data source server goes sleeping, it will take minutes to wake it up. So the first connection may take minutes as well, and causes Tableau error before connection is make by JDBC driver.

Is that possible to configure "connection timeout" in a Tableau connector?

**Comment by pvanderknyff** [comment]
Unfortunately, it is not possible to configure the connection timeout.
