### ISSUE TITLE
Tableau Desktop is not recognizing the signed taco

### ISSUE THREAD

**Issue by roshanrajan-test** [tableau/connector-plugin-sdk#1244]
**About You:**
Name: Roshan

**Your question:**
I have a taco file signed using a codesigning certificate.
The file verification with "jarsigner -verify test.taco -verbose -certs -strict" is done with no error or warnings.
Done using jdk-22.

<img width="353" alt="Verify" src="https://github.com/user-attachments/assets/9d166a53-aa81-4c53-9e4c-99f798903122">

However still getting error in Tableau Desktop/Server when using the taco.

Attached error: 
<img width="373" alt="TDError" src="https://github.com/user-attachments/assets/d7e1bab7-3eac-45dc-bdd0-93cd71e2df5f">

**Comment by pvanderknyff** [comment]
What do the logs say? https://tableau.github.io/connector-plugin-sdk/docs/log-entries

Is this a self-signed certificate? Tableau doesn't accept those.

Also, if this is a cert that you manually added to your JRE's cacerts you'll also need to do that for the bundled JRE that Tableau uses. However, a taco signed like this will not be accepted to the Tableau Exchange, as the taco should work on any machine without needing to import certs.

If it's not the above, it may be a bug with the taco verification, although it's usually an environmental issue. Can you post the full jarsigner output and the taco signature verification log lines?

**Comment by roshanrajan-test** [comment]
Hi @pvanderknyff 

To answer your question, it is a CA signed certificate.

And based on your suggestion I was able to fix the issue by adding the certificate chain to the Tableau bundled keystore.
Appreciate your prompt response and valuable inputs.

**Comment by roshanrajan-test** [comment]
Thank you.
