### ISSUE TITLE
How to enable recommended test

### ISSUE THREAD

**Issue by kaklakariada** [tableau/connector-plugin-sdk#1249]
**About You:**
Name: Christoph Pirkl
Company: Exasol AG

**Your question:**
I would like to add support for the `DATEPARSE` function in our [Tableau connector](https://github.com/exasol/tableau-connector/blob/main/tdvt_jdbc/config/exasol_jdbc.ini) and enable the TDVT tests for this function. They seem to be deactivated by default. I didn't find an option 

This is our current TDVD configuration: https://github.com/exasol/tableau-connector/blob/main/tdvt_jdbc/config/exasol_jdbc.ini

**Comment by yurifal** [comment]
add the following section in your config:

```
[DateParseTests]
Type = expression
Name = DateParseTests.
TDS = cast_calcs.*.tds
TestPath = exprtests/dateparse

```

**Comment by kaklakariada** [comment]
Thank you for your help, it worked!

**Comment by yurifal** [comment]
Nice.
