### ISSUE TITLE
Remember or store password

### ISSUE THREAD

**Issue by chriiisiscoding** [tableau/connector-plugin-sdk#1254]
**About You:**
Name: Chris A
Company:

**Your question:**

We have built a custom connector where users need to enter an API key to connect to the data source. Currently, we are using the password field in the form and insert the API key into the JDBC string. Rather than having to enter the password every time they connect to the data source, would it be possible for the connector to remember the API key / password?

**Comment by pvanderknyff** [comment]
By design, we do not have the connector remember the password for security reasons. If you're on server, I believe you can use Saved Credentials to not be prompted every time in Account Settings: https://help.tableau.com/current/online/en-us/manage_stored_credentials.htm

**Comment by pvanderknyff** [comment]
Updating this for posterity. I was mistaken in my previous answer, saved credentials only works for OAuth connectors, not for password-only connectors. For those, you can embed the password when publishing the workbook. 

https://help.tableau.com/current/pro/desktop/en-us/publishing_sharing_authentication.htm

**Comment by chriiisiscoding** [comment]
In the [documentation](https://help.tableau.com/current/online/en-us/manage_stored_credentials.htm) it says "...OAuth access tokens, or other credentials, such as user name and password...". Is that not correct?
