### ISSUE TITLE
Connector not available in Account Settings

### ISSUE THREAD

**Issue by chriiisiscoding** [tableau/connector-plugin-sdk#1258]
**About You:**
Name: Chris
Company:

**Your question:**

This is a follow-up to a [previous question](https://github.com/tableau/connector-plugin-sdk/issues/1254) about storing credentials. According to that documentation, the user should be able to go to Account Settings and [store the credentials](https://help.tableau.com/current/online/en-us/manage_stored_credentials.htm). We provided the user with an (unsigned) `.taco` file and he was able to see the connector. However, he did not see it in the Account Settings. Do we need to configure the connector in a specific way that makes it show up in Account Settings so that credentials can be stored? Or is it a problem that the connector is not signed yet?

**Comment by pvanderknyff** [comment]
Hi, I was mistaken in the previous answer, saved credentials only works for OAuth connectors, not for password-only connectors. For those, you can embed the password when publishing the workbook. Will update the previous answer as well.

https://help.tableau.com/current/pro/desktop/en-us/publishing_sharing_authentication.htm
