### ISSUE TITLE
2019.2 Beta Appears to try to load built-in plugins twice

### ISSUE THREAD

**Issue by jkew** [tableau/connector-plugin-sdk#133]
{"ts":"2019-04-28T22:05:20.586","pid":17338,"tid":"41ee7b","sev":"error","req":"-","sess":"-","site":"-","user":"-","k":"connector-plugin-error","e":{"log-code":"0e9acd07","log-source":"needs-classification"},"v":"Class already registered: memsql"}

**Comment by sidwray** [comment]
@jainam1995 Can you file this as a defect in the backlog?

**Comment by lriggs** [comment]
This is an internal problem that happens when transitioning an existing connector to a plugin. Memsql should be fixed and Mongo is pending.
