### ISSUE TITLE
Tableau does not attempt to load plugin, or insufficient debugging information on load

### ISSUE THREAD

**Issue by jkew** [tableau/connector-plugin-sdk#134]
I have a fairly new attempt at a plugin and while 2019.1 and 2019.2 Beta load the shipped plugins fine I'm unable to get much debugging information out of the one I built. If the git repro repository is simply cloned from the following repository 

>     https://github.com/jkew/airtable.tableau

I'll get an error about the .git directory:

> {"ts":"2019-04-28T22:11:34.574","pid":17463,"tid":"4201b9","sev":"error","req":"-","sess":"-","site":"-","user":"-","k":"connector-plugin-error","e":{"log-code":"3834cf96","log-source":"needs-classification"},"v":"Failed to validate /Users/johnkew/Develop/airtable.tableau/.git"}

Removing that doesn't provide any additional insight into what went wrong though.

I'm using the following command line options:

> /Applications/Tableau\ Desktop\ 2019.2.app/Contents/MacOS/Tableau -DConnectPluginsPath=/Users/johnkew/Develop/airtable.tableau/ -DLogLevel=Debug

**Comment by sxlin** [comment]
**ConnectPluginsPath** need point to parent directory of tableau connectors.  Each connector is either in packaged form or in a sub-directory. 

In your case, set **DConnectPluginsPath=/Users/johnkew/Develop**. The connector is under airtable.tableau sub-directory.

**Comment by jkew** [comment]
Ah ha! Maybe a simple example would help on the following page:
    https://tableau.github.io/connector-plugin-sdk/docs/share

**Comment by lriggs** [comment]
Docs were updated.
