### ISSUE TITLE
Need more examples for extract only connectors

### ISSUE THREAD

**Issue by jkew** [tableau/connector-plugin-sdk#135]
I'm writing a plugin for a JDBC driver that has, well, no chance of being SQL92 compliant. I would like to see an example of an extract-only plugin.

**Comment by lriggs** [comment]
Tracked internally: 936118

**Comment by jkew** [comment]
Any update on this? My sort of general rule with plugin development is that I can't look at internal resources to cheat and get something working - so the lack of a set of solid examples is really limiting when you are developing things without the benefit of harassing the team directly.

**Comment by lriggs** [comment]
0209eceda5ffb96341971eb5d27ae5d60eea0754 Added an example of an extract only connector based off SQLite.

**Comment by rosswbrown** [comment]
https://github.com/tableau/connector-plugin-sdk/tree/master/samples/scenarios/extract_only/sqlite_extract

Please see our latest release for 2020.3.  It includes scenario focused examples like extract only.
