### ISSUE TITLE
Better clarity on the dialect base classes

### ISSUE THREAD

**Issue by jkew** [tableau/connector-plugin-sdk#139]
Some of the dialect base classes listed in the documentation make sense, and some do not. For instance; I'm not aware of any database that is a snowflake derivative. It seems like the base classes should be limited to things which would be reasonably extended.

    https://tableau.github.io/connector-plugin-sdk/docs/design

It would also be good to have more information on the dialect itself. I'm not sure what each dialect actually provides for each base class, and therefore what I need to override. Is there a way to create a "dialect base class" reference?

I do like the xsd available at:

    https://github.com/tableau/connector-plugin-sdk/blob/master/validation/tdd_latest.xsd

... but I would like to see the existing implementations for some common classes

**Comment by lriggs** [comment]
Tracked internally: 934724
