### ISSUE TITLE
Disable "Server" field in Dialog

### ISSUE THREAD

**Issue by jkew** [tableau/connector-plugin-sdk#141]
My airtable connector does not need a server field, because it is a well-known API endpoint. Is there a way to remove this from the dialog?

**Comment by lriggs** [comment]
Currently there is no way to do this. I opened an internal story: 936132

**Comment by jkew** [comment]
I opened a new bug, but this is still does not appear to be possible in 2019.3

**Comment by lriggs** [comment]
That's because we haven't made the change yet. It's tracked in 936132.

**Comment by lriggs** [comment]
This will be fixed in Tableau 2019.4.
