### ISSUE TITLE
Service Prompt and Warehouse Prompt does not appear to work

### ISSUE THREAD

**Issue by jkew** [tableau/connector-plugin-sdk#142]
The example dialog for "new_text_field" does not appear to work, at least in 2019.2 Beta. The dialog does not pass validation on startup

https://github.com/tableau/connector-plugin-sdk/blob/master/samples/components/dialogs/new_text_field/connection-dialog.tcd

>     <service-prompt value="Table" />
> 	<show-service-prompt value="true" />
>     <warehouse-prompt value="Another new warehouse text field" />
>     <show-warehouse-prompt value="true" />

**Comment by lriggs** [comment]
Seems to be working fine for me in 2019.2 at the moment.
