### ISSUE TITLE
Add Generic UI form components

### ISSUE THREAD

**Issue by ChristopherhCData** [tableau/connector-plugin-sdk#146]
Generic TCD types with specified parameters would be useful for building and customizing UI:

String: Custom name, optional default value
Boolean: Custom name, optional default value
Int: Custom Name, optional default value
Enum: Custom Name, custom enum types, optional default value

**Comment by lriggs** [comment]
Thanks Christopher. I agree this would be a very useful feature and have it on our planning backlog for future development work. I'm going to close this issue for now since it is being tracked elsewhere.
