### ISSUE TITLE
Documentation improvement - String Extras to connectionBuilder.js

### ISSUE THREAD

**Issue by BobSenturus** [tableau/connector-plugin-sdk#158]
Since many of us are likely coming from the ODBC connector, one thing that wasn't clear right away is that all the "String Extras" should go into params in the connectionBuilder.js file.

Can you update this page, section 4 to speak more clearly to that for anyone else that runs into this issue?
https://tableau.github.io/connector-plugin-sdk/docs/example

Between the connection dialog options, manifest options, and connectionBuilder options all sounding very similar, its a bit hard to tell where each setting lands.

**Comment by lriggs** [comment]
Updated docs.
