### ISSUE TITLE
Unable to make the database optional?

### ISSUE THREAD

**Issue by BobSenturus** [tableau/connector-plugin-sdk#159]
We're trying to make the database name optional on our Connector.

We created the connectionRequired.js file...
![image](https://user-images.githubusercontent.com/40360824/58357094-26c51380-7e3f-11e9-8064-48ced3095b38.png)

We set it up in the TDR file...
![image](https://user-images.githubusercontent.com/40360824/58357049-01d0a080-7e3f-11e9-953f-b72a5900320f.png)

But when we view the connector, it is always required / won't let you hit "Sign In" until you type in something.
![image](https://user-images.githubusercontent.com/40360824/58357198-7dcae880-7e3f-11e9-9e54-d4518896c6fc.png)

(after you type a letter in database, the button enables)
![image](https://user-images.githubusercontent.com/40360824/58357180-7277bd00-7e3f-11e9-9d86-82bf74f05153.png)

Is this a bug or are we missing a trick?

**Comment by pvanderknyff** [comment]
You can set the database to be optional in the tcd file like so:
`<db-name-prompt enabled="true" optional="true" value="@string/database_prompt/" />`

Taken from this sample: https://github.com/tableau/connector-plugin-sdk/blob/dev/samples/components/dialogs/ldapAuthOption.tcd

**Comment by BobSenturus** [comment]
that did the trick, thanks @pvanderknyff !
