### ISSUE TITLE
TCD - any hooks for adding dynamic data into a dropdown?

### ISSUE THREAD

**Issue by BobSenturus** [tableau/connector-plugin-sdk#162]
Is there any way to take the username, password, and server from the dialog the TCD creates, then call an API / ODBC function, then update the TCD dialog with choices in a dropdown?

Or is there a way to override the browse action of the database browse button to do something like that?

**Comment by sidwray** [comment]
Not at the moment, but we've heard it a few times, and that use case is pretty high on the priority list.

**Comment by BobSenturus** [comment]
thanks @sidwray .

Ideally we would be able to use the server, username, and password to make an initial call to the odbc layer, but we could work on other angles as well.

Feel free to close if you're already tracking this.
