### ISSUE TITLE
Multiple authentication option in Dialog

### ISSUE THREAD

**Issue by ahoora08** [tableau/connector-plugin-sdk#164]
Hi,

Like what we can see in Hortonworks Hadoop connector I want to design dialog with a ComboBox choose the authentication type from and each type should have specific fields that will be shown in the dialog if the realted type is chosen. For example if "username and password" type was set on the ComboBox just username and password field should be shown to the user.
Currently the following is my .tcd file contents"
`
<connection-dialog class='jdbc_connector'>

  <connection-config>

    <authentication-mode value='ComboBox' />
    <authentication-options>
      <option name="UsernameAndPassword" />
      <option name="Username" />
      <option name="No Authentication" />
    </authentication-options>
	<db-name-prompt value="Database: " />
    <has-pre-connect-database value="true" />
    <port-prompt value="Port: " default="1234" />
  </connection-config>
</connection-dialog>
`
The above .tcd file just show the ComboBox field which I can choose the options there but for all options just username and password field will be shown. I wanted to have specific fields for each type of the UsernameAndPassword, Username and No Authentication.

How can I design such a form?

**Comment by lriggs** [comment]
Hi, We have items on our backlog to provide a framework for more customizable connection dialogs. Currently the options are fairly limited and we don't support dynamically enabling/hiding text boxes. We hope to have a new system in upcoming releases.
