### ISSUE TITLE
Kerberos Authentication Examples

### ISSUE THREAD

**Issue by jcpkanuri** [tableau/connector-plugin-sdk#166]
Hi Logan,
Thanks for publishing detailed article and example provided. I  managed to use the Postgres example and build a mysql connector to connect to MEMSQL. I am currently trying to add Kerberos authentication and wanted to check if you could either share example or SDK documentation?

**Comment by lriggs** [comment]
Can you provide more information about your requirements? If it is just passing certain connection strings to the driver then we can probably find a way to get things working.

**Comment by jcpkanuri** [comment]
Hi Logan,
Thanks for your response. I will reach out to the customer and get back to you. Would it be possible for you to join the call with the customer to ask relevant questions, just in case?
