### ISSUE TITLE
TDVT expected value contains a special date part

### ISSUE THREAD

**Issue by cornmonster** [tableau/connector-plugin-sdk#169]
Hi,

I am a developer at MaxCompute.

There is a case in TDVT, the test category is calcs_data and the test name is calcs_data. 

The SQL statement is:
```
SELECT `calcs`.`time1` AS `temp_test__665897456__0_`
FROM `odpsdemo_dev`.`calcs` `calcs`
GROUP BY `calcs`.`time1`
```

The type of calcs.time1 is TIME and in dataset TestV1 this field only contains data like "hh:MM:ss". 

But the expected value is:
```
%null%
#1901-01-31 00:05:57#
#1901-01-31 02:05:25#
#1901-01-31 04:40:49#
#1901-01-31 04:48:07#
#1901-01-31 09:33:31#
#1901-01-31 12:33:57#
#1901-01-31 18:58:41#
#1901-01-31 19:36:22#
#1901-01-31 19:48:23#
#1901-01-31 19:57:33#
#1901-01-31 22:20:14#
#1901-01-31 22:50:16#
```

The "1901-01-31" part is quite confusing. I guess it may be an internal default date of Tableau. And it can be really hard for MaxCompute to pass this case.

Here is the snapshot of the test result:
![image](https://user-images.githubusercontent.com/20107543/60171230-c578d180-983c-11e9-98ae-5ab1df1e389b.png)

Thank you very much for your time!

**Comment by liyunbao** [comment]
It looks like there is no problem with the actual result. The failure is caused by TDVT is not running against the right expected. It may be a configuration issue. Could you share your ini and tds so we can take a look?

Below is Cloudera's test result for this test case for your reference.
![image](https://user-images.githubusercontent.com/20933524/60206836-63eb3f80-9809-11e9-8b56-768c99b07bc8.png)

**Comment by lriggs** [comment]
You can safely skip this test. It is only used to verify all the data in the test table, but that column is not used in any tests.

Tableau has some built in workaround for Time types which involve loading the data with a '1899-12-31' or in some cases '1900-01-01' date portion. This is then stripped out for Time columns, and it looks like something may be behaving strangely related to this.

**Comment by cornmonster** [comment]
> It looks like there is no problem with the actual result. The failure is caused by TDVT is not running against the right expected. It may be a configuration issue. Could you share your ini and tds so we can take a look?
> 
> Below is Cloudera's test result for this test case for your reference.
> ![image](https://user-images.githubusercontent.com/20933524/60206836-63eb3f80-9809-11e9-8b56-768c99b07bc8.png)

Thanks for replying, here is my ini:
```
[Datasource]
Name = odps
LogicalQueryFormat = odpsdemo_dev_logical
CommandLineOverride = -DConnectPluginsPath=/Users/jon/tmp/tableau/workspace/plugins
MaxThread = 3
[StandardTests]

[LODTests]

[UnionTest]

[LogicalConfig]
Name = odpsdemo_dev_logical
tablename = $dsName
tablePrefix = [odpsdemo_dev].
tablenameLower = True
fieldnameLower = True
```
