### ISSUE TITLE
How to add field to my authentication string

### ISSUE THREAD

**Issue by ari-sqream** [tableau/connector-plugin-sdk#170]
We have a couple of unique fields in our authentication string that have to be available in the dialog. 
IS there a reference or an example of how such thing should be done?

**Comment by lukewrites** [comment]
Ari, here's a way you can do that using a `service-field`: https://github.com/tableau/connector-plugin-sdk/blob/dev/samples/components/dialogs/new_text_field/connection-dialog.tcd#L12
Note that this is not a secure field (so not a good place for a pw). We have an issue open to provide this functionality, but this should work until we do.

**Comment by lriggs** [comment]
We also have an example here: https://github.com/tableau/connector-plugin-sdk/tree/dev/samples/components/dialogs/new_text_field

The "service" attribute is the best one to reuse.
