### ISSUE TITLE
Mapping a TDVT query to a tdd section

### ISSUE THREAD

**Issue by ari-sqream** [tableau/connector-plugin-sdk#171]
Is there an easy way to understand how a query running through TDVT was formed so I can handle it with the right dialect section?
I have few queries that fail, but I do not know how to map them to the right element in the .tdd file. I am using the full tdd example.

**Comment by lukewrites** [comment]
Hi again, Ari, we have a TDVT test categorization workbook that we are planning to publish soon that should help you with this. When we publish it I'll bump this thread so you get a notification.
