### ISSUE TITLE
Custom ordering of input fields in the dialog

### ISSUE THREAD

**Issue by yoav-einav** [tableau/connector-plugin-sdk#175]
We organized the fields in the .tcd files in a certain way (popular/required fields first, then the rest), but they're not displayed in the same order in the actual dialog.
We'd like them to be displayed in the same order, or alternatively a syntax to enforce order.

**Comment by pvanderknyff** [comment]
We don't have support for changing the order at the moment. We have items on our backlog to look at providing a framework for more customizable connection dialogs, and hope to have a new system in a future release.
