### ISSUE TITLE
Additional input types (other than string)

### ISSUE THREAD

**Issue by yoav-einav** [tableau/connector-plugin-sdk#176]
One of our fields is boolean. We'd like to somehow define it in the .tcd file and have it shown as a checkbox instead of a textbox where the user needs to type "true" or "false".

**Comment by pvanderknyff** [comment]
This is a good idea. As I mentioned on your other issue, we have items on our backlog to look at providing a framework for more customizable connection dialogs, and hope to have a new system in a future release.
