### ISSUE TITLE
Better classpath support

### ISSUE THREAD

**Issue by yoav-einav** [tableau/connector-plugin-sdk#177]
Currently we have to copy the JDBC jars to %ProgramFiles%\Tableau\Drivers. This raises certain issues:
* It requires elevated privileges, which we'd like to avoid.
* It may cause conflicts with other vendors drivers (all drivers in the same classpath)
* We'd like to support side-by-side versions of our driver (e.g. bug fixes or performance enhancements).
Proposed solution: If a user activates a custom connector, extend the JDBC classpath with that connector's classpath, either via a fixed folder (e.g. a 'jars' folder within the connector), or from some config file within the connector (which should be relative to the connector's location).

**Comment by lriggs** [comment]
Thank you for the feedback. I've opened an internal item to track this feature development: 942364
