### ISSUE TITLE
Alternatives to the "-DConnectPluginsPath" command line arg

### ISSUE THREAD

**Issue by yoav-einav** [tableau/connector-plugin-sdk#178]
The problem with a command line arg is that the user has to launch tableau with it each time, instead of using the shortcut created by the installation.
We provide a batch script to simply this, which the user can shortcut, but it's a compromise.
Suggestion: if "-DConnectPluginsPath" is not specified, scan for plugins at "%USERPROFILE%\Documents\My Tableau Repository\Plugins" - standard tableau folder which does not require elevated permissions.

**Comment by pvanderknyff** [comment]
We are working on packaging and signing solutions that will allow a clean user experience for installing connector plugs with version 1.0 of the SDK.

**Comment by lriggs** [comment]
The default path is not a bad idea but I think we want to keep loading connectors an explicit user action for the time being. The packaging work that Patrick mentioned will be a better long term solution for this and will be seamless and unobtrusive to the end user once the connector is installed.
