### ISSUE TITLE
[BUG] Document Improvement on INI part

### ISSUE THREAD

**Issue by lyman** [tableau/connector-plugin-sdk#188]
The [document of TDVT](https://tableau.github.io/connector-plugin-sdk/docs/tdvt
) mentioned following properties in "INI file structure" part:

```
#You can add a new logical config here and use it above. These are example attributes; you wouldn't set them all since some are mutually exclusive.

tablenameUpper = True
tablenameLower = True
boolUnderscore = True
fieldnameDate_underscore = True
fieldnameLower = True
fieldnameUpper = True
fieldnameNoSpace = True
fieldnameLower_underscore = True
fieldnameUnderscoreNotSpace = True
```

As mentioned in the comment some of the attributes are "mutually exclusive" so we tried to turn some of them to "False".

The confusing part is that it makes no difference to change the value to "False". TDVT code (eg. [line 40 of tdvt/tdvt/config_gen/gentests.py](https://github.com/tableau/connector-plugin-sdk/blob/dev/tdvt/tdvt/config_gen/gentests.py#L40)) only checks if the corresponding key is present and ignore whatever the value is. The only way to turn the switch off is to remove or comment the line from INI file.

It might be better to clarify this behavior in the comment since the form "key = True" is really misleading.

**Comment by lriggs** [comment]
Thanks for the feedback. I opened an internal item to track fixing this: 942383
