### ISSUE TITLE
Search option not present under Schema in Tableau Desktop and cannot able to list the DSN in the connection dialog 

### ISSUE THREAD

**Issue by PiraisudanM** [tableau/connector-plugin-sdk#190]
Hi,
Started implementing Tableau plugin feature for our named connector. The connection is successful to my data source from my named Plugin and I can able to list the schema and tables. But we have a few problems, 
1. I'm unable to see any Search option under the Schema (Select Schema), with that search option we are doing some customized search. So how to get that? 

2. On the initial connection dialog for the plugin, how to show the list of DSN under the system?

Thanks.

**Comment by lriggs** [comment]
Hi,

#1 You can set 'CAP_FAST_METADATA' to false in your manifest file to enable searching. It will use the ODBC or JDBC API.
#2 This might be available in a latter version of the SDK. We've had a few customers ask for something similar.

**Comment by PiraisudanM** [comment]
Hi Iriggs,

Thanks for your prompt response.

Are we able to customize the initial plugin connection dialog like adding a new textbox and using that value when building a connection string?
