### ISSUE TITLE
Abstract query SELECT [field] is not defined

### ISSUE THREAD

**Issue by cornmonster** [tableau/connector-plugin-sdk#192]
**About You:**
Name: Jon
Company: MaxCompute

**Your question:**
Hi,

I am trying to figure out the root cause of two failed test cases, lod.17_Nesting and lod.16_As Group. 

Since you said you didn't get much information from the Tableau log, I checked the log of our db and it seemed everything worked fine. Tabquery did nothing except read the metadata of table 'Staples'. I am afraid that Tabquery failed before executing any test case.

Then I noticed that both of the failed case printed an error message like "Abstract query [field] is not defined".

Here is an example:
```
Abstract query [ship_mode] is not defined
``` 

Then I found a related issue: https://kb.tableau.com/articles/issue/error-abstract-query-is-not-defined-when-viewing-data-in-a-google-bigquery-connection?lang=fr-fr

Is it possible that the failures are caused by this issue? 

I have attached the test case, hope that could help.

[setup.lod.17_Nesting.odpsdemo_dev_logical.xml.zip](https://github.com/tableau/connector-plugin-sdk/files/3367225/setup.lod.17_Nesting.odpsdemo_dev_logical.xml.zip)

Thank you very much!
Jon

**Comment by liyunbao** [comment]
The generated SQL contains Cartesian product which is currently not allowed in MaxCompute. We will leave this failure as known issue.

**Comment by neosujoy** [comment]
I have a similar issue with my connector, i have defined some virtual columns, and getting failures for test cases like lod

DataSourceException: Abstract query SELECT [date0] is not defined.
DataSourceException: Abstract query SELECT [Order Date] is not defined.
