### ISSUE TITLE
Cannot able to customize the connection dialog

### ISSUE THREAD

**Issue by PiraisudanM** [tableau/connector-plugin-sdk#200]
Hi Team, 
Are we able to customize the initial plugin connection dialog like adding a new textbox and using that value when building a connection string?

**Comment by sidwray** [comment]
Hi!  Can you comment on which partner you are from? 

We have some significant enhancements to this on the near term roadmap, but as of now, "Service" is a field that you can use.   Here is an example: https://github.com/tableau/connector-plugin-sdk/blob/dev/samples/components/dialogs/new_text_field/connection-dialog.tcd

**Comment by jainam1995** [comment]
We have released connection dialog v2 using which addition of new fields is now possible. The documentation is available here : https://tableau.github.io/connector-plugin-sdk/docs/mcd . Hope this helps !
