### ISSUE TITLE
Cannot able to work with existing workbook directly

### ISSUE THREAD

**Issue by PiraisudanM** [tableau/connector-plugin-sdk#210]
Started implementing Tableau plugin feature for our named connector. I have the following questions,

1. When I open the saved workbook by double-click on the workbook, Tableau Desktop shows "Tableau doesn't recognize the data source type....". Every time I need to run Tableau using the "-DConnectPluginsPath" command-line argument and open the workbook from there. Is there any solution for that?

2. We have existing workbooks that are all created using "Other Database(ODBC)" with our ODBC connector in the Tableau Desktop. How can we open and work with that existing workbook with the newly developed tableau plugin named connector?

**Comment by sidwray** [comment]
We're putting the finishing touches on a packaging and signing tool, which you'll see here in the SDK very soon.  This will allow you to package up all the connector files, and save them to your Tableau repository folder, so they are always available when you start Tableau.  Using the command line is primarily for the development period of the connector.  

You may be able to us the replace data source feature to convert from Other ODBC to your plugin: connector.  https://onlinehelp.tableau.com/current/pro/desktop/en-us/connect_basic_replace.htm
Let me know how it goes!

**Comment by PiraisudanM** [comment]
Thank you for your prompt response, I'll check.

**Comment by lriggs** [comment]
Other ODBC has some additional logic to detect what the driver supports and uses that to customize the dialect. The SDK doesn't have this feature currently. We are also looking into making a tool to print out a dialect file which would mean you could use Other ODBC to get the dialect and then export it for use in your connector. It will also make troubleshooting these issues easier.

I recommend trying to find another dialect that most closely matches what your database supports. Perhaps MySQL or Postgres, for example.

Regarding question #2, I have't thoroughly tested this but you could try opening your workbook XML file and changing the class attribute to match your new connector's class.
