### ISSUE TITLE
Support for CAP_QUERY_TOP_N

### ISSUE THREAD

**Issue by iancr01** [tableau/connector-plugin-sdk#214]
Name: Cris Ianculovici
Company: Actian

The Actian/Ingres query syntax supports the behavior required for CAP_QUERY_TOP_N=yes in the form of
SELECT FIRST n  ... FROM ...
How can I get that to work?

**Comment by lukewrites** [comment]
Cris, we are going to need to look into this before we can give an answer. I'll keep this issue open and we will update it once we've researched it.

**Comment by iancr01** [comment]
We got this one to work with a combination ofCAP_ flags...

**Comment by esinger5** [comment]
Could you please share te CAP_flags combination that worked for you?

**Comment by iancr01** [comment]
Here is what we have though not sure all are involved...

      <customization name="CAP_QUERY_TOP_N" value="yes"/>  
      <customization name="CAP_QUERY_TOP_SAMPLE" value="no"/>
      <customization name="CAP_QUERY_TOP_SAMPLE_PERCENT" value="no"/>
      <customization name='CAP_QUERY_TOPSTYLE_LIMIT' value='no' />
      <customization name='CAP_QUERY_TOPSTYLE_ROWNUM' value='no' />
      <customization name='CAP_QUERY_TOPSTYLE_TOP' value='yes' />
      <customization name='CAP_QUERY_TOP_0_METADATA' value='no' />
