### ISSUE TITLE
JDBC Connectivity gives "An error occurred while communicating"

### ISSUE THREAD

**Issue by iancr01** [tableau/connector-plugin-sdk#215]
**Describe the bug**
We created a custom connector using the Actian JDBC Driver and found that JDBC Connectivity is inconsistent with many "Unable to complete action. An error occurred while communicating with the data source." errors. The connection is already established as it is able to obtain metadata.

**Note** that the same errors happen with the Generic JDBC option.

A couple of examples where the error occurs consistently:
- data source data preview: When Clicking on the button labeled "Update Now":
```
Unable to complete action
An error occurred while communicating with the data source.
```
- when trying to add a calculated field in a worksheet (dropping it in the sheet). The query that is given with the error message runs fine outside of Tableau:
```
An error occurred while communicating with data source 'my_table (actian)'.

Bad Connection: Tableau could not connect to the data source.
An error occurred while communicating with the data source.

SELECT 'test' AS "Calculation_3586272695231557632"
FROM "actian"."my_table" "my_table"
HAVING (COUNT(1) > 0)
```

**Desktop (please complete the following information):**
 - OS: Windows (10)
 - Tableau Version 2019.2.1

**About you:**
 Name: Cris Ianculovici
 Company: Actian

**Comment by lriggs** [comment]
Hi, We can investigate if you collect debug level logs. Just start 'tableau.exe -DLogLevel=Debug". Please also send any crashdump files that might be present.

**Comment by iancr01** [comment]
[Logs.zip](https://github.com/tableau/connector-plugin-sdk/files/3493580/Logs.zip)

**Comment by clach04** [comment]
Update from @lriggs:

> I took a look at the logs that Cristian posted to the GitHub issue and it looks like it might be a JDBC binding issue. I think that the ‘Number of Records’ column from the query is coming back in lower case so Tableau is unable to match it with the expected metadata. You could try setting ‘CAP_JDBC_BIND_DETECT_ALIAS_CASE_FOLDING’ to true in your manifest file. That may fix the issue.
> Relevant section of the logs:

    {
        "ts":"2019-08-12T12:12:26.282","pid":39160,"tid":"12b88",
        ......
        "query":"SELECT TOP 1000 1 AS \"Number of Records\",.........
        ......
        "v":"Protobuf-java-binding: Binding JDBC type 5 'smallint' for column 'number of records' to protobuf type LONG",
        ......
        "v":"tableau::data::protobuf::ProtobufTupleSource::MakeBindings: ignoring unexpected column number of records",
            "ctx":{"client-type":"desktop","procid":"53128","tid":"48892","version":"20192.19.0718.1543"}
    }

I.e. `"Number of Records"` versus `'number of records'`.

**Comment by clach04** [comment]
@iancr01 can you try out https://github.com/clach04/connector-plugin-sdk/commit/7926f3d8c8de248650e4e484595341f57adf73db ? Its in branch https://github.com/clach04/connector-plugin-sdk/tree/issue_215

**Comment by clach04** [comment]
Thanks @lriggs, @iancr01 tested this and it works! 🎉 :-)

Recommend we remove BUG from the title on this and close down. I was going to open a new ticket for documentation but https://tableau.github.io/connector-plugin-sdk/docs/capabilities#jdbc now has the JDBC cap entries 👍 

There are some related issues that now I know about this need to change direction. Thanks for your help, lets close this down and I'll ask related questions in:
   * #229 
  * #216
