### ISSUE TITLE
TDVT Tests for JDBC with Mixed Case

### ISSUE THREAD

**Issue by iancr01** [tableau/connector-plugin-sdk#216]
**About You:**
Name: Cris Ianculovici
Company: Actian

**Your question:**
The ODBC capabilities have support for case of objects (our objects are lower case for non-delimited ids), via CAP_ODBC_BIND_DETECT_ALIAS_CASE_FOLDING, we can’t see an equivalent for JDBC at https://tableau.github.io/connector-plugin-sdk/docs/capabilities#metadata. What is the alternative for JDBC? 
 
We have been running tdvt with simple/simple_lower/simple_lower_lower with no success, the error out of the test suite (e.g. for Staple and Discount) is not helpful so our guess based on observations may be off.

**Comment by clach04** [comment]
RE above testing is the smoke test where these settings have no impact.

**Comment by clach04** [comment]
Trying CAP_ODBC_BIND_DETECT_ALIAS_CASE_FOLDING in a manifest.xml for a jdbc based connector does not have any impact (which sort of makes sense based on the name containing ODBC).

Definitely need something for JDBC, either ODBC equivilent or ideally rely on JDBC driver to report correctly. If the JDBC driver implements the correct DatabaseMetaData api Tableau could determine this. E.g.:

* https://docs.oracle.com/javase/7/docs/api/java/sql/DatabaseMetaData.html#storesLowerCaseIdentifiers()
* https://docs.oracle.com/javase/7/docs/api/java/sql/DatabaseMetaData.html#storesMixedCaseIdentifiers()
* https://docs.oracle.com/javase/7/docs/api/java/sql/DatabaseMetaData.html#storesMixedCaseQuotedIdentifiers()
* etc.

**Comment by lriggs** [comment]
You should be able to remap column names using the Logical Config. For example, if you loaded the Staples table with lowercase column names. The CAP_ mentioned above is mainly used when the driver/database returns results that have been unexpectedly converted to lower case.

**Comment by clach04** [comment]
> Trying CAP_ODBC_BIND_DETECT_ALIAS_CASE_FOLDING in a manifest.xml for a jdbc based connector does not have any impact (which sort of makes sense based on the name containing ODBC).
> 
> Definitely need something for JDBC, either ODBC equivilent or ideally rely on JDBC driver to report correctly. If the JDBC driver implements the correct DatabaseMetaData api Tableau could determine this. E.g.:
> 
>     * https://docs.oracle.com/javase/7/docs/api/java/sql/DatabaseMetaData.html#storesLowerCaseIdentifiers()
> 
>     * https://docs.oracle.com/javase/7/docs/api/java/sql/DatabaseMetaData.html#storesMixedCaseIdentifiers()
> 
>     * https://docs.oracle.com/javase/7/docs/api/java/sql/DatabaseMetaData.html#storesMixedCaseQuotedIdentifiers()
> 
>     * etc.

As of 2019-08-14 https://tableau.github.io/connector-plugin-sdk/docs/capabilities#jdbc now has the CAP entries for JDBC and they work with the sdk as of today alone with Desktop 2019.2.2, so my comment above is only partially relevant. I'll log a new enhancement request to avoid the need for CAP_JDBC_BIND_DETECT_ALIAS_CASE_FOLDING.

However both this and #229 are issues for the smoke test. @lriggs I did some searching but I didn't find anything on "Logical Config". Can you point me at some documentation for this please? I would like to move to running the tests with lower case names as that is the default for us, I'm still using MixedCase for current tests but I'd like to avoid the need for it. Thanks!

**Comment by lriggs** [comment]
Closing this old issue. Please open another one if this is still a problem. Thanks.
