### ISSUE TITLE
Schema information missing in the datasource tab

### ISSUE THREAD

**Issue by iancr01** [tableau/connector-plugin-sdk#217]
**About You:**
Name: Cris Ianculovici
Company: Actian

**Your question:**
It seems that for out custom connector the section for Schema selection is missing, but for the generic (ODBC or JDBC) connector it's there. This is in the first tab (Data source) In Tableau Desktop. 

What setting should we use to put it back on? I've looked at different capabilities, but none seem to describe anything like that.

**Comment by pvanderknyff** [comment]
Hi Cris. You can add the schema selection to the data tab by adding the following line to your connection dialog (.tcd) file:
`<has-schemas value="true" />`

One note is that the schema selection may not show the available schemas until you search for them. If you search an empty string it will return all schemas.

Let me know if you have any trouble adding the attribute to the tcd file.

**Comment by iancr01** [comment]
I changed connection-dialog.tcd and it seems to break the connector... these are 2 versions of the entire file (I tried 2 different things).
```
<connection-dialog class='actian_odbc'>
  <connection-config>
    <authentication-mode value='Basic' />
    <authentication-options>
      <option name="UsernameAndPassword" default="true" />
    </authentication-options>
    <db-name-prompt value="Database: " />
    <has-pre-connect-database value="true" />
    <port-prompt value="Port: " default="VW" />
  </connection-config>
  <has-schemas value="true" />
</connection-dialog>
```

```
<connection-dialog class='actian_odbc'>
  <connection-config>
    <authentication-mode value='Basic' />
    <authentication-options>
      <option name="UsernameAndPassword" default="true" />
    </authentication-options>
    <db-name-prompt value="Database: " />
    <has-pre-connect-database value="true" />
    <port-prompt value="Port: " default="VW" />
    <has-schemas value="true" />
  </connection-config>
</connection-dialog>
```

**Comment by lriggs** [comment]
Try moving has-schemas above port-prompt in the second example. The XML validation want things in a certain order: https://github.com/tableau/connector-plugin-sdk/blob/dev/validation/tcd_latest.xsd#L20

**Comment by iancr01** [comment]
Thanks! Thank works.
