### ISSUE TITLE
[BUG] YEAR() function inconsistent behavior

### ISSUE THREAD

**Issue by iancr01** [tableau/connector-plugin-sdk#223]
**Describe the bug**
The YEAR() function shows an inconsistent behavior with a custom connector. When dragging a date field to the Rows section, the SQL that gets generated is:

```
SELECT CAST(TRUNCATE (
			EXTRACT(YEAR FROM "Staples"."Order Date")
			,0
			) AS INTEGER) AS "Calculation_4840525192484175872"
FROM "actian"."Staples" "Staples"
GROUP BY 1
```
but if this is don as a calculated field instead - e.g. `YEAR([Order Date])` - which is the same as what Tableau generates on dragging the field - the SQL query is:

```
SELECT CAST(TRUNCATE (
			EXTRACT(YEAR FROM "Staples"."Order Date")
			) AS INTEGER) AS "Calculation_4840525192484175872"
FROM "actian"."Staples" "Staples"
GROUP BY 1
```
The first syntax is incorrect while the second is accepted. 

However, when doing the same with the generic ODBC connector, the correct syntax is being generated in both cases. 

**Screenshots**

**Desktop (please complete the following information):**
 - OS: Windows
 - Tableau Version: 2019.3, 2019.2.2

**About you:**
 Name: Cris Ianculovici
 Company: Actian Corp.

**Comment by iancr01** [comment]
Plugin at https://github.com/clach04/connector-plugin-sdk/tree/actian/samples/plugins.

**Comment by iancr01** [comment]
Making changes in the dialect file to override the YEAR() function does not make a difference.

**Comment by lriggs** [comment]
Hi, Thanks for the detailed notes. In the first case I beilieve Tableau is using the "YEAR" function and in the second it is using a DATEPART function. I checked our internal implementation and the reinforces this idea.

One solution could be to pick another base dialect that more close matches your database SQL. Overriding the YEAR function should work. What did you add to your dialect file to do that?

**Comment by iancr01** [comment]
We tried a few different things... 


    <function group='date' name='YEAR' return-type='int'>
      <formula>YEAR(%1)</formula>
      <argument type='datetime' />
    </function>
    <function group='date' name='YEAR' return-type='int'>
      <formula>YEAR(%1)</formula>
      <argument type='date' />
    </function>

We even tried with a constant... 

    <function group='date' name='YEAR' return-type='int'>
      <formula>9990</formula>
      <argument type='date' />
    </function>

We're getting the same error:
```
An error occurred while communicating with data source 'testv1_lower'.

Bad Connection: Tableau could not connect to the data source.
[Actian][Ingres ODBC Driver][Ingres]line 3, Function 'trunc' does not take an argument of type 'integer'. Explicitly convert the argument to the desired type.
SELECT CAST(TRUNCATE(EXTRACT(YEAR FROM "staples"."order date")) AS INTEGER) AS "yr:order date:ok"
FROM "actian"."staples" "staples"
GROUP BY 1

```
The trunc function indeed does not support a second parameter.

**Comment by lriggs** [comment]
You could try overriding the DATEPART functions as well.

    <date-function name='DATEPART' return-type='int'>
      <formula part='year'>YEAR(%2)</formula>
      <formula part='quarter'>CAST((MONTH(%2) - 1) / 3 + 1 AS BIGINT)</formula>
      <formula part='month'>MONTH(%2)</formula>
      <formula part='dayofyear'>DATEDIFF(TO_DATE(%2), TO_DATE(CAST(TRUNC(%2,&apos;YY&apos;) AS DATE))) + 1</formula>
      <formula part='day'>DAY(%2)</formula>
      <formula part='weekday'>(8 + DATEDIFF(%2,NEXT_DAY(CAST(%2 AS DATE),&apos;SU&apos;)))</formula>
      <formula part='week'>FLOOR((14 + DATEDIFF(%2, TRUNC(%2,&apos;YY&apos;)) + DATEDIFF(TRUNC(%2,&apos;YY&apos;),NEXT_DAY(TRUNC(%2,&apos;YY&apos;),&apos;SU&apos;)))/7)</formula>
      <formula part='hour'>HOUR(%2)</formula>
      <formula part='minute'>MINUTE(%2)</formula>
      <formula part='second'>SECOND(%2)</formula>
      <argument type='localstr' />
      <argument type='datetime' />
    </date-function>
    <date-function name='DATEPART' return-type='int'>
      <formula part='year'>YEAR(%2)</formula>
      <formula part='quarter'>CAST((MONTH(%2) - 1) / 3 + 1 AS BIGINT)</formula>
      <formula part='month'>MONTH(%2)</formula>
      <formula part='dayofyear'>DATEDIFF(TO_DATE(%2), TO_DATE(CAST(TRUNC(%2,&apos;YY&apos;) AS DATE))) + 1</formula>
      <formula part='day'>DAY(%2)</formula>
      <formula part='weekday'>(8 + DATEDIFF(%2,NEXT_DAY(CAST(%2 AS DATE),&apos;SU&apos;)))</formula>
      <formula part='week'>FLOOR((14 + DATEDIFF(%2, TRUNC(%2,&apos;YY&apos;)) + DATEDIFF(TRUNC(%2,&apos;YY&apos;),NEXT_DAY(TRUNC(%2,&apos;YY&apos;),&apos;SU&apos;)))/7)</formula>
      <formula part='hour'>HOUR(%2)</formula>
      <formula part='minute'>MINUTE(%2)</formula>
      <formula part='second'>SECOND(%2)</formula>
      <argument type='localstr' />
      <argument type='datetime' />
      <argument type='localstr' />
    </date-function>

**Comment by iancr01** [comment]
This is working after implementing the recommendations. Closing.
