### ISSUE TITLE
[BUG] CAP_ODBC_BIND_DETECT_ALIAS_CASE_FOLDING has no effect

### ISSUE THREAD

**Issue by clach04** [tableau/connector-plugin-sdk#229]
**Describe the bug**

`CAP_ODBC_BIND_DETECT_ALIAS_CASE_FOLDING` documentation at https://tableau.github.io/connector-plugin-sdk/docs/capabilities indicates case differences will be taken care of. The tdvt smoke test fails to run if a database metadata case is set to lowercase and the `CAP_ODBC_BIND_DETECT_ALIAS_CASE_FOLDING` in manifest.xml has no impact.

tdvt appears to always expected mixed case, case sensitivity.

Related to #216 

**Screenshots**

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Tableau Version 2019.2.2

**About you:**

 Name: Chris Clark
 Company: Actian Corp.

**Comment by lriggs** [comment]
Closing this old issue. Please open another if this is still a problem. If you can, please attach the tabquery_logs.zip file showing the test failure.
