### ISSUE TITLE
[BUG]m tdvt_runner tool references

### ISSUE THREAD

**Issue by clach04** [tableau/connector-plugin-sdk#230]
**Describe the bug**

https://tableau.github.io/connector-plugin-sdk/docs/tdvt documents:

> When TDVT is installed as a Python module it can be invoked as follows: `python -m tdvt.tdvt`.

> If you have Python 2 and Python 3 installed, run `py -3 -m tdvt.tdvt`. This ensures Python 3 is used. In the examples below `tdvt` is used, but one of the above would be used in actual practice.

However when invoking the tool to get help, `python -m tdvt.tdvt --help`, it reports:

    usage:
        TDVT Driver. Run groups of logical and expression tests against one or more datasources.

        Show all test suites
            tdvt_runner --list
    ......

I.e. `tdvt_runner`.

**Screenshots**

    usage:
        TDVT Driver. Run groups of logical and expression tests against one or more datasources.

        Show all test suites
            tdvt_runner --list

        See what a test suite consists of
            tdvt_runner --list sqlserver
            tdvt_runner --list standard

        The 'run' argument can take a single datasource, a list of data sources, or a test suite name. in any combination.
            tdvt_runner --run vertica
            tdvt_runner --run sqlserver,vertica
            tdvt_runner --run standard

        The 'run' argument can also take the --verify flag to run a connection test against tests with SmokeTest = True set.
            tdvt_runner --run postgres --verify

        Both logical and expression tests are run by default.
        Run all sqlserver expression tests
            tdvt_runner -e --run sqlserver

        Run all vertica logical tests
            tdvt_runner -q --run vertica

        There are two groups of expression tests, standard and LOD (level of detail). The config files that drive the tests
        are named expression_test.sqlserver.cfg and expression.lod.sqlserver.cfg.
        To run just one of those try entering part of the config name as an argument:
            tdvt_runner -e lod --run sqlserver
        This will run all the LOD tests against sqlserver.

        And you can run all the LOD tests against the standard datasources like
            tdvt_runner -e lod --run standard

        Run one test against many datasources
            tdvt_runner --exp exprtests/standard/setup.date.datepart.second*.txt --tdp cast_calcs.*.tds --run sqlserver,vertica

        The 'exp' argument is a glob pattern that is used to find the test file. It is the same style as what you will find
        in the existing *.cfg files.
        The 'test-ex' argument can be used to exclude test files. This is a regular expression pattern.
        The tds pattern is used to find the tds. Use a '*' character where the tds name will be substituted,
        ie cast_calcs.*.tds for cast_calcs.sqlserver.tds etc.

        Run one logical query test against many datasources
            tdvt_runner --logp logicaltests/setup/calcs/setup.BUGS.B1713.?.xml --tdp cast_calcs.*.tds --run postgres

        This can be combined with * to run an arbitrary set of 'correct' logical query tests against a datasources
            tdvt_runner --logp logicaltests/setup/calcs/setup.BUGS.*.?.xml --tdp cast_calcs.*.tds --run postgres
        Alternatively
            tdvt_runner --logp logicaltests/setup/calcs/setup.BUGS.*.dbo.xml --tdp cast_calcs.*.tds --run sqlserver

        But skip 59740?
            tdvt_runner --logp logicaltests/setup/calcs/setup.BUGS.*.dbo.xml --tdp cast_calcs.*.tds --test-ex 59740 --run sqlserver

    TDVT Driver.

    optional arguments:
      -h, --help            show this help message and exit
      --list [LIST_DS]      List datasource config.
      --list_logical_configs [LIST_LOGICAL_CONFIGS]
                            List available logical configs.
      --generate            Force config file generation.
      --setup               Create setup directory structure.
      --add_ds ADD_DS       Add a new datasource.
      --run DS, -r DS       Comma separated list of Datasource names to test or
                            'all'.
      --logical [LOGICAL_ONLY], -q [LOGICAL_ONLY]
                            Only run logical tests whose config file name matches
                            the supplied string, or all if blank.
      --expression [EXPRESSION_ONLY], -e [EXPRESSION_ONLY]
                            Only run expression tests whose config file name
                            matches the suppled string, or all if blank.
      --threads THREAD_COUNT, -t THREAD_COUNT
                            Max number of threads to use.
      --verbose             Verbose output.
      --no-clean            Leave temp dirs.
      --exp [EXPRESSION_PATTERN]
                            Only run expression tests whose name and path matches
                            the supplied string. This is a glob pattern. Also set
                            the tds-pattern to use when running the test.
      --logp [LOGICAL_PATTERN]
                            Only run logical tests whose name and path matches the
                            supplied string. this is a glob pattern. Also set the
                            tds-pattern to use when running the test. Use a ? to
                            replace the logical query config component of the test
                            name.
      --tdp [TDS_PATTERN]   The datasource tds pattern to use when running the
                            test. See exp and logp arguments.
      --test-ex [TEST_PATTERN_EXCLUDE]
                            Exclude tests whose name matches the supplied string.
                            This is a regular expression pattern. Can be used with
                            exp and logp arguments. Also set the tds-pattern to
                            use when running the test.
      --compare-sql         Compare SQL.
      --nocompare-tuples    Do not compare Tuples.
      --diff-test DIFF, -dd DIFF
                            Diff the results of the given test (ie
                            exprtests/standard/setup.calcs_data.txt) against the
                            expected files. Can be used with the sql and tuple
                            options.
      -f RUN_FILE           Json file containing failed tests to run.
      --verify [SMOKE_TEST]
                            Verifies the connection to a data source against test
                            in your .ini file with SmokeTest = True.

**Desktop (please complete the following information):**
 - OS: NA
 - Tableau Version NA

**About you:**
 Name: Chris Clark
 Company: Actian Corp.

**Comment by lukewrites** [comment]
Thanks, Chris. We'll get those references to `tdvt_runner` removed.
