### ISSUE TITLE
[FEATURE] use JDBC driver meta data to determine object case

### ISSUE THREAD

**Issue by clach04** [tableau/connector-plugin-sdk#242]
**Is your feature request related to a problem? Please describe.**

From #216 - using Java/JDBC DatabaseMetaData api Tableau could determine the case scheme for a backend. E.g.:

  *  https://docs.oracle.com/javase/7/docs/api/java/sql/DatabaseMetaData.html#storesLowerCaseIdentifiers()
  *  https://docs.oracle.com/javase/7/docs/api/java/sql/DatabaseMetaData.html#storesMixedCaseIdentifiers()
  *  https://docs.oracle.com/javase/7/docs/api/java/sql/DatabaseMetaData.html#storesMixedCaseQuotedIdentifiers()
    etc.

This could be used to avoid the need to manually specify CAP_JDBC_BIND_DETECT_ALIAS_CASE_FOLDING.

This may be more of a Desktop enhancement than SDK, opening here for comment/feedback

**Describe the solution you'd like**

Use JDBC driver reported information to avoid need for CAP_JDBC_BIND_DETECT_ALIAS_CASE_FOLDING

**Describe alternatives you've considered**

Other option would be to use the config .ini file and use the `LogicalQueryFormat` setting

**About You**
Name: Chris Clark
Company: Actian Corp

**Comment by sidwray** [comment]
tfs 1197844

**Comment by rosswbrown** [comment]
Closing this enhancement request after internal backlog priority review of JDBC related work.

The current public [documentation](https://tableau.github.io/connector-plugin-sdk/docs/capabilities) of CAP_JDBC_BIND_DETECT_ALIAS_CASE_FOLDING is all that is planned at this time.
