### ISSUE TITLE
[BUG]  Can't run single tests or rerun test files

### ISSUE THREAD

**Issue by lriggs** [tableau/connector-plugin-sdk#258]
These commands fail with syntax errors:
  tdvt -f tdvt_output_combined.json
  tdvt --run myds --exp exprtests\standard\setup.agg.avg.txt --tdp cast_calcs.*.tds
  tdvt --run myds --logp logicaltests/setup/calcs/setup.BUGS.B1713.?.xml --tdp cast_calcs.*.tds

Commit ec04f063cbb6b66a3030ec01dc9ab3ec77991167 added ds_name paramter but usage was not updated: https://github.com/tableau/connector-plugin-sdk/commit/ec04f063cbb6b66a3030ec01dc9ab3ec77991167#diff-31386d9964a82308f0ae1caf6f065530L226

Commit  458f0521e896d66b40fe64aed0bd211dcd5b309f added timeout_seconds but usage was not updated: https://github.com/tableau/connector-plugin-sdk/commit/458f0521e896d66b40fe64aed0bd211dcd5b309f#diff-31386d9964a82308f0ae1caf6f065530R257

**Comment by lriggs** [comment]
Fixed in dev with commit 27a642459db0e1e52983b09ca6293cf332ca3e26

**Comment by lukewrites** [comment]
Resolved in #259
