### ISSUE TITLE
[BUG] Documentation - Improve Basic Plugin Loading Documentation

### ISSUE THREAD

**Issue by jkew** [tableau/connector-plugin-sdk#277]
It is not easy to find out the command line option or how to load a plugin
    * “Share” your connector was a bit hard to find. At first I just want to test my connector… so it took a while to find this documentation.
    * I didn’t want to use command line options to test my connector because at first, I couldn’t find the right command line option to use.
    * I tried to create a symbolic link from the "/Applications/Tableau Desktop 2019.3.app/Contents/Frameworks/connectors/" folder to my plugin development folder.
    * Then I tried copying the whole folder over to the Applications directory and that didn’t work either.
    * Finally I found the command line option and that worked.
* Why can’t I just drop my plugin folder in the “connectors” directory?
* Can you improve the documentation or make it part of the “Getting Started / Example pages”?

**Comment by pvanderknyff** [comment]
Hi John,

We can definitely look at making the documentation clearer and easier to find. I'll look at adding this to our teams backlog.

The command line option is considered a developer path to test a connector while it is being developed. In the 2019.4 Tableau release, we will release a tool that will package the plugin files into a Tableau Connector (.taco) file. These files can be dragged and dropped your "My Tableau Repository/connectors" folder and Tableau will automatically load them.

**Comment by lriggs** [comment]
I updated the getting started page with 967082143111f58aa1a329fd0bd5ef9120b7fd8f.
