### ISSUE TITLE
[BUG] javaScriptConsoleMessage: message=HybridUI:pluginHostDesktop: 454ms sourceId=qrc:///HybridUI/PluginUtil.js lineNumber=159

### ISSUE THREAD

**Issue by jkew** [tableau/connector-plugin-sdk#278]
![image](https://user-images.githubusercontent.com/723652/64903984-65ddd580-d677-11e9-86cf-013659d8bf99.png)

https://github.com/jkew/airtable.tableau

And the following was in the log. This is Tableau 2019.3

`{"ts":"2019-09-13T22:44:53.265","pid":0,"tid":"0","sev":"info","req":"-","sess":"-","site":"-","user":"-","k":"begin-commands-controller.invoke-command","l":{},"a":{"depth":0,"id":"HJAejJGjUx5KHERT3OtDbs","name":"commands-controller.invoke-command","req-desc":"-","type":"begin"},"v":{"args":"tabui:create-connection-ui suppress-switch-tab=\"false\" value-class-attr=\"airtable_jdbc\"","name":"tabui:create-connection-ui"},"ctx":{}}
{"ts":"2019-09-13T22:44:53.356","pid":31314,"tid":"14ff48","sev":"warn","req":"-","sess":"-","site":"-","user":"-","k":"msg","e":{"log-code":"00000000","log-source":"needs-classification"},"v":"Property 'props'' of object 'PluginInteropObject' has no notify signal and is not constant, value updates in HTML will be broken!"}
{"ts":"2019-09-13T22:44:53.795","pid":31314,"tid":"14ff48","sev":"info","req":"-","sess":"-","site":"-","user":"-","k":"msg","e":{"log-code":"b0ef223f","log-source":"needs-classification"},"v":"WebPage javaScriptConsoleMessage: message=HybridUI:pluginHostDesktop: 454ms sourceId=qrc:///HybridUI/PluginUtil.js lineNumber=159"}`

**Comment by jkew** [comment]
This is my dialog file:

`  
<connection-dialog class='airtable_jdbc'>
  <connection-config>
    <authentication-mode value="None" />

    <db-name-prompt value="Airtable Database: " />
    <has-pre-connect-database value="true" />
  </connection-config>
</connection-dialog>`

**Comment by lriggs** [comment]
We will investigate this issue in our next sprint.

**Comment by jsun28** [comment]
@jkew Based on my investigation, that line is logged from line 163 and line 170 at http://opengrok.prod.tableautools.com/source/xref/dev_tableau-2019-4-dev/modules/web/plugin-host-desktop/PluginUtil.js#163
it is just a hint message while loading hybird dialog, it happens to all connectors using hybird connection dialog. not only hybird connection dialog, it also happens to other hybird dialog, like error detail dialog.
So I think it is not a bug, just a hint message logged while hybird dialog loading process.

**Comment by jsun28** [comment]
Here the link for writing no-auth correctly.
https://tableau.github.io/connector-plugin-sdk/docs/auth-modes
