### ISSUE TITLE
[BUG] Can't figure out how to get rid of the server field

### ISSUE THREAD

**Issue by jkew** [tableau/connector-plugin-sdk#279]
My connector does not require a server field.

From the xsd in the repository here:
https://github.com/tableau/connector-plugin-sdk/blob/master/validation/tcd_latest.xsd

I tried various forms of the following:
<server-prompt enabled="false" />

{"ts":"2019-09-13T22:58:42.419","pid":31621,"tid":"152854","sev":"error","req":"-","sess":"-","site":"-","user":"-","k":"connector-plugin-error","e":{"log-code":"0e9a4f13","log-source":"needs-classification"},"v":"Error loading connection dialog file (.tcd) for class 'airtable_jdbc'. Skipping plugin."}

**Comment by rosswbrown** [comment]
In the upcoming Tableau 2019.4 release we will support suppressing this field by using the `enabled` attribute on the `TextField-CT` type.  Example: 
`<server-prompt enabled='false' value='Server: ' />`

In general though we recommend connector developers use the server field whenever their connector can connect to different user-defined endpoints, files, etc.  This aligns with existing usage of Tableau connectors by the platform.
