### ISSUE TITLE
How to develop custom connector with kerberos in tableau?

### ISSUE THREAD

**Issue by FengJinghHua** [tableau/connector-plugin-sdk#280]
According to [this page](https://help.tableau.com/current/server/en-us/kerberos_delegation.htm) the tableau doesn't support the Kerberos authentication for Other custom connector. Should I develop a new connector? or there is a way to use the build-in custom connector with Kerberos?

I can not find any documents or announcement about it. Please help ,I am really lost.

**Comment by pvanderknyff** [comment]
Hi Ansel, 

Unfortunately we do not support Kerberos authentication in the SDK at this time. It is on our roadmap, however.

If you can give us some of the details of your Kerberos implementation, it could help us refine our stories.

**Comment by sidwray** [comment]
DelegationUID is now supported.   https://tableau.github.io/connector-plugin-sdk/docs/auth-modes
tfs 957487
