### ISSUE TITLE
CAP_CREATE_TEMP_TABLES=ON generates huge temp table

### ISSUE THREAD

**Issue by iancr01** [tableau/connector-plugin-sdk#282]
We enabled this capability and correctly configured the dialect file to use the accepted syntax for temp tables. However, we found that Tableau wants to generate a very large temp table based off of our fact table, which, of course, kills performance. 

Tableau Desktop 2019.2.3 on Windows.

**Comment by lriggs** [comment]
Subqueries are an alternative to temp tables. You can disable CAP_CREATE_TEMP_TABLES and CAP_SELECT_INTO and then turn on CAP_QUERY_SUBQUERIES and possibly CAP_QUERY_SUBQUERIES_WITH_TOP.

Tableau requires either temp tables or subqueries for certain functionality such as grouping.
