### ISSUE TITLE
Some of the expression.standard tests for cast_calcs  aggr.*  are failing with Invalid Expression

### ISSUE THREAD

**Issue by hegdean** [tableau/connector-plugin-sdk#290]
Anuradha Hegde from Esgyn Corporation

The error that I got back for this  set of tests was "Invalid Expression".  
 The reason being for EsgynDB the columns should be invoked without square brackets. How would I make the test refer to a regular column name  without square brackets which is already in the metadata of the datasource

Here is a snippet :
 COUNT([int0])   returns "Invalid expression"  Actual result is 11

Below is the information in cast_calcs.esgyndb.tds

      <metadata-record class='column'>
        <remote-name>INT0</remote-name>
        <remote-type>3</remote-type>
        <local-name>[INT0]</local-name>
        <parent-name>[CALCS]</parent-name>
        <remote-alias>INT0</remote-alias>
        <ordinal>11</ordinal>
        <local-type>integer</local-type>
        <aggregation>Sum</aggregation>
        <precision>10</precision>
        <contains-null>true</contains-null>
        <attributes>
          <attribute datatype='string' name='DebugRemoteType'>&quot;SQL_INTEGER&quot;</attribute>
          <attribute datatype='string' name='DebugWireType'>&quot;SQL_C_SLONG&quot;</attribute>
        </attributes>
      </metadata-record>

**Comment by lriggs** [comment]
Hi Anuradha, you can change this behavior in the generated SQL by setting it here in your dialect file: https://github.com/tableau/connector-plugin-sdk/blob/master/validation/tdd_latest.xsd#L616

Let me know if this works for you.
