### ISSUE TITLE
custom connector tdvt test result diff with generic odbc

### ISSUE THREAD

**Issue by FengJinghHua** [tableau/connector-plugin-sdk#313]
I use tdvt dataset to test my custome connector,which pass about 65%,the connector use odbc to  mydatasource，but when I use tdvt to connect my odbc,it pass about 92%.  Both of them use the same TDC file. I am confused about why both of them use the same odbc,the result are difference. I found docs about dialect, my connector use the DefaultSQLDialect ,is it a right way ??? Ican not found the generic odbc tdd in the docs or github. 

How can I improve the result with my connector,at least the result is the same as when connecting generic ODBC, I am really lost，please help,thanks

**Comment by lriggs** [comment]
Hi, the 'Other ODBC' connector uses a different path in the code and has other ways to customize the dialect, some of which can be figured out by asking the driver what it supports. An SDK connector requires you to pick the dialect more carefully but offers more customization.

We would like to enhance this in the future so going from "odbc" to sdk is easier. In the mean time I recommend picking a starting dialect (.tdd file) for your connector that most closely matches the SQL it supports. Does your database support SQL like PostGres or MySQL for example? If so, its a lot easier to start with one of those dialects.

**Comment by FengJinghHua** [comment]
Thanks @lriggs .  I found the [dialect file ](https://github.com/tableau/connector-plugin-sdk/blob/master/samples/components/dialects/full_dialect.tdd)o n tableau. I modified some dialects,like startwith  function, but I found that most of the error date functions, such as datediff, datename in tdvt result report. It seems those part of the function will call some children functions such as DATE_DIFF, but DATE_DIFF cannot be found in the full_dialect file. Is there a related document or a sample dialect file modify example modified in this respect? Another question is, does the TDVT test include all the tableau functions ?  Looking forward to your answer, thank you

**Comment by sidwray** [comment]
Just to help add context this request is from Kyligence.

**Comment by FengJinghHua** [comment]
I fixed the top logical test, I found some logical error called "NVL function not sopport" in logical test. I try to add NVL function in tdd with "function mapping", it works in  expression but not in logical test. How to fix it in dialect.tdd file ,I can not find any docs about it, thanks.

**Comment by lriggs** [comment]
See #323 for the NVL question.
