### ISSUE TITLE
[custom connector]how to change the query the same as "Other ODBC"

### ISSUE THREAD

**Issue by FengJinghHua** [tableau/connector-plugin-sdk#314]
Can you tell us which dialect the ODBC connector in Tableau uses? We're trying the DefaultSQLDialect in our custom plugin connector with tdvt test. The  result is different with  we get with just ODBC . Is it normal？

 I found some interesting that if I use "Other ODBC" to connect my data, I use the "DATEDIFF" function, the query is

```
SELECT SUM({fn CONVERT({fn TIMESTAMPDIFF(SQL_TSI_DAY,"CALCS"."DATE3","CALCS"."DATE2")}, SQL_BIGINT)}) AS "sum_Calculation_336925591305351168_ok"
FROM "TDVT"."CALCS" "CALCS"
HAVING (COUNT(1) > 0)
```

But when I use the custom Connector (dialect is DefaultSQLDialect) to connect my data,the  query is 

`SELECT SUM(CAST((CAST("CALCS"."DATE2" AS DATE) - CAST("CALCS"."DATE3" AS DATE)) AS INTEGER)) AS "sum:Calculation_262897672424624128:ok",   1.1000000000000001 AS "$__alias__0" FROM "TDVT"."CALCS" "CALCS" GROUP BY 1.1000000000000001`

How change all of my custom connector query to be the same as the "Other ODBC"?

**Comment by lriggs** [comment]
This is the same basic issue as #313 so lets keep the conversation to that one.
