### ISSUE TITLE
Plus operator for DATEs and DATETIMEs

### ISSUE THREAD

**Issue by astefan** [tableau/connector-plugin-sdk#317]
I am trying to define the `+` operator for DATE and DATETIME data types, but I am lost to what the addition would yield. In the [full_dialect sample file](https://github.com/tableau/connector-plugin-sdk/blob/master/samples/components/dialects/full_dialect.tdd#L1129) the formula for these data types is as simple as

```
    <function group='operator' name='+' return-type='datetime'>
      <formula>(%1 + %2)</formula>
      <argument type='datetime' />
      <argument type='datetime' />
    </function>
```

The dialect I'm working on needs to come up with a smarter formula for this operator, since the underlying database doesn't support adding two dates. All other sample dialects on this repo do not provide a formula for `+`, so I'm curious on the expectation for such an operation on these data types.

As a similar task - adding an INT to a DATE - the formula looks intuitive and defines this addition as adding DAYs to the date/datetime:

```
    <function group='operator' name='+' return-type='date'>
      <formula>(%1 + %2 * INTERVAL &apos;1&apos; DAY)</formula>
      <argument type='date' />
      <argument type='int' />
    </function>
```

but for [date]+[date] I can only speculate, but not knowing for sure: CASTing the DATE to a LONG and extracting the milliseconds, adding both milliseconds and then re-CASTing to a date at the end?

**Comment by lriggs** [comment]
I'm pretty sure that snuck into our dialect example by accident. I wasn't able to add two dates in Tableau either so I don't think it's a supported scenario. I also did not find any TDVT tests that covered this.

I'd recommend continuously running your connector through TDVT and fixing dialect issues that way. The dialect format its self is very expressive and you can add many functions that Tableau doesn't need. The TDVT was made to be the verification tool that makes sure your dialect has all the right functions. TDVT also has expected outputs which can help indicate what Tableau is expecting. For example the 'date.math' test has a few cases for date+int and the expected results.
