### ISSUE TITLE
TDVT - Most of the testes are failed for my named connector.

### ISSUE THREAD

**Issue by PiraisudanM** [tableau/connector-plugin-sdk#325]
I'm trying to test my named connector using TDVT. But all the tests are failed even if I configured proper settings mentioned in the following document: https://tableau.github.io/connector-plugin-sdk/docs/tdvt 

What I have done:
1. Installed "tdvt-1.5.23.tar.gz" using Python 3.
2. Configured proper path in the .ini file and followed File Structure as mentioned in the above document ( all the configuration steps are done successfully without any issue) and copied our named connector SDK files into the plugins folder.
3. After failing all tests, I analyzed the 'tdvt_log_combined.txt' log file, but I could not find any error on that log. Also, I verified with "Frequently found issues and troubleshooting" and checked everything but I can't able to get past this issue. 

Note: We are imported given 'Staples' and 'Calc' tables in our DB, but we added an additional id column in both of the tables for Data Modeling purpose (without adding that column we could not able to load those tables using our named connector). 
Is this cause all the tests to fail? If yes, how can I overcome this issue?

Please provide the solution to get past this issue. Thank You.

**Comment by sidwray** [comment]
What connector is this for?  Have you rebased with master to pick up the smoke tests we added?

**Comment by PiraisudanM** [comment]
It is the connector to visualize OBIEE data into Tableau. 

I followed all the steps mentioned in the TDVT document. Can you please provide the details about rebasing?

**Comment by lriggs** [comment]
Have you looked at the csv file called 'test_results_combined.csv'? That will list every test case and the reason they failed. You could also narrow it down to the simpler test cases by running 'tdvt --run your_datasource -e standard' and work on getting those passing first.

**Comment by PiraisudanM** [comment]
Hi  lriggs,

Thank you for your prompt response. I am working on resolving all the failed test cases based on the error message from the 'test_results_combined.csv' file.

I have an issue with bool data type columns when I run the tests under the "calcs_data". It sends the following query,
        SELECT (CASE
        WHEN "Calcs"."bool0" THEN 1
        WHEN NOT "Calcs"."bool0" THEN 0
        ELSE NULL END) AS "TEMP(Test)(3428507074)(0)"
        FROM "TestV1"."Calcs" "Calcs"
        GROUP BY "TEMP(Test)(3428507074)(0)"

Instead of sending like below query,
        SELECT (CASE
        WHEN "Calcs"."bool0" = 1 THEN 1
        WHEN NOT "Calcs"."bool0" =1 THEN 0
        ELSE NULL END) AS "TEMP(Test)(3428507074)(0)"
        FROM "TestV1"."Calcs" "Calcs"
        GROUP BY "TEMP(Test)(3428507074)(0)"

As per the document, I tried with setting the CAP_QUERY_BOOL_IDENTIFIER_TO_LOGICAL to "yes" and "no". But in both cases no difference in the generated query.
Please provide the solution to get past this issue.

**Comment by lriggs** [comment]
Try setting CAP_QUERY_BOOLEXPR_TO_INTEXPR to true in your manifest file.

**Comment by PiraisudanM** [comment]
Hi  lriggs,

Tried with setting CAP_QUERY_BOOLEXPR_TO_INTEXPR to true, but still facing the same problem.

**Comment by PiraisudanM** [comment]
Hi lriggs, Any updates on the above issues?

And when I run 'COUNT([int0])' expression test case, it sends 'SUM(1)' in the select list without column name. But for the 'COUNT([date3])' test case, it sends proper column name 'COUNT("Calcs"."date3")' in select list. How can I resolve this issue?

**Comment by lriggs** [comment]
You don't need to change the version number in any of your files.
Is the count test failing? I can take a look if you'd like to post your csv test file.

**Comment by PiraisudanM** [comment]
Hi lriggs, 

Thanks for your reply. I am facing few issues while running the TDVT test. Issues are listed below, please provide the solution as soon as possible. 

**Base Dialect used in "dialect.tdd" file: DefaultSQLDialect.**

1) For the COUNT test failing, 
**TestName:** "agg.count".

- When I look into the CSV test file, the same query generated without column name in the select part of the query for COUNT([int0]), COUNT([bool0]), COUNT([num4]) and COUNT([str2]) test cases. The only difference in each of the generated query is column alias. So I'm getting "Actual does not match expected" error.  The generated query below,

> SELECT SUM(1) AS "TEMP(Test)(1133866179)(0)"
> FROM "TestV1"."Calcs" "Calcs"
> HAVING (COUNT(1) > 0)

- But for the "COUNT([date3])" test case, proper query generated like below,

> SELECT COUNT("Calcs"."date3") AS "TEMP(Test)(3590771088)(0)"
> FROM "TestV1"."Calcs" "Calcs"
> HAVING (COUNT(1) > 0)

2) The issue with bool data type columns when I run the tests under the "calcs_data". It sends the following query without any condition before "THEN" in "CASE", So the query execution failed.    

- The generated failed query,  

> SELECT (CASE       
> WHEN "Calcs"."bool0" THEN 1        
> WHEN NOT "Calcs"."bool0" THEN 0       
> ELSE NULL END) AS "TEMP(Test)(3428507074)(0)"       
> FROM "TestV1"."Calcs" "Calcs"        
> GROUP BY "TEMP(Test)(3428507074)(0)" 

- Instead of sending like below query,
>SELECT (CASE
>WHEN "Calcs"."bool0" > 0 THEN 1
>WHEN NOT "Calcs"."bool0" > 0 THEN 0
>ELSE NULL END) AS "TEMP(Test)(3428507074)(0)"
>FROM "TestV1"."Calcs" "Calcs"
>GROUP BY "TEMP(Test)(3428507074)(0)"

- I tried setting the "CAP_QUERY_BOOL_IDENTIFIER_TO_LOGICAL" and "CAP_QUERY_BOOLEXPR_TO_INTEXPR" to true. But I'm getting the same query without condition before THEN in CASE. 

3) The TIMESTAMPADD() function query generated with NULL value in interval, but "DefaultSQLDialect (SQL 92 Implementation)" doesn't support NULL value in TIMESTAMPADD() function. I need a generated query that has equivalent CAST to the NULL value.  How to resolve this issue?

- The generated failed query,

> SELECT TIMESTAMPADD(SQL_TSI_YEAR,1,TIMESTAMPADD(SQL_TSI_DAY,NULL,{d '1900-01-01'})) AS "TEMP(Test)(1053114602)(0)"
> FROM "TestV1"."Calcs" "Calcs"
> HAVING (COUNT(1) > 0)

- I tried setting "CAP_QUERY_NULL_REQUIRES_CAST" to "yes" but no changes in the generated query. 

4) When I run the "agg.countd" test case, the generated query contains "TRUE" and "FALSE" keyword in the CASE statement of the query instead of setting equivalent integer value for that.

- The failed query,

> SELECT COUNT(DISTINCT (CASE WHEN ("Calcs"."bool0" <> FALSE) THEN 1 WHEN NOT ("Calcs"."bool0" <> FALSE) THEN 0 ELSE NULL END)) AS "TEMP(Test)(1408008556)(0)"
> FROM "TestV1"."Calcs" "Calcs"
> HAVING (COUNT(1) > 0)

- Expected query,

> SELECT COUNT(DISTINCT (CASE WHEN ("Calcs"."bool0" <> 0) THEN 1 WHEN NOT ("Calcs"."bool0" <> 0) THEN 0 ELSE NULL END)) AS "TEMP(Test)(1408008556)(0)"
> FROM "TestV1"."Calcs" "Calcs"
> HAVING (COUNT(1) > 0)

- For this test case also, tried setting "CAP_QUERY_BOOLEXPR_TO_INTEXPR" to "yes", but no changes in the generated query. 

5) When I'm running the logical test, few tests passed successfully but most of the test cases got the following error without generating any query,

> **"Error. Previous error message is: Attempting to run query...
> TableauException: Tableau cannot evaluate the query that results from this calculation.
> Error running query"**

- Please find the attached screenshot of the CSV file when ran the logical test.
![2019-11-20_12h03_57](https://user-images.githubusercontent.com/29723277/69215861-c23a0580-0b90-11ea-95a4-f96cc47932e9.png)

It will be extremely helpful if I get a solution to all the above-mentioned issues.

**Comment by PiraisudanM** [comment]
Hi lriggs, 
Any update on these issues?
I am stuck on these issues, I looking for your solution to move forward.

**Comment by lriggs** [comment]
You might consider picking another dialect that more closely matches your database. This could give you a better starting point.

The first case has to do with improper null metadata. For ODBC, Tableau checks the SQLColAttribute with SQL_DESC_NULLABLE on the result set metadata for ODBC connections. If it thinks there are no nulls then it will try and optimize the query by just selecting sum(1).

You might be able to fix number 2 with https://github.com/tableau/connector-plugin-sdk/blob/master/samples/components/dialects/Annotated.tdd#L446

For 3 you could add a cast in the date function here I think: https://github.com/tableau/connector-plugin-sdk/blob/master/samples/components/dialects/Annotated.tdd#L950

For number 4, try setting format-true and format-false in the dialect. https://github.com/tableau/connector-plugin-sdk/blob/master/samples/components/dialects/Annotated.tdd#L1363

Number 5 probably has to do with the logical test config settings. Is the staples table loaded in a schema called TestV1?

**Comment by PiraisudanM** [comment]
Hi lriggs, 

Thank you for the response.

**For 2 :** (The issue with bool data type columns when I run the tests under the "calcs_data". It sends the following query without any condition before "THEN" in "CASE", So the query execution failed. ).

Referred the [link](https://github.com/tableau/connector-plugin-sdk/blob/master/samples/components/dialects/Annotated.tdd#L446) you provided and added the following lines in the dialect file but no changes in the generated query, 

```
  <function group='logical' name='IFNULL' return-type='bool'>
    <formula>(CASE WHEN %1 THEN 1 WHEN NOT %1 THEN 0 ELSE NULL END)=1</formula>
    <argument type='bool' />
    <argument type='bool' />
  </function>
```

**For 4 :** (When I run the "agg.countd" test case, the generated query contains "TRUE" and "FALSE" keyword in the CASE statement of the query instead of setting equivalent integer value for that.)

Referred the provided [link](https://github.com/tableau/connector-plugin-sdk/blob/master/samples/components/dialects/Annotated.tdd#L1363) and added the following lines in the dialect file but no changes in the generated query,
```
  <sql-format>
    <format-false value='0' />
    <format-true value='1' />
  </sql-format>
```

**For 5 :** (When I'm running the logical test, all the test cases under "Staples" and "LOD" are failing.)

Yes, I added the "**Staples**" table in the "**TestV1**" schema. The connection also successfully passed when running the tests. Screenshot below, 

![2020-02-07_18h30_44](https://user-images.githubusercontent.com/29723277/74032986-3f7c5600-49db-11ea-98ed-ed91c4700975.png)



But all the Staples and LOD test cases have failed.  

**Note:** I am using "**DefaultSQLDialect**" but currently, it is missing under the "**Dialect base classes**" in the TDVT document. Is there any equivalent dialect for that? (when using a dialect other than DefaultSQLDialect, the success count is less).


We are anticipating a quicker resolution for the issues.

**Comment by PiraisudanM** [comment]
Hi lriggs, any updates on the issues?

**Comment by sidwray** [comment]
Sorry to appear to be having a number of issues with your connector.  We not in a position to help you make your connector, but are fulling supporting the use of the SDK.  Many of the items you are encountering are the natural integration process of dev/test.  We're working closely with a few partners on an initial validation process, and will be able to help you more after that.
