### ISSUE TITLE
custom odbc connector Case 1 error

### ISSUE THREAD

**Issue by FengJinghHua** [tableau/connector-plugin-sdk#335]
Hi,

I am using the connector SDK to develop a custom odbc connector. I have encountered a few issues that i hope you can help me with

`Case  when 1 ` as limiter - the odbc connector dialect ProgressOpenEdgeDialect. when trying to run tdvt expression test,the test file is "setup.logical.txt",I test the `IF NOT FALSE THEN 'yes' END` or other test case in setup.logical.txt , the sql in my datasourec is : 
```
SELECT (CASE WHEN 1 THEN 'yes' ELSE CAST(NULL AS VARCHAR(1)) END) AS "TEMP_Test__1030668643__0_",
1.1000000000000001 AS "X__alias__0"
FROM "TDVT"."CALCS" "CALCS"
GROUP BY 1.1000000000000001
```

 and  the  the error message：` Syntax error:"Expected a boolean type".`  My odbc driver does not support the int  as the boolean type . If I change the sql as 
```
SELECT (CASE WHEN 1<>0 THEN 'yes' ELSE CAST(NULL AS VARCHAR(1)) END) AS "TEMP_Test__1030668643__0_",
1.1000000000000001 AS "X__alias__0"
FROM "TDVT"."CALCS" "CALCS"
GROUP BY 1.1000000000000001
```
It can works. I find the config item `CAP_QUERY_BOOLEXPR_TO_INTEXPR`, it works but for global，I will make some function fail like `contains , startwith, endwith`; I think modify in tdd file will be a good way,  but I can not find any config in [Annotated.tdd](https://github.com/tableau/connector-plugin-sdk/blob/master/samples/components/dialects/Annotated.tdd)  about it.
Any idea how to modify to pass it?

Thank you

**Comment by lriggs** [comment]
Hi, can you share the first part of your tdd file which should look something like this?
    <dialect name='AnnotatedOracleDialect'
         class='oracle'
         dialect-version='1.0'
         base='OracleTDDHelper'
         version='18.1'>

There is a ProgressOpenEdgeDialect dialect which you can use for the base attribute. It should generate the SQL you are looking for for this test case.

Otherwise you should be able to set format-true and format-false to control this: https://github.com/tableau/connector-plugin-sdk/blob/master/samples/components/dialects/Annotated.tdd#L1363

**Comment by FengJinghHua** [comment]
Thanks , I have real use the ProgressOpenEdgeDialect dialect in my tdd file. 

![image](https://user-images.githubusercontent.com/15244686/67825699-26732780-fb05-11e9-8fc5-5f6ffe4d6ba2.png)

**Comment by lriggs** [comment]
That looks correct. It would be worthwhile to review the log files to make sure its picking up that tdd file. You can search for 'connector-plugin' in the log.txt file. An easy way to test this is to start Tableau Desktop with your plugin loaded, then open the cast_calcs tds file. You can then create a calculated field and put in the Test Case as the value, for example: "IF NOT FALSE THEN 'yes' END" Then if you drag that new field to the viz you should be able to reproduce the error. If you want to send the log files to connectorsdk [at] tableau.com then I can take a look.

**Comment by rosswbrown** [comment]
Closing answered or inactive issues.
