### ISSUE TITLE
Configure WHERE expressions differently

### ISSUE THREAD

**Issue by iancr01** [tableau/connector-plugin-sdk#362]
**About You:**
Name: Cris Ianculovici
Company: Actian Corp

**Your question:**
How to configure WHERE clauses differently than SELECT clauses?
E.g.
Syntax
`SELECT expression1 FROM ... WHERE expression2`

The dialect.tdd files seem to allow only for one set of configuration for both. However we need to be able to independently configure the 2 expressions. 

For example, that's needed when the DB supports in the WHERE clause only 

`WHERE a=b`

but not 

`WHERE bool_value`

The first is SQL standard, the second is not.

**Comment by lriggs** [comment]
Hi Cris, I don't think Tableau has the ability to do that right now. Which tdvt test is impacted by this? Can you provide the failing query for that test?

**Comment by iancr01** [comment]
Many of the tests are impacted. One example is  tdvt\exprtests\standard\setup.date.now.txt. 

The problem is that the dialect has only one options for how to generate the SQL for both SELECT LIST and WHERE.
So if we fix the issue for the WHERE clause, for example we add IS TRUE at the end of the expression, so that the expression reads something like: 
WHERE parameter IS TRUE (instead of the unsupported syntax WHERE parameter)

Then it would break it or the SELECT LIST, because it would be something like:
SELECT parameter IS TRUE 

Which is not supported syntax.

**Comment by lriggs** [comment]
I checked that test for the other connectors that we test and I didn't find any examples of similar behavior. Could you share a concrete example for that particular test? Which SQL is being generated?

We have some special handling for boolean fields, but nothing for other types. If I can understand the use case better we might be able to add more flexibility to the dialect.

**Comment by iancr01** [comment]
Here is a specific example:

dialect.tdd:

    <function group='operator' name='==' return-type='bool'>
       <formula>(CASE WHEN %1 IS NULL OR %2 IS NULL THEN NULL WHEN %1 = %2 THEN TRUE ELSE FALSE END)        IS TRUE</formula>
       <argument type='int' />
       <argument type='int' />
     </function>

Test output:

    <test name='datepart(&apos;second&apos;, now()) = datepart(&apos;second&apos;, now())'>
      <sql>
      SELECT (CASE WHEN SECOND(TIMESTAMP(CURRENT_TIMESTAMP,0)) IS NULL OR SECOND(TIMESTAMP(CURRENT_TIMESTAMP,0)) IS NULL THEN NULL WHEN SECOND(TIMESTAMP(CURRENT_TIMESTAMP,0)) = SECOND(TIMESTAMP(CURRENT_TIMESTAMP,0)) THEN TRUE ELSE FALSE END)        IS TRUE AS &quot;TEMP_Test__1432496731__0_&quot;&#10;FROM &quot;actian&quot;.&quot;Calcs&quot; &quot;Calcs&quot;&#10;HAVING (COUNT(1) &gt; 0)
      </sql>
      <query-time>
      715.000
      </query-time>
      <error>
      [Actian][Ingres ODBC Driver][Ingres]line 1, Syntax error on &apos;IS&apos;.  The correct syntax is: &#10; PREPARE stmnt_name [INTO name] FROM statement_text&#10;
      </error>
      <error-type>
      QueryCompilation
      </error-type>
      <table>
      </table>
    </test>

However, if we change the dialect to eliminate the IS TRUE part and use:

    <function group='operator' name='==' return-type='bool'>
       <formula>(CASE WHEN %1 IS NULL OR %2 IS NULL THEN NULL WHEN %1 = %2 THEN TRUE ELSE FALSE END)</formula>
       <argument type='int' />
       <argument type='int' />
     </function>

Then filters will have
    WHERE 
        CASE WHEN %1 IS NULL OR %2 IS NULL THEN NULL WHEN %1 = %2 THEN TRUE ELSE FALSE END

This fails with Syntax error
    Syntax error on 'EOF'.  The correct syntax is:
      SELECT [ALL|DISTINCT] target_list
        FROM table(s)
        [WHERE search_cond]
        [GROUP BY col(s)]
        [HAVING search_cond]
        [WINDOW window_defn]
     [UNION subselect]
     [ORDER BY col(s)]

This is because in this situation the IS TRUE syntax is necessary in the WHERE clause.

**Comment by lriggs** [comment]
Thanks for the detailed example. Some of the connectors that we've developed do use this pattern. You can enabled it by turning on CAP_QUERY_BOOLEXPR_TO_INTEXPR in your manifest file. In that case your equals operator can simply be '%1 = %2' and then Tableau's query engine will wrap that in a CASE statement to generate a boolean expression.

If you use a calculated field like `datepart('second', now()) == datepart('second', now())` as a filter then the generated WHERE clause will just have '%1 = %2'. 

Would that type of sql work for you?

**Comment by iancr01** [comment]
This is working for us. Thanks!
