### ISSUE TITLE
loading  custom  plugin failed  with error code 37CE01A3

### ISSUE THREAD

**Issue by hegdean** [tableau/connector-plugin-sdk#368]
Anuradha Hegde, Esgyn Corporation
When I test the connector manually  with 2019.2 or 2019.4 version  it is unable to load the plugin
"C:\Program Files\Tableau\Tableau 2019.2\bin\tableau.exe" -DConnectPluginsPath=E:\tableau_connectors

<img width="668" alt="connector-error" src="https://user-images.githubusercontent.com/12959032/68439952-5a41f300-017e-11ea-900b-33c0ad2bdbf4.PNG">

**Comment by pvanderknyff** [comment]
Hi Anuradha,

That error is thrown when one of the javascript components encounters an error. The logs should have more information. The relevant log line will be in either log.txt or the latest tabprotosrv log in "My Tableau Repository/Logs". Search for the keyword "connector-plugin-error".

**Comment by hegdean** [comment]
Thank you!  It was syntax error for  one of the parameters . Fixed the parameter and now it works!

{"function":"SyntaxError: Expected token `,'","line":"\u0006","msg":"QJSEngineWrapper::RunScriptImpl Error running script.","script":"(function dsbuilder(attr)\n{\n    var params = {};\n\n

**Comment by pvanderknyff** [comment]
I'm glad the script is working now! Closing since this is resolved.
