### ISSUE TITLE
Documentation update needed

### ISSUE THREAD

**Issue by astefan** [tableau/connector-plugin-sdk#372]
It seems that the TDVT tests suite (code checked out on Nov 12th, 2019) have changed significantly enough that the[ documentation on how to run it](https://tableau.github.io/connector-plugin-sdk/docs/tdvt) is not up-to-date anymore (compared to the code from Oct 8th, 2019).

The steps that don't match the new version are not few, but for one `tdvt --add_ds` and other similar commands don't work anymore.

From what I could tell `tdvt --add_ds` is now `tdvt action --add_ds` and `tdvt --run` is now `tdvt run`. 
`py -3 -m tdvt.tdvt --setup` doesn't work anymore, and same goes for `tdvt --generate`. It's a lot of guessing now, which makes tdvt usage time consuming and not user friendly.

**Comment by lukewrites** [comment]
Hi, Andrei, thanks for opening the issue. Apologies for the docs issue, we will get them updated as soon as possible. 

In the meantime, if you'd like to check out to 99159b8, that release of the sdk should work as expected with the current docs.

**Comment by astefan** [comment]
@lukewrites thanks for the reply and acknowledgement.

Indeed, the docs work fine for 2019.3, 2019.2 and 2019.1, but there are some [fixes](https://github.com/tableau/connector-plugin-sdk/issues/317) (and [this one](https://github.com/tableau/connector-plugin-sdk/issues/305#issuecomment-541795824)) that I'm eagerly waiting to check out, thus my interest in the 2019.4 version and the up-to-date TDVT suite.

**Comment by lukewrites** [comment]
@astefan [docs have been updated.](https://tableau.github.io/connector-plugin-sdk/docs/tdvt)
