### ISSUE TITLE
Tests do not run on 2019.4

### ISSUE THREAD

**Issue by astefan** [tableau/connector-plugin-sdk#373]
After [struggling a bit with the new version of the TDVT suite](https://github.com/tableau/connector-plugin-sdk/issues/372) I might have been (or not, since I have issues getting results out of these tests runs) able to generate tests and run them eventually.

But, even if I am able to start Tableau Desktop 2019.4 and, also, see my connector in the list of databases at the startup and use it to connect to the server properly, the TDVT test suite seems to encounter a roadblock and none of the tests pass.

Below you can see a snippet from logs... the server IP address is correct, the port is correct (I checked the TDS files), the same for the password, the location of the custom connector is specified, as it always has been, properly in `config\[ds_name].ini` file using `CommandLineOverride = -DConnectPluginsPath`.

The error message does seem to indicate an issue with the connection itself, but I am leaning to believe this is a red herring, given the `Error starting Java Protocol Server. Couldn't read socket or port.` error message before the `Unable to connect` one.

```
2019-11-13 15:42:59,373 Thread-[4] CalledProcessError: Return code: 14 LoadDatasource TableauException: Error starting Java Protocol Server. Couldn't read socket or port.
Unable to connect to the Test JDBC server "10.0.2.2". Check that the server is running and that you have access privileges to the requested database.

No data source specified

2019-11-13 15:42:59,374 Thread-[4] Command line output:LoadDatasource TableauException: Error starting Java Protocol Server. Couldn't read socket or port.
Unable to connect to the Test JDBC server "10.0.2.2". Check that the server is running and that you have access privileges to the requested database.

No data source specified

2019-11-13 15:42:59,385 Thread-[6] CalledProcessError: Return code: 14 LoadDatasource TableauException: Error starting Java Protocol Server. Couldn't read socket or port.
Unable to connect to the Test JDBC server "10.0.2.2". Check that the server is running and that you have access privileges to the requested database.


2019-11-13 15:42:59,386 Thread-[6] Command line output:LoadDatasource TableauException: Error starting Java Protocol Server. Couldn't read socket or port.
Unable to connect to the Test JDBC server "10.0.2.2". Check that the server is running and that you have access privileges to the requested database.
```

Any ideas/workarounds? Things I could have broken in my attempts to make TDVT suite run?

**Comment by lriggs** [comment]
Could you attach your jprotocolserver.log file (or email it to connectorsdk at tableau). It isn't captured in the tabquery log zip file but you can run your tests with the `--no-clean` option. That will leave behind some tempdirs and if you look in there you will find the jdbc log file.

**Comment by astefan** [comment]
Sent via email. Thanks.

**Comment by lriggs** [comment]
There seems to be a resource contention issue with JDBC based connectors. It can be worked around by running fewer threads when running tdvt tests. The '-t 1' argument will use just one thread to run tests for example. Some experimentation may be required, but 2 or 3 threads may work.

**Comment by lriggs** [comment]
FYI, we are continuing to look into a long term fix for this. In the meantime running fewer threads is the preferred workaround. It is related to starting several JVMs simultaneously on lower powered systems.
