### ISSUE TITLE
unable to select database catalog after successful connection using custom connector

### ISSUE THREAD

**Issue by hegdean** [tableau/connector-plugin-sdk#374]
I have the custom connector folder (e:\tableau_connectors) and it contains esgyn_odbc folder with  these set of files  manifest.xml, dialect.tdd, connectionResolver, connection-dialog.tcd and connectionBuilder. I am able to launch the the connector  using -DConnectPluginsPath  setting  but after I enter the user credentials and sign in successfully I am able to see the database tab and when I select my catalog nothing happens. Is there any suggestion on what I might be missing? I do not see any obvious error in tabprotosrv log files.

**Comment by lriggs** [comment]
What do you have for required attributes in the resolver? It should have something for database.

**Comment by hegdean** [comment]
Yes; TRAFODION is our default catalog and I see that being displayed. I can even see that the connection has succeeded from the server side. but  when I click on the database nothing happens. screenshot attached.  The name of the connector will say Trafodion  but it is the same as EsgynDB
[database-screen.docx](https://github.com/tableau/connector-plugin-sdk/files/3849251/database-screen.docx)

**Comment by hegdean** [comment]
Is there a verbose option that I can enable to see what error when I click on the database catalog (TRAFODION). The tabprotosrv log has the same usual set of errors 

{"error-desc":"[TRAF][Trafodion ODBC Driver][Trafodion Database] SQL error:*** ERROR[1720] Isolation Level 'SERIALIZABLE' is not supported. 
[TRAF][Trafodion ODBC Driver][Trafodion Database] SQL error:*** ERROR[8822] The statement was not prepared. [2019-12-01 03:17:14]\n[TRAF][Trafodion ODBC Driver][Trafodion Database] SQL error:*** ERROR[15001] A syntax error occurred at or before: \nCREATE LOCAL TEMPORARY TABLE \"XT01_4D29D98F_BA41_4BCF_81C1_BAD335F098D5_1_Conne\nct_CheckCreateTempTableCap\" (\n \"COL\" INTEGER\n ) ON COMMIT PRESERVE ROWS;\n           ^ (136 characters from start of SQL statement) [2019-12-01 03:17:14]\n"

**Comment by rosswbrown** [comment]
Closing answered or inactive issues.
