### ISSUE TITLE
Appending to the default ODBC catalog content

### ISSUE THREAD

**Issue by bdeboe** [tableau/connector-plugin-sdk#39]
Hi,
great to see the SDK is now available for public consumption / production. Building a simple connector wrapping an existing ODBC or JDBC driver seems straightforward (we'll be starting that very soon), but we're curious about possibilities to append additional information to the ODBC (or JDBC) catalog content that Tableau automatically retrieves once the connection has been established. More to the point, our database supports some back-end BI modeling capabilities of its own (dimension info, pretty names, ...) and we'd like to be able to leverage that metadata when Tableau builds a .tds file or at least the data source browser in which you build that. 
Any suggestions on how we could inject that information are much appreciated.

Thanks,
benjamin

**Comment by lriggs** [comment]
Thanks Benjamin. We don't have a way to surface these capabilities at the moment but we'll take it under consideration for future versions.

Can you describe the requirements a little more? How do you envision using this catalog data in Tableau? How is it returned through the ODBC API?

**Comment by bdeboe** [comment]
Thanks @lriggs. We're exposing it through a stored procedure that can be accessed as a table from SQL, as it doesn't fit in the standard ODBC catalog tables. We can already write a script that generates a .tds file based on this metadata, but that'd be a manual step if there's no way of driving it from the connector and IMHO this is exactly the sort of added UX value custom connectors could and should bring :-)
How does this work for multidimensional data sources like MS Analysis Services or the Teradata OLAP connector. There's supposedly something in there that feeds the dimension metadata through to Tableau, so feeding that API would likely be all we need.

**Comment by BobSenturus** [comment]
Agreed on this concept being a highly desired feature.  Two other use cases: 

* Being able to mark columns as hidden when loading a table (i.e. we generate link columns that a user would never leverage in a Viz, but Tableau needs them to join tables).  I don't believe ODBC has anything to leverage, but code in our custom connector level could watch for a special column name and toggle it to hidden.

* Being able to set a "Notes" property on the "Describe..." popup would be very handy for underlying lineage info or similar content.  Again, nothing in ODBC would help with this, but code at the custom connector level could ping a function/stored proc/ special table in the data source to get more info and populate it.

**Comment by hutchijo** [comment]
I noticed that this line in the documentation 

tableau.exe -DConnectPluginsPath =C:\tableau_connectors

should not have a space after DConnectPluginsPath.

I was able to get things working with this:

tableau.exe -DConnectPluginsPath=C:\tableau_connectors

**Comment by lriggs** [comment]
Tracking internally: 936099
