### ISSUE TITLE
[FEATURE] Support PKCS#11 store for code signing

### ISSUE THREAD

**Issue by laurentgo** [tableau/connector-plugin-sdk#395]
**Is your feature request related to a problem? Please describe.**
Packaging tool signing feature only support local keystore. But often code signing certificates are stored on a hardware device (like smartcard). The signing tool should allow to use those.

**Describe the solution you'd like**
PKCS11 is a common interface to access cryptographic tokens. It is also supported by Java signing tools. TACO signing tool should allow user to provider the name of the pkcs#11 and its configuration file, along with the public certificate chain (some tokens do not allow the whole chain to be stored)

**Describe alternatives you've considered**
Instructions on how to sign directly with jarsigner

**About You**
Name: Laurent
Company: Dremio

**Comment by lriggs** [comment]
Thanks for the feedback. I opened an internal item to track this work: 1039666

**Comment by clach04** [comment]
We're using yet another keystore :-) I'm OK without adding additional parameters being passed through the SDK (our security team would want to complete a security audit of the SDK if we were make use of a new feature like this)

We're creating the taco without a signature and then signing after the taco creation is complete.

**Comment by jainam1995** [comment]
We encourage partners to use jarsigner itself to sign the taco . The process that chris mentioned above is the one that we recommend. Please let us know by re-opening this issue if there is an issue with this process.
