### ISSUE TITLE
[FEATURE] Support package timestamping

### ISSUE THREAD

**Issue by laurentgo** [tableau/connector-plugin-sdk#396]
**Is your feature request related to a problem? Please describe.**
TACO code signing tool does not have secure timestamping.  As a consequence, it means the taco package becomes invalid as soon as the certificate expires.

**Describe the solution you'd like**
A set of options should be added to the packaging tool to provide at least the timestamping authority url and possibly related urls like digest algorithm. Of course Tableau should also make sure to check the timestamp too.

**Describe alternatives you've considered**

**About You**
Name: Laurent
Company: Dremio

**Comment by lriggs** [comment]
Thanks for the feedback. I opened an internal item to track this work: 1039663.

**Comment by sxlin** [comment]
Before we address this in packaging tool, you can use JDK jarsigner to sign the .taco file.

**Comment by laurentgo** [comment]
That's what I did using the following command:
```
jarsigner -keystore NONE -storetype PKCS11 -tsa <timestamping serverl url> -providerClass sun.security.pkcs11.SunPKCS11 -providerArg <path/to/pkcs11.cfg> -certchain <path/to/chain.pem> <path/to/connector.taco> <alias>
```

**Comment by pvanderknyff** [comment]
The error on MacOS is a known issue. The fix is coming in the first maintenance release for 2019.4.

**Comment by jainam1995** [comment]
The Fix is out . Do let us know if you are still facing an issue
