### ISSUE TITLE
API documentation makes it sound like this should work with Tableau 9.0

### ISSUE THREAD

**Issue by pettiross** [tableau/connector-plugin-sdk#40]
In the [API reference](https://tableau.github.io/connector-plugin-sdk/docs/capabilities) under CAP_FAST_METADATA, it says "This capability is available in 9.0 and later." I suggest striking that sentence, since connector plug-ins don't work with versions that far back.

**Comment by kpwilson** [comment]
Removed version references on this page. Added a key for the table. Changed the bold content to bold red text.
