### ISSUE TITLE
taco error - Error Code: 14D18B1F

### ISSUE THREAD

**Issue by clach04** [tableau/connector-plugin-sdk#401]
**About You:**
Name: Chris Clark
Company: Actian

I'm getting:

    Unexpected Error
    There was a problem while running the connector plugin. Reinstall the plugin or contact the plugin provider.
    Note that you might need to make local configuration changes to resolve the error.
    Error Code: 14D18B1F
    Package signature verification failed during connection creation.

From https://github.com/tableau/connector-plugin-sdk/blob/gh-pages/docs/log-entries.md there are some notes on extra information that can be found in the log.txt (under Windows `"%USERPROFILE%\Documents\My Tableau Repository\Logs\Log.txt"` but I'm getting a different failure type:

    Bad key usage

tableau support case 05527127 has the full log if that's needed.

**Comment by pvanderknyff** [comment]
Hi Chris, I've seen this error just recently, and am looking into it. Can I ask you a couple of questions?

1) When you run` jarsigner -verify [your-taco].taco`, does the output show "jar verified"?
2) Did you sign the taco using the packager included in the Connector SDK, or did you sign it manually using jarsigner after the taco was packaged?

Thanks.

**Comment by clach04** [comment]
Thanks for the quick response:

1. Yes
2. I used jarsigner.

    (.venv) C:\tableau\connector-plugin-sdk_packaging\connector-packager>jarsigner -verify  "C:\Users\clach04\Documents\My Tableau Repository\Connectors\actian_jdbc.taco"
    
    jar verified.

Let me know if I can help with anything else. Do you want to see the taco file? I have test taco files at https://github.com/clach04/actian_tableau_connector/releases

**Comment by pvanderknyff** [comment]
Hi Chris, it turns out there is a bug in our verifier code in Tableau that flags some valid signatures as invalid. I have a fix, and am hoping to get it into a maintenance release for 2019.4. I'll update this issue when it goes out. Sorry about that.

**Comment by clach04** [comment]
Thanks @pvanderknyff - I'm glad you were able to see this. I can wait for the official patch. but if it helps to have a tester, ping me.

**Comment by NicolasKo** [comment]
Hi guys, we seems to have exactly the same problem over there. 
Do you have info about the packaging date of the fix ? How can we help ?

**Comment by pvanderknyff** [comment]
@NicolasKo The fix has been completed and added to the next maintenance release of 2019.4. I do not have a date for when that will be released, I'll update this issue when the fix is released.

Just out of curiosity, which CA did you get your taco signed by? The two I've looked at for this bug were both signed by GoDaddy, and I'm wondering how widespread it is.

**Comment by NicolasKo** [comment]
That's a good news, I hope the next release will arrive soon.
The CA we use in this case is Comodo (using sectigo at the very end).

Do you want me to send you our .taco ?

**Comment by jainam1995** [comment]
The new release is here https://www.tableau.com/support/releases/desktop/2019.4.2#esdalt. i tested it at my end and it seems to be working correctly. Please could you check it ?

**Comment by clach04** [comment]
Just tested a single taco *successfully* 👍 - I need to do some more testing (more tacos, and also MacOS) but looking good. This was on Windows 64-bit with Tableau Desktop 2019.4.3 (20194.20.0119.2058).

@jainam1995 thanks for the heads up, your message is how I heard about the new patch being available :)

**Comment by NicolasKo** [comment]
Same here - my taco is now accepted :-)
Thanks a lot guys !

**Comment by pvanderknyff** [comment]
Glad your tacos are working! Closing this since it is fixed, thanks for your help in identifying it.
