### ISSUE TITLE
[BUG] python -m tdvt.tdvt run NAME --verify , exits with failure on successful smoke test

### ISSUE THREAD

**Issue by clach04** [tableau/connector-plugin-sdk#403]
**Describe the bug**

    python -m tdvt.tdvt run NAME --verify 

exits with:

    2 smoke test(s) ran.
    Smoke tests failed, exiting.

Even though output test_results_combined.csv indicates passes.

**Desktop (please complete the following information):**
 - OS: Windows - NA
 - Tableau Version 2019.4 - NA

**About you:**
 Name: Chris Clark
 Company: Actian

It looks like a spurious message. This used to work a few months back (commit 7da82beb98a75acaf67fc92acf529c0492b4303c from July 2018) and there was no message. See comment on https://github.com/tableau/connector-plugin-sdk/commit/c3599be53c38fba2665e2806c9d1d11199c370b7

**Comment by clach04** [comment]
Original code at https://github.com/tableau/connector-plugin-sdk/blob/b9ed43a68d5bc76c16cb81757b134435d4adf010/tdvt/tdvt/tdvt.py#L535

**Comment by clach04** [comment]
Posted https://github.com/tableau/connector-plugin-sdk/pull/404

**Comment by lukewrites** [comment]
Thanks for opening a PR for this! We have it fixed in the `dev-tdvt` branch ([here](https://github.com/tableau/connector-plugin-sdk/blob/dev-tdvt/tdvt/tdvt/tdvt.py#L595)) and will get it released to master soon.

**Comment by lukewrites** [comment]
Fixed in #397
