### ISSUE TITLE
[BUG] In the docs, it's not clear where the ‘connectionHelper’ object originates?  

### ISSUE THREAD

**Issue by sidwray** [tableau/connector-plugin-sdk#409]
**Describe the bug**
In the PostGres JDBC example, it’s not obvious to me where the ‘connectionHelper’ object originates in the two JavaScript files.  I assume it’s introduced from somewhere else outside my visibility – or am I supposed to implement it?   I am not a JavaScript programmer.

https://github.com/tableau/connector-plugin-sdk/blob/master/samples/plugins/postgres_jdbc/connectionBuilder.js

**Comment by pvanderknyff** [comment]
Hi Sid! 

connectionHelper originates from Tableau itself, and allows you to call certain methods and constants inside Tableau from the JavaScript. You can see what methods are available on this page: https://tableau.github.io/connector-plugin-sdk/docs/api-reference
