### ISSUE TITLE
SDK docs don't give a minimum Tableau version

### ISSUE THREAD

**Issue by pettiross** [tableau/connector-plugin-sdk#41]
I can't find a reference to the minimum Tableau version needed anywhere in the docs. One good place to put it could be in the bulleted list under "Before you begin" at the bottom of the [Get Started](https://tableau.github.io/connector-plugin-sdk/docs/) page. If it requires a pre-release version at this point, we might also want to link to the directions for getting a beta.

**Comment by kpwilson** [comment]
Tableau 2019.1 Beta 2 is the required version. I'll update the Get Started page and add a link to the beta site.
