### ISSUE TITLE
[BUG] not possible to provide paths with spaces to -DConnectPluginsPath 

### ISSUE THREAD

**Issue by clach04** [tableau/connector-plugin-sdk#411]
**Describe the bug**

Under Windows, if the path contains spaces the connectors will not load. Escaping path does not work (both "" and \^). Using Windows short paths with `...~1...` (for `dir /x`) does not work either

See Tableau  Case# 05542036  for more details

https://tableau.github.io/connector-plugin-sdk/docs/share does not cover this.

Workaround is to create paths without spaces but it does mean My Documents (etc.) can not be used as a location.

**Screenshots**

NA

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Tableau Version 2019.4

**About you:**
 Name: Chris Clark
 Company: Actian

**Comment by pvanderknyff** [comment]
Wrapping the path in quotes works for me (tested in 2019.4): `tableau.exe -DConnectPluginsPath="C:\Users\pvanderknyff\Desktop\connectors space\conn"` Does this work for you?

**Comment by clach04** [comment]
@pvanderknyff  you are 💯 % right. I have no idea what was going wrong for me when I tested this.

Its even working with USERPROFILE variables in the environment:

    tableau.exe -DConnectPluginsPath=%USERPROFILE%\"Documents\My Tableau Repository\Connectors_git"

Thanks for the quick response and apologies for the non-issue.
