### ISSUE TITLE
How to remove the db from the left panel ?

### ISSUE THREAD

**Issue by NicolasKo** [tableau/connector-plugin-sdk#413]
Hi,
Thanks a lot for the SDK. We followed the doc and works fine for us.
In our case, there is schema but the dbname field is not necessary. I would love to remove it from the left panel. I didn't found the way to do that.

Can you tell me where to specify that
1. I do not need a database name (db-name)
2. If needed, where to specify the default one

Regards

**Comment by pvanderknyff** [comment]
Hi Nicolas,

You can try setting has-databases to false in your connection dialog (.tcd) file like we do in our SQLite sample: https://github.com/tableau/connector-plugin-sdk/blob/master/samples/plugins/sqlite_extract/connectionDialog.xml#L7.

**Comment by NicolasKo** [comment]
Thanks a lot, adding the has-databases to false in the connection dialog (.tcd) file remove the database part in the left panel.
Doing that, I can still select my schemas and tables, but the list of columns disappear.

**Comment by NicolasKo** [comment]
Hi @pvanderknyff : I'm still stuck on this issue, do you think you can help ?

**Comment by pvanderknyff** [comment]
Apologies for not getting to this earlier, just got back from vacation. 

If you could see the tables before, you probably need to set the default database in your connection builder script. You can try something like the following:

`params["DATABASE"] = "Default";`

**Comment by NicolasKo** [comment]
Thanks, I have already tried that.
I also tried adding the database in the jdbc URI.
But it do not makes appears the columns :-(

**Comment by pvanderknyff** [comment]
Can you check the queries for getting the column names? They can be found in the tabprotosrv log located in your My Tableau Repository folder. Seeing what query worked before the change can help pinpoint why it isn't working anymore.

**Comment by NicolasKo** [comment]
Hi @pvanderknyff 

I finally found how to achieve : instead of adding the database in the connection builder script, I simply had to add it in the connectionresolver.tdr.

the default value with 

        <default-attributes>
          <default-attribute name='dbname'>default</default-attribute>
        </default-attributes>

And then the fact that it is mandatory

        <attribute-list>
          ...
          <attr>dbname</attr>
        </attribute-list>

Thanks for your help !

**Comment by saikeerthi733** [comment]
hi @NicolasKo can you please share the tdr file if you can. i am trying to implement the same but the validation fails when i add default attributes
