### ISSUE TITLE
How to add support for an ODBC driver

### ISSUE THREAD

**Issue by iancr01** [tableau/connector-plugin-sdk#436]
**About You:**
Name: Cris Ianculovici
Company: Actian

**Your question:**
Our ODBC driver is not currently supported on Linux / with Tableau Server. We've tested the install of the driver in a Linux environment but can't get it to work with Tableau Server, even though the ODBC driver works perfectly well with other applications. What needs to be done so that Tableau Server can use the ODBC driver? Is there a place to setup certain environment variables to get it to work?

**Comment by clach04** [comment]
I believe Tableau Server does not have the required paths in shared library path (binary path too). Errors strongly indicate a failure to load a shared library. tsm (start) appears to reset the environment.

**Comment by lriggs** [comment]
Generally we don't make any changes when testing a driver on Linux or Server. It's possible there are driver environment variables that need to be set.

**Comment by iancr01** [comment]
Where would we set environmental variables at the Tableau Server level? I tried to find that in the documentation but I was not able to find anything...

**Comment by sidwray** [comment]
tfs 1197828

**Comment by sxlin** [comment]
@iancr01 Is this still an issue? I see Actian connector already published in Tableau Extension Gallery.

**Comment by clach04** [comment]
@sxlin, I think this is still a limitation of Tableau Server. Is there a version of Server that supports user configuration of the environment, specifically environment variables and shared/binary paths?

**Comment by sxlin** [comment]
@clach04 Can you email me(slin @ tableau . com) the logs of `vizqlserver`?

Does the driver installer updates odbcinst.ini?  Can you send me a copy of the odbcinst.ini file?

**Comment by sxlin** [comment]
BTW, Tableau uses unixODBC driver manager.

**Comment by clach04** [comment]
> @clach04 Can you email me(slin @ tableau . com) the logs of `vizqlserver`?

@iancr01  is this something you can do? I only have Desktop and not Server installed at the moment :(

@sxlin out of curiosity what are you looking for from this?

> Does the driver installer updates odbcinst.ini? 

No it does not update that file, that's not really appropriate for drivers to modify, its really for admins to edit.

> Can you send me a copy of the odbcinst.ini file?

Here is a sample:

    $ cat /opt/Actian/Vector_Client/ingres/files/odbcinst.ini
    [ODBC Drivers]
    Ingres=Installed
    Ingres CL=Installed

    [Ingres]
    Driver=/opt/Actian/Vector_Client/ingres/lib/libiiodbcdriver.1.so
    DriverODBCVer=3.50
    DriverReadOnly=N
    DriverType=Ingres
    Vendor=Actian Corporation
    DontDlClose=1

    [Ingres CL]
    Driver=/opt/Actian/Vector_Client/ingres/lib/libiiodbcdriver.1.so
    DriverODBCVer=3.50
    DriverReadOnly=N
    DriverType=Ingres
    Vendor=Actian Corporation
    DontDlClose=1

    [ODBC]
    Trace=N
    Trace File=odbctrace.log
    TraceFile=odbctrace.log
    PoolTimeout=-1

What are you looking for in the ini file? I'm not understanding what this has to do with operating system environment variables. I do not believe UnixODBC supports setting operating system environment variables in its config files.

I believe it expects the process to have those set already, for example UnixODBC's isql tool and Tableau Desktop, etc. Tableau Server appears to reset the environment. If this has changed can you link to relevant docs so we can take a look?

Thanks for taking a look into this 👍

**Comment by sxlin** [comment]
@clach04 I want first verify if Tableau is able to resolve the driver.  Tableau uses unixODBC driver manager to resolve driver.  It looks for /etc/odbcinst.ini. 

Here is the document for installing MariaDB driver. 

> After you install the driver, append the following section to the /etc/odbcinst.ini file (if it's not already there), using the correct information for your environment. For example, make sure the driver is located in the path specified.
> 
> [MariaDB ODBC 3.0 Driver]
> Description = MariaDB Connector/ODBC v.3.0
> Driver = opt/mariadb/libmaodbc.so

**Comment by iancr01** [comment]
@sxlin The Actian ODBC driver needs certain OS environment variables to be set. Our understanding (according to Tableau Support) is that there is no way to set anything at the environment (OS) level that the Tableau Server would read. This is prior to even getting to the odbc.ini or odbcinst.ini. This is specific to Linux. Other services that are registered with the OS (Linux) allow for environment variables to be set before the actual start of the service process. Has this changed recently?

**Comment by clach04** [comment]
@sxlin as Cris noted, Tableau Desktop is working fine on all platforms (Linux, Windows, Mac - each one users a different manager). Cris and I wrote the Taco a while back as part of early adopters for the SDK so we are familiar with the difference flavors of ODBC environments and Tableau Desktop.

This is specific to Tableau Server. Can you help us with Tableau Server questions?

**Comment by sxlin** [comment]
@clach04 @iancr01 You are right, Tableau Server on Linux doesn't support set environment variables for server processes. 

We used to have partner's driver required LD_LIBRARY_PATH being set.  They were able to rebuild the driver to avoid it.

**Comment by sxlin** [comment]
@iancr01 @clach04 There is a way to set environment variables for Tableau server processes.  You can use systemd unit file to set environment variable. You can add a conf file to `<unpriviliged_user_home_dir>/.config/systemd/tableau_server.conf.d/` folder. 

Here is an example for unit file,
https://help.tableau.com/current/server-linux/en-us/proxy.htm#configuring-tableau-server-on-linux-to-work-with-a-forward-proxy

It's really not recommended to have to set environment variables to use the driver.  We used to have a partner had driver requiring setting `LD_LIBRARY_PATH`, they were able to rebuild the driver to avoid that requirement. 

This issue is really not a Connector SDK question.  I am closing it.
