### ISSUE TITLE
custom fields in connection dialog

### ISSUE THREAD

**Issue by clach04** [tableau/connector-plugin-sdk#443]
**About You:**
Name: Chris Clark
Company: Actian

**Your question:**

Is it possible to add custom fields to connection dialogs? I can't see anything about this in https://tableau.github.io/connector-plugin-sdk/docs/ui - e.g. a new field called "custom_field". Supporting string entry as well as drop downs would be very useful.

Right now I'm handling this by adding extra options to the database name and using a special character as a separator which is not ideal.

**Comment by pvanderknyff** [comment]
Hi Chris,

At the moment, we do not have support for custom fields. For now, we do have an example where we rename the Service field and re-label it here: https://github.com/tableau/connector-plugin-sdk/tree/master/samples/components/dialogs/new_text_field

With the 2020.1 release of Tableau, there will be support for an additional 3 custom text fields.

We are also working on a more modular connection dialog that supports an arbitrary number of fields for a future release.

**Comment by jainam1995** [comment]
@clach04 
With the connection dialog v2 we now enable creating custom fields making them required and optional as required . The documentation for that is available here : https://tableau.github.io/connector-plugin-sdk/docs/mcd . Does this fix the issue ?
