### ISSUE TITLE
[BUG] Tableau Connector (.taco) failed on exception: Class is com.tableau.connector.verifier.JarVerifier

### ISSUE THREAD

**Issue by yoav-einav** [tableau/connector-plugin-sdk#447]
We've encountered a bug as part of the Tableau Connector SDK Beta packaging:

1. We received a code signing certificate from GoDaddy

2. Our team managed to import the certificate and sign the taco file with it. 
Used a windows application called keystore explorer to import the certificate.

3. After signing the i9e taco file our team managed to pass the initial exception but encountered another one. This is the Tableau log snippet
Taco signature verification failed, Exit code: 1.
Verify signature: C:\Users\intreviews\Documents\My Tableau Repository\Connectors\i9e_taco.taco
Taco is unsigned or the signer certificate is not trusted.
Signed by:
CN=Gigaspaces Technologies Ltd., O=Gigaspaces Technologies Ltd., L=Herzliya, C=IL
CN=Go Daddy Secure Certificate Authority - G2, OU=http://certs.godaddy.com/repository/, O="GoDaddy.com, Inc.", L=Scottsdale, ST=Arizona, C=US
Bad key usage
4. We managed to remote debug Tableau Java code and found the method that throws the exception: Class is com.tableau.connector.verifier.JarVerifier and method is checkKeyUsage. 

We'd love your assistance here.

**Comment by jainam1995** [comment]
Hi,
This was a known bug for which the fix has been completed and will be out in the next release of 2019.4. I will update the issue when the fi has been released

**Comment by sidwray** [comment]
@jainam1995 Can you confirm the MR release details here?

**Comment by jainam1995** [comment]
The MR 2019.4.2 has been released. Please could you check it now ?

**Comment by jainam1995** [comment]
@yoav-einav Were you able to test it successfully ?

**Comment by yoav-einav** [comment]
We’ve validated the fix and it works well!

We’d recommend improving the documentation on how to import the certificate and link it to .taco file

Thanks

**Comment by jainam1995** [comment]
Resolving the bug
