### ISSUE TITLE
[BUG][DOCS] "Create .tds file" tells users to use "other ODBC"

### ISSUE THREAD

**Issue by sidwray** [tableau/connector-plugin-sdk#448]
**Describe the bug**
Under the section describing how to add a new data source, the docs describing using "Other ODBC".  This line should be updated to describe that a user should be using the their new plugin for this step, and the section should be updated to make sure there are not other similar incorrect references. 

**Screenshots**

![image](https://user-images.githubusercontent.com/13004792/73027486-5e2dfa80-3de8-11ea-9fef-b4314c27f863.png)
**Desktop (please complete the following information):**
 - OS:
 - Tableau Version

**About you:**
 Name: Sid
 Company: Wray

**Comment by pvanderknyff** [comment]
Updated the docs, thanks Sid!
