### ISSUE TITLE
[FEATURE] Actian Connector

### ISSUE THREAD

**Issue by clach04** [tableau/connector-plugin-sdk#455]
Artifacts requested by BlairH

[ManualTests_31-01-2010.xlsx](https://github.com/tableau/connector-plugin-sdk/files/4148602/ManualTests_31-01-2010.xlsx)
[Tableau Connector Artefact.zip](https://github.com/tableau/connector-plugin-sdk/files/4148604/Tableau.Connector.Artefact.zip)

**About You**
Name: Chris Clark
Company: Actian

**Comment by lukewrites** [comment]
Hi Chris, Blair's gotten them and I'm removing the file links from your post.
