### ISSUE TITLE
Setting fetch size in connector plugin?

### ISSUE THREAD

**Issue by cshrauder** [tableau/connector-plugin-sdk#461]
**About You:**
Name: Christian Shrauder
Company:  Yellowbrick 

**Your question:**

We are using a postgres driver as a base for Yellowbrick.  The default fetch size for the connector we are using is 2048.  We would like to adjust this and measure the performance benefits for returning larger datasets.   I've found reference to these parameters in TDC files:
customization name='CAP_ODBC_FETCH_BUFFERS_SIZE_MASSIVE' value='yes' 
or
customization name='odbc-connect-string-extras' value='Fetch=XXXXXX
customization name='CAP_ODBC_FETCH_BUFFERS_RESIZABLE' value='yes' 
Is there a similar knob to adjust in the connector plugin?  If so, where is the correct place to set this?
###

**Comment by pvanderknyff** [comment]
Hi Christian:

You can set capabilities in your manifest file. We have an example of capabilities being set in the manifest [here](https://github.com/tableau/connector-plugin-sdk/blob/master/samples/plugins/postgres_odbc/manifest.xml#L14), and a list of supported capabilities [here](https://tableau.github.io/connector-plugin-sdk/docs/capabilities). CAP_ODBC_FETCH_BUFFERS_SIZE_MASSIVE and CAP_ODBC_FETCH_BUFFERS_RESIZABLE both are on the list.

For the odbc-string-extras, you should be able to set that in the connection builder script, which constructs the connection string, and have that be passed in to the driver. We have an example of setting the driver's fetch size in the connection builder [here](https://github.com/tableau/connector-plugin-sdk/blob/master/samples/plugins/postgres_odbc/connectionBuilder.js#L13).

**Comment by cshrauder** [comment]
Got it working now.  Thanks for the pointer!
