### ISSUE TITLE
[FEATURE] Access Tableau version from connection-builder.js

### ISSUE THREAD

**Issue by juliuszsompolski** [tableau/connector-plugin-sdk#464]
**Is your feature request related to a problem? Please describe.**

We would like to access Tableau version in connection-builder.js, to be able to pass it as part of the connection string to the ODBC driver.

**Describe the solution you'd like**

We would like to have Tableau version available as a string constant that can be used in the JS files implementing the connector.

**Describe alternatives you've considered**
-

**About You**
Name: Juliusz Sompolski
Company: Databricks

**Comment by pvanderknyff** [comment]
Thanks for opening this Juliusz. Tracking this story internally, will update this issue if there is any news.

**Comment by sidwray** [comment]
tfs 1079045

**Comment by alismess-db** [comment]
We also would like to put the deployment type (Desktop/Server/Online) in the user agent.

**Comment by VasanthiNeelagiri** [comment]
Thanks Julius. Getting this prioritized. I would also appreciate if you can give your feedback for our product via this form. It should only take 2-5 mins but would be super valuable to our team. Thanks in advance!!
https://docs.google.com/forms/d/e/1FAIpQLSfs5OreNsxnva_uTO2vTxnoF-oq-37tEdrUpirUKwqud2Ib7g/viewform?usp=sf_link

**Comment by kaklakariada** [comment]
Hi @VasanthiNeelagiri,
I am working at @exasol and we are interested in this feature for the same reasons as @juliuszsompolski.
