### ISSUE TITLE
How use multiple connection type ?

### ISSUE THREAD

**Issue by estebgonza** [tableau/connector-plugin-sdk#465]
Hello :-) !

**About You:**
Name: Esteban
Company: Indexima

**Your question:**
I'm trying to add a connection mode on my taco: Zookeeper.
But I can't find anything that talks about this subject in the documentation.

Then I saw **connection-options** in the SDK code, I tried this:

```
<connection-options>
             <option name="Host" connection-type="host-port" show-port-prompt="true" show-service-prompt="false" server-prompt="Host" />
           <option name="Quorum" connection-type="zookeeper" show-port-prompt="false" show-service-prompt="false" server-prompt="Zookeeper"/>
         </connection-options>

```
For two connection types: Host/Port and Zookeeper.
But now the connection options name in the menu list are empty.

<img width="401" alt="4e5bf32c95aefa0df6ecbeaa242355cd" src="https://user-images.githubusercontent.com/32603471/75136846-3af7b300-56e6-11ea-9c79-3060d270347c.png">

Then, have you some documentation on this subject, or a good way to use multiple connections type? :-)

Regards,
Esteban

**Comment by rosswbrown** [comment]
Hi Esteban,

The use of the **connection-options** was outside the core scenarios for general connector plugins.  It was provided externally in the SDK for some narrow use cases around Hive connectors as base classes.  This is the reason it is not better documented.

We are working on a much more flexible connection dialog definition structure in upcoming releases.  I will leave this open as an enhancement and reply back when there is more to share publicly.

Thanks,
Ross

**Comment by rosswbrown** [comment]
https://tableau.github.io/connector-plugin-sdk/docs/mcd

Please also see our latest release notes for more details.  

Thanks,
Ross
