### ISSUE TITLE
tdvt test fails on basic postgres_odbc test

### ISSUE THREAD

**Issue by MaxB-Giga** [tableau/connector-plugin-sdk#470]
**About You:**
Name:Max
Company:Gigaspaces

**Your question:**

A basic postgres_odbc TDVT test is failing due to "Tableau doesn't recognize the data source type 'postgres_odbc'", please see the details below.

C:\tdvt_workspace_02>py -m tdvt.tdvt list

Available datasources:
mydb
postgres_jdbc
postgres_odbc

Available suites:
all
        mydb, postgres_jdbc, postgres_odbc

C:\tdvt_workspace_02>py -m tdvt.tdvt run postgres_odbc
....
Test Count: 806 tests
        Passed tests: 0
        Failed tests: 806
        Tests run: 806
        Disabled tests: 0
        Skipped tests: 0

Other information:
        Smoke test time: 0 seconds
        Main test time: 11.33 seconds
        Total time: 11.34 seconds

The test_results_combined.csv shows:
"LoadDatasource TableauException: Tableau doesn't recognize the data source type 'postgres_odbc'. It might not be available in this version of Tableau, or it might be a connector plugin that's not installed on this system.

No data source specified"

 # cat postgres_odbc.ini
[Datasource]
Name = postgres_odbc
LogicalQueryFormat = simple_public
CommandLineOverride = -DConnectPluginsPath=plugins

[StandardTests]
ExpressionExclusions_Standard = string.isdate,date.datediff.day,date.datediff.dayofyear,date.datediff.hour,date.datediff.minute,date.datediff.second,date.datediff.sow.day,date.datediff.sow.dayofyear,date.datediff.weekday,date.datediff.sow.hour,date.datediff.sow.minute,date.datediff.sow.second,date.datediff.sow.weekday,datetime.cast.float
LogicalExclusions_Calcs = BUGS.B26728, Filter.Date_In
LogicalExclusions_Staples = lod.17_Nesting

[LODTests]

[UnionTest]

 What did I miss?

Thanks 
Max

**Comment by pvanderknyff** [comment]
Hi Max,

This error means that your connector is not loaded into Tableau. In your ini file, you have:
`CommandLineOverride = -DConnectPluginsPath=plugins`
Make sure that DConnectPluginsPath contains the full path to the directory that includes the folder containing your connector files. If you've launched Tableau Desktop using the command line option, it will be the same path: https://tableau.github.io/connector-plugin-sdk/docs/share

**Comment by MaxB-Giga** [comment]
Hi, 
the Tableau Desktop was not running when I made this tvdt test.
This test is "Test the sample connectors"  from https://tableau.github.io/connector-plugin-sdk/docs/tdvt . 
Not sure it was intended for running by tvdt or just a driver example.

Regards
Max

**Comment by jainam1995** [comment]
Were you able to run tdvt successfully after the above change ? If not what error are you seeing now ?

**Comment by MaxB-Giga** [comment]
It runs on the test that uses postgresql data source that I created according to the manual. 
The - "Test the sample connectors" from https://tableau.github.io/connector-plugin-sdk/docs/tdvt , that I mentioned earlier does not run. Is the documentation correct? I wanted to run it just to make sure I am able to run the tdvt.
Anyway, I am now working on bringing Calcs and Staples into Gigaspaces. Will see how the test will work with my data source.
Regards
Max

**Comment by MaxB-Giga** [comment]
This one became not relevant as I was able to start using the tool for testing our connector
