### ISSUE TITLE
Fails to publish data source to server

### ISSUE THREAD

**Issue by MaxB-Giga** [tableau/connector-plugin-sdk#473]
**About You:**
Name: Max 
Company: Gigaspaces

**Your question:**
I am having an issue publishing a data source from a desktop to a server when Gigaspaces connector is in use.
We are using a connector that is not packed as a taco file.
Connectivity to Desktop works with no issues.
Failed to publish data source from Desktop to a Tableau server, getting error "Tableau doesn't recognize the data source type 'insightedge_jdbc'... "

Tableau Desktop version 2019.2.8

Tableau Services Manager command line version 20192.20.0218.0709.
Tableau Server version 20192.20.0218.0709.

C:\tdvt_workspace_02>tsm configuration get -k native_api.connect_plugins_path
C:/insightedge-connector

In log vizportal/vizportal_node1-0.log.2020-03-11

Caused by: com.tableausoftware.nativeapi.exceptions.DataSourceException: Tableau doesn't recognize the data source type 'insightedge_jdbc'. It might not be available in this version of Tableau, or it might be a
 connector plugin that's not installed on this system..
.
        at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method).
        at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62).
        at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45).
        at java.lang.reflect.Constructor.newInstance(Constructor.java:423).
        at com.tableausoftware.nativeapi.serialization.ExceptionMapper.mapTableauException(ExceptionMapper.java:111).
        at com.tableausoftware.nativeapi.serialization.ExceptionMapper.mapVizqlWorkerException(ExceptionMapper.java:57).
        at com.tableausoftware.nativeapi.serialization.ExceptionMapper.mapVizqlWorkerException(ExceptionMapper.java:74).
        at com.tableausoftware.nativeapi.dll.NativeApiJNI.ExtractAndDCInfo_getDSExtractAndDCInfoFromFile(Native Method).
        at com.tableausoftware.nativeapi.dll.ExtractAndDCInfo.getDSExtractAndDCInfoFromFile(ExtractAndDCInfo.java:103).
        at com.tableausoftware.nativeapi.connections.DatasourceInfoUtils.extractDatasourceInfoFromDatasourceFile(DatasourceInfoUtils.java:49).
        at com.tableausoftware.model.workgroup.service.VqlServerService.extractDatasourceInfoFromDatasourceFile(VqlServerService.java:346).
        at com.tableausoftware.domain.content.publishing.DatasourceExtractInfo.<init>(DatasourceExtractInfo.java:44).
        ... 21 more.
2020-03-11 15:06:11.868 +0000 (Default,admin@local,sgsniONpSoOrXN7H9LfR7A,Xmj@Y7VUAe9Z3nr7ikgVXgAAAgE,0:-7dee36a5:170be04a8b6:a2f) pool-28-thread-1 vizportal: INFO  com.tableausoftware.domain.asyncjobs.AsyncJob
Service - Async job id: [14], type: [Publish Datasource], status: [failed].

**Comment by sxlin** [comment]
Did you call command `tsm pending-changes apply` to apply the change and restart server?

If so, check logs nativeapi_vizqlserver*.txt in C:\ProgramData\Tableau\Tableau Server\data\tabsvc\logs\vizqlserver see if the connector is loaded correctly.

**Comment by MaxB-Giga** [comment]
Yes, the changes were applied. 
C:\Users\Administrator>tsm pending-changes list
Topology
There are no pending topology changes.

I did not see any obvious errors in the logs.
Attaching some snippets from the logs. 
Please let me know if you want me to send over the full log files and how to transfer the logs to you.


  12/03/2020   13:06.37   /drives/c/ProgramData/Tableau/Tableau Server/data/tabsvc/logs/vizqlserver  grep insight nativeapi_vizqlserver_1-1_2020_03_12_00_00_00.txt
{"ts":"2020-03-12T11:23:01.822","pid":6056,"tid":"8e0","sev":"info","req":"-","sess":"-","site":"-","user":"-","k":"server-startup-options","v":{"kms.use_mock":"false","license.server":"localhost","licenseservice.vendor_daemon.port":"8153","licensing.app.lmreread":"C:/Program Files/Tableau/Tableau Server/packages/bin.20192.20.0218.0709/lmreread.exe","licensing.asr.dir":"C:/ProgramData/Tableau/Tableau Server/data/tabsvc/services/vizqlserver_1.20192.20.0218.0709/lib","licensing.file":"C:/ProgramData/Tableau/Tableau Server/data/tabsvc/config/vizqlserver_1.20192.20.0218.0709/tableau.lic","licensing.log.dir":"C:/ProgramData/Tableau/Tableau Server/data/tabsvc/logs/licensing","licensing.login_based_license_management.default_requested_duration_seconds":"0","licensing.login_based_license_management.enabled":"true","licensing.login_based_license_management.max_requested_duration_seconds":"15552000","licensing.random_extra_sleep":"0.5","licensing.sleep_between_tries":"3.0","licensing.tries":"5","line.separator":"\r\n","local_metadata.worker.connectiontimeout":"30","local_metadata.worker.hcfails":"2","local_metadata.worker.hcinterval":"30","local_metadata.worker.hcpasses":"1","local_metadata.worker.retry":"300","local_vizportal.worker.connectiontimeout":"30","local_vizportal.worker.hcfails":"2","local_vizportal.worker.hcinterval":"30","local_vizportal.worker.hcpasses":"1","local_vizportal.worker.retry":"300","log.rotate":"true","log.rotate_interval":"86400","log4j.configuration":"file:///C:/ProgramData/Tableau/Tableau%20Server/data/tabsvc/vizqlserver/1/conf/log4j.xml","logdir":"C:\\ProgramData\\Tableau\\Tableau Server\\data\\tabsvc\\logs\\vizqlserver","logfile":"C:\\ProgramData\\Tableau\\Tableau Server\\data\\tabsvc\\logs\\vizqlserver\\vizqlserver_node1-1.log","longRunningTransactions.CheckFrequencySeconds":"300","longRunningTransactions.LongRunningWarningThresholdSeconds":"60","longRunningTransactions.TransactionStuckAlertThresholdSeconds":"600","maestro.featureFlags.futureFeature":"false","maestro.input.allowed_paths":"","maestro.output.allowed_paths":"","maestro.server_bin_path":"C:/ProgramData/Tableau/Tableau Server/data/tabsvc/services/vizqlserver_1.20192.20.0218.0709/bin","maestro.show_allowed_paths":"true","managed_keychain.ttl_in_sec":"21600","managed_keychains.enable_cache":"false","managed_keychains.max_cache_size":"100","materializedViews.BloomFilterBuildPeriod":"10","materializedViews.MaxBatchSubmissionCount":"100","materializedViews.WebAuthoringBatchHoldMinutes":"10","materializedViews.max_allowed_percentage_of_hyper_memory":"50","materializedViews.max_query_cache_entry_size_in_kb":"262144","max_allowed_document_version":"","messagebus.config.topics.dir":"C:/ProgramData/Tableau/Tableau Server/data/tabsvc/config/vizqlserver_1.20192.20.0218.0709/messagebus/topics","messagebus.core.messageRetentionTimeInMinutes":"2880","messagebus.core.messageSizeLimitKb":"10","messagebus.subscriber.longPollSeconds":"20","messagebus.subscriber.maxRetryCount":"100","messagebus.subscriber.sessionTimeoutSeconds":"60","metadata.service.graphdb.type":"sqlg","metadatasearchquery.procs":"0","metadatasearchquery.vmopts":"-XX:+UseConcMarkSweepGC -Xmx128m -XX:+ExitOnOutOfMemoryError","metricsservices.authoring.enabled":"false","mode.standalone.enabled":"true","mongrel.tcpqueue.length":"100","monitoring.dataengine.connection_timeout":"30000","monitoring.hyper.connection_timeout":"30000","monitoring.initial_delay":"20","monitoring.interval":"6","monitoring.num_threads":"2","monitoring.shutdown_delay":"5","monitoring.time_period":"60","monitoring.up_percentage":"0","native_api.MaterializedViewMaxNumConnectionsForCacheWarming":"10","native_api.MaterializedViewMinQueryExecutionDurationThresholdInMs":"500","native_api.MaterializedViewQueryExecutionDurationToLoadingRatioInPercentage":"200","native_api.MaterializedViewQueryExecutionDurationToLoadingRatioInPercentageForSpatialData":"240","native_api.MaterializedViewQueryResultReductionRatioInPercentage":"90","native_api.MemberIdentityValidationEnabled":"true","native_api.MemberIdentityValidationMaxBlockDepth":"10","native_api.UseAlternativeFederationEngine":"true","native_api.allowed_paths":"*","native_api.connect_plugins_path":"C:/insightedge-connector","native_api.cpu_use_average":"false","native_api.default_cache_timeout_minutes":"720","native_api.device_specific_dashboard_phone_size":"500","native_api.device_specific_dashboard_tablet_size":"800","native_api.external_cache.use_timestamp":"true","native_api.external_cache_disable":"false","native_api.internal_disallowed_paths":"C:/Program Files/Tableau/Tableau Server; C:/ProgramData/Tableau/Tableau Server","native_api.java_home":"C:/ProgramData/Tableau/Tableau Server/data/tabsvc/services/vizqlserver_1.20192.20.0218.0709/repository/jre"}}
                                                                                                                                                                                                                    ✔

  12/03/2020   13:06.45   /drives/c/ProgramData/Tableau/Tableau Server/data/tabsvc/logs/vizqlserver  grep insight nativeapi_vizqlserver_1-0_2020_03_12_00_00_00.txt
{"ts":"2020-03-12T11:23:01.482","pid":6032,"tid":"33a4","sev":"info","req":"-","sess":"-","site":"-","user":"-","k":"server-startup-options","v":{"kms.use_mock":"false","license.server":"localhost","licenseservice.vendor_daemon.port":"8153","licensing.app.lmreread":"C:/Program Files/Tableau/Tableau Server/packages/bin.20192.20.0218.0709/lmreread.exe","licensing.asr.dir":"C:/ProgramData/Tableau/Tableau Server/data/tabsvc/services/vizqlserver_0.20192.20.0218.0709/lib","licensing.file":"C:/ProgramData/Tableau/Tableau Server/data/tabsvc/config/vizqlserver_0.20192.20.0218.0709/tableau.lic","licensing.log.dir":"C:/ProgramData/Tableau/Tableau Server/data/tabsvc/logs/licensing","licensing.login_based_license_management.default_requested_duration_seconds":"0","licensing.login_based_license_management.enabled":"true","licensing.login_based_license_management.max_requested_duration_seconds":"15552000","licensing.random_extra_sleep":"0.5","licensing.sleep_between_tries":"3.0","licensing.tries":"5","line.separator":"\r\n","local_metadata.worker.connectiontimeout":"30","local_metadata.worker.hcfails":"2","local_metadata.worker.hcinterval":"30","local_metadata.worker.hcpasses":"1","local_metadata.worker.retry":"300","local_vizportal.worker.connectiontimeout":"30","local_vizportal.worker.hcfails":"2","local_vizportal.worker.hcinterval":"30","local_vizportal.worker.hcpasses":"1","local_vizportal.worker.retry":"300","log.rotate":"true","log.rotate_interval":"86400","log4j.configuration":"file:///C:/ProgramData/Tableau/Tableau%20Server/data/tabsvc/vizqlserver/0/conf/log4j.xml","logdir":"C:\\ProgramData\\Tableau\\Tableau Server\\data\\tabsvc\\logs\\vizqlserver","logfile":"C:\\ProgramData\\Tableau\\Tableau Server\\data\\tabsvc\\logs\\vizqlserver\\vizqlserver_node1-0.log","longRunningTransactions.CheckFrequencySeconds":"300","longRunningTransactions.LongRunningWarningThresholdSeconds":"60","longRunningTransactions.TransactionStuckAlertThresholdSeconds":"600","maestro.featureFlags.futureFeature":"false","maestro.input.allowed_paths":"","maestro.output.allowed_paths":"","maestro.server_bin_path":"C:/ProgramData/Tableau/Tableau Server/data/tabsvc/services/vizqlserver_0.20192.20.0218.0709/bin","maestro.show_allowed_paths":"true","managed_keychain.ttl_in_sec":"21600","managed_keychains.enable_cache":"false","managed_keychains.max_cache_size":"100","materializedViews.BloomFilterBuildPeriod":"10","materializedViews.MaxBatchSubmissionCount":"100","materializedViews.WebAuthoringBatchHoldMinutes":"10","materializedViews.max_allowed_percentage_of_hyper_memory":"50","materializedViews.max_query_cache_entry_size_in_kb":"262144","max_allowed_document_version":"","messagebus.config.topics.dir":"C:/ProgramData/Tableau/Tableau Server/data/tabsvc/config/vizqlserver_0.20192.20.0218.0709/messagebus/topics","messagebus.core.messageRetentionTimeInMinutes":"2880","messagebus.core.messageSizeLimitKb":"10","messagebus.subscriber.longPollSeconds":"20","messagebus.subscriber.maxRetryCount":"100","messagebus.subscriber.sessionTimeoutSeconds":"60","metadata.service.graphdb.type":"sqlg","metadatasearchquery.procs":"0","metadatasearchquery.vmopts":"-XX:+UseConcMarkSweepGC -Xmx128m -XX:+ExitOnOutOfMemoryError","metricsservices.authoring.enabled":"false","mode.standalone.enabled":"true","mongrel.tcpqueue.length":"100","monitoring.dataengine.connection_timeout":"30000","monitoring.hyper.connection_timeout":"30000","monitoring.initial_delay":"20","monitoring.interval":"6","monitoring.num_threads":"2","monitoring.shutdown_delay":"5","monitoring.time_period":"60","monitoring.up_percentage":"0","native_api.MaterializedViewMaxNumConnectionsForCacheWarming":"10","native_api.MaterializedViewMinQueryExecutionDurationThresholdInMs":"500","native_api.MaterializedViewQueryExecutionDurationToLoadingRatioInPercentage":"200","native_api.MaterializedViewQueryExecutionDurationToLoadingRatioInPercentageForSpatialData":"240","native_api.MaterializedViewQueryResultReductionRatioInPercentage":"90","native_api.MemberIdentityValidationEnabled":"true","native_api.MemberIdentityValidationMaxBlockDepth":"10","native_api.UseAlternativeFederationEngine":"true","native_api.allowed_paths":"*","native_api.connect_plugins_path":"C:/insightedge-connector","native_api.cpu_use_average":"false","native_api.default_cache_timeout_minutes":"720","native_api.device_specific_dashboard_phone_size":"500","native_api.device_specific_dashboard_tablet_size":"800","native_api.external_cache.use_timestamp":"true","native_api.external_cache_disable":"false","native_api.internal_disallowed_paths":"C:/Program Files/Tableau/Tableau Server; C:/ProgramData/Tableau/Tableau Server","native_api.java_home":"C:/ProgramData/Tableau/Tableau Server/data/tabsvc/services/vizqlserver_0.20192.20.0218.0709/repository/jre"}}
                                                                                                              


Regards
Max

**Comment by saugatt** [comment]
Can you see the connector listed in the connector list in your tableau server?

**Comment by MaxB-Giga** [comment]
Is this what you mean? 

C:\Users\Administrator>tsm configuration get -k native_api.connect_plugins_path
C:/insightedge-connector

C:\Users\Administrator>dir c:\insightedge-connector
 Volume in drive C has no label.
 Volume Serial Number is 14D2-3798

 Directory of c:\insightedge-connector

03/04/2020  01:02 PM    <DIR>          .
03/04/2020  01:02 PM    <DIR>          ..
01/29/2020  01:03 PM               212 ._connection-dialog.tcd
01/29/2020  01:03 PM               212 ._connectionBuilder.js
01/29/2020  01:03 PM               212 ._connectionRequired.js
01/29/2020  01:03 PM               212 ._connectionResolver.tdr
01/29/2020  01:03 PM               212 ._dialect.tdd
01/29/2020  01:03 PM               212 ._manifest.xml
01/29/2020  01:03 PM               586 connection-dialog.tcd
01/29/2020  01:03 PM               930 connectionBuilder.js
01/29/2020  01:03 PM               199 connectionRequired.js
01/29/2020  01:03 PM               356 connectionResolver.tdr
01/29/2020  01:03 PM               857 dialect.tdd
01/29/2020  01:03 PM             1,743 manifest.xml
              12 File(s)          5,943 bytes
               2 Dir(s)   6,336,880,640 bytes free

**Comment by MaxB-Giga** [comment]
Hello
I was suggested to change the directory structure where the connector files were placed and copied the files into a folder under the directory configured as native_api.connect_plugins_path.
After applying the changes and clicking "Publish data source" I was forwarded to the Tableau Server web page. First, I got the message saying that the data source was successfully published, but then I was prompted to provide credentials required for accessing the data source.
The request for credentials comes regardless of the security settings configured on the data source site and in all cases, I receive the error outlined below.

An unexpected error occurred. If you continue to receive this error please contact your Tableau Server Administrator.

Session ID: 195E3126122D409F989D467A82EC86EF-1:0

java.lang.RuntimeException: Error instantiating JsonCustomSchema(name=processorSpace)

There was a Java error.

Unable to connect to the Gigaspaces InsightEdge server "127.0.0.1". Check that the server is running and that you have access privileges to the requested database.

DataServiceFailure

There was an error with the data source "Orders (processorSpace)". Verify that the data source is configured correctly.

![image](https://user-images.githubusercontent.com/60573339/77077627-23b69780-69fe-11ea-930a-8c1a94a17419.png)
Please advice.

Regards
Mad

**Comment by sidwray** [comment]
tfs 1197820

**Comment by MaxB-Giga** [comment]
the request for credentials is not related to the issue discussed in this ticket.
Changing the directory structure was the solution in our case.
Closing
