### ISSUE TITLE
Can't run TDVT on Tableau 2020.2 beta release

### ISSUE THREAD

**Issue by srinadhkunam** [tableau/connector-plugin-sdk#480]
**Can't run TDVT on Tableau 2020.2 beta release**
We tried to run the TDVT on Tableau 2020.2 beta release. But we are facing "Missing connection name in relation" error message after run "py -3 -m tdvt.tdvt action --add_ds dbadmin" command also not able to open with Tableau (Before run this command we are able to open the tds with Tableau 2020.2 beta).

We are using TDVT 2.1.7.

**Desktop (please complete the following information):**
 - Windows
 - Tableau 2020.2

**About you:**
 Name: Srinadh Kunam
 Company: Kyvos Insights

**Comment by srinadhkunam** [comment]
Do we have any update ob this issue @sidwray @pvanderknyff

**Comment by rosswbrown** [comment]
Hi,

Thanks for reporting. I have opened a bug for the team to take a look.  In the meantime I believe you can workaround this issue by following the TDS creation steps in the [instructions](https://tableau.github.io/connector-plugin-sdk/docs/tdvt#add-a-new-datasource) with Tableau Desktop 2020.1 and then run the tests against Tableau 2020.2 Beta.

Thanks,
Ross

**Comment by rosswbrown** [comment]
This issue has been resolved in latest version, [TDVT 2.1.9](https://github.com/tableau/connector-plugin-sdk/blob/master/tdvt/CHANGELOG.md#219---2020-04-13), with the linked pull request.  Please let us know if you continue to experience this issue.
