### ISSUE TITLE
-DConnectPluginsPath cannot be recognized by tabquerytool 

### ISSUE THREAD

**Issue by cornmonster** [tableau/connector-plugin-sdk#482]
**About You:**
Name: Jon
Company: Alibaba

**Your question:**

Hi,

I am trying to pass the TDVT using our connect plugin with the latest Tableau DeskTop (2020.2 beta). But all the test cases failed and the error message is: 

```
tdvt_test2,StaplesConnectionTesttdvt_test2,Staples.tdvt_test2,staples_connection_test,/usr/local/lib/python3.7/site-packages/tdvt/exprtests/pretest/connection_tests/staples/setup.staples_connection_test.txt,False,0,0,,expression,,"LoadDatasource TableauException: Tableau doesn't recognize the data source type 'maxcompute_jdbc'. It might not be available in this version of Tableau, or it might be a connector plugin that's not installed on this system.

",Error.,0.0,,,
tdvt_test2,CastCalcsConnectionTesttdvt_test2,cast_calcs.tdvt_test2,calcs_connection_test,/usr/local/lib/python3.7/site-packages/tdvt/exprtests/pretest/connection_tests/calcs/setup.calcs_connection_test.txt,False,0,0,,expression,,"LoadDatasource TableauException: Tableau doesn't recognize the data source type 'maxcompute_jdbc'. It might not be available in this version of Tableau, or it might be a connector plugin that's not installed on this system.
```

However, the connect plugin path is correctly configured in config/tdvt_test2.ini: 
![image](https://user-images.githubusercontent.com/20107543/77386175-2b42bb80-6dc5-11ea-9af8-a8a6a72ae197.png)

And the path is correct:
![image](https://user-images.githubusercontent.com/20107543/77386246-5af1c380-6dc5-11ea-914d-d0bba8271d3a.png)

And when I tried to debug this problem, I found that "-DConnectPluginsPath" was passed to tabquerytool but didn't work due to some unknown reason.
![image](https://user-images.githubusercontent.com/20107543/77386851-d3a54f80-6dc6-11ea-957b-0eb8d26c9f7e.png)

Could you please help me with this problem?

Thanks!

**Comment by cornmonster** [comment]
Btw, I am using TDVT 2.1.7

**Comment by pvanderknyff** [comment]
Can you try launching the connector in Tableau Desktop? If the path itself is correct, it may be that the connector isn't loading, and in Tableau desktop we have pretty good logging as to why that may be in your "My Tableau Repository/Logs/log.txt" file (search for your connector's class or the keyword connector-plugin-error).

**Comment by cornmonster** [comment]
> Can you try launching the connector in Tableau Desktop? If the path itself is correct, it may be that the connector isn't loading, and in Tableau desktop we have pretty good logging as to why that may be in your "My Tableau Repository/Logs/log.txt" file (search for your connector's class or the keyword connector-plugin-error).

Thanks for replying. But it seems that the Alibaba MaxCompute connector is a built-in connector in the release 2002.2 and I have to remove it before testing if the '-DConnectPluginsPath' works. Could you tell me how to do that?

**Comment by pvanderknyff** [comment]
You can find the built-in connectors in your Tableau install's bin\connectors folder. Delete the alibaba-maxcompute.dll file (back up first), and the built-in connector will be removed.

**Comment by cornmonster** [comment]
> You can find the built-in connectors in your Tableau install's bin\connectors folder. Delete the alibaba-maxcompute.dll file (back up first), and the built-in connector will be removed.

Could you please provide the path in Mac OS?

**Comment by cornmonster** [comment]
I tried with Tableau 2019.2.10 with the same configs and it worked. Here is what I did:
    1. Ran TDVT against 2020.2 beta and all test cases failed. The error msg was "Tableau doesn't recognize the data source type 'maxcompute_jdbc'"
    2. change the path of tabquerytool to Tableau 2019.2.10
    3. Ran TDVT again and  it worked

**Comment by pvanderknyff** [comment]
On Mac, it's under Frameworks/Connectors, and the connector files are .dylibs. You can remove libalibaba-maxcompute.dylib to remove the connector, although it looks like you've already done that.

That error message means that Tableau can't load maxcompute. Did you end up deleting the libalibaba-maxcompute.dylib from the 2020.2 beta install? If so, you then need to make sure that you're pointing the connect plugins path argument to the right folder, and that the connector is valid. Check log.txt to see the specific errors (search for maxcompute_jdbc to see the messages related to your connector)

**Comment by cornmonster** [comment]
Tableau 2020.2 beta cannot load maxcompute connector:
![image](https://user-images.githubusercontent.com/20107543/78205586-15bd4800-74cf-11ea-94ae-b0c3e9c469ba.png)

But, Tableau 2019.2, with same -DConnectPluginsPath argument, can load it:
![image](https://user-images.githubusercontent.com/20107543/78205668-5ae17a00-74cf-11ea-8a18-934678625ecc.png)

**Comment by pvanderknyff** [comment]
When a connector doesn't load, we log the reason in your log.txt file, search for maxcompute_jdbc . The logs can be found in "My Tableau Repository/Logs" ("My Tableau Repository (Beta)/Logs" for beta versions of Tableau). Can you post the log.txt file here so I can take a look?

**Comment by cornmonster** [comment]
I found some errors in the log.txt:

{"ts":"2020-04-02T10:36:47.781","pid":41212,"tid":"28cb78","sev":"warn","req":"-","sess":"-","site":"-","user":"-","k":"msg","e":{"excp-error-code":"0x98155DB8","excp-source":"Configuration","excp-status-code":"UNKNOWN"},"v":"manifest.xml: Malformed XML, showing first 5 errors."}
{"ts":"2020-04-02T10:36:47.781","pid":41212,"tid":"28cb78","sev":"warn","req":"-","sess":"-","site":"-","user":"-","k":"msg","v":"manifest.xml: Error(89,20): element 'connection-customization' is not allowed for content model '(vendor-information,platforms?,connection-customization?,(connection-fields?|connection-dialog?),connection-metadata?,connection-resolver?,dialect?,oauth-config?,license-key*)' (id: )"}
{"ts":"2020-04-02T10:36:47.781","pid":41212,"tid":"28cb78","sev":"error","req":"-","sess":"-","site":"-","user":"-","k":"connector-plugin-error","e":{"excp-error-code":"0x0E9A05C7","excp-source":"NeedsClassification","excp-status-code":"UNKNOWN"},"v":"Failed to load manifest.xml from /Users/jon/workspace/github/aliyun-maxcompute-tableau-connector/plugins/maxcompute_jdbc"}

Here is the log.txt:
[log.txt](https://github.com/tableau/connector-plugin-sdk/files/4422273/log.txt)

And here is our manifest.xml:

https://github.com/aliyun/aliyun-maxcompute-tableau-connector/blob/master/plugins/maxcompute_jdbc/manifest.xml

**Comment by pvanderknyff** [comment]
Your manifest is missing the vendor-information section. This portion isn't normally required for MaxCompute since it is a built-in connector and those are loaded in a different way than using -DConnectoPluginsPath or taco files, but since you're doing development you need to add a dummy section for it to be loaded.

You can see an example in our postgres samples [here](https://github.com/tableau/connector-plugin-sdk/blob/master/samples/plugins/postgres_odbc/manifest.xml#L5). You only need to add the company name and the support link, the driver download link is optional. This will make the connector show up as "Alibaba MaxCompute by Alibaba" (or whatever you set the company name to), this will not be the case when the changes are handed back to us and integrated into the next Tableau release.

**Comment by cornmonster** [comment]
The tdvt passed after adding the vendor-information section and regenerate the tds files with Tableau Desktop 2019.2. Thank you very much for your time!
