### ISSUE TITLE
Many failed logical tests

### ISSUE THREAD

**Issue by MaxB-Giga** [tableau/connector-plugin-sdk#485]
**About You:**
Name: Max 
Company: GigaSpaces

**Your question:**
Hello. We are testing our connector with TDVT and see that many tests are failing. 
Below is an example of a failing query.
I am trying to understand the reason for this test failure, can you kindly advice what can be the reason for this failure or help me to shorten the query in order to nail down the problem.
Please see the original query and the error at the bottom.

SELECT CAST(CONCAT('1234.', CASE WHEN 2 >= 0 THEN RIGHT("Calcs"."key",2) ELSE NULL END) AS FLOAT) AS "TEMP(Test)(93928613)(0)" FROM "TestV1"."Calcs" "Calcs" GROUP BY 1

For validation, this one works: 
SELECT "Calcs"."key" FROM "TestV1"."Calcs" "Calcs"
key
--
key01
key07
key16
key10
key12
key03
key14
key09
key05
key04
key02
key00
key11
key06
key08
key15
key13

 2020-03-26 10:28:26,302  SEVERE [com.tableausoftware.jdbc.JDBCProtocolImpl] - Exception in runQuery for query: SELECT CAST(CONCAT('1234.', CASE WHEN 2 >= 0 THEN RIGHT("Calcs"."key",2) ELSE NULL END) AS FLOAT) AS "TEMP(Test)(93928613)(0)"
FROM "TestV1"."Calcs" "Calcs"
GROUP BY 1. Error while executing SQL "SELECT CAST(CONCAT('1234.', CASE WHEN 2 >= 0 THEN RIGHT("Calcs"."key",2) ELSE NULL END) AS FLOAT) AS "TEMP(Test)(93928613)(0)"
FROM "TestV1"."Calcs" "Calcs"
GROUP BY 1": From line 1, column 51 to line 1, column 72: No match found for function signature RIGHT(<CHARACTER>, <NUMERIC>)

Thanks
Max

**Comment by saugatt** [comment]
Hi Max, For this query, your error message is  `No match found for function signature RIGHT(, )` You will need to create RIGHT() function with currently available functions for your database in the dialect file.

**Comment by jainam1995** [comment]
hey @MaxB-Giga any update on testing for this ? Thanks !

**Comment by sidwray** [comment]
tfs 1197816

**Comment by MaxB-Giga** [comment]
Hello @jainam1995 
This issue can be closed, I didn't hear about reoccurrence.

Thanks and regards
Max

**Comment by MaxB-Giga** [comment]
Closing
