### ISSUE TITLE
[BUG] Extract only crashing on joins

### ISSUE THREAD

**Issue by Relucin** [tableau/connector-plugin-sdk#494]
**Describe the bug**
Tableau crashes on trying to extract with a join. If the join contains no data it will not crash unless you undo.
Removing extract only allows the extract to happen and does not crash Tableau.
[tabprotosrv_2020_04_07_08_30_54.txt](https://github.com/tableau/connector-plugin-sdk/files/4445568/tabprotosrv_2020_04_07_08_30_54.txt)

**Desktop (please complete the following information):**
 - OS: MacOS 10.14.6
 - Tableau Version 2019.4.1 & 2020.1

**About you:**
 Name: Brandon Montoya
 Company: Beezwax

**Comment by tsjoblad** [comment]
Hi Brandon,
We opened a story on this issue to determine the source of the bug. We will get back to you as soon as there are further updates from our engineering team.

In the meantime, can you please provide the source files for the Connector? Either a github repo or sharing directly with me is fine.

Thank you!
TS
