### ISSUE TITLE
Package signature verification failed during connection creation with signed .taco

### ISSUE THREAD

**Issue by aaron-newberg** [tableau/connector-plugin-sdk#515]
**About You:**
Name: Aaron
Company: MarkLogic

**Your question:**
Hi, 
I'm throwing together a named connector for MarkLogic but am running into issues with the signing process. I've signed the .taco

![image](https://user-images.githubusercontent.com/32000371/82577699-348ba280-9b40-11ea-8986-77d009b267ad.png)

and I see this in the logs:

![image](https://user-images.githubusercontent.com/32000371/82577866-71579980-9b40-11ea-9ab1-2caf1b72d2cf.png)

Zooming in on the last entry:
![image](https://user-images.githubusercontent.com/32000371/82577923-892f1d80-9b40-11ea-910f-5965f0a8d0a0.png)

I'm new to signing .jar files. What am I doing wrong? Attached is the log file
[log.txt](https://github.com/tableau/connector-plugin-sdk/files/4663359/log.txt)

Thanks in advance,
Aaron

**Comment by jainam1995** [comment]
Hi,
Which CA's certificate did you use to sign your taco file ? Is it one that is trusted by the java key store (present in the cacerts java store as a trusted CA) ?

**Comment by pvanderknyff** [comment]
Hi Aaron,

Can you run the following:
`jarsigner -verify marklogic_odbc.taco -verbose -strict`
By default, jarsigner -verify only checks if the .jar file is signed, and will "verify" a signature that is not ultimately signed by a trusted certificate authority. In the logs, you can see that Tableau says the "Path does not chain with any of the trust anchors"

To have the taco accepted by Tableau, you need to generate a Certificate Signing Request (csr) and get that signed by a certificate authority that is accepted by the java truststore. (Make sure you get a code signing certificate). We have documentation on that topic [here](https://tableau.github.io/connector-plugin-sdk/docs/package-sign#sign-your-packaged-connector-with-jarsigner).

As a workaround, you can skip signature verification by launching Tableau from the command line or a shortcut with "-DDisableVerifyConnectorPluginSignature=true" set.

One note is that, if you're using Tableau 2019.4, you should update to the latest maintenance release. There was a bug in the verification code on launch that we fixed that rejected some valid certs.

**Comment by aaron-newberg** [comment]
Thanks for the replies. It seems my company did not give me a cert signed by a CA that is accepted by the java trust store. I'll push back on this. Thanks

**Comment by aaron-newberg** [comment]
Hi,
Which certificate authority do we recommend to certify the Tableau connector? Would this one work: [https://secure.trust-provider.com/products/CodeSigningSignup1a](https://secure.trust-provider.com/products/CodeSigningSignup1a)?

**Comment by jainam1995** [comment]
I get a ```Bad Request
Your browser sent a request that this server could not understand.``` 
when i try to open the url.

 In general any CA which is listed as trusted in the JRE cert store should be used.

**Comment by pvanderknyff** [comment]
Also make sure it is a code-signing certificate, otherwise it will not work.

**Comment by dobrych** [comment]
Just wanted to leave a note, this code-signature certificate provider worked for my case
https://ksoftware.freshdesk.com/support/solutions/articles/17164-how-do-i-sign-and-timestamp-a-java-jar-file-

https://www.ksoftware.net/code-signing-certificates/ (OV version worked)

**Comment by aaron-newberg** [comment]
Thanks
