### ISSUE TITLE
TDVT - Missing Column Data in Report

### ISSUE THREAD

**Issue by ocientdmurphy** [tableau/connector-plugin-sdk#516]
**About You:**
Name: Dylan Murphy
Company: Ocient

**Your question:**

Greetings! I'm running the tdvt tool with a custom connector. In the test_results_combined.csv file, I'm not seeing all of the column data populated. For example, there is no data in the SQL column. When running the tool, it gives you the count of tests run, passed, and failed. These must be lining up with the data in the spreadsheet. I know that the SQL is hitting the database and that the actual data does match the expected data for many of the queries. Actual data is not showing up in the report either. 

Any ideas on how to troubleshoot this would be appreciated.

[mydb copy.ini.txt](https://github.com/tableau/connector-plugin-sdk/files/4665605/mydb.copy.ini.txt)

[test_results_combined.csv.zip](https://github.com/tableau/connector-plugin-sdk/files/4665583/test_results_combined.csv.zip)

**Comment by jainam1995** [comment]
In the csv file under the Error Msg column, for all the tests, the entry  is 

``` An error occurred while communicating with the data source``` .  

Are you able to open the .tds file directly in tableau or do you get a similar error message ?

**Comment by ocientdmurphy** [comment]
I've been opening all of these in excel and it hasn't been showing me a lot of this information. So, I guess much of the SQL is in these files. I just for the first time opened the file in Tableau and it looks good. Ha! The network connections are something I need to troubleshoot on our end. Thank you for the help :)

**Comment by jainam1995** [comment]
I was able to see the ```An error occurred while communicating with the data source``` in excel it self. Try double clicking any cell under the column Error Msg  . It should expand and you should be able to see the error message.
