### ISSUE TITLE
Could not connect to MySQL data source

### ISSUE THREAD

**Issue by yuqi1129** [tableau/connector-plugin-sdk#52]
When all was configured according to the document, I run
`python3 -m tdvt.tdvt --run test4dmp`
to test mysql connector(via jdbc), however, the following error occur

```
hyperd server version 9.1.0 build version master.0.0.0.5690.r3a6612de
LoadDatasource TableauException:
Unable to establish connection: Data source "MySQL" is not licensed) 无法建立连接: 数据源“MySQL”未得到许可。
```
any wrong with my config?

**Comment by sxlin** [comment]
Were you able to connect using your connector with Tableau desktop?  

BTW, better name your Connector something else than "MySQL", since we have builtin MySQL connector in Tableau.

**Comment by yuqi1129** [comment]
You are right, i just solve it as you said, thanks a lot
