### ISSUE TITLE
Custom JDBC connector issues & debugging

### ISSUE THREAD

**Issue by dobrych** [tableau/connector-plugin-sdk#520]
I'm trying to implement custom JDBC connector for Avatica driver and encountered `getTableTypes() is not implemented` error.

Interestingly, when I use "Other JDBC" native connection option with PostgreSQL dialect and include Avatica driver in JDBC URL – everything works fine including list of DBs, Schemas and Tables. When I copy `samples/plugins/postgres_jdbc` into a custom connector, change some metadata and make sure JDBC URL is the same as in default "Other JDBC" connection option, I get this error.

Seems like "Other JDBC" connector is using different JDBC mechanism or configuration than my custom one which based on `superclass='jdbc'`

I just don't know how to debug it further from here, `log.txt` doesn't give any more hints except having the same error message as in UI.

Would appreciate any directions and tips.

**Comment by pvanderknyff** [comment]
In the same folder as log.txt there should be a jdbcprotocolserver.log file that contains the logs for the process that communicates with the JDBC driver, you should get more detailed information there. If it's not clear, post both logs here and we can take a quick look.

Also make sure your JDBC driver fulfills the following requirements. I don't expect that to be the issue since it's working with Other JDBC, but it's a good thing to check:
- You must have read permissions on the .jar file.
- Tableau requires a JDBC 4.0 or later driver.
- Tableau requires a Type 4 JDBC driver.

**Comment by dobrych** [comment]
Thanks for the feedback @pvanderknyff

I can see more info in the `jprotocolserver.log`, regarding other items, since the driver works fine via "Other JDBC" option, I'd assume it validates all three requirements.

Seems like the error comes from avatica driver itself, it weirdly behaves in case it can't access some of the table metadata. I will close the issue for now and if anything else pops up I'll comment. Appreciate the hint for the right log file!

**Comment by dobrych** [comment]
Another question about customizing JDBC connector:
Design docs mention [Base Dialect Classes](https://tableau.github.io/connector-plugin-sdk/docs/design#dialect-base-classes), is there a way to look at one?

For example, I'd like to customize some of the date-related functions for `PostgreSQL90Dialect` specifically, but [full_dialect.tdd](https://github.com/tableau/connector-plugin-sdk/blob/master/samples/components/dialects/full_dialect.tdd) seem to cover SQL92 dialect.

It's hard to understand without looking at the `PostgreSQL90Dialect` tdd file which exact function is used for particular Tableau functionality/query.

Here is an example:
```sql
CAST(
  (DATE_TRUNC( 'day', CAST("table"."time_utc" AS DATE) ) 
   +
   (-EXTRACT(DOW FROM "table"."time_utc") * INTERVAL '1 DAY')) 
AS DATE)
```
I'd like to replace `'1 DAY'` with ANSI-SQL `'1' DAY` in this function, but by looking at `full_dialect.tdd ` I can't really tell which function to replace. 

Here is another example:
```sql
DATE_TRUNC( 
     'MONTH', CAST(CURRENT_TIMESTAMP AS TIMESTAMP)
) + 1 * INTERVAL '1 MONTH'
```
I'd like to change `'1 MONTH'` to `'1' MONTH`

I was able to fix one specific issue, but it's hard to track a few others. Here is a sample of my current dialect.tdd:

```xml
<?xml version='1.0' encoding='utf-8' ?>

<dialect name='Custom JDBC Dialect'         
         class='custom_jdbc'
         base='PostgreSQL90Dialect'
         version='18.1'>

  <function-map>
    <function group='cast' name='DATE' return-type='date'>
      <formula>date_trunc(&apos;day&apos;, CAST(&apos;1900-01-01&apos; AS DATE) + %1 * INTERVAL &apos;1&apos; DAY)</formula>
      <argument type='real' />
    </function>
    <function group='cast' name='DATE' return-type='date'>
      <formula>((DATE &apos;1900-01-01&apos;) + %1 * INTERVAL &apos;1&apos; DAY)</formula>
      <argument type='int' />
    </function>

    <remove-function name='DATE'>
      <argument type='real' />
    </remove-function>
    <remove-function name='DATE'>
      <argument type='int' />
    </remove-function>

  </function-map>
</dialect>
```

Would appreciate any tips and suggestions, thanks!

**Comment by dobrych** [comment]
@rosswbrown thanks for linking #527 here, I was able to pin-point functions for replacement very quickly using https://github.com/tableau/connector-plugin-sdk/blob/934724/samples/plugins/postgres_jdbc/dialect.tdd

**Comment by rosswbrown** [comment]
Great, I'm glad it was helpful.  There are few more documentation improvements related to dialects still to come in the next few weeks based on feedback.  Thank you.
