### ISSUE TITLE
Authentication in the connector using the same credentials as that foer the tableau server

### ISSUE THREAD

**Issue by swapnil-pandey** [tableau/connector-plugin-sdk#524]
Name: Swapnil
Company: Info

Hi, I have been looking into the tableau connector sdk and I was wondering if there is a way to use the credentials of the tableau server I have logged into, in my odbc connector. 

Suppose I have logged into my tableau server with username: testUser and password: testPassword. Is there any way to use the **same** username and password in the connector as well without asking it from the user again?

**Comment by jainam1995** [comment]
Hi @swapnil-pandey ! Apologies did not get your question exactly . Based on the authentication modes wired up for the connection dialog , the user will have to type in the credentials on selecting the connection form the connection pane on server. The way to control the behavior of the connection dialog can be looked at the [documentation page] : [https://tableau.github.io/connector-plugin-sdk/docs/](url)

**Comment by jainam1995** [comment]
Closing. Please reopen if still occurring
