### ISSUE TITLE
TDVT - Licensing Errors When MaxThread > 3

### ISSUE THREAD

**Issue by ocientdmurphy** [tableau/connector-plugin-sdk#532]
**About You:**
Name:Dylan Murphy
Company:Ocient

**Your question:**
When I set MaxThread > 3 in my mydb.ini file, I start getting the error below and entire test groups fail. For MaxThreads <= 3, it runs normally.

2020-06-10 21:59:16,464 Thread-[3] Running test:logical.lod.mydb
2020-06-10 21:59:22,206 Thread-[3] Command line output: 
 
LoadDatasource TableauException: Unable to establish connection: Data source 'Ocient JDBC by Ocient' has not been licensed.

No data source specified

From CLI output

EEEEEEEEEEEEEEEEEEEEEEEEEEE
Finished mydb logical.lod.mydb 3

**Comment by tsjoblad** [comment]
Hey Dylan,
We're looking into this on our side, but in the meantime can you confirm that you are using a standard license for Desktop? or do you have the embedded SKU licensing? If you are using the embedded SKU, you have to name the set amount datasources you want to be able to work with, and the plugin probably wouldn't be one of them.
Thanks,
TS

**Comment by ocientdmurphy** [comment]
Hi TS,

We’re using the license that Blair gave us to do the integration testing. I’m pretty certain that it’s just a regular Desktop one.

Trial License Information
Product Type: Creator - Desktop & Prep
Key: TCWT-4406-DA70-5E7D-918B
Expiration Type: Expiration Date
Expiration Term: 7-Jul-2020

Thanks,

Dylan Murphy

Senior Product Manager
(617) 659-3075
dmurphy@ocient.com
