### ISSUE TITLE
Unable to preview data with custom connector

### ISSUE THREAD

**Issue by aaron-newberg** [tableau/connector-plugin-sdk#535]
**About You:**
Name: Aaron
Company: MarkLogic

**Your question:**

Hi, 
I started writing a custom Tableau connector for MarkLogic.
It uses ODBC to connect to the data source

I can connect to my server just fine
![image](https://user-images.githubusercontent.com/32000371/84689558-0195be00-aef6-11ea-895b-579311f33af6.png)

The tables are populated on the left pane, but the 'Preview data source' button is grayed out, preventing me from getting a look at the data before connecting live or extracting. 
![image](https://user-images.githubusercontent.com/32000371/84689787-546f7580-aef6-11ea-826d-eb35bbbf2d7c.png)

Is this a problem with my connector?

Thanks,
Aaron

**Comment by tsjoblad** [comment]
Hi Aaron--to confirm, is this the behavior once a table has been brought out onto the top pane? The screenshots don't display any tables shown. Let me know!

**Comment by aaron-newberg** [comment]
Hi Tucker,

This is what it looks like when I drag a table in. I expect to see a preview of the data, but only see a list of the columns in the table

![image](https://user-images.githubusercontent.com/32000371/84699717-e4b5b680-af06-11ea-9203-e32f0b927748.png)

Thanks

**Comment by tsjoblad** [comment]
Got it--looks like the solution could be the CAP_EXTRACT_ONLY capability is enabled and is blocking the preview from loading. Try removing that from your manifest and seeing if we can preview the data.

**Comment by aaron-newberg** [comment]
Thanks for the suggestion, Tucker. CAP_EXTRACT_ONLY is not enabled. I tried setting this to "no", but still no preview. 
Here's the zip of my plugin
[marklogic_odbc.zip](https://github.com/tableau/connector-plugin-sdk/files/4782769/marklogic_odbc.zip)

**Comment by tsjoblad** [comment]
Thanks, Aaron. I may give switching "CAP_QUERY_TOP_N" to yes, since the preview pane does a top 1000 query. Let me know if that works!

**Comment by aaron-newberg** [comment]
Thank you, that worked!
