### ISSUE TITLE
Supporting additional customisations options

### ISSUE THREAD

**Issue by cdesouza21** [tableau/connector-plugin-sdk#539]
Seems like the list of customisations that can be specified for a connector: https://tableau.github.io/connector-plugin-sdk/docs/capabilities#odbc are a subset of those supported for generic odbc connections: https://help.tableau.com/current/pro/desktop/en-us/odbc_capabilities.htm. 

For example, there doesn't appear to be a way to specify `CAP_QUERY_TOPSTYLE_LIMIT` in a connector's manifest file. Are there any plans to support passing through the full list of ODBC customisations options?

I tested this on 2020.2.

**Comment by rosswbrown** [comment]
Generally the difference in capabilities listed in those documents means they are specific to the Generic ODBC (Other Databases (ODBC)) connector.

For example if your database used LIMIT as the row-limiting clause in Generic ODBC `CAP_QUERY_TOPSTYLE_LIMIT` would be set.  In a connector developed with the SDK this customization would be made in the [dialect definition file](https://tableau.github.io/connector-plugin-sdk/docs/dialect).  Example:
```
    <format-select>
      <part name='Select' value='SELECT %1' />
      <part name='From' value='FROM %1' />
      <part name='Where' value='WHERE %1' />
      <part name='Group' value='GROUP BY %1' />
      <part name='Having' value='HAVING %1' />
      <part name='OrderBy' value='ORDER BY %1' />
      <part name='Top' value='LIMIT %1' />
      <part name='TopPercent' value='LIMIT %1 PERCENT' />
      <part name='TopSamplePercent' value='LIMIT %1 PERCENT' />
      <part name='TopSampleRecords' value='LIMIT %1' />
    </format-select> 
```

If you do identify a gap please let us know and we'll consider it for the backlog.  

Thanks,
Ross
