### ISSUE TITLE
Tableau Server Linux question

### ISSUE THREAD

**Issue by aaron-newberg** [tableau/connector-plugin-sdk#540]
Hi,
If I develop a connector and it gets certified, will it be accessible from Tableau Server Linux?

Where is the Linux variant of the "C:/...Documents/My Tableau Repository/Connectors" directory?

Thanks,
Aaron

**Comment by pvanderknyff** [comment]
Server loads connectors from a different directory than desktop. Try:
`C:\ProgramData\Tableau\Tableau Server\data\tabsvc\vizqlserver\Connectors`
Note that you will have to restart the server for new connectors to be picked up.

Documentation on running connectors is available [here](https://tableau.github.io/connector-plugin-sdk/docs/run-taco#run-a-packaged-connector-in-tableau-server).

**Comment by aaron-newberg** [comment]
Thanks
