### ISSUE TITLE
How to output log from custom JDBC driver ?

### ISSUE THREAD

**Issue by tkcmada** [tableau/connector-plugin-sdk#541]
Hi,
I'm trying to develop my own JDBC driver for some internal data source and its Tableau's connector based on JDBC dialect.

I see jprotocolserver.log has a lot of messages issued by protocolserver. ( I'm launching Tableau with tableau.exe -DLogLevel=debug )
I'd like to output logs from my JDBC driver to this log file.
What log framework should I use in my JDBC ? (log4j, java.util.logging, logpack...)
And how to control log level of each my class hierarchy ?

Thanks !

**Comment by sidwray** [comment]
tfs 1197798

**Comment by jkoskela** [comment]
We use slf4j with log4j-impl.

**Comment by jkoskela** [comment]
There's no good way to configure log level via for jprotocolserver. There is a log42.xml embedded in the Jar. You might can try to use [CompositeConfiguration](https://logging.apache.org/log4j/2.x/manual/configuration.html#CompositeConfiguration) to provide your own, in addition to the embedded one. You can pass custom properties to the JVM by starting Tableau with `-DJdbcVmOptions="-Xmx256m ...."`
