### ISSUE TITLE
The custom jdbc driver does not have the custom SQL option

### ISSUE THREAD

**Issue by peacewong** [tableau/connector-plugin-sdk#544]
Hello, I customized a JDBC Driver with reference to Doc, but I found that there is no option of custom SQL. What parameters need to be configured；
https://tableau.github.io/connector-plugin-sdk/docs
![image](https://user-images.githubusercontent.com/11496700/85848771-4d8d1080-b7dc-11ea-9bff-4b9488b45877.png)

**Comment by sxlin** [comment]
https://kb.tableau.com/articles/howto/convert-a-connection-to-custom-sql

You need drag at least one table into the canvas area.

**Comment by peacewong** [comment]
Thank you very much, that is, I have to implement the getTables method of JDBC, and then drag a table
