### ISSUE TITLE
[BUG] Connector packager validation fails if connector uses custom vendor properties

### ISSUE THREAD

**Issue by jordanw-bq** [tableau/connector-plugin-sdk#561]
**Describe the bug**
When running the `connector_packager` tool, the validation step fails if the connector uses custom vendor properties (like `vendor1-prompt`). It seems that these properties are missing from `validation/tcd_latest.xsd`, and are therefore unexpected by the schema validator.

```
(.venv) PS C:\Development\Projects\connector-plugin-sdk\connector-packager> py.exe -m connector_packager.package --validate-only <plugin-folder-path>

The log path C:\Development\Projects\connector-plugin-sdk\connector-packager exists
XML Validation failed for connection-dialog.tcd
Validation failed. Check C:\Development\Projects\connector-plugin-sdk\connector-packager\packaging_logs.txt for more information.
```

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Tableau Version: 2020.2

**About you:**
 Name: Jordan Wilson
 Company: Bit Quill Technologies

**Comment by pvanderknyff** [comment]
Hi Jorden,

Thanks for raising this issue and opening the pull request. I'll take a look at your pull request and see if it can be merged, and see if there are any other missing elements in our XSD's.

**Comment by jainam1995** [comment]
The fix has been merged. Please re open if you still face the issue
