### ISSUE TITLE
[FEATURE] Long description names in forms cause entry fields to become truncated and unusable

### ISSUE THREAD

**Issue by clach04** [tableau/connector-plugin-sdk#568]
**Is your feature request related to a problem? Please describe.**

Its possible this is a UX bug, opening as an enhancement initial

Long description names in forms cause entry fields to become truncated and unusable, for example (server hostname below):

![image](https://user-images.githubusercontent.com/424032/89354473-cac66380-d66d-11ea-8a07-fad4af02cc81.png)

versus

![image](https://user-images.githubusercontent.com/424032/89354491-d87be900-d66d-11ea-9eb1-4cfc59d3b779.png)

There is no control in the SDK over placement other than the text content (which is our current workaround). 

**Describe the solution you'd like**

It would be nice for either of (or both):

1. auto wrapping in the text
2. more control over the dialog for connectors that are using the connector SDK.

**Describe alternatives you've considered**

limiting description length

**About You**
Name: Chris Clark
Company: Actian

**Comment by clach04** [comment]
Discovered as part of workarounds for issue #443

**Comment by jainam1995** [comment]
Hi Chris,
We will be releasing  Modular Connection Dialog  in 2020.3 release. They are a way to create connection dialogs with more flexibility (example having arbitrary number of fields). This kind of an UI issue will not happen with Modular Connection Dialogs

**Comment by jainam1995** [comment]
Tableau 2020.3 is not released and you can refer to https://tableau.github.io/connector-plugin-sdk/docs/mcd on how to use it to create connection dialogs. Using that will resolve this issue

**Comment by jainam1995** [comment]
Resolving the bug. Do re open if you still face an issue
