### ISSUE TITLE
[BUG] Connector fails to load in Tableau 2020.1

### ISSUE THREAD

**Issue by gs-manvig** [tableau/connector-plugin-sdk#571]
**Describe the bug**
When trying to load a connector which is successfully packaged using the `connector_packager`, into Tableau Server 2020.1, it fails to load with the error logs below. (Thanks @pvanderknyff for pointing us to the right logs)
The same connector works without issues in 2019.4
It appears the the company name field was made mandatory starting v2020.1

We believe it would be better to fail the connector packing with a validation error rather than discover the issue from logs while loading the connector in Tableau Server.
Would it be okay if we open a pull request with the proposed changes?

**Logs**
```
{"ts":"2020-07-21T23:48:41.808","pid":11192,"tid":"70c8","sev":"warn","req":"-","sess":"-","site":"-","user":"-","k":"connector-plugin-warning","v":"ReadVendorInfoFromDOM: company name is empty"}
{"ts":"2020-07-21T23:48:41.808","pid":11192,"tid":"70c8","sev":"error","req":"-","sess":"-","site":"-","user":"-","k":"connector-plugin-error","e":{"log-code":"0e9a05c7","log-source":"needs-classification"},"v":"Failed to load manifest.xml from D:\\Tableau_Connectors\\alloy.taco"}
```

**Server (please complete the following information):**
 - OS: Windows Server 2016
 - Tableau Version: Tableau Server 2020.1

**About you:**
 Name: Vignesh
 Company: Goldman Sachs

**Comment by pvanderknyff** [comment]
That's a good idea. We would welcome a pull request, if you are willing. Otherwise, I can look at doing it during our hackathon time coming up.

If you end up opening a pull request, please add me to the review, I'll take a look and merge it in if there are no problems and the pipeline passes.

**Comment by gs-manvig** [comment]
We're working on getting the corporate CLA signed now; we will submit a PR once that is complete.
