### ISSUE TITLE
Live connections using tableau sdk

### ISSUE THREAD

**Issue by praveenkanamarlapudi** [tableau/connector-plugin-sdk#574]
I am a platform engineer at PayPal.

Name: Praveen Kanamarlapudi
Company: PayPal Inc

Is there any way to create live connections using tableau sdk and publishing to tableau

**Comment by jainam1995** [comment]
Tableau Connector SDK provides a framework to create connectors to be used as a part of tableau. More documentation available [here](https://tableau.github.io/connector-plugin-sdk/docs/) . You can use the SDK to make the connector and once the connector is loaded successfully with tableau, it can be used to make live connections with your database, publish workbooks and the other features tableau provides.

Hope this answers your question and do let me know in the comments if there are any other questions.

**Comment by saikeerthi733** [comment]
can we create twb or twbx or tds files using document API or anyother API? I belive twb or tds is a standard xml file with connection and columns information. Can we create that if we have a sql and connection parameters?

**Comment by rosswbrown** [comment]
The [Tableau Document API](https://www.tableau.com/developer/automation) is where you can find documentation related to the second question.  It has a related [github](http://tableau.github.io/document-api-python/) project is the best place to ask questions for those APIs.
