### ISSUE TITLE
[FEATURE] TDVT should automatically detect the tabquery cli location and prefer getting the location from an environment variable

### ISSUE THREAD

**Issue by jkew** [tableau/connector-plugin-sdk#585]
There's a few different ini files which can be edited within the TDVT and the documentation does not make it clear whether a ini file needs editing or if we can pull the location from an environment variable.

None of that work is particularly necessary. I would establish an env variable from which the location can be pulled, like "TABQUERRYCLI" and prefer that, then fall back to scanning the /Applications or Program Files directories for an existing installation to find the tool.

**Comment by saugatt** [comment]
Create a ticket for the feature in TFS
