### ISSUE TITLE
[BUG] OSX TDVT cannot run headless because it requires the pasteboard

### ISSUE THREAD

**Issue by jkew** [tableau/connector-plugin-sdk#586]
When running the tdvt over ssh (without having logged into the desktop through vnc) all tests fail with:

   "PasteBoard: Error creating pasteboard: com.apple.pasteboard.clipboard [-4960]
PasteBoard: Error creating pasteboard: com.apple.pasteboard.find [-4960]

The same tests work fine when logged in through the desktop, and this is because the clipboard is just not available over SSH: https://stackoverflow.com/questions/1224500/is-it-possible-to-access-the-mac-os-x-pasteboard-when-logged-in-via-ssh

This prohibits some automated test scenarios.

**Comment by saugatt** [comment]
Created a defect for the bug.
