### ISSUE TITLE
[BUG][TDVT - 2.1.16] Can't connect to staples with error message "TableauException: No such table: [Staples]"

### ISSUE THREAD

**Issue by MoemenEb** [tableau/connector-plugin-sdk#587]
**Describe the bug**

1. Create a database with both Calcs and Staples 
2. Create the .tds for both and they work over tableau correctly
3. Save the .tds under the /tds of the workspace 
4. Run the "tdvt action --add_ds ds_name"
5. Run the "tdvt run ds_name --generate" 

**Actual Result** 

> Test Count: 841 tests
>         Passed tests: 1
>         Failed tests: 1
>         Tests run: 2
>         Disabled tests: 0
>         Skipped tests: 839
> 
> Other information:
>         Smoke test time: 17.97 seconds
>         Main test time: 0.49 seconds
>         Total time: 18.48 seconds

**Expected Results** 
Smoke should run correctly

**Possible Root Cause** 
27 days ago a change was made for the staples running files, since older versions of TDVT works correctly and since it only fails with staples.

**Screenshots**
<img width="1281" alt="Screen Shot 2020-08-24 at 12 22 19 PM" src="https://user-images.githubusercontent.com/24305261/91033941-7aa34700-e604-11ea-9a27-010b5bafd48a.png">

**Desktop**
 - OS:Windows 10
 - Tableau Version: 2020.2

**About you:**
 Name: Moemen Ebrahim
 Company: Incorta

**Comment by pvanderknyff** [comment]
Can you try running TDVT with the `--force-run` option? That will run the rest of the tests even though the smoke tests fail. I want to see if some of the tests that use the staples table still manage to run and pass, in which case it may be related to a bug in the TDVT harness we're triaging internally.

We'll take a look at that TDVT change 27 days ago you mentioned, see if that looks promising.

**Comment by MoemenEb** [comment]
<img width="1575" alt="Screen Shot 2020-08-26 at 9 49 03 AM" src="https://user-images.githubusercontent.com/24305261/91276303-a1d35300-e781-11ea-8273-75336a371196.png">

NOTE: we used to have fail rate of 184 already, I m not sure about the new 70 failure yet, but at least run was done. All staples test are failing except for 1 test only 

`sqli_tdvt	logical.staples.sqli_tdvt	Staples.sqli_tdvt	BUGS.B530764	c:\users\ahmed\desktop\connector-plugin-sdk-master\connector-plugin-sdk-master\tdvt\tdvt\logicaltests/setup/staples\setup.BUGS.B530764.prefix.xml	TRUE	0	0	c:\users\ahmed\desktop\connector-plugin-sdk-master\connector-plugin-sdk-master\tdvt\tdvt\logicaltests/setup/staples\setup.BUGS.B530764.prefix.xml	logical	"Attempting to run query...
DataSourceException: No such column [Received Date].

DataSourceException: No such column [Ship Date].

DataSourceException: No such column [Customer Name].

DataSourceException: No such column [Order Date].

DataSourceException: No such column [Market Segment].

DataSourceException: No such column [Order Date].

DataSourceException: No such column [Order Date].

DataSourceException: No such column [Product Name].

DataSourceException: No such column [Order Date].

DataSourceException: No such column [Order Date].

DataSourceException: No such column [Order Date].

DataSourceException: No such column [Order Date].

DataSourceException: No such column [Order Date].

DataSourceException: No such column [Customer Name].

DataSourceException: No such column [Customer Name].

DataSourceException: No such column [Customer Name].

DataSourceException: No such column [Customer Name].

DataSourceException: No such column [Customer Name].

DataSourceException: No such column [Customer Name].

DataSourceException: No such column [Customer Name].

DataSourceException: No such column [Customer Name].

DataSourceException: No such column [Customer Name].

DataSourceException: No such column [Order Date].

DataSourceException: No such column [Customer Name].

DataSourceException: No such column [Call Center Region].

DataSourceException: No such column [Order Date].

DataSourceException: No such column [Customer Name].

DataSourceException: No such column [Call Center Region].

DataSourceException: No such column [Order Date].

DataSourceException: No such column [Prod Type1].

DataSourceException: No such column [Prod Type1].

DataSourceException: No such column [Prod Type1].

DataSourceException: No such column [Prod Type1].

DataSourceException: No such column [Call Center Region].

DataSourceException: No such column [Customer Name].

DataSourceException: No such column [Customer Name].

DataSourceException: No such column [Customer Name].

DataSourceException: No such column [Employee Name].

DataSourceException: No such column [Customer Balance].

DataSourceException: No such column [Customer Balance].

DataSourceException: No such column [Gross Profit].

Run query successful! Check output file
"	None	None	654	"
      SELECT SUM((CASE WHEN 1.1000000000000001 = 0 THEN NULL ELSE CAST(""Staples"".""Price"" AS DOUBLE PRECISION) / 1.1000000000000001 END)) AS ""sum:Calculation_555068687593533440:ok""
FROM ""TestV1"".""Staples"" ""Staples""
HAVING (COUNT(1) > 0)
    "	4275856.2	4275856.2
`

**Comment by JhusiJeremy** [comment]
Same issue here. Run test with --force-run. The smoke test for [Staples] failed with `TableauException: No such table: [Staples]` but other tests passed.

**Comment by sidwray** [comment]
tfs 1197796

**Comment by rosswbrown** [comment]
Resolved in [tdvt-2.3.1](https://github.com/tableau/connector-plugin-sdk/releases/tag/tdvt-2.3.1)
