### ISSUE TITLE
[BUG] an all Left Join Data Model with Live connection will send inner join query to data source. 

### ISSUE THREAD

**Issue by joannahe** [tableau/connector-plugin-sdk#596]
**Describe the bug**
an all Left Join Data Model with Live connection will send inner join query to data source. 
1. Create a data model using Kyligence as data source, with the connector we built for Kyligence
2. the data model contain a star schema with one fact table and two dimension table. all the joins are left joins
3. Enable performance recording in Tableau Desktop 
4. in Tableau Desktop, drag one dimension, measure, and filter one dimension
5 Stop performance recording, check the query, it contains inner join from fact table to dimension table

**Screenshots**
![WeChatWorkScreenshot_cbbe1855-c550-49d2-89af-29b4eef47a36](https://user-images.githubusercontent.com/7544864/91845759-51318d80-ec8c-11ea-8af1-558ad69a2af7.png)
![image](https://user-images.githubusercontent.com/7544864/91845797-64445d80-ec8c-11ea-9ab6-9b8725086b41.png)
![image](https://user-images.githubusercontent.com/7544864/91845882-8b029400-ec8c-11ea-8be9-5bf902133162.png)

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Tableau Version: Tableau Desktop 2020.1.8

**About you:**
 Name: Joanna He
 Company: Kyligence

**Comment by saugatt** [comment]
Hi Jingke,
Can you check the supported join in your dialect file and see if there is something off with it. [These](https://github.com/tableau/connector-plugin-sdk/blob/master/samples/components/dialects/SQLDialect.tdd#L262) are the only supported values. My assumption is there is something invalid there.

**Comment by joannahe** [comment]
Thanks, Saugat.  I will check these values first.

**Comment by joannahe** [comment]
@saugatt our engineer has tried the supported values setting, but it did not help with this inner join change. As our engine expect the join to be exact the same as it is defined in the Data Model so that the query can utilize pre-calculated of our OLAP cube. 

Is there any setting to diable this behavior in Tableau? that means, for left join mode, Tableau only sends left join query instead of inner join in some cases.

**Comment by saugatt** [comment]
I am looking into this issue by testing the bug with once of our test connectors to see if the problem lies in our end. Will get back to you once I figure out where the problem lies.

**Comment by saugatt** [comment]
Hi, @joannahe  I was not able to repro the bug in our test connector, and supported joins worked correct, both with the generated query and in UI. 
Could you send m the connector files and the DB instance credentials so that I can check what is going on? 
Also just to confirm that I understand the bug correctly, are all left joins converted to inner joins in the generated query or does this only happen sometimes.

**Comment by joannahe** [comment]
@saugatt I have sent the connector file and the DB instance credentials to Tucker Sjoblad in email.
I have also provided a workbook that can quickly reproduce the issue with the DB instance credential I provided. 

The issue only arise when a filter is applied on a dimension.

**Comment by saugatt** [comment]
Thanks for doing that. I'll ask Tucker for the files and credentials.

**Comment by saugatt** [comment]
Hi @joannahe , could you take a look at the GREEN_TRIP_DATA. I seem to get `[Simba][ODBC] (10001) General error: No realization found for OLAPContext, rel#404` for it.

**Comment by joannahe** [comment]
@saugatt it is expected to get such error. If there is a pre-calculated data model with all left join model defined in Kyligence. In order for user to leverage this model, the engine expects to received SQL with all left join between tables to match the data model. Otherwise, user will get error like you mentioned. 

we noticed that in Tableau 2019 and below, tableau always sends SQL with left joins if the model defined with all left joins. This is a issue customer would encounter when they upgrade to Tableau 2020.

Maybe it would be helpful to arrange a meeting to explain the details.

**Comment by saugatt** [comment]
Thanks, I think a call should be good. You should contact @tsjoblad  to set up a meeting. Also just to check, I was not able to access the data in GREEN_TRIP_DATA table even without joining it with other table. Can you confirm if this is expected?

**Comment by sidwray** [comment]
tfs 1197789

**Comment by saugatt** [comment]
@joannahe Wanted to confirm that the solution presented by the query team is working.

**Comment by joannahe** [comment]
Saugatt, where can I see the solution presented by the query team?

**Comment by saugatt** [comment]
In the "Data Source" page, "Data" menu, there is an option to "Convert to Custom SQL". If we use that option, the Join type should not be changed. The support team had confirmed that this is working for a customer.

**Comment by saugatt** [comment]
@joannahe could you check on the solution to convert to custom SQL to get the same queries as in the cube works.

**Comment by joannahe** [comment]
@saugatt  yes, this walkaround would work for some of the customers.  We have also released a new version of our product with a property setting that can answer an inner-join query with the same result using a left join model. https://docs.kyligence.io/books/v3.4/en/query/query_enhanced.en.html
We can close this issue.
