### ISSUE TITLE
[BUG] (In README) Link to developer forum is broken

### ISSUE THREAD

**Issue by geordielad** [tableau/connector-plugin-sdk#599]
**Describe the bug**

In https://github.com/tableau/connector-plugin-sdk

clicking https://community.tableau.com/community/developers/content in the **Get Help** section results in https://community.tableau.com/s/FileNotFound 

Should it be https://community.tableau.com/s/topic/0TO4T000000SFBTWA4/connector-sdk? 

**Screenshots**

**Desktop (please complete the following information):**
 - OS:
 - Tableau Version

**About you:**
 Name: Robin Cottiss
 Company: Tableau

**Comment by sidwray** [comment]
Yikes! Thank you.  We'll get this fixed.

**Comment by rosswbrown** [comment]
Linked pull request where this was fixed in gh-pages.  Still needs to be done in [README.md](https://github.com/tableau/connector-plugin-sdk/blob/master/README.md#get-help) as this issue notes.

**Comment by sidwray** [comment]
TY! Made a hot fix in master.
