### ISSUE TITLE
teradata sdk jdbc connector loading all tables in all databases instead of database specified on connector tcd prompt

### ISSUE THREAD

**Issue by saikeerthi733** [tableau/connector-plugin-sdk#600]
**About You:**
Name: Venkata Sangaraju
Company: PayPal Inc.

**Your question:**
We are building a teradata sdk jdbc connector to be able to create workbooks directly from web authoring on tableau server. We are passing servername, port, database name, username and password in the connection dialog file. However after connection is made, its pulling all tables in all databases. Database prompt value is not cascading to filter tables in that database itself. Can someone please help to restrict tables from a database passing in connection dialog for teradata connector. Attaching the tcd file sample
<img width="404" alt="teradata_ConnectionDialog_tcd" src="https://user-images.githubusercontent.com/37277905/92035633-d916a680-ed23-11ea-9887-5528ece5dc8d.png">

Thanks
Venkata S

**Comment by saugatt** [comment]
Hi Venkata, the problem should be that the database  attribute is not being passed in the JDBC connect string. You should check your connectionBuilder.js to see that database is being passed and also that the database is a required attribute in connectionResolver.tdr.  See the example in [this](https://github.com/tableau/connector-plugin-sdk/tree/master/samples/plugins/postgres_jdbc) and check if something is missing.

**Comment by saikeerthi733** [comment]
Hi @saugatt 
Thanks for your response. this helps
