### ISSUE TITLE
[FEATURE] Add capability to suppress SHOW VIEWS, SHOW TABLES queries in Spark base connector 

### ISSUE THREAD

**Issue by CJStuart** [tableau/connector-plugin-sdk#601]
**Is your feature request related to a problem? Please describe.**
When listing tables in the connector we’re seeing that in addition to the ODBC SQLTables call, Tableau is issuing a ‘SHOW TABLES IN’ and a ‘SHOW VIEWS IN’ query. These two queries are redundant, and with our setup these perform a lot worse than SQLTables, so we’d like to suppress them. When querying a database with ~2000 tables, SHOW VIEWS can take up to a minute to complete. It seems that these queries are called from the Spark base class of the connector.

**Describe the solution you'd like**
We would like to be able to set a capability flag to suppress those queries

**About You**
Name: Christian Stuart
Company: Databricks

**Comment by sidwray** [comment]
Thanks Christian!  I filed enhancement: 1168693

**Comment by jsun28** [comment]
Hey Christian, I have added a capability called `CAP_SUPPRESS_ENUMERATE_TABLES_VIA_SQL` in our internal code, will be ready to use in our next release, 2020.1. feel free to reach out to me if you have any issues regarding this, thanks!
