### ISSUE TITLE
Question about migration to Dialog V2

### ISSUE THREAD

**Issue by sidwray** [tableau/connector-plugin-sdk#602]
**About You:**
Name: Christian Stuart
Company: Databricks

**Your question:**
The modular dialog api doesn’t allow us to reuse the field dbname as the http path field, since it throws the following error when trying to load the connector: Error loading connection fields for class 'databricks', reserved field name 'dbname' used. Skipping plugin.. We had to rename it to v-http-path. This is a breaking change for our connector, and old workbooks that still specify dbname as a connection parameter won’t work. Does the SDK provide a way to migrate older workbooks to this newer format?

**Comment by rosswbrown** [comment]
To use the reserved field `dbname` you'll additionally need to author a connection-metadata.xml file.  See the [The Connection Metadata File](https://tableau.github.io/connector-plugin-sdk/docs/mcd) section.  In Connection Dialog V2 the relationship between describing the connection dialog and the connection metadata was separated and formalized to be easier to understand than V1.

In connection dialog V1 file connection-dialog
```
<connection-dialog>
  <db-name-prompt value="Http Path" />
  <has-databases value='false' />
  ...
```

To this representation in connection-metadata file
```
<connection-metadata>
  <database enabled='true' label='Http Path'>
    <field optional='false' />
  </database>
  ...
```

This conversion will result in an Http Path label and value also appearing on the Data Source pane.  Hiding this in the Data Source pane will be opened as a potential enhancement request for future releases.

Thanks,
Ross
