### ISSUE TITLE
Extract Year function is not working with teradata jdbc connector

### ISSUE THREAD

**Issue by saikeerthi733** [tableau/connector-plugin-sdk#606]
**About You:**
Name: Venkata Sangaraju
Company: PayPal Inc

**Your question:**
We are developing teradata jdbc sdk connector and we are able to connect to teradata server and pull data, but the extract year from date function which uses datepart is not working correctly. we get "aggregate used for year is not supported by datasource" error. attaching the error. I believe this may be because of the dialect file we are using. Can you please share if there is a dialect file for teradata or compatible with teradata. 

thanks
![image](https://user-images.githubusercontent.com/37277905/93145772-08bd9b00-f6a2-11ea-8dfc-66dab0db201a.png)

**Comment by jainam1995** [comment]
Hi,
At the moment we do not have a .tdd dialect file for teradata. Wanted to make sure you are using the base dialect as [Teradata1410Dialect](https://tableau.github.io/connector-plugin-sdk/docs/design) or referring from the [full_dialect](https://github.com/tableau/connector-plugin-sdk/blob/master/samples/components/dialects/full_dialect.tdd) example . You can also refer to the dialect documentation for [date](https://tableau.github.io/connector-plugin-sdk/docs/dialect) functions. 

If the above suggestions do not help, unfortunately we would need case by case specific questions to dig into this further.
Thanks !

**Comment by saikeerthi733** [comment]
Hi @jainam1995  thanks for your response.
It was the dialect. After using Teradata1410Dialect and full_dialect, it works as expected. This can be closed. Thanks again.
