### ISSUE TITLE
How to assign database name to schema name without explicitly selecting schema name

### ISSUE THREAD

**Issue by saikeerthi733** [tableau/connector-plugin-sdk#611]
**About You:**
Name: Venkata Sangaraju
Company: PayPal Inc.

**Your question:**
Hi Team
We want to assign database name to schema name without explicitly searching for schema name again after establishing connection to teradata database. Because in teradata database and schema are one and the same. However, the SDK connector is listing tables from all databases if we dont specify schema. How can we search tables within the database specified in the connection or pass the schema name same as database name.

thanks
Venkata S

**Comment by rosswbrown** [comment]
I think in this case you'll need to specify your connector does not use Schemas.  In Connection Dialog V1 use `<has-schemas value="false" />` in the tcd file.  In [Connection Dialog V2](https://tableau.github.io/connector-plugin-sdk/docs/mcd) see the 'The Connection Metadata File' section for changing schema usage.  Additionally in the `connectionBuilder.js` file you can assign the database name from the connection dialog to any part of the connection string as needed.

**Comment by saikeerthi733** [comment]
hi but this feature is available only on 2020.3. we are on 2020.1.6 and packaging fails when we use connection-metadata in manifest file. Can you please help how to fix it in 2020.1 version?

**Comment by rosswbrown** [comment]
Please see the 'Define Tableau Custom Dialog file elements' section in the [Connection Dialog V1](https://tableau.github.io/connector-plugin-sdk/docs/ui) page.  The full list of available elements for that file can be found in [tcd_latest.xsd](https://github.com/tableau/connector-plugin-sdk/blob/master/validation/tcd_latest.xsd).
