### ISSUE TITLE
 Database impersonation using embedded credentials (DelegationUID) failed

### ISSUE THREAD

**Issue by JhusiJeremy** [tableau/connector-plugin-sdk#612]
**About You:**
Name: Weihong Lou
Company: Kyligence

**Your question:**
Hi, Tableau Team:
     We are trying to implement database impersonation using the Connector SDK and ODBC, but got the following error:
![image](https://user-images.githubusercontent.com/9805908/93562860-67905680-f9b9-11ea-907a-aaf8da53f1c9.png)

![image](https://user-images.githubusercontent.com/9805908/93562891-77a83600-f9b9-11ea-9cee-48b44c587e1c.png)

There are also lots of logs like:
```./vizportal/tabprotosrv_vizportal_1-0_2020_09_18_14_15_46.txt:{"ts":"2020-09-18T14:15:46.482","pid":8241,"tid":"7f30f1994700","sev":"warn","req":"-","sess":"-","site":"-","user":"-","k":"excp","e":{"excp-error-code":"0x0E9A82BE","excp-source":"Content","excp-status-code":"INVALID_ARGUMENT"},"v":{"class":"","dse-type":"ConnectorPluginFailure","excp-msg":"Running the plugin script failed.\n","excp-type":"DataSourceException","is-bad-request":false,"is-capability-probe-failure":false,"is-local-configuration-error":true,"is-remote-configuration-error":false,"msg":"DataSourceException::Init"},"ctx":{"client-procid":"124458","client-request-id":"-","client-session-id":"","client-tid":"139875267360512","client-type":"vizportal","client-user":"tabadmin"}}```

We have done the following work to implement the impersonation:

1）Modified `connectionBuilder.js` to attach `DelegationUID` to ODBC connection string:
![image](https://user-images.githubusercontent.com/9805908/93563390-5eec5000-f9ba-11ea-9ea1-df1ef9864bfe.png)

2）Added `<setImpersonateAttributes/>` tag in `connectionResolver` since you added it in the impala sample:
![image](https://user-images.githubusercontent.com/9805908/93563568-c0142380-f9ba-11ea-9d3e-85aaf81189e3.png)

3）Added `<customization name='CAP_AUTH_DB_IMPERSONATE' value='yes' />` in `manifest.xml`:
![image](https://user-images.githubusercontent.com/9805908/93563836-429ce300-f9bb-11ea-8a45-2016c3441b25.png)

4）On the Tableau Server side, configured `native_api.connect_plugins_path`, apply pending changes and restart. The version is 2020.3 .

5）Embedded Credentials enabled on Server side.
![image](https://user-images.githubusercontent.com/9805908/93564622-95c36580-f9bc-11ea-9e13-bc95833badf1.png)

6）On the Tableau Desktop side, started tableau with the same connector. The version is 2020.2 .
![image](https://user-images.githubusercontent.com/9805908/93564294-04ec8a00-f9bc-11ea-8132-5530491fdb33.png)

7）Create workbook with connector:
![image](https://user-images.githubusercontent.com/9805908/93564446-47ae6200-f9bc-11ea-9627-b3768386bd6e.png)
![image](https://user-images.githubusercontent.com/9805908/93564499-5eed4f80-f9bc-11ea-9cab-99dced20ae53.png)

8）Publish the workbook, configured server account and `Impersonate via embedded password`.
![image](https://user-images.githubusercontent.com/9805908/93564718-c0adb980-f9bc-11ea-9dc9-36b515ae3d10.png)

![image](https://user-images.githubusercontent.com/9805908/93565455-fe5f1200-f9bd-11ea-829c-ec1fce4826f1.png)

9）After publishing the workbook to server，the error happened. If I publish the workbook with `Prompt user`, the data source can be connected successfully.

There must be some misconfiguration since in logs there are words like "is-local-configuration-error:true," and "excp-status-code:INVALID_ARGUMENT".

Look forward to your reply. Thanks!

**Comment by devanshsoni9** [comment]
Hi @JhusiJeremy 

Would you be able to paste the error message which has this key "connector-plugin-error". 

Thanks.

**Comment by devanshsoni9** [comment]
Also, 

In your connectionBuilder I do not see the definition of isEmpty() method although you have used it. This might be the reason the script is failing to compile. Including it may solve the issue. 

`
function isEmpty(str) {
        return (!str || 0 === str.length); 
 }
`

**Comment by JhusiJeremy** [comment]
Hi @devanshsoni9 
You are right. It is the script that causes the failure. Now the we can connect to the datasource, but still fail to get tableau username.

The new code is:
```
(function dsbuilder(attr)
{
    var params = {};

    params["SERVER"] = attr[connectionHelper.attributeServer];
    params["PORT"] = attr[connectionHelper.attributePort];
    params["PROJECT"] = attr[connectionHelper.attributeDatabase];
    params["UID"] = attr[connectionHelper.attributeUsername];
    params["PWD"] = attr[connectionHelper.attributePassword];

    params["ServerAuthModeForTest"] = attr[connectionHelper.attributeTableauServerAuthMode];
    params["AuthModeDBImpersonateForTest"] = attr[connectionHelper.valueAuthModeDBImpersonate];
    params["TableauServerUserForTest"] = attr[connectionHelper.attributeTableauServerUser];

    /*
    //Connection properties
    function isEmpty(str) {
        return (!str || 0 === str.length); 
    }     

    if (attr[connectionHelper.attributeTableauServerAuthMode] == connectionHelper.valueAuthModeDBImpersonate) {
        var str = attr[connectionHelper.attributeTableauServerUser];
        
        if (!isEmpty(str)){
            params["EXECUTE_AS_USER_ID"] = attr[connectionHelper.attributeTableauServerUser];
        }
    }
    */

    var formattedParams = [];

    formattedParams.push(connectionHelper.formatKeyValuePair(driverLocator.keywordDriver, driverLocator.locateDriver(attr)));

    for (var key in params)
    {
        formattedParams.push(connectionHelper.formatKeyValuePair(key, params[key]));
    }

    return formattedParams;
})
```

And in our ODBC log:
```
Sep 21 10:48:25.647 TRACE 3843561216 ConnectionState2::SQLDriverConnectW: +++++ enter +++++
Sep 21 10:48:25.647 INFO  3843561216 ConnectionSettings::LoadSettings: ConnString setting: "AUTHMODEDBIMPERSONATEFORTEST" = ""
Sep 21 10:48:25.647 INFO  3843561216 ConnectionSettings::LoadSettings: ConnString setting: "DRIVER" = "KyligenceODBCDriver"
Sep 21 10:48:25.647 INFO  3843561216 ConnectionSettings::LoadSettings: ConnString setting: "PORT" = "7090"
Sep 21 10:48:25.648 INFO  3843561216 ConnectionSettings::LoadSettings: ConnString setting: "PROJECT" = "TDVT"
Sep 21 10:48:25.648 INFO  3843561216 ConnectionSettings::LoadSettings: ConnString setting: "PWD" = "***"
Sep 21 10:48:25.648 INFO  3843561216 ConnectionSettings::LoadSettings: ConnString setting: "SERVER" = "10.1.2.43"
Sep 21 10:48:25.648 INFO  3843561216 ConnectionSettings::LoadSettings: ConnString setting: "SERVERAUTHMODEFORTEST" = "db-impersonate"
Sep 21 10:48:25.648 INFO  3843561216 ConnectionSettings::LoadSettings: ConnString setting: "TABLEAUSERVERUSERFORTEST" = ""
Sep 21 10:48:25.648 INFO  3843561216 ConnectionSettings::LoadSettings: ConnString setting: "UID" = "***"
Sep 21 10:48:25.648 TRACE 3843561216 KyConnection::UpdateConnectionSettings: +++++ enter +++++
```

We can get the `connectionHelper.attributeTableauServerAuthMode` which is `db-impersonate`. But `connectionHelper.valueAuthModeDBImpersonate` and `connectionHelper.attributeTableauServerUser` pass empty string to ODBC.

Thanks!
Weihong

**Comment by devanshsoni9** [comment]
Hi @JhusiJeremy 

I am not getting a hang of what is going wring in this case. Send us your server logs and I will be happy to take a look.I am particularly interested in logs/vizportal and logs/vizqlserver folders

**Comment by JhusiJeremy** [comment]
Hi @devanshsoni9 

Glad to hear from you! What we want to do is to pass the `DelegationUID` to ODBC, like what you describe in https://tableau.github.io/connector-plugin-sdk/docs/auth-modes . In our `connectionBuilder`, we use `"EXECUTE_AS_USER_ID` instead.
![image](https://user-images.githubusercontent.com/9805908/94097442-166ce080-fe59-11ea-9d4e-45358443563e.png)

At Sep 24 2020, 11:21 am and 11:30 am, I triggered the `Test Connect` twice to launch the connection.
![image](https://user-images.githubusercontent.com/9805908/94097841-df4aff00-fe59-11ea-8ca8-4b5c7878584b.png)

In ODBC log, we got an empty string from `DelegationUID`. So we suspect that in `connectBuilder`, we also got empty string from `attr[connectionHelper.attributeTableauServerUser]`. 

Here are the vizportal and vizqlserver logs:
[vizportal.tar.gz](https://github.com/tableau/connector-plugin-sdk/files/5273307/vizportal.tar.gz)
[vizqlserver.tar.gz](https://github.com/tableau/connector-plugin-sdk/files/5273308/vizqlserver.tar.gz)

**Comment by devanshsoni9** [comment]
Hi @JhusiJeremy 

I looked at the logs and looked at our code. I tested with an Impala ODBC driver and found that I needed to add the DelegationUID and AuthMech in the required attributes to make it work. I would suggest to add the  EXECUTE_AS_USER_ID under the attribute list under the required attributes so that it can be passed to the Connect String

**Comment by JhusiJeremy** [comment]
Hi @devanshsoni9 

Tried adding DelegationUID and AuthMech to resolver, but still got empty string. Here are the logs and connectionBuilder, connectionResolver and manifest.

[logs_and_connector.zip](https://github.com/tableau/connector-plugin-sdk/files/5282474/logs_and_connector.zip)

Thanks!
Weihong

**Comment by devanshsoni9** [comment]
Hi @JhusiJeremy, 

I think I could not explain you well. DelegationUID and AuthMech are Impala specific attributes and would NOT apply in your case. 


I would suggest to add the **EXECUTE_AS_USER_ID** under the attribute list under the required attributes in the connectionResolver.tdr file so that it can be passed to the Connect String. 


```
<required-attributes>
    <setImpersonateAttributes/>
        <attribute-list>
          <attr>class</attr>
          <attr>server</attr>
          <attr>port</attr>
          <attr>username</attr>
          <attr>password</attr>
          <attr>sslmode</attr>
          <attr>EXECUTE_AS_USER_ID</attr>
        </attribute-list>
</required-attributes>
````


This code for connectionBuilder is fine 

```
 (function dsbuilder(attr)
{
    var params = {};

    params["SERVER"] = attr[connectionHelper.attributeServer];
    params["PORT"] = attr[connectionHelper.attributePort];
    params["PROJECT"] = attr[connectionHelper.attributeDatabase];
    params["UID"] = attr[connectionHelper.attributeUsername];
    params["PWD"] = attr[connectionHelper.attributePassword];

    //Connection properties
    function isEmpty(str) {
        return (!str || 0 === str.length); 
    }     

    if (attr[connectionHelper.attributeTableauServerAuthMode] == connectionHelper.valueAuthModeDBImpersonate) {
        var str = attr[connectionHelper.attributeTableauServerUser];
        
        if (!isEmpty(str)){
            params["EXECUTE_AS_USER_ID"] = attr[connectionHelper.attributeTableauServerUser];
        }
    }
    

    var formattedParams = [];

    formattedParams.push(connectionHelper.formatKeyValuePair(driverLocator.keywordDriver, driverLocator.locateDriver(attr)));

    for (var key in params)
    {
        formattedParams.push(connectionHelper.formatKeyValuePair(key, params[key]));
    }

    return formattedParams;
})
```

**Comment by devanshsoni9** [comment]
From the logs I can see that in one of the attempts, connection was established wherein I am assuming EXECUTE_AS_USER_ID was passed correctly. So even though in Tableau logs it shows up as empty (I would figure out why that is happening later), If you have access to the database server logs and you can check for that time, you should be able to check the current user and impersonator user. (Some hadoop databases call it audit_event_logs - not sure what term is for Kyligence)

This is the file where I found the log entries
vizportal/tabprotosrv_vizportal_1-0_2020_09_25_11_17_14.txt

```
"k": "construct-protocol",
	"v": {
		"attributes": {
			":dialect-name": "ProgressOpenEdgeDialect",
			":protocol-customizations": "",
			":subclass": "kyligence_odbc",
			":tableau-server-user": "",
			":thread-session": "1",
			":workgroup-auth-user": “REDACTED”,
			"AuthMech": "",
			"DelegationUID": "",
			"EXECUTE_AS_USER_ID": "",
			"class": "odbc",
			"dbname": "TDVT",
			"one-time-sql": "",
			"password": "********",
			"port": "REDACTED",
			"server": "REDACTED",
			"sslmode": "",
			"tableau-server-user": "",
			"username": "REDACTED",
			"workgroup-auth-mode": "db-impersonate"
		},
		"created": "2020-09-25T11:17:14.523",
		"created-elapsed": 0.286,
		"disconnected": false,
		"id": 1,
		"this": "0x00007f0e10000e10"
	}
```

```
"k": "protocol-logsession",
	"v": {
		"Class": "odbc",
		"Driver Name": "Kyligence",
		"Driver ODBC Name": "KyligenceODBCDriver",
		"Driver ODBC Version": "03.80",
		"Driver Version": "10.01.1016",
		"ODBC Driver Manager Version": "03.52",
		"Protocol": "ODBCProtocol",
		"Server Version": "00.00.0000"
	},
```

**Comment by JhusiJeremy** [comment]
Hi @devanshsoni9 

Thank you so much! I figured it out. According to the tabprotosrv_vizportal log you've mentioned, it is the `:workgroup-auth-user` that I really want to pass as `EXECUTE_AS_USER_ID`.  What I actually passed before was `:tableau-server-user`, which is an empty string. 

Here is the connectionBuilder:

```
(function dsbuilder(attr)
{
    var params = {};

    params["SERVER"] = attr[connectionHelper.attributeServer];
    params["PORT"] = attr[connectionHelper.attributePort];
    params["PROJECT"] = attr[connectionHelper.attributeDatabase];
    params["UID"] = attr[connectionHelper.attributeUsername];
    params["PWD"] = attr[connectionHelper.attributePassword];

    function isEmpty(str) {
        return (!str || 0 === str.length);
    }

    if (attr[connectionHelper.attributeTableauServerAuthMode] == "db-impersonate") {
        var str = attr[":workgroup-auth-user"];

        if (!isEmpty(str)){
            params["EXECUTE_AS_USER_ID"] = str;
        }
    }

    var formattedParams = [];

    formattedParams.push(connectionHelper.formatKeyValuePair(driverLocator.keywordDriver, driverLocator.locateDriver(attr)));

    for (var key in params)
    {
        formattedParams.push(connectionHelper.formatKeyValuePair(key, params[key]));
    }

    return formattedParams;
})
```

**Comment by JhusiJeremy** [comment]
So what are the differences between attribute `:workgroup-auth-user` and `:tableau-server-user`? In your Impala example, it passes `attr[connectionHelper.attributeTableauServerUser]`, which is also the `attr[":tableau-server-user"]`, to `DelegationUID`. But in my case, `:tableau-server-user` is an empty string but `:workgroup-auth-user` is the tableau server username. Is it datasource related or just because of my way of publishing the workbook?

**Comment by devanshsoni9** [comment]
Hey @JhusiJeremy 

`:workgroup-auth-user` and `:tableau-server-user` are same thing except that we remove domain from :tableau-server-user. We had renamed it for plugin developers' easy understanding.  However as I was looking into Tableau code base, it seems like we are missing the logic to pass tableau-server-user in the ODBC connection whereas it works fine in JDBC Connection. I would create a bug for us to track internally and fix it in the next release.

For now, you can continue to use the `:workgroup-auth-user` for extracting the server user's identification and pass it as EXECUTE_AS_USER_ID in the params.  

For my future reference can you confirm that you are needing to add EXECUTE_AS_USER_ID in the required attributes list to make db-impersonation work for your ODBC driver?

**Comment by JhusiJeremy** [comment]
Hi @devanshsoni9 

It seems like I don't need EXECUTE_AS_USER_ID in my resolver file to make it work.  From what I understand, those key words under <attribute-list> are allowed to be used as key to map `attr` in connectionBuilder.js . EXECUTE_AS_USER_ID, on the other hand, is a key to map `params` in connectionBuilder and is not controlled by <attribute-list> tag.

Also, while you are checking `:tableau-server-user` for ODBC, can you also check the constant value for `connectionHelper.valueAuthModeDBImpersonate`? It is also an empty string. It should be `dp-impersonate` since the Impala JDBC sample is working. Now I am just hard coding the `dp-impersonate` to make the equality condition works.

Thanks!
Weihong

**Comment by joannahe** [comment]
@devanshsoni9 Thanks for your help on this issue!

**Comment by devanshsoni9** [comment]
@joannahe I try. Thanks for being a Tableau customer.
