### ISSUE TITLE
what tdd config can generate date format 'yyyy-MM-dd' instead of 'YYYY-MM-DD'

### ISSUE THREAD

**Issue by JhusiJeremy** [tableau/connector-plugin-sdk#613]
**About You:**
Name: Weihong Lou
Company: Kyligence

**Your question:**
Hi Tableau Team:

We are configuring `dialect.tdd` in order to pass TDVT. When it comes to test case `join.null.date` and `join.null.datetime`, TDVT generates something like `TO_DATE('1990-01-02','YYYY-MM-DD')` while our data source only accepts date format like `yyyy-MM-dd`.

I've tried copying `<icu-date-token-map>` tag in `Annotated.tdd` and mapping all `y` keys to value `yyyy`. TDVT still generates 'YYYY-MM-DD'.

Our dialect inherits from "ProgressOpenEdgeDialect", and we didn't override TO_DATE function. Is there any other tags in dialect.tdd that control this behavior?

Thanks,
Weihong

**Comment by saugatt** [comment]
This issue is resolved.
