### ISSUE TITLE
Failed to load connector taco using 2020.1 and earlier version

### ISSUE THREAD

**Issue by JhusiJeremy** [tableau/connector-plugin-sdk#622]
**About You:**
Name: Weihong Lou
Company: Kyligence

**Your question:**

Hi Tableau Team:

Our connector can be successfully loaded in Tableau Desktop 2020.2 with command: 
![image](https://user-images.githubusercontent.com/9805908/94510887-79d88300-024a-11eb-8c46-4f17c7e5d91b.png)

![image](https://user-images.githubusercontent.com/9805908/94510946-9e345f80-024a-11eb-8699-c9b3e136dfb4.png)

While in 2020.1 and 2019.4, the connector cannot be loaded and there is error in logs:
```
{"ts":"2020-09-29T11:22:18.341","pid":8216,"tid":"197c","sev":"error","req":"-","sess":"-","site":"-","user":"-","k":"connector-plugin-error","e":{"log-code":"0e9a4f13","log-source":"needs-classification"},"v":"Error loading connection dialog file (.tcd) for class 'kyligence_odbc'. Skipping plugin."}
```

Look forward to your reply.

**Comment by pvanderknyff** [comment]
Hi Weihong,

Can you post your .tcd file? My initial guess is that you may have used a feature added in 2020.2 or higher that doesn't work in earlier versions. 

You should also have some log lines before the one you posted that show which lines in xml of the connection dialog file were malformed. That will hopefully pinpoint which element is failing. If you're having trouble, feel free to attach those as well.

**Comment by JhusiJeremy** [comment]
Hi @pvanderknyff 

You are right. Seems the tcd is malformed, here are the logs:
```
{"ts":"2020-09-28T09:10:02.731","pid":6596,"tid":"d3c","sev":"warn","req":"-","sess":"-","site":"-","user":"-","k":"msg","v":"ConnectionDialogParser::ParseDialog: Malformed XML, showing first 5 errors."}
{"ts":"2020-09-28T09:10:02.731","pid":6596,"tid":"d3c","sev":"warn","req":"-","sess":"-","site":"-","user":"-","k":"msg","e":{"log-code":"f2cf6b5e","log-source":"needs-classification"},"v":"ConnectionDialogParser::ParseDialog: Error: Error(12,23): element 'authentication-mode' is not allowed for content model '(authentication-mode?,authentication-options?,connection-options?,db-name-prompt?,default-ssl-mode?,extended-properties?,has-databases?,has-pre-connect-database?,has-schemas?,port-prompt?,server-prompt?,service-prompt?,show-connection-prompt?,show-db-browse-button?,show-encryption-checkbox?,show-import-ssl-cert-label?,show-service-prompt?,show-ssl-checkbox?,show-uncommitted-data-checkbox?,ssl-requires-certificate?,vendor1-prompt?,vendor2-prompt?,vendor3-prompt?,warehouse-prompt?)' (id: )"}
{"ts":"2020-09-28T09:10:02.733","pid":6596,"tid":"d3c","sev":"error","req":"-","sess":"-","site":"-","user":"-","k":"connector-plugin-error","e":{"log-code":"0e9a4f13","log-source":"needs-classification"},"v":"Error loading connection dialog file (.tcd) for class 'kyligence_odbc'. Skipping plugin."}
```
And here is the tcd:
```
<connection-dialog class='kyligence_odbc'>
  <connection-config>
    <has-schemas value="true" />
    <authentication-mode value='Basic' />
    <authentication-options>
      <option name="UsernameAndPassword" default="true" />
    </authentication-options>
    <db-name-prompt value="Project: " />
    <has-pre-connect-database value="true" />
    <port-prompt value="Port: " default="7070" />
    <show-ssl-checkbox value="true" />
  </connection-config>
</connection-dialog>
```

**Comment by pvanderknyff** [comment]
Looks like the xml elements are out of order. With 2020.2 we changed the XSD's so that order didn't matter, but earlier versions it did. I think moving "has-schemas" to right after "has-preconnect-database" should work.

**Comment by JhusiJeremy** [comment]
Hi @pvanderknyff 

It is now working on 2020.1 after I moved "has-schemas" . But still not working on 2019.4 .
Running 2020.1 with taco files will print something like 
```
{"ts":"2020-10-09T12:05:16.127","pid":10592,"tid":"be8","sev":"info","req":"-","sess":"-","site":"-","user":"-","k":"connector-plugin","v":"Loading connector plugin kyligence_odbc from C:\\Users\\Kyligence\\Documents\\My Tableau Repository\\Connectors\\kyligence_odbc.taco"}
```
in Documents\My Tableau Repository\Logs\log.txt .

However, running 2019.4 with taco files leaves no information, no error, not even any info with `"k":"connector-plugin"` in log.txt. 
I also tried Demior connector taco. It works fine on 2020.1 but not works with 2019.4 .
Thanks!

Weihong

**Comment by pvanderknyff** [comment]
If Dremio isn't working either, and there is no mention of the taco file in the logs, that sounds like a problem how the tacos are installed since it seems like it's not finding any. Double check that the tacos are in the right place relative to your 2019.4 install (and are on the same drive). (Is the 2019.4 install the latest version of that release? If it's the beta version, then you'd need to be the tacos in "My Tableau Repository (Beta)\Connectors".)

You can also try specifying the path manually with the command line using `-DConnectPluginsPath=[path to folder with tacos in it]`.

**Comment by JhusiJeremy** [comment]
Right! After setting `-DConnectPluginsPath`, it works!
Thanks!

Weihong
