### ISSUE TITLE
[BUG] Kyvos Connector throwing DataSourceClassMissing exception intermediately 

### ISSUE THREAD

**Issue by srinadhkunam** [tableau/connector-plugin-sdk#624]
We connected to the Kyvos data source using Kyvos connector (Certified by Tableau) it is connected and we are able to perform all the operations as well. But randomly got "error occurred while communicating with the data source" and exception as below in Tableau Desktop logs

{"ts":"2020-09-20T12:29:18.724","pid":12412,"tid":"33b8","sev":"warn","req":"-","sess":"-","site":"-","user":"-","k":"excp","e":{"log-code":"09df5c3f","log-source":"indistiguishable"},"v":{"class":"","dse-type":"DataSourceClassMissing","error-source":"NeedsClassification","error-source-raw":"NeedsClassification","excp-msg":"Tableau doesn't recognize the data source type ''. It might not be available in this version of Tableau, or it might be a connector plugin that's not installed on this system.\n","excp-type":"DataSourceException","is-bad-request":false,"is-local-configuration-error":false,"is-remote-configuration-error":false,"msg":"DataSourceException::Throw","status-code":13},"ctx":{"client-type":"desktop","procid":"18448","tid":"15044","version":"20194.19.1211.1636"}}

**Screenshots**
![image](https://user-images.githubusercontent.com/52819363/94775793-26973980-03de-11eb-9f1b-8d9f4d9d690b.png)

**Desktop (please complete the following information):**
 - OS: Windows 
 - Tableau Version: 2019.4 (20194.19.1211.1636)

**About you:**
 Name: Srinadh Kunam
 Company: Kyvos Insights

**Comment by srinadhkunam** [comment]
@sidwray and @pvanderknyff Can you please help us at here. We are getting the same exception in Tableau version 2019.4.11 (20194.20.0818.0857) as well

**Comment by pvanderknyff** [comment]
I'm not sure the missing datasouce error in the logs is relevant, it looks like a javascript component is taking longer than 3 seconds and is timing out. The full logs should show which script is timing out (most likely the connection builder in your case). The scripts should be very simple and self contained, so a timeout is very strange, especially intermittently. Did you update the script recently? Or are you using the built-in connector? 

Can you attach the full logs and the connector files you are using (if you're not using the built-in one)?  That will help pinpoint the issue.

**Comment by srinadhkunam** [comment]
@pvanderknyff we replicated the issue again and the exception comes as "ConnectorPluginFailure" this time

{"ts":"2020-10-06T11:34:45.586","pid":13140,"tid":"1570","sev":"warn","req":"-","sess":"-","site":"-","user":"-","k":"excp","e":{"log-code":"0e9a5d2f","log-source":"system"},"v":{"class":"","dse-type":"ConnectorPluginFailure","error-source":"NeedsClassification","error-source-raw":"NeedsClassification","excp-msg":"Running the plugin script component exceeded the timeout: 3000ms\n","excp-type":"DataSourceException","is-bad-request":false,"is-local-configuration-error":true,"is-remote-configuration-error":false,"msg":"DataSourceException::Throw","status-code":13}}
{"ts":"2020-10-06T11:34:45.586","pid":13140,"tid":"1570","sev":"warn","req":"-","sess":"-","site":"-","user":"-","k":"cache-lock-detected","v":{"cache-size-abstract":"125","cache-size-logical":"131","cache-size-metadata":"2","cache-size-native":"122","elapsed-ms":"5479","elapsed-write-block-ms":"5478","function":"GetCachedAbstractQueryFromMemory"}}
{"ts":"2020-10-06T11:34:45.587","pid":13140,"tid":"46f8","sev":"error","req":"-","sess":"-","site":"-","user":"-","k":"connector-plugin-error","e":{"log-code":"0e9a5d2f","log-source":"needs-classification"},"v":"Connect::JavascriptConnectionResolver::MatchesConnectionAttributes Script execution exceeded timeout of (3000)ms."}
{"ts":"2020-10-06T11:34:45.587","pid":13140,"tid":"46f8","sev":"warn","req":"-","sess":"-","site":"-","user":"-","k":"msg","e":{"log-code":"421760b0","log-source":"user"},"v":"DataSourceException::GetAttribute: class "}

Kyvos custom connector is certified by Tableau and comes with Tableau build from 2019.4
We haven't done any recent changes in the Kyvos connector plugins https://github.com/kyvos-insights/KyvosNamedConnector

**Comment by pvanderknyff** [comment]
Thanks for providing the logs.

That is very strange, since it's timing out on the MatchesConnectionAttributes step, but you don't implement that in javascript. I do see above it a warning about a cache lock, which may be triggering the same error. I'll ask around internally, but this may be a general Tableau error and not related to Kyvos specifically.

**Comment by pvanderknyff** [comment]
Also, it looks like I need a login to Expanse to download the complete logs. Is there a place I can sign up, or does someone at Kyvos need to make an account for me?

**Comment by srinadhkunam** [comment]
@pvanderknyff thanks for the update.
Please download logs from [here](https://expanse.kyvosinsights.com/s/y2z6EoWwdZD7ALe/download). It will start downloading automatically. Please let us know if you face any challenges.

**Comment by pvanderknyff** [comment]
Got the logs, taking a look and asking around. Will keep you updated.

**Comment by jainam1995** [comment]
@srinadhkunam just to get a little more information , have  you noticed this error with later versions of tableau ?

**Comment by srinadhkunam** [comment]
@jainam1995 we will try in 2020.3 and update.

**Comment by jainam1995** [comment]
Hi @srinadhkunam any updates on this ? Thanks !

**Comment by sidwray** [comment]
tfs 1197783

**Comment by srinadhkunam** [comment]
Hi @jainam1995 the issue is not replicating now on the same Tableau version. We haven't done any changes. Since last three week we are not seeing this issue

**Comment by jainam1995** [comment]
Thanks! Closing the issue
