### ISSUE TITLE
[BUG] CData suspects that double byte characters in “C:\Users\Administrator\Documents\マイ Tableau リポジトリ\コネクタ” prevents Desktop from opening customer connector file.

### ISSUE THREAD

**Issue by sidwray** [tableau/connector-plugin-sdk#625]
**A clear and concise description of what the bug is.**
When Tableau Desktop (JP) is launched, it seems that Desktop cannot open custom connector file. Error messages in the log file are:
 
{"ts":"2020-09-29T15:28:25.481","pid":4204,"tid":"1ba8","sev":"error","req":"-","sess":"-","site":"-","user":"-","k":"connector-plugin-error","e":{"excp-error-code":"0x0E9A20BD","excp-source":"NeedsClassification","excp-status-code":"UNKNOWN"},"v":"Failed to open connector package C:\\Users\\Administrator\\Documents\\\u30de\u30a4 Tableau \u30ea\u30dd\u30b8\u30c8\u30ea\\\u30b3\u30cd\u30af\u30bf\\cdata.kintone.taco.”}
 
CData suspects that double byte characters in “C:\Users\Administrator\Documents\マイ Tableau リポジトリ\コネクタ” prevents Desktop from opening customer connector file.

**Screenshots**

**Desktop (please complete the following information):**
 - OS: Windows
 - Tableau Version: 2020.3

**About you:**

 Company: CData

**Describe the bug**

CData Tableau Connectors was released in the US, using new Tableau SDK.  Release in Japan is being planned.  https://www.cdata.com/tableau/
cidBFB25B88-7059-464E-A9A9-86096373CB52
 
New connector enables Desktop to use dedicated connector such as “Kintone with CData”, as opposed to “Other JDBC”.
 
cidF03B77E7-80FE-4E87-A795-7E14CA0FF80F
 
While conducting testing before final release, CData faced issue with Tableau Desktop (2020.3) with Japanese setting.
What happened was, custom connector was not displayed at datasource list only when Tableau Desktop Japanese setting is used.
 
CData Tableau connector is developed by Tableau Connector SDK ( https://tableau.github.io/connector-plugin-sdk/docs/ ). Customer connector file has .taco extension (zip file), and when this file is added to following folder, it appears on datasource list.
 
EN : C:\Users\Administrator\Documents\My Tableau Repository\ Connectors
JP : C:\Users\Administrator\Documents\マイ Tableau リポジトリ\コネクタ
 
 
When Tableau Desktop (JP) is launched, it seems that Desktop cannot open custom connector file. Error messages in the log file are:
 
{"ts":"2020-09-29T15:28:25.481","pid":4204,"tid":"1ba8","sev":"error","req":"-","sess":"-","site":"-","user":"-","k":"connector-plugin-error","e":{"excp-error-code":"0x0E9A20BD","excp-source":"NeedsClassification","excp-status-code":"UNKNOWN"},"v":"Failed to open connector package C:\\Users\\Administrator\\Documents\\\u30de\u30a4 Tableau \u30ea\u30dd\u30b8\u30c8\u30ea\\\u30b3\u30cd\u30af\u30bf\\cdata.kintone.taco.”}
 
CData suspects that double byte characters in “C:\Users\Administrator\Documents\マイ Tableau リポジトリ\コネクタ” prevents Desktop from opening customer connector file.
 
 
Alternatively, .taco file can be executed via command line. This worked fine, and screenshot above was captured with this procedure.
 
C:\Program Files\Tableau\Tableau 2020.3\bin>tableau.exe -DConnectPluginsPath="C:\Users\Administrator\Documents\マイ Tableau リポジトリ\コネクタ”
 
This is just workaround, and I don’t think this is solid solution for everyone…

**Comment by sidwray** [comment]
Filed: 1180538

**Comment by sxlin** [comment]
This bug has been fixed.  The fix will be included in release 2020.4 and 2020.3.2.
