### ISSUE TITLE
Help required on Blending & Joining

### ISSUE THREAD

**Issue by srinadhkunam** [tableau/connector-plugin-sdk#632]
**About You:**
Name: Srinadh Kunam
Company: Kyvos Insights

**Your question:**
We would like to check with you below observation regarding Tableau data blending.
 
While blending data on Tableau, every time Tableau sends left outer join request to Kyvos, due to this we are not able to see what we are expecting in the visualization. Requesting you to please help us at here if there is any configuration or method to change the request from left join to full using data blending.
 
Kyvos also supports SQL connectivity over MOLAP cubes. When we tried joining MOLAP cubes at data source level it is sending query without aggregations which is not supported by Kyvos. Requesting you to please help us at here if there is any configuration or method to send the aggregated query from data source joining.

**Comment by saugatt** [comment]
Hi Srinadh, 

Could you sent us the

- Repro steps with screenshots
- The product(s) it appears in
- The exact version of the Tableau products you are using (ie Desktop 2020.3.1, Server 2020.2.2, TDVT 2.1.1, etc), as relevant to the bug
-  a workbook where we should be able to repro the bug easily should be great. 

- Clean logs showing the error. This will be in the "My Tableau Repository\Logs" folder for desktop. 
  -  For server, the "tsm maintenance ziplogs" command can be used, see this [page](https://help.tableau.com/current/server/en-us/logs_loc.htm).
   - Desktop: This will be in the "My Tableau Repository\Logs" folder for desktop. Remove all items from the folder and then reproduce the bug, then copy the remaining files.
   - For server, the "tsm maintenance ziplogs" command can be used, see this page

Also, wanted to check if this bug appears in the build-in connector or a plugin connector that you are trying to build.

**Comment by sidwray** [comment]
tfs 1197780

**Comment by saugatt** [comment]
@srinadhkunam do we have any updates on the details of this bug.

**Comment by saugatt** [comment]
@srinadhkunam wanted to check back to see if there is some update from your side.

**Comment by srinadhkunam** [comment]
@saugatt we are actually asking an question here, is there any configuration or method to change the request from left join to full when working on Tableau data blending.

**Comment by saugatt** [comment]
@srinadhkunam  You could try this process. In the "Data Source" page, "Data" menu, there is an option to "Convert to Custom SQL". If we use that option, the Join type should not be changed. This should get the same queries as you have in your MOLAP cube.

**Comment by saugatt** [comment]
For data blending, we do not have a way to change the join type. Closing this issue, you could reopen the issue if you still need help.
