### ISSUE TITLE
JDBC live connection timeout 

### ISSUE THREAD

**Issue by venkatasangaraju** [tableau/connector-plugin-sdk#638]
**About You:**
Name: Venkata
Company: PayPal Inc.

**Your question:**
When we are creating live connection to database using jdbc sdk connector, if the database is busy and the query is running for longer than 10 minutes, jdbc connector is throwing an error that "Deadline exceeded". Screenshot attached. Is there any timeout setting that we can increase to 30 minutes on JDBC connector or on tableau server. I believe this error is coming from JDBC connector as we see this error even on desktop. Attaching the desktop logs as well.
[jdbcerror.txt](https://github.com/tableau/connector-plugin-sdk/files/5442039/jdbcerror.txt)

![image](https://user-images.githubusercontent.com/73504650/97239266-63213f80-17a8-11eb-8d54-032fbbb80556.png)

**Comment by venkatasangaraju** [comment]
@saugatt @sidwray can anyone help on this? why would connector kill the query if it does not receive response from database after 10 mins

**Comment by sidwray** [comment]
tfs 1197773

**Comment by venkatasangaraju** [comment]
hi 
with odbc connector we dont see this issue. so we are moving with odbc connector. closing this case

**Comment by jkoskela** [comment]
This says it was taking 10 minutes in com.teradata.jdbc.TeraDatabaseMetaData.getColumns(), not running a regular query, that's an unacceptable amount of time to get metadata, from a user experience.
