### ISSUE TITLE
Complex connection dialog options are missing

### ISSUE THREAD

**Issue by bogdanghit** [tableau/connector-plugin-sdk#64]
Hello,

I'm checking out the connector SDK and trying to build a small custom example. I noticed that the current examples contain very basic connection dialogs. Would it be possible to expose the full set of available options in Tableau? Also, can you add to the repository more complex examples that show how to make dropdowns, how to disable certain options when a particular field value is chosen, how to redirect connection to a web page etc?

Bogdan

**Comment by bogdanghit** [comment]
I found the xml schema here: https://github.com/tableau/connector-plugin-sdk/blob/master/validation/tcd_latest.xsd and partly answered my previous questions.

Follow-up question: When using the Hive authentication-mode the dialog shows a Type field that is disabled. What does this field mean and how can I edit the .tcd file to enable a particular Type?

**Comment by bogdanghit** [comment]
@lriggs

**Comment by lriggs** [comment]
The connection type is specific to our hive connectors. I don't think we have a way to customize this right now, but we are planning on making enhancements in this areas. Closing for now since we are tracking this internally.
