### ISSUE TITLE
Quote column names in DDL scripts

### ISSUE THREAD

**Issue by redcatbear** [tableau/connector-plugin-sdk#640]
**Is your feature request related to a problem? Please describe.**
Column names in DDL scrips can conflict with reserved names depending on the database the DDL is us executed on. The word "YEAR" for example is a reserved word in Exasol.

**Describe the solution you'd like**
Wrapping the column names in the DDL script in quotes would keep the column names intact while at the same time clearly indicating that the are identifiers. This resolve any potential keyword conflict.

**Describe alternatives you've considered**
Renaming columns would break existing tests and there is no guarantee that a renamed column would not conflict with a different database.

**About You**
Name: @redcatbear 
Company: Exasol AG

**Comment by redcatbear** [comment]
Examples for reserved words in https://github.com/tableau/connector-plugin-sdk/tree/master/tests/datasets/TestV1
- `year`
- `cs`
- `key`

**Comment by sidwray** [comment]
tfs 1197768

**Comment by jsun28** [comment]
Column name quoting was done in this PR: https://github.com/tableau/connector-plugin-sdk/pull/674, so I am going to close this.
also, our DDL scripts were meant to be an example for individuals to modify as needed to meet their needs, so if you have other needs in the future, you can also modify them yourself.
