### ISSUE TITLE
Configurable TDVT output directory

### ISSUE THREAD

**Issue by redcatbear** [tableau/connector-plugin-sdk#642]
**Is your feature request related to a problem? Please describe.**
When running TDVT, it must be started from a directory that contains the TDVT test setup sources. By default all produced log files end up in the same directory.

Since sources and generated files should never be mixed &mdash; especially if the generated files are log &mdash; it would be good to be able to configure an independent directory, where the logs are written.

I checked the existing options with

```bash
py -m tdvt.tdvt -h
```

It looks like the output directory is not configurable yet.

**Describe the solution you'd like**
I would like to be able to configure the directory like this:

```bash
export TDVT_LOG_DIR="$TEMP/tdvt_logs"
mkdir -p "$TDVT_LOG_DIR"
py -m tdvt.tdvt -o "$TDVT_LOG_DIR" run <connector-name>
```

**Describe alternatives you've considered**
One alternative would be wrapping `tdvt` in a shell script and moving the log files, but that seems like an unnecessary overhead and an additional source of failure. Since putting log files in the current directory is generally a bad practice, I think TDVT should be able to create them in a directory outside of the sources out-of-the-box.

**About You**
Name: @redcatbear (Sebastian Bär)
Company: Exasol

**Comment by lukewrites** [comment]
Thanks, Sebastian, good suggestion. I'll create a story for it.

**Comment by VasanthiNeelagiri** [comment]
Hi, I am a new PM for the Connector SDK and I am looking at our feature backlog and getting things prioritized. I would appreciate if you can give your feedback for our product via this form. It should only take 2-5 mins but would be super valuable to our team. Thanks in advance!!
https://docs.google.com/forms/d/e/1FAIpQLSfs5OreNsxnva_uTO2vTxnoF-oq-37tEdrUpirUKwqud2Ib7g/viewform?usp=sf_link

**Comment by redcatbear** [comment]
@VasanthiNeelagiri, the link you sent requires a Google login, so I unfortunately can't give you feedback there. Could you provide an alternative here on GitHub, please?

**Comment by VasanthiNeelagiri** [comment]
Hi Sebastian, I made the email non-mandatory field. So, you don't have to give your email now. Let me know if this works. You can give feedback here - https://docs.google.com/forms/d/1itfVluk-4Nsaom6dudp71Jan-I3jE6tuwre-1uCwHX4/edit
