### ISSUE TITLE
[BUG] Connection Dialog v2 fails to pass password to connection in Tableau Server 2020.4 beta

### ISSUE THREAD

**Issue by CJStuart** [tableau/connector-plugin-sdk#646]
**Describe the bug**

With Connection Dialog v2 we built a dialog that lets the user choose between token and username/password authentication, both using the `password` field, but using conditional fields to show a different label. It works as expected on Tableau Desktop 2020.4, but trying the same on Tableau Server fails with an authentication error. In _connectionBuilder.js_, Throwing an error when `attr[connectionHelper.attributePassword]` is empty reveals that the input is never passed to the javascript function. 

The `password` field is included in the `<required-attributes>` list of the normalizer. 

The password field declaration looks like this:
```xml
    <field name="password" label="@string/password_prompt/" category="authentication" value-type="string" secure="true">
        <conditions>
            <condition field="authentication" value="auth-user-pass" />
        </conditions>
    </field>

    <field name="password" label="@string/token_prompt/" category="authentication" value-type="string" secure="true">
        <conditions>
            <condition field="authentication" value="auth-pass" />
        </conditions>
    </field>
```
We tried simplifying it to a single field for both auth modes, but this did not resolve the issue:
```xml
    <field name="password" label="@string/password_prompt/" category="authentication" value-type="string" secure="true" />
```

**Screenshots**
![image](https://user-images.githubusercontent.com/2796609/98272435-5dd6a880-1f91-11eb-9b6f-8ac6f20a764f.png)

When throwing an error from connectionBuilder.js:
![image](https://user-images.githubusercontent.com/2796609/98275506-fde20100-1f94-11eb-8514-38dbc5118a8e.png)

**Desktop (please complete the following information):**
 - OS: Windows
 - Tableau Version: Tableau Server 2020.4 Beta

**About you:**
 Name: Christian
 Company: Databricks

**Comment by jainam1995** [comment]
Having defined the password field twice may be causing the issue. The Example 2 - Conditional Display of Fields section of [Connection DIalog V2](https://tableau.github.io/connector-plugin-sdk/docs/mcd) has the reference code that can be used for this case , the `<field name ='authentication' ... >` part of the code specifically.

Could you try rewriting the password field declaration so that the password field is declared only once taking reference from the example mentioned above and retry ?

**Comment by CJStuart** [comment]
We tried the following, but it didn't resolve the problem: 

```
<field name="password" label="@string/password_prompt/" category="authentication" value-type="string" secure="true">
</field>
```

**Comment by jainam1995** [comment]
Could you try : 
`<field name="password" label="@string/password_prompt/" category="authentication" value-type="string" secure="true">
        <conditions>
           <condition field="authentication" value="auth-pass" />
            <condition field="authentication" value="auth-user-pass" />
        </conditions>
    </field>`

**Comment by CJStuart** [comment]
I gave it a try, but it gives the same result. 

I tested the following thus far:

**Works:**
New connector with Dialog v2, Tableau Desktop 2020.4-beta
Old connector (embedded), Tableau Desktop 2020.4-beta 
Old connector (embedded), Tableau Server 2020.4-beta 

**Does not work:**
New connector with Dialog v2, Tableau 2020.4-beta Server, fails with an empty password in connectionBuilder.js

**Comment by jainam1995** [comment]
I see. Could you pass along the credentials internally, that i can use if i want to test it on my end ?

**Comment by jainam1995** [comment]
Actually i may not need the credentials to test this . Could you confirm if [this](https://github.com/databricks/tableau-connector/tree/master/tableau-databricks) is the connector that i can use to repro this on my end ?

**Comment by CJStuart** [comment]
Yes, that's correct, I'm using the version at f82f498e4c28be1664d5a503abe42a6db3fb605e

**Comment by jainam1995** [comment]
Thanks @CJStuart  ! Also could you mention the length of the token being used ?

**Comment by CJStuart** [comment]
It's a 36 character alphanumeric token.

**Comment by jainam1995** [comment]
Opened item 1195907 to work on  internally . Will post an update on this issue once we are able to resolve it

**Comment by jainam1995** [comment]
Add the line  ` <attr>authentication-type</attr> ` to the set of required-aatributes in the connection-resolver.tdr file . That will solve the issue. Im still keeping this bug open untill documentation is updated (if required) or some other way to fix this issue is completed.

**Comment by jainam1995** [comment]
Seems that authentication-type was removed in the [commit](https://github.com/databricks/tableau-connector/commit/aa4693603e3efa1453a177afa9154aeae6ee5493#diff-5f58d09955b155ea6cbccdc8f9e1e22a649c59fe73926418634773c079c67e92) , which as added in the [commit](https://github.com/databricks/tableau-connector/commit/11ba7f14f3905144e43962fbc4512ac4b4755104#diff-5f58d09955b155ea6cbccdc8f9e1e22a649c59fe73926418634773c079c67e92) as a part of tableau hading over the code to databricks , which caused this issue . `authentication-type` is not unused . As this imformation was already present as a part of the tableau hand over code to databricks (the above mentioned commit) , closing this issue

**Comment by jainam1995** [comment]
[This documentaiton page](https://tableau.github.io/connector-plugin-sdk/docs/auth-modes) is also helpful for any authentication related issues especially the section `Considerations for ‘hadoophive’ and ‘spark’ base classes` for databricks

**Comment by CJStuart** [comment]
Thanks for the detailed info. Do you happen to know why we didn't see this problem in Desktop? Is `authentication-type` used for a server-specific mechanism?

**Comment by jainam1995** [comment]
There are certain implementaion differences in the way desktop and web-authoring connect due to which this occurred.
