### ISSUE TITLE
Connection customizations are not loaded

### ISSUE THREAD

**Issue by bogdanghit** [tableau/connector-plugin-sdk#65]
I'm using the following manifest.xml file:

```
<?xml version='1.0' encoding='utf-8' ?>

<connector-plugin class='myconnector' superclass='odbc' plugin-version='0.0.0' name='MyConnector' version='18.1'>
  <connection-customization class="myconnector" enabled="true" version="10.0">
    <vendor name="vendor"/>
    <driver name="driver"/>
    <customizations>
    ....
    </customizations>
  </connection-customization>
  <connection-dialog file='connection-dialog.tcd'/>
  <connection-resolver file="connectionResolver.tdr"/>
  <dialect file='dialect.tdd'/>
</connector-plugin>
```

I successfully connect to my data source, that is the calcs tdvt table and I save the .tds file with the  'Add to the saved datasources' option. The saved file does not contain the list of customizations I added in the manifest.xml file. Is this normal? If not, how can it be fixed? @

@lriggs

**Comment by sxlin** [comment]
This is correct.  The customizations you specify in manifest.xml apply to all connections using your connector.  They don't need be in TDS.

**Comment by bogdanghit** [comment]
Thanks for clarification @sxlin. On a similar note, is it possible to customize the connection dialog in such a way that it displays a dropdown with the available data sources at the given server? More specifically, can I make REST API calls in the connectionBuilder.js to retrieve the list of data sources and then display those in a dropdown menu in the connection dialog?

**Comment by lriggs** [comment]
To answer the latest question, we are tracking this feature internally: 936110
