### ISSUE TITLE
How to get the connector path in repository for each language

### ISSUE THREAD

**Issue by kuwazzy** [tableau/connector-plugin-sdk#650]
**About You:**
Name: Kuwajima
Company: CData Software Japan

**Your question:**
We are working on CData installer, and it is copying the .taco file to the connector path in the repository.
For English version, .taco file is copied to "C:¥Users¥Administrator¥Documents¥My Tableau Repository¥Connectors".
But, the connector path is different for each language. For example, in case of Japanese version is "C:¥Users¥Administrator¥Documents¥マイ Tableau リポジトリ¥コネクタ". We are wondering how to obtain Connecter Path from CData installer. Is there any way to obtain Connector path automatically? The way I expect is to get it from the command line or Config (registory or file). Otherwise we need to copy .taco file manually or hardcoding for each language.

Thanks,
-Kuwajima

**Comment by sxlin** [comment]
Hi Kuwajima,

Unfortunately, the localized `My Tableau Repository/Connectors` directory name is not saved in registry or configuration files. 

The best way you can do is to use the following pattern to find if the directory exists. Take Windows as an example,
C:\Users\<user_name>\<localized_my_tableau_repository>/<localized_connectors>

Here are current translation of the localized directory names for languages Tableau supports at this time. 
**My Tableau Repository**
en_US: My Tableau Repository
en_GB: My Tableau Repository
es_ES: Mi Repositorio de Tableau
fr_FR: Mon dossier Tableau
it_IT: Repository personale di Tableau
ja_JP: マイ Tableau リポジトリ
ko_KR: 내 Tableau 리포지토리
pt_BR: Meu Repositório do Tableau
zh_CN: 我的 Tableau 存储库
zh_TW: 我的 Tableau 存放庫

**Connectors**
en_US: Connectors
en_GB: Connectors
es_ES: Conectores
fr_FR: Connecteurs
it_IT: Connettori
ja_JP: コネクタ
ko_KR: 커넥터
pt_BR: Conectores
zh_CN: 连接器
zh_TW: 連接器

Please be aware that new languages will be supported by Tableau. Even though it's unlikely, we can't guarantee the translations will never change.

**Comment by kuwazzy** [comment]
Hi Sxlin

Thank you for your answer. My questions was cleared up. The list of directory names for each language you described is very helpful for us. I close this ticket.

Thanks,
-Kuwajima
