### ISSUE TITLE
[BUG] Tableau fail to identify the .taco file when the tableau repository folder is in non-english

### ISSUE THREAD

**Issue by joannahe** [tableau/connector-plugin-sdk#654]
**Describe the bug**
This is an issue reported by a customer who conducted the Beta program of our recently launched Kyligence connector.
The user placed the connector in its My Tableau Repository folder on Windows. 
The Windows is in Chinese. So does the folder name of the My Tableau Repository.
The user restarted Tableau Desktop, but the connector did not show up on the data source menu.

Our engineer provided a walk round that makes the .taco effective. 
Adding a parameter in the shortcut of Tableau Desktop to specify an English My Tableau Repository Directory
for example: "C:\Program Files\Tableau\Tableau 2020.1\bin\tableau.exe"  -DConnectPluginsPath="C:\"

This walkaround would work for Beta testing, however, it is unreasonable to ask every analyst in the company adds such a parameter. The customer wish this issue can be resolved so that no such walkaround is needed.

**Screenshots**
![image](https://user-images.githubusercontent.com/7544864/100710035-10135b80-33ea-11eb-9703-898224b72876.png)
![image](https://user-images.githubusercontent.com/7544864/100710024-0ab61100-33ea-11eb-8ffd-c5574f2683fc.png)

**Desktop (please complete the following information):**
 - OS: Windows
 - Tableau Version: to be confirmed. one version in Tableau 2020

**About you:**
 Name: Joanna He
 Company: Kyligence

**Comment by sxlin** [comment]
This is a bug already fixed. Please try Tableau version 2020.3.2 or later. 

tfs1180538

**Comment by joannahe** [comment]
@sxlin  Thanks for the prompt response, Stephen. I will let the customer know.
