### ISSUE TITLE
[FEATURE] Replace LIMIT_ZERO with SQLGetColumns 

### ISSUE THREAD

**Issue by bogdanghit** [tableau/connector-plugin-sdk#662]
**Is your feature request related to a problem? Please describe.**
In a benchmark joining three tables we have the following query execution breakdown in Tableau:
1. set -v (generated by Simba which will be removed
2. SELECT * FROM (SELECT * from table_1) LIMIT_ZERO
3. SELECT * FROM (SELECT * from table_2) LIMIT_ZERO
4. SELECT * FROM (SELECT * from table_3) LIMIT_ZERO
5. SELECT * query

The LIMIT_ZERO query is expensive and running three of them increases the end-to-end latency. We want to improve both.

**Describe the solution you'd like**
The LIMIT_ZERO query was intentionally added by us to reduce the total number of roundripts. Since we reduced the per-query roundtrips to 1, moving forward we want to improve the end-to-end latency by using native ODBC metadata calls like SQLGetColumns instead of this LIMIT_ZERO query. 

In doing so, we would like to have an explicit CAPABILITY in the connector that enables coalescing all three metadata calls in a single SQLGetColumns request, which will be properly handled by the Simba driver.

**About You**
Name: Bogdan Ghit
Company: Databricks

**Comment by bogdanghit** [comment]
@rosswbrown I removed all our capabilities and tried out different combinations for the following subset. All these lead to LIMIT_ZERO queries being generated.

```
<customization name="CAP_ODBC_METADATA_SUPPRESS_PREPARED_QUERY" value="yes"/>
<customization name="CAP_ODBC_METADATA_SUPRESS_SELECT_STAR" value="yes"/>
<customization name="CAP_QUERY_WHERE_FALSE_METADATA" value="no"/>
<customization name="CAP_ODBC_METADATA_SUPPRESS_EXECUTED_QUERY" value="yes"/>
<customization name="CAP_QUERY_TOP_0_METADATA" value="no"/>
<customization name="CAP_ODBC_METADATA_SUPPRESS_SQLCOLUMNS_API" value="yes"/>
```

What is the proper way of making sure the metadata is retrieved using SQLGetColumns calls?

**Comment by jsun28** [comment]
Hey Bogdan @bogdanghit, I just sent this [PR](https://github.com/tableau/connector-plugin-sdk/pull/688) out to document How ODBC metadata reading is determined by capabilities.
For your capabilities combo you mentioned above, you should make CAP_ODBC_METADATA_SUPPRESS_SQLCOLUMNS_API to `no` to be able to execute SQLGetColumns calls, I manually tested it on my end, Tableau could execute SQLGetColumns calls, but failed to return any result, and then fall back to a default behavior, which is select *. But at least, the SQLGetColumns calls were executed. 
Can you try to change the CAP_ODBC_METADATA_SUPPRESS_SQLCOLUMNS_API cap on your end? and please let me know what is your result. if this couldn't solve your issue, let's discuss it further. Thanks

**Comment by jsun28** [comment]
New documentation for metadata enumeration: https://tableau.github.io/connector-plugin-sdk/docs/metadata-enumeration

**Comment by bogdanghit** [comment]
We verified that the fix works as expected on our side and completed TDVT validation. We can close this ticket.
