### ISSUE TITLE
Gap between metadata operations and query exection

### ISSUE THREAD

**Issue by bogdanghit** [tableau/connector-plugin-sdk#667]
**About You:**
Name: Bogdan Ghit
Company: Databricks

**Your question:**

For a 3-way join query, our connector emits 3 LIMIT_ZERO queries to fetch table metadata, then there is a 1.2s gap before the actual query is executed. What is happening on Tableau during that gap? We'd like to understand if it's something that can be optimized.

**Comment by rosswbrown** [comment]
Hi Bogdan,

Can you provide some additional details like Tableau product/version, driver version and attach a .twb or .tds with the repro case.  This [page](https://tableau.github.io/connector-plugin-sdk/docs/bug-artifacts) is a helpful reference for what we normally need to do an investigation.

Also, helpful for this case, what logs lines specifically are you looking at for these measures?  This will help us narrow down on your exact question more easily.

Thanks,
Ross

**Comment by rosswbrown** [comment]
Feel free to re-open with the information above if this continues to be an issue. Thanks.
