### ISSUE TITLE
Date provided in the test case argument is not returned in the query

### ISSUE THREAD

**Issue by PiraisudanM** [tableau/connector-plugin-sdk#668]
**About You:**
Name: Piraisudan M.
Company: Guidanz

**Your question:**

Test cases with the following pattern "**int(#2050-01-01#)**" is generating query without the date argument as mentioned below:

```
SELECT CAST((  - {d '1900-01-01'}) AS INTEGER) AS "TEMP(Test)(1685825827)(0)",
COUNT(1) AS "$__alias__0"
FROM "TestV1"."Calcs" "Calcs"
HAVING (COUNT(1) > 0)
```

As suggested by the Tableau TDVT team, we started with "**full_dialect.tdd**" and modifying the query patterns based on our requirements.
We already tried the below configuration for the date arguments in our "**dialect.tdd**", but still facing the same issue. 
```
<function group='cast' name='DATE' return-type='date'>
  <formula>CAST(%1 AS DATE)</formula>
  <argument type='date'/>
</function>

<function group='cast' name='DATE' return-type='int'>
  <formula>CAST(%1 AS INTEGER)</formula>
  <argument type='date' />
</function>

<function group='cast' name='INT' return-type='int'>
  <formula>CAST(%1 AS INTEGER)</formula>
  <argument type='date' />
</function>
```

We tried with different formulae for both the date and datetime type arguments, but the issue is that whatever date provided in the test case argument is not being returned in the position denoted by "%1" in the formula.

Please find the attached TDVT test results.
[test_results_combined.zip](https://github.com/tableau/connector-plugin-sdk/files/5696460/test_results_combined.zip)

**Comment by PiraisudanM** [comment]
Hi Team,
Hope you are doing well. 
Did you get a chance to look into this issue?

**Comment by PiraisudanM** [comment]
Hi Team,
Any update on this?

**Comment by erademacher** [comment]
Hi Piraisudan,

Thank you for your patience. It looks like there are actually several failing tests that involve date literals, so I'd start with that part of your dialect. What does your current `format-date-literal` tag look like in the `sql-format` section?

**Comment by PiraisudanM** [comment]
Hi Evan,

We have the following `sql-format` section in our dialect file.

```
<sql-format>	
  <format-false value='(1=2)' />
  <format-true value='(1=1)' />   
  <supported-joins>
    <part name='Inner' />
    <part name='Left' />
    <part name='Right' />
    <part name='Full' />
    <part name='Cross' />
  </supported-joins>
</sql-format>
```

Please let us know the changes required to be added for the date literals.

**Comment by erademacher** [comment]
Please check samples/components/dialects/Annotated.tdd for a full list of `sql-format` settings.

Here's the snippet on date/datetime literals:
```
     <!--
      format-date-literal
      Specifies a formula for expressing a date literal, as well as an *ICU* date format.
      %1 is the format string and %2 is the formatted date literal.
    -->
    <format-date-literal formula="TO_DATE('%1', '%2')"  format='yyyy-MM-dd' />
    <format-datetime-literal formula="TO_TIMESTAMP('%1', '%2')" format='yyyy-MM-dd HH:mm:ss.SSS' />
```

Apparently the SDK reference isn't as thorough as it should be. I'll create a work item to add this information to the dialect guide. In the meantime, please scan through Annotated.tdd and see if there are any other settings that may be relevant.

**Comment by PiraisudanM** [comment]
Hi Evan,

Thank you for the update.
We will keep you posted on this.

**Comment by erademacher** [comment]
Thank you for confirming that adding date literal formatting to the dialect resolved the issue. I'm going to create an internal work item to add this info to our docs.
