### ISSUE TITLE
All the logical test cases under "Staples" are failing

### ISSUE THREAD

**Issue by PiraisudanM** [tableau/connector-plugin-sdk#669]
**About You:**
Name: Piraisudan M.
Company: Guidanz.

**Your question:**
All the logical test cases under "**Staples**" are failing with the following error without generating any query,

![Staples_error](https://user-images.githubusercontent.com/29723277/102228038-3ec42280-3f10-11eb-964d-ffd1c49d61c9.png)

Please find the attached TDVT test results.
[test_results_combined.zip](https://github.com/tableau/connector-plugin-sdk/files/5696498/test_results_combined.zip)

Please let us know how to get past this issue.

**Comment by PiraisudanM** [comment]
Hi Team,
Hope you are doing well.
Did you get a chance to look into this issue?

**Comment by sxlin** [comment]
This is usually caused by dialect not implemented correctly. Please refer to [this document](https://tableau.github.io/connector-plugin-sdk/docs/dialect) to check your dialect definition.

**Comment by PiraisudanM** [comment]
As suggested by the Tableau TDVT team, we started with "**full_dialect.tdd**" and modifying query patterns based on our requirements in the "**dialect.tdd**". Also, we have had referred to the mentioned article and made the changes appropriately.

Currently, we have 728 test cases (**87%**) getting passed out of the total 839 test cases.

Under the logical tests, the "**Calcs**" tests are running. The issue is only with the "**Staples**" and "**LOD**" tests where all the logical test cases are failing without generating any query (as mentioned in the earlier screenshot).

**Note**: The data has been added properly for both "Calcs" and "Staples" tables. The connection test also successfully passed as shown in the below screenshot. 
![TDVT_Connection_Test](https://user-images.githubusercontent.com/29723277/103356276-80d79180-4ad6-11eb-9540-b89004166e51.png)

Can you please provide some insights on the changes required to be done to get past this issue?

**Comment by PiraisudanM** [comment]
Hi Team,
Any update on this?

**Comment by erademacher** [comment]
Thank you for confirming via email that the data type was incorrect for a few columns in Staples, and that changing them from string to date in the database resolved the issue.
