### ISSUE TITLE
Extended-properties does not work

### ISSUE THREAD

**Issue by bogdanghit** [tableau/connector-plugin-sdk#67]
I want to configure additional parameters in the dialog box. For this, I'm trying to use the extended-dialog option, but it doesn't seem to work:

ConnectionDialogParser::ParseDialog: Error: Error(15,23): element 'extended-properties' is not allowed for content model '(authentication-mode?,authentication-options?,connection-options?,db-name-prompt?,default-ssl-mode?,extended-properties?,has-databases?,has-pre-connect-database?,has-schemas?,port-prompt?,server-prompt?,service-prompt?,show-connection-prompt?,show-db-browse-button?,show-encryption-checkbox?,show-import-ssl-cert-label?,show-service-prompt?,show-ssl-checkbox?,show-uncommitted-data-checkbox?,ssl-requires-certificate?,warehouse-prompt?)' (id: )"}
{"ts":"2019-02-27T12:31:56.603","pid":7548,"tid":"af0","sev":"error","req":"-","sess":"-","site":"-","user":"-","k":"connector-plugin-error","e":{"category":"needs-classification","log-code":"0e9a4f13"},"v":"Error loading connection dialog file (.tcd) for class 'example'. Skipping plugin."}

**Comment by lriggs** [comment]
Thanks for bringing this up. First, the order of elements in the xml file needs to match the xsd. That's what the error you are getting is about. https://github.com/tableau/connector-plugin-sdk/blob/master/validation/tcd_latest.xsd

I looked into the code and the extended-properties are used to override some UI element strings during the data prep stage. 

Are you looking to add another text box to the connection dialog? You can do that by reusing the 'service' or 'warehouse' elements. I put up an example here: https://github.com/tableau/connector-plugin-sdk/tree/master/samples/components/dialogs/new_text_field

**Comment by bogdanghit** [comment]
A couple of more questions:
1) Is there a more generic way of adding extra text boxes? Let's say I want to add 5, that won't work anymore with the service-prompt and warehouse fields.
2) Is there a way to set the size of these text fields? Most of them I need for integers or boolean values, so displaying a long text field for that is a bit ugly.

**Comment by lriggs** [comment]
These latter questions will be addressed in upcoming dialog enhancements.
