### ISSUE TITLE
Tableau trust store 

### ISSUE THREAD

**Issue by aaron-newberg** [tableau/connector-plugin-sdk#671]
Hi,

What kind of keystore does Tableau use to verify the certificate a .taco was signed with?
Is it like a java keystore similar to one that comes out of the box with a JAVA install?
Is it viable to ask connector users to import a new CA root into Tableau's keystore if a connector is signed by a Certificate Authority that is not in the java keystore by default?

Thanks
Aaron

**Comment by jainam1995** [comment]
Tableau uses the Java keystore that come out of the box with JAVA .  We do not encourage that approach because it is a bad user experience for the connector user and thus go the route of asking the connector developer to sign the taco with a certificate from a CA trusted by the Java keystore
