### ISSUE TITLE
Invalid input: expected '[' --- Input: $Staples$

### ISSUE THREAD

**Issue by zz-big** [tableau/connector-plugin-sdk#680]
**About You:**
Name: z
Company:

**Your question:**

hi :
my tdvt cersion is    2.3.0
tebleau 2020.3
 when i execute the tdvt, the exception as follow :

Exception processing 'C:\Programs\Python37-32\lib\site-packages\tdvt\exprtests/pretest/connection_tests/staples/setup.Query.Filter_Exclude1.xml'

Problem loading logical query XML:

Qualified Name Parse Error --- Invalid input: expected '[' --- Input: $Staples$

how can i specify this variable？ 
  thank you.

**Comment by tsjoblad** [comment]
Can you please attach the .ini file you used to configure TDVT? Thanks

**Comment by tsjoblad** [comment]
Hi z, can you confirm this is still an issue? Otherwise I'll close the ticket. Thanks.

**Comment by tsjoblad** [comment]
Closed due to inactivity.
