### ISSUE TITLE
[QUESTION] generated query includes invalid implicit type conversion

### ISSUE THREAD

**Issue by cornmonster** [tableau/connector-plugin-sdk#683]
**About You:**
Name: Zhong Wang
Company: Alibaba

**Your question:**
Hi, I am the developer of the Alibaba MaxCompute plugin. We have received an issue from our customer that the query generated by Tableau is rejected by MaxCompute due to some semantic errors.

Here is part of the query generated by Tableau. The type of `Fact_Suborders.order_date` is DATETIME (a MaxCompute-defined type)
```
`Fact_Suborders`.`order_date` >= CAST(CONCAT(DATE_ADD(CAST(CAST(CONCAT(TO_DATE(CAST(FROM_UNIXTIME(UNIX_TIMESTAMP()) AS TIMESTAMP)), ' 00:00:00') AS TIMESTAMP) AS TIMESTAMP), CAST(-89 AS INT)), SUBSTR(CAST(CAST(CAST(CONCAT(TO_DATE(CAST(FROM_UNIXTIME(UNIX_TIMESTAMP()) AS TIMESTAMP)), ' 00:00:00') AS TIMESTAMP) AS TIMESTAMP) AS TIMESTAMP), 11)) AS TIMESTAMP)
```

The generated query includes a comparison between a DATETIME and a TIMESTAMP, which is invalid. Since the implicit conversion from DATETIME to TIMESTAMP is unsupported yet, we have to cast the DATETIME to a TIMESTAMP before comparing them. 

Can I have some advice from your team? 

Thank you very much!

**Comment by jsun28** [comment]
Hey Zhong, we have a work item internal to track this issue, will get back to you as soon as we have a clear solution, thanks

**Comment by jsun28** [comment]
@cornmonster Any updates on this? I sent you an email regarding help needed for maxcompute tdvt last Thursday, don't know if you got it or not, please let me know if you can help me with setting up maxcompute's tdvt, thanks.

**Comment by cornmonster** [comment]
> @cornmonster Hey Zhong, after spending some time with this bug, the issue was due to how maxcompute format datetime literal, the old behavior was like `CAST('2022-01-01 00:00:00' AS TIMESTAMP)`, which inherits from base dialect.
> 
> Two things are wrong with this format, one is maxcompute doesn't have implicit conversion between DATETIME and TIMESTAMP, so it will cause type mismatch when compare datetime with timestamp, two is the for datetime format, the correct one for maxcompute is `yyyy-MM-dd HH:mm:ss`, otherwise the comparison will be invalid. My fix is add this line to dialect file:
> `<format-datetime-literal formula="('%1')" format='yyyy-MM-dd HH:mm:ss' />`
> 
> I manually tested this change locally, it can resolve the issue. I was trying to open a pull request in your [repo](https://github.com/aliyun/aliyun-maxcompute-tableau-connector), failed to do so since I don't have permission for that. can you give me permission for that? in the meanwhile, I am making this change to our internal repo, will keep you updated on that.

Sorry I didn't see your replies. I will verify the solution locally. And I have invited you as a contributor to our repo. Could you please submit a merge request?

**Comment by jsun28** [comment]
@cornmonster I sent out a PR in your repo https://github.com/aliyun/aliyun-maxcompute-tableau-connector/pull/2, let us know how it goes, thanks.

**Comment by cornmonster** [comment]
> @cornmonster I sent out a PR in your repo [aliyun/aliyun-maxcompute-tableau-connector#2](https://github.com/aliyun/aliyun-maxcompute-tableau-connector/pull/2), let us know how it goes, thanks.

Hi, I changed the dialect and run the TDVT. But there is a new failure:
Test name: Filter.datetime_fractional
Test path: /tdvt/logicaltests/setup/calcs/setup.Filter.datetime_fractional.tdvt_test2_logical.xml
Generated SQL: 

SELECT ('2016-07-15 10:11:12') AS `calculation_958703807427547136`,
  1.1000000000000001 AS `x__alias__0`
FROM `tdvt_test3`.`calcs` `Calcs`
WHERE (CAST('2016-07-15 10:11:12.123' AS TIMESTAMP) = ('2016-07-15 10:11:12'))
GROUP BY 1.1000000000000001

Please see the attachment for the raw TDVT results. 
[tdvt_results.zip](https://github.com/tableau/connector-plugin-sdk/files/6088319/tdvt_results.zip)

**Comment by cornmonster** [comment]
The test case fails because of the where condition. (CAST('2016-07-15 10:11:12.123' AS TIMESTAMP) results in a MaxCompute Timestamp value. And ('2016-07-15 10:11:12') will be parsed as another MaxCompute Timestamp value before the comparison. 

Since the MaxCompute Timestamp supports nanosecond precision, the where condition returns false so that there is no output.

**Comment by cornmonster** [comment]
The string literal of MaxCompute DATETIME is: "DATETIME 'yyyy-MM-dd hh:mm:ss'". But the test case still fails after I changed the line to

`<format-datetime-literal formula="(DATETIME '%1')" format='yyyy-MM-dd HH:mm:ss' />`

Also, I am not sure why changing the format of DATETIME's string literal solves this issue, could you please explain it?

Thanks!

**Comment by cornmonster** [comment]
I guess the problem is that Tableau follows the type system defined by java.sql.Types, while MaxCompute driver maps both MaxCompute-defined DATETIME and TIMESTAMP to java.sql.Types.TIMESTAMP. So Tableau cannot tell the difference between a MaxCompute DATETIME from a MaxCompute TIMESTAMP.

Thus, one solution is that Tableau sees a java.sql.Types.TIMESTAMP, it cast the column to MaxCmopute TIMESTAMP explicitly. For example, let's say the type of my_table.my_col is DATETIME, the generated SQL should be "CAST `my_table`.`my_col` AS TIMESTAMP".

Is it possible to do it by changing the dialect?

**Comment by jsun28** [comment]
@cornmonster 
can we set up a call for this issue? It is too tricky to comment back and forth on the github issue page, if ok with you, let me know your availability please, thanks.

**Comment by cornmonster** [comment]
> @cornmonster
> can we set up a call for this issue? It is too tricky to comment back and forth on the github issue page, if ok with you, let me know your availability please, thanks.

Sure, thanks!

**Comment by jsun28** [comment]
Haven't heard from @cornmonster for two weeks, so close this, feel free to reopen if you think my solution is not sufficient.
