### ISSUE TITLE
Double quote issues in generated "select queries" from Tableau or Tableau-connector 

### ISSUE THREAD

**Issue by rhtpandeyIN** [tableau/connector-plugin-sdk#691]
**About You:**
Name: Rohit Pandey
Company: HCL Software (Informix and OneDb Database)

**Your question:**
**Background:**
Hi team,
We (Informix/OneDb team) are trying to create our own connector for Tableau (using Postgres-odbc connector as a reference), and in the process, we are facing some issues related to query generation in Tableau. 
We are actually working closely with Tucker, and he suggested us to open an issue here so that the dev community can help us in this situation.

**Problem:**
So, we are able to connect with Informix database server, and we can see the tables catalog inside of the selected database on Tableau data-source page. And, we are able to see the selected Table's schema in Sheets as well. But when we are trying to fetch the data for the selected table, or trying to do some operation on data on the Sheets, we are getting "Syntax Error" errors.

**Diagnosis so far:**
I checked our Informix ODBC logs as well Informix Database Server logs, and the problem which I found was in SQL syntaxes.
Actually, our ODBC driver is receiving incompatible SQLs, having some extra double quotes over table and column names.
If I manually change those SQL, they run properly in our system.
BTW, catalog related queries like- Database names, table's schema, are getting formed correctly. 

**Help required:**
Is there any way which we can use to solve this double-quote related problem, without modifying Tableau's internal code?
Like, I mean in our connector if there is any parameter we can set? I am suspecting like "customization" fields in manifest.xml file.

**Attachments:**
Here, I am attaching the ODBC traces of the problem.
Few hints/points before looking into the traces -

**1)** C->S : it means Client (ODBC) to Server (Informix) transmission.
**2)** S->C : it means Server to Client transmission.
**3)** Search for SQ_ERR and -201, and you will find the bad SQL (having some kind of Syntax error).
**4)** In the C->S section there will be CMD sub-section that will have the SQL syntax.
**5)** For the correct SQL run, there will be SQ_DESCRIBE or SQ_DONE or both.

**For, example:**

**Case1: (When double-clicking on countries table in data-source)**  --> In below trace SQL has extra “double quotes” in Informix.countries, and because of this Server is giving -201 error (Syntax error).

C->S (50)                                                          Time: 2021-01-13 14:27:23.61200
               SQ_PREPARE
                              # values: 0
                              CMD.....: "**SELECT *
FROM "informix"."countries"**" [36]
               SQ_NDESCRIBE
               SQ_WANTDONE
               SQ_EOT

S->C (14)                                                          Time: 2021-01-13 14:27:23.61200
               **SQ_ERR**
                              **SQL error..........: -201**
                              ISAM/RSAM error....: 0
                              Offset in statement: 26
                              Error message......: "" [0]
               SQ_EOT

**Case2: (When dragging “capital column” to Columns in sheet)**

C->S (144)                                                         Time: 2021-01-13 14:27:40.45700
               SQ_PREPARE
                              # values: 0
                              CMD.....: "**SELECT "countries"."capital" AS "capital",
  "countries"."country" AS "country"
FROM "informix"."countries" "countries**"
LIMIT 1000" [130]
               SQ_NDESCRIBE
               SQ_WANTDONE
               SQ_EOT

S->C (14)                                                           Time: 2021-01-13 14:27:40.45700
               **SQ_ERR**
                              **SQL error..........: -201**
                              ISAM/RSAM error....: 0
                              Offset in statement: 33
                              Error message......: "" [0]
               SQ_EOT

**Comment by rhtpandeyIN** [comment]
[sqli.txt](https://github.com/tableau/connector-plugin-sdk/files/5816085/sqli.txt)

**Comment by sxlin** [comment]
Hi Rohit,

It's a good practice to use delimited identifiers in SQL statement so that the keywords or special characters in identifier can be allowed.  Tableau uses double quote marks (") to delimit identifiers by default, as specified in SQL-92.

In Informix, you can define DELIMIDENT environment variable to enable delimited identifiers.
[https://www.ibm.com/support/knowledgecenter/SSGU8G_14.1.0/com.ibm.sqls.doc/ids_sqs_1667.htm](https://www.ibm.com/support/knowledgecenter/SSGU8G_14.1.0/com.ibm.sqls.doc/ids_sqs_1667.htm)

Tableau con be configured to use different characters to quote the identifiers or not to quote identifiers.  To do so, you can define `<id-quotes>` element in `<sql-format>` element.  Define it as an empty string disables quoting identifiers.

```
 <sql-format>
   ...
   <id-quotes value='' />
   ...
 <sql-format>
```

~Stephen

**Comment by sxlin** [comment]
@rhtpandeyIN
I believe the above answer addressed your question.  Please reopen the issue if it's not resolved.

**Comment by rhtpandeyIN** [comment]
Thanks for the quick help and guidance, @sxlin .
Yes, the issue got fixed by setting the "DELIMIDENT" env variable. I was about to close this ticket now, but you already did (at the same time :D ).

If I will have further questions I will open a new ticket. Thanks again for all the work you guys are doing 👍

**Comment by smartin-tableau** [comment]
@rhtpandeyIN Rohit, would you be kind enough to share how you set the "DELIMIDENT" env variable?  I've been scouring the documentations trying to find out how to enable this via the connection string or via Windows environmental variables.

Thanks much!
-Steve
