### ISSUE TITLE
[BUG] fieldnameLower in LogicalConfig not applied for staples smoke test

### ISSUE THREAD

**Issue by waraposn** [tableau/connector-plugin-sdk#699]
**Describe the bug**
'fieldnameLower = True' for db config does not work as reflected by the error message in logs file (specifically for the tests related to Staples)

**Screenshots**
<img width="1141" alt="Staples_connection_test" src="https://user-images.githubusercontent.com/47156058/105700361-9d8c9c80-5ebd-11eb-881d-128d196e007a.png">

**Log File**
[tdvt_log_combined.txt](https://github.com/tableau/connector-plugin-sdk/files/5866567/tdvt_log_combined.txt)

**Desktop (please complete the following information):**
 - OS: MacOS Catalina
 - Desktop 2020.4

**About you:**
Neeraj Soparawala
Starburst Data

Let me know if these details are enough, if not I can provide whatever else is needed.

**Comment by waraposn** [comment]
Some more debugging -- the `db.ini` file setup is this:

> [LogicalConfig]
> Name = sb_trino
> tablename = $dsName
> tablePrefix = [default].
> tablenameLower = True
> fieldnameLower = True
> 
> [Datasource]
> Name = trino
> LogicalQueryFormat = sb_trino
> CommandLineOverride = -DConnectPluginsPath=/Users/waraposn/Desktop/sbd_presto/tableau-plugin
> 
> [StaplesDataTest]
> 
> [StandardTests]
> 
> [LODTests]
> 
> [UnionTest]
> 
> [ConnectionTests]
> StaplesTestEnabled = True
> CastCalcsTestEnabled = True

Now, I tried removing `[` and `]` around the LogicalConfig section (b/c that's how it is in the docs). That didn't fix the issue, in fact the test suite could not find the tests at all. 

Next, I changed the `tablePrefix` in `LogicalConfig` to something random `defasdasdasdad` and I still get the same error -- "Reference to undefined field" (and that's only for staples tests, calcs still go through just fine). This basically means, LogicalConfig section is not being applied while running the tests.

Not sure if I'm missing something -- but any guidance to resolve this issue would be appreciated!

**Comment by lukewrites** [comment]
Hi, Neeraj, the `Staples` tests are Expression tests rather than Logical tests, so it is expected that they won't follow the Logical config. I should be pushing a change soon to make these tests Logical, after which it they should run for you.

Hope that helps.
