### ISSUE TITLE
[FEATURE] SDK Support for multiple OAuth endpoints per connector

### ISSUE THREAD

**Issue by bogdanghit** [tableau/connector-plugin-sdk#705]
**Is your feature request related to a problem? Please describe.**

Databricks already supports multiple (currently 2) OAuth endpoint configurations at the same time. Whereas the Tableau SDK has the capabilities needed to enable the OAuth flow in both Azure and AWS, in our connector we are unable to ship this feature to all our customers. We’d like our customers to have the ability of dynamically loading the `oauth-config.xml` configuration that is required based on the cloud provider. 

**Describe the solution you'd like**
Based on the connection string that is taken as input from the connection dialog (Server Hostname, HTTP Path), the connector will detect to which cloud the endpoint is deployed and provides a drop-down with the specific cloud authentication options:
`Azure: AAD, PAT, usernameuser name/pwd `
`AWS: OAuth, PAT, usernameuser name/pwd`
`<SOME_OTHER_CLOUD>: OAuth, PAT,  usernameuser name/pwd`

**Describe alternatives you've considered**
We explored the idea of having a gallery connector and doing federation, but we aren't convinced that they will deliver a good customer experience.

**About You**
Name: Bogdan Ghit
Company: Databricks

**Comment by sidwray** [comment]
How many customers would you expect to run Databricks in both places simultaneously?  Given the IDP implications, would they most likely choose one or the other, and you'd like the connector to support the one chosen by the customer?
