### ISSUE TITLE
[BUG] Preview results + Custom SQL Fails

### ISSUE THREAD

**Issue by waraposn** [tableau/connector-plugin-sdk#709]
**Describe the bug**
After the connector connects to the datasource, we cannot preview the data nor run a custom sql query against the datasource. 

**Screenshots**
<img width="1508" alt="BugReportPreview" src="https://user-images.githubusercontent.com/47156058/106969145-24801700-66ff-11eb-8ee5-22108335b581.png">
<img width="1507" alt="BugReportCustomSQL" src="https://user-images.githubusercontent.com/47156058/106969154-29dd6180-66ff-11eb-9676-0961674e8e1f.png">

**Desktop (please complete the following information):**
 - OS:  MacOS Catalina
 - Tableau Version: Desktop 2020.4

**About you:**
 Name: Neeraj Soparawala
 Company: Starburst Data

**Comment by lukewrites** [comment]
I have logs that I will add to the defect in Slack.

**Comment by joe-langford** [comment]
Tableau was unable to generate a query to perform this operation.
93FB1021
94F50E12

adding to make this searchable

**Comment by dcory** [comment]
I wonder if you don't have any of the variants of TOP configured. Try setting one of CAP_QUERY_TOPSTYLE_LIMIT, CAP_QUERY_TOPSTYLE_ROWNUM, CAP_QUERY_TOPSTYLE_TOP to yes. These aren't documented for connectors but probably still work.

And make sure CAP_QUERY_TOP_N is yes as well.

**Comment by rosswbrown** [comment]
The `CAP_QUERY_TOPSTYLE_LIMIT`, `CAP_QUERY_TOPSTYLE_ROWNUM`, and `CAP_QUERY_TOPSTYLE_TOP` are only relevant to the [Other ODBC](https://help.tableau.com/current/pro/desktop/en-us/odbc_capabilities.htm) and [Other JDBC](https://help.tableau.com/current/pro/desktop/en-us/jdbc_capabilities.htm) connectors.  

Connectors based on the Tableau Connector SDK should use [this page](https://tableau.github.io/connector-plugin-sdk/docs/capabilities) as reference for the supported capabilities documentation.

**Comment by tsjoblad** [comment]
@rosswbrown the Postgres JDBC manifest was used as a starting point, IIRC

**Comment by waraposn** [comment]
I sent the connector files (including manifests and changes over base dialect) to @lukewrites -- but yes, Postgres JDBC manifest was used as a starting point.

**Comment by rosswbrown** [comment]
In this scenario it appears `CAP_QUERY_SUBQUERIES` should be set to 'yes'.  This is because the connector provided has temporary tables disabled.

When implementing a new connector we advise reviewing the Recommended column in the [Capabilities](https://tableau.github.io/connector-plugin-sdk/docs/capabilities).  The recommendations that differ from the default are noted in red. Some capabilities like `CAP_QUERY_SUBQUERIES` Tableau does not attempt to provide a default value.

**Comment by waraposn** [comment]
That worked -- the custom sql and preview data functionality works just fine! Thanks @rosswbrown for working on this with us!
