### ISSUE TITLE
Dialect File Base Class not performing as expected

### ISSUE THREAD

**Issue by holt-calder** [tableau/connector-plugin-sdk#712]
**About You:**
Name: Holt Calder
Company: InterWorks

**Your question:**
I am developing a connector. I initially authored a TDC file and used the Other JDBC connector to produce my data sources, then tested with TDVT. I have since moved on to developing a custom connector to include functions that were not working, but each test with the custom connector performs worse than the TDC & Other JDBC data sources (544 passed without the custom connector, 360 passing with the custom connector) . 

I've tried pinpointing the differences, and it appears to be tied directly to the dialect being passed. I have tried base class "jdbc" and "otherjdbc", but it appears to be behaving differently than just the standard Other JDBC connection. I also have tried "DefaultSQLDialect" after reading [this issue](https://github.com/tableau/connector-plugin-sdk/issues/118) but the two base classes return the exact same results. Aside from the dialect file, my two sets of data sources are identical (same data types, same tableau metadata attributes, same customizations in manifest/tdc file). 

What is the base class for the Other JDBC connector in Tableau? I imagined that I would be able to plug that in (along with my TDC customizations in the manifest file), and receive the same testing results. So far that has not been the case, so am I misunderstanding the work required here? 

Additionally, here is the beginning of my dialect file if that is useful..

`<dialect name='Druid'
         class='druid'
         base='genericjdbc'
         version='18.1'>`

**Comment by jsun28** [comment]
Hey Holt, thanks for reaching out. 

your current tdd file use` base='genericjdbc'`, genericjdbc is not a valid base dialect name, so I believe it wouldn't have any effects on your dialect. we have various base dialects for you to choose from, please refer to "Choose a dialect" section in this [doc](https://tableau.github.io/connector-plugin-sdk/docs/design).

Tdvt test pass rate is all about the dialect you are using(the tdd file). note that base dialect has nothing to do with base class, the base dialect, which is the `base=` in your dialect file has to point to a specific base dialect. In your case, you prefer to inherit genericjdbc's dialect, which should be SQL92Dialect(I looked it up in our code base), but SQL92Dialect is not in our recommendation base dialect list, if a dialect is not listed there, that means either it has some bugs or not ready to be a base yet. if you'd like to try it, go ahead and use SQL92Dialect as base dialect to test, but it is not a reliable solution.

another thing you can do is, If you like to use genericjdbc's dialect without any customizations, you can also delete the all tdd file configuration, just put `superclass='genericjdbc'` in your manifest file. check out the third scenario of "choose a dialect" section in this [doc](https://tableau.github.io/connector-plugin-sdk/docs/design).

I highly recommend you to check out [Connector Design Considerations](https://tableau.github.io/connector-plugin-sdk/docs/design) and [Create a Tableau Dialect Definition File](https://tableau.github.io/connector-plugin-sdk/docs/dialect.html), and maybe [Connector Example](https://tableau.github.io/connector-plugin-sdk/docs/example.html) and other useful documentation there, to get you started on developing a connector. Let me know if you have further questions.

**Comment by jsun28** [comment]
@holt-calder haven't heard from you for over a week, I think my last response is good enough to get you started on this, feel free to reopen this if you still need help, thanks.
