### ISSUE TITLE
How do I pass a flag to JVM when Tableau Desktop is launched?

### ISSUE THREAD

**Issue by pshrivas** [tableau/connector-plugin-sdk#714]
**About You:**
Name: Prateek Shrivastava
Company: Dremio

**Your question:**
Our current tableau SDK connector is based on JDK 8 while Tableau with its 2020.4 release possibly moved to Java11 (though not sure on the exact timeline).

While we will move to java11 or later, but in short-term to make the experience seamless, we have couple of questions:

1.  Our current connector can pass a jvm flag but we do NOT know how to do that without launching Tableau desktop through CLI. What's a mechanism to do that for tableau desktop?
2. While we build a new Oath connector on 2021.1 SDK, we wanted to understand if there is a min. java version requirement for tableau online/server or will connector based on jdk8 will work as well?

**Comment by bmackas** [comment]
Hi Prateek,

1 - You can't customize JVM options from the SDK.  For internal testing you can use either command line or edit the shortcut to include them.  What are the options you are needing to configure?

2 - Online use the same version of Java we ship with Tableau desktop and server on prem (11), I'd assume you should be fine to build with 8, but be sure to test with our bundled version.  Also making sure you are aware of min-version-tableau=‘…’ which will make sure people don't try to use the OAuth version of the connector with an older release.

**Comment by jkoskela** [comment]
We don't have a good way to customize the JVM flags yet for Tableau Desktop. What flags were you wanting to use?

**Comment by pshrivas** [comment]
Thanks! we have the solution. Please close this ticket
