### ISSUE TITLE
TDC files for JDBC connections and figuring out the "vendor name" and "driver name" that Tableau recognizes

### ISSUE THREAD

**Issue by krusaderjake** [tableau/connector-plugin-sdk#718]
**How can I find in the logs what vendor name is being used and the driver name that Tableau recognizes?** Here's my current TDC file:

~~~ xml
<connection-customization class='sas_jdbc' enabled='true' version='18.1'>
    <vendor name="SAS"/>
    <driver name="driver"/>
    <customizations>
        <customization name="CAP_JDBC_TRIM_STRING_PADDING" value="yes"/>
    </customizations>
  </connection-customization>
</connection-customization>
~~~

**How will I know in the logs if this TDC is being enforced?**

Two questions I'm curious on to get custom JDBC capabilities recognized by Tableau...

**Comment by rosswbrown** [comment]
When this section is used as a part of a `manifest.xml` file within the context of the Connector SDK the values in the `vendor` and `driver` elements are ignored.

In the context of a standalone .tdc file the Tableau [Customize and Tune JDBC Connections](https://help.tableau.com/current/pro/desktop/en-us/jdbc_customize.htm) is the best point of reference for this scenario.  I believe [this answer](https://community.tableau.com/s/question/0D54T00000C6nkv/detecting-tdc-file-for-generic-jdbc-on-desktop) to the same question in the community forums is correct: vendor always equals `genericjdbc`

I'll open an issue for our documentation to suggest making this more clear.

Thanks.

**Comment by krusaderjake** [comment]
Okay I see, I made changes to include the customizations in my `manifest.xml` file and now I'm seeing the customizations applied. Thanks.
