### ISSUE TITLE
How to get to base dialect files to customize from them

### ISSUE THREAD

**Issue by krusaderjake** [tableau/connector-plugin-sdk#723]
Hi - I see documentation here about dialect files: https://github.com/tableau/connector-plugin-sdk/tree/master/samples/components/dialects

I'm curious if it's possible to get to any "base file" dialect like the base dialects mentioned here in the docs: https://tableau.github.io/connector-plugin-sdk/docs/design#dialect-base-classes

I have a JDBC connector working to connect to SAS and I can bring over dimensions into a tableau sheet but the measures aren't working. So I'd like to explore various base dialect files to see how their function-mapping works and how I can customize to my JDBC connector.

For example, if I use the Teradata1410Dialect base dialect I am able to drag measures into my sheet but the sum formula doesn't work with my SAS connection so I'd like to copy what that function mapping looks like from a base dialect and edit/tweak from there.

**Comment by erademacher** [comment]
Hello,

Unless you're developing a connector that's closely related to an existing native Tableau connector (and I don't believe SAS is), we do not recommend specifying a base dialect, but rather starting with the [Postgres ODBC](https://github.com/tableau/connector-plugin-sdk/blob/master/samples/plugins/postgres_odbc/dialect.tdd) example and modifying it as necessary.

If measures aren't working, that most likely means your dialect is missing the `supported-aggregations` element.

You can also check [Annotated.tdd](https://github.com/tableau/connector-plugin-sdk/blob/master/samples/components/dialects/Annotated.tdd) for some descriptive comments about each dialect component.

Hope this helps.

Evan
