### ISSUE TITLE
TDVT tests -  TableauException: Unable to establish connection

### ISSUE THREAD

**Issue by inbarb** [tableau/connector-plugin-sdk#736]
**About You:**
Name: Inbar
Company: SQream

**Your question:**
I am trying to run TDVT tests on our connector, using a signed TACO file we created
I followed all the steps in this guide: https://tableau.github.io/connector-plugin-sdk/docs/tdvt
I believe everything is in place and when I'm connecting manually my connection is good
but when tryng to run the tests (using this command: `python3 -m tdvt.tdvt run sqream`

the connection isn't working and in the log files I see
`2021-03-07 08:19:31,842 Thread-[7] Command line output:LoadDatasource TableauException: Unable to establish connection: Data source 'SQream DB by SQream Technologies' has not been licensed.`

Any advise?

**Comment by tsjoblad** [comment]
Hey Inbar, can you confirm you have a valid license on the version of Tableau Desktop you are using for the tabquery tool?

**Comment by inbarb** [comment]
Yes

**Comment by erademacher** [comment]
Hi Inbar. This is a weird issue. If Tableau Desktop can pick up and use the .taco, then TDVT should be able to use it, too.

I did find an issue from a while back where a partner reported licensing errors when MaxThread was set too high:
https://github.com/tableau/connector-plugin-sdk/issues/532

Could you try setting MaxThread = 3 in sqream.ini? If that solves your issue, I'll open an internal defect to track down the threading bug.

**Comment by erademacher** [comment]
Actually, please set MaxThread = 1 to rule out any possibility of concurrency issues.

**Comment by erademacher** [comment]
I'm going to go ahead and close this until I hear back.
