### ISSUE TITLE
SDK Connector for BigQuery

### ISSUE THREAD

**Issue by venkatasangaraju** [tableau/connector-plugin-sdk#749]
**About You:**
Name: Venkata Sangaraju
Company: PayPal Inc.

**Your question:**
Can we create SDK Connector connecting to BigQuery with user OAuth connection? Does tableau sdk connector support connecting to bigquery yet? Any direction to this is very helpful

**Comment by sidwray** [comment]
Hey Venkata, 

Starting with Tableau 21.1, we are adding support for OAuth to the SDK, so conceivably you could build a connector to BigQuery using their provided ODBC or JDBC driver.  May I ask what you are trying to accomplish that isn't available in the native connector?  That feedback is helpful.  You can email me directly at swray@... if you'd like. 

Regards,
Sid

**Comment by ncwhh** [comment]
Hi Sid,

Nils from the Otto Group here. Like Venkata, we are also looking for a way to use OAuth in an SDK connector to connect to BigQuery. The reason why we can't take the native connector is that we need to route the connection through a proxy, which ensures the GDPR compliance of the queries. It's great to hear that you are already working on it. When can we expect the release of Tableau 21.1?

Regards,
Nils

**Comment by sidwray** [comment]
Unfortunately, I'm not able to provide a specific date other that to share that the release is soon.  That said, can you send me an email regarding the proxy support enhancement request?
