### ISSUE TITLE
Unable to publish custom Connector data source to tableau online

### ISSUE THREAD

**Issue by pavel-vp** [tableau/connector-plugin-sdk#754]
Name: Pavel Pinegin
Company: Agiloft

I have created a sample connector "postgres_jdbc.taco", signed it and used it in Tableau Desktop. It works well locally, but when I am trying to publish the Data Source based on this connector to Tableau Online - it gives me an error "Publish Failure. The server encountered an error and cannot complete your request." 
When I am using builtin PostgreSQL connector to the same Database, I can publish it without problem.

Does it mean we can't publish Data Sources based on non-builtin connectors to Tableau Online?
Even if this custom Connector will be approved by Tableau?

**Comment by tsjoblad** [comment]
Hi Pavel, currently .taco files are not supported in Online. We are actively working on supporting this use case for Gallery-approved connectors in coming releases. Thanks
