### ISSUE TITLE
[QUESTION] How to ensure CASE filters use comparisons

### ISSUE THREAD

**Issue by kylepbit** [tableau/connector-plugin-sdk#760]
**About You:**
Name: Kyle Porter
Company: Dremio

**Your question:**
Repro Steps:

1.  Install Tableau Desktop (eval) version 2020.4.2 (20204.21.0217.1203) 64-bit
2. Install Dremio ODBC 32-bit driver version 1.5.1.1000. Use the instructions found here: https://docs.dremio.com/drivers/dremio-connector 

Configure an ODBC DSN.

3. Upload the following CSV file to your Dremio home space:

cat < EOF > cato_txn_oneview.csv
rowid,mifid_ii_priips_bmk_id,mifid_ii_priips_bmk_source,asset_class
1,1001,AA,F
2,1002,BB,G
3,1003,CC,H
4,1004,DD,I
5,1005,EE,J
6,1006,FF,K
7,1007,GG,L
8,1008,HH,L
EOF

4. Go into the “cato_txn_oneview” VDS and click on the “tableau” tool bar button to generate a Tableau .tds file.
5. Click on the .tds file and sign into the Dremio server via the Tableau workbook
  a. Create a worksheet that uses the Tableau live connection with an exclude filter:
  b. Drag the “Asset Class” field to the “Filters” box.
  c. Select the “F” value and press OK.
  d. Drag the “mifid_ii_priips_bmk_source” field to the “Rows” section.
  e. See the rows that have an “Asset Class” of “F”.
  f. Edit the “Asset Class” filter.
  g. Select the “Exclude” option and press OK.
  h. See the Tableau error message.
  i. See the Dremio Jobs page and see the SQL generated by Tableau is not valid Dremio syntax:

WHERE clause must be a condition

`SELECT "cato_txn_oneview"."mifid_ii_priips_bmk_source" AS "mifid_ii_priips_bmk_source"
FROM "home.Preparation_Tier"."cato_txn_oneview" "cato_txn_oneview"
WHERE (CASE WHEN ("cato_txn_oneview"."asset_class" = 'F') THEN 0 ELSE 1 END)
GROUP BY "cato_txn_oneview"."mifid_ii_priips_bmk_source"`

When similar operation performed with Table -> Oracle below is where condition 

Tableau → Oracle

`WHERE ((CASE WHEN ("EMPLOYEES"."JOB" = 'Analyst') THEN 0 ELSE 1 END) <> 0)`

but when dremio is involved Tableau → Dremio → Oracle

`WHERE ((CASE WHEN ("EMPLOYEES"."JOB" = 'Analyst') THEN 0 ELSE 1 END))`

Is there a capability that can be added to the TDC file which will ensure that the CASE has the <> 0 added to it as Dremio cannot handle filters that are essentially `WHERE 0` or `WHERE 1`.

**Comment by pvanderknyff** [comment]
Other ODBC isn't a part of the Connector SDK. Documentation for Other ODBC can be found here: https://help.tableau.com/current/pro/desktop/en-us/examples_otherdatabases.htm
