### ISSUE TITLE
[BUG] Connector vendor parameter does not get saved

### ISSUE THREAD

**Issue by iancr01** [tableau/connector-plugin-sdk#770]
**Describe the bug**
We have added a new vendor (custom) parameter to the connection interface (of the Actian Avalanche ODBC connector - https://extensiongallery.tableau.com/connectors/167).

When creating a new workbook the connection works as expected taking the parameter we provide. 

However, when we save the workbook and reopen it, the parameter is not saved and the workbook acts like the parameter is not set, even if you enter the parameter value and the password again.

**Screenshots**
![ConnectorDialog](https://user-images.githubusercontent.com/45437933/115455808-0d25d580-a1e8-11eb-8a7b-d35c7de28249.png)

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Tableau Version: Tableau Desktop 2021.1.1 (20211.21.0320.1853)

**About you:**
 Name: Cris Ianculovici
 Company: Actian

**Comment by clach04** [comment]
In this instances this is a `vendor1-prompt`, for a code example see https://github.com/ActianCorp/actian_tableau_connector/blob/e2e3642c3274547131622093089bc1da1f3abeee/actian_odbc/connection-dialog.tcd#L13

A couple of examples of possible entries into the Options field are:


    SELECTLOOPS=Y

    NUMERIC_ OVERFLOW=IGNORE

    SELECTLOOPS=Y;NUMERIC_ OVERFLOW=IGNORE

etc.

**Comment by rosswbrown** [comment]
Hi Cris,

I took a look at that linked connection-dialog.tcd above.  I believe the extra whitespace around `vendor1`, `<attr> vendor1 </attr>` in [connectionResolver.tdr](https://github.com/ActianCorp/actian_tableau_connector/blob/e2e3642c3274547131622093089bc1da1f3abeee/actian_odbc/connectionResolver.tdr#L17) may be causing this issue.

Let us know if that doesn't resolve this, thanks.

**Comment by iancr01** [comment]
Hi @rosswbrown,

I've made the changes as you suggested and re-tested. The problem happens the same way - it seems that there is no change in the behavior.

**Comment by rosswbrown** [comment]
I wasn't able to repro this issue locally using our [vendor_attributes](https://github.com/tableau/connector-plugin-sdk/tree/master/samples/scenarios/vendor_attributes/postgres_vendor) sample.

Can provide some additional [details](https://tableau.github.io/connector-plugin-sdk/docs/bug-artifacts) for an investigation: 
- attach or a link to the version of the connector you used
- the repro steps, please include a twb since I think that is relevant here
- the exact version of the Tableau products you are using (ie Desktop 2020.3.1, Server 2020.2.2), as relevant to the bug
- the operating system you are using

**Comment by iancr01** [comment]
The twb file is not quite relevant as I always start from scratch. I create a new workbook, I add one datasource table , I save it, and when I reopen it it loses the vendor1 parameter. I'm attaching one which I manually edited (the xml code) to hard code the vendor1 parameter. 

I use this syntax to start Tableau to use the new connector followed by my twb file.
` "C:\Program Files\Tableau <version>\bin\tableau.exe" -DConnectPluginsPath=D:\tableau_connectors `

You will see that in my twb file the vendor1 parameter is there but as soon as you refresh the data source, it becomes empty and it is no longer applied. 

[option_connector.zip](https://github.com/tableau/connector-plugin-sdk/files/6408452/option_connector.zip)

I'm using Desktop 2021.1.1 on Windows 10.

**Comment by rosswbrown** [comment]
I was able to repro your issue with the [actian_odbc](https://github.com/ActianCorp/actian_tableau_connector/tree/master/actian_odbc) connector found in master of your repro.

Modify [connectionResolver.tdr](https://github.com/ActianCorp/actian_tableau_connector/blob/master/actian_odbc/connectionResolver.tdr#L17) line 17 to:
`<attr>vendor1</attr>`

This resolved the issue locally for me. The leading and trailing space within the value of the `<attr>` element was the issue.

**Comment by rosswbrown** [comment]
Please reopen this issue if this did resolve the bug.  Thanks.
