### ISSUE TITLE
Differences in Oauth configuration for Tableau Desktop, Server and Online

### ISSUE THREAD

**Issue by tifflhl** [tableau/connector-plugin-sdk#772]
**About You:**
Name: Tiffany Lam
Company: Dremio

I want to check my understanding on the non-configurable and configurable values for Oauth configurations in all three platforms. 

Tableau Desktop: configurations not overridable, redirect uri should be in the format `http://localhost:port/Callback`.

Tableau Server: client id, client secret and the redirect uri are overridable. The redirect uri should be in the format `https://Myserver/auth/add_oauth_token`.

Tableau Online: I couldn't find official documentation about this, could you provide more details on whether client id, client secret and the redirect uri are fixed or configurable on this platform?

Thanks!

**Comment by jainam1995** [comment]
Tracking internally . Id : 1257444

**Comment by tifflhl** [comment]
@jainam1995 I'm wondering if I can get an answer on this thread regarding redirect uri for the oauth mode in Tableau Online? Thanks!

**Comment by wangxinlei** [comment]
@tifflhl 
For desktop and server they are correct.
For server you will be able to configure those in the server level or site level.
For online our doc is not published yet but you will be able to configure your cientId, clientSecret, instanceUrl and rediretUri at the site level only.

**Comment by tifflhl** [comment]
@wangxinlei Can you elaborate more on what you mean by "site level only"? As I understand, Tableau Online is accessed via the browser, would the redirect uri be fixed for all Tableau Online users? Say I am using Chrome to login to Tableau Online, what should I set the value of redirect uri be? Thanks!

**Comment by wangxinlei** [comment]
Yeah so since Tableau Online is a giant server you can only set up oauth client for your site, not for another cusomter's site.
Your redirect uri will be your Tableau online server address + /auth/add_oauth_token. 
E.g. https://us-west-2b.online.tableau.com/auth/add_oauth_token.

**Comment by tifflhl** [comment]
Just want to confirm, does that mean that my Tableau Online site's name does not need to be included in the redirect uri? Meaning that if I want to support all Tableau Online Servers, I simply need to add a redirect uri to the authorization server/service I am using for each of the servers listed here? (https://help.tableau.com/current/online/en-us/to_keep_data_fresh.htm#tableau-online-ip-addresses-for-data-provider-authorization)

**Comment by wangxinlei** [comment]
So as a online user you will have your own site which sits on a specific pod such as 10ax.online.tableau.com. Other sites/other pods will not be able to access your oauth clients config since they're site specific. So you only need to register your own pod's name as redirect uri, not others. And yes you do not need to specify the site.
What's the scenario that you need all Tableau online users, i.e. users from other sites?

**Comment by tifflhl** [comment]
@wangxinlei We are trying to figure out whether Tableau Online redirect uris can be whitelisted in a custom OAuth 2.0 authorization server. Since site name does not need to be included and there is a known set of Tableau Online severs, sounds like that is possible then. This is all from an oauth authorization server perspective though.

From a Tableau Online site administrator perspective, I will still need to add the redirect uri override for all my datasources, is that correct?

**Comment by wangxinlei** [comment]
Yep you should be able to whitelist that in you oauth auth server.
Yes you need to override for all your datasources, usually a set of CI/CS will be only used by one datasource and when you register you need to put the data source name in the registry.
