### ISSUE TITLE
[BUG] Data source not refreshable if not embedded in workbook

### ISSUE THREAD

**Issue by Relucin** [tableau/connector-plugin-sdk#774]
**Describe the bug**
If data source isn't embedded in a workbook and gets published to the server, when you refresh the data source you get an error code 2000. However, this works fine when embedded on a workbook. This is with an extract only taco.

 - Desktop Version:  2020.3.5
 - Desktop OS: MacOS
 - Server OS: Windows
 - Tableau Version:  2020.3.4 (20203.20.1208.1036)

**About you:**
 Name: Brandon 
 Company: Apple

**Comment by pvanderknyff** [comment]
Hi Brandon,

Can you list the UI steps you used to refresh the extract on server? It'd also be useful to get the [server logs](https://help.tableau.com/current/server/en-us/logs_loc.htm) showing this error.

Thanks,
Patrick

**Comment by tsjoblad** [comment]
Brandon confirmed that updating to 21.1 solved the issue.
