### ISSUE TITLE
Disable LIMIT and Alias when retrieving data from connector

### ISSUE THREAD

**Issue by anthonylouisbsb** [tableau/connector-plugin-sdk#775]
**About You:**
Name: Anthony Louis
Company: Simbiose Ventures

**Your question:**
We created a general connector using the **Tableau Connector SDK** to connect with the multiple connections we have, some of them are MySQL databases and others are Oracle Databases.

To load the data from the tables in the sources, Tableau sends this query:
```sql
SELECT "alias"."column1" AS "column1", "alias"."column2" AS "column2" .... FROM "database"."table" AS "alias" LIMIT 1000
```

The problem is that `LIMIT` is only recognized by Mysql sources and the `"` to quote alias are supported only by the Oracle sources.

Is there some option that I can add in the connector files to disable the `alias` for columns and tables and the `LIMIT`when the Tableau is retrieving the data from the sources?

I have already searched in the [capabilities reference](https://tableau.github.io/connector-plugin-sdk/docs/capabilities) but I did not found any option related to this.

**Comment by jainam1995** [comment]
Internally tracked by item 1259981

**Comment by anthonylouisbsb** [comment]
@jainam1995 did you mean that is not possible to do what I want in the actual version of the connector SDK and the question is being discussed and executed internally by the Tableau team?

**Comment by sxlin** [comment]
@anthonylouisbsb  I don't think  it's a good idea to have one connector to connect to different kind of databases. The connetor capabilities and dialect are used to tune the connector for a specific database. 

How ever, I will try to answer your specific questions. 
1. You can set capability `CAP_QUERY_TOP_N` to `no` to disable Tableau generating query using LIMIT clause or TOP N. 
2. We need use alias to support join.  If your question is how to disable quoting the identifiers, please refer to 
[this issue](https://github.com/tableau/connector-plugin-sdk/issues/691).

**Comment by sxlin** [comment]
@anthonylouisbsb I am closing this issue.  Please file a new issue or reopen if you have further questions.
