### ISSUE TITLE
ODBC/JDBC Meatdata Enumeration

### ISSUE THREAD

**Issue by tifflhl** [tableau/connector-plugin-sdk#778]
Name: Tiffany Lam
Company: Dremio

Wondering if Metadata Enumeration documented [here](https://tableau.github.io/connector-plugin-sdk/docs/metadata-enumeration) is also an available feature for a JDBC based SDK connector?

**Comment by tifflhl** [comment]
In addition, looking at the [Tableau Snowflake example](https://help.tableau.com/current/pro/desktop/en-us/examples_snowflake.htm) ([screenshot](https://cdns.tblsft.com/sites/default/files/blog/snowflake2_0.png)), the workbook there appears to be other selectable options like "Warehouse". Is this an implementation example of Metadata Enumeration? If not, could you please let me know how that can be accomplished in the connector?

**Comment by jainam1995** [comment]
Tracking internally : 1262383

**Comment by jsun28** [comment]
@tifflhl Hey Tiffany, The Metadata Enumeration documented there are for ODBC only, I am working on writing documentation for JDBC Metadata Enumeration, will let you know when I am done. thanks

**Comment by jsun28** [comment]
@tifflhl Please refer to the new JDBC Metadata Enumeration section at https://tableau.github.io/connector-plugin-sdk/docs/metadata-enumeration, I am going to close thisfo r now, feel free to reopen if you still have questions.
