### ISSUE TITLE
[FEATURE] Provide support for running the `TDVT` in Linux environments

### ISSUE THREAD

**Issue by chiaradiamarcelo** [tableau/connector-plugin-sdk#782]
**Is your feature request related to a problem? Please describe.**
I'm trying to automate all tests related for a connector in a Linux environment, meaning the manual tests described in https://tableau.github.io/connector-plugin-sdk/docs/manual-test and the execution of the `TDVT`.
The execution of the `TDVT` requires the `tabquerytool.exe` tool, that at the moment comes only with the Tableau Desktop installation and it seems to be only available for Windows and not for Linux.

**Describe the solution you'd like**
I would like to be able to execute the `TDVT` in a Linux environment, thus an equivalent of the `tabquerytool.exe` should be available for Linux, ideally delivered with Tableau Server for Linux.

**Describe alternatives you've considered**
I have considered starting a Windows VM in Linux, but it's totally impractical.

**About You**
Name: @chiaradiamarcelo (Marcelo Chiaradia)
Company: Exasol

**Comment by jainam1995** [comment]
Internal tracking id : 1264723

**Comment by rosswbrown** [comment]
At this time we do not have a way to distribute tabquerytool on Linux for partners. We are exploring ways to do this in future releases, but do not currently have a specific release target.  This item will be updated when we have any future TDVT on Linux details to share.

**Comment by iqDF** [comment]
Hi any updates on this? Interested to also automate TDVT on linux machine. We are keen on adding our data source for Tableau.

**Comment by iqDF** [comment]
Or is there a way around this where Tableau team can help?

**Comment by VasanthiNeelagiri** [comment]
Hi, I am a new PM for the Connector SDK and I am looking at our feature backlog and getting things prioritized. I would appreciate if you can give your feedback for our product via this form. It should only take 2-5 mins but would be super valuable to our team. Thanks in advance!!
https://docs.google.com/forms/d/e/1FAIpQLSfs5OreNsxnva_uTO2vTxnoF-oq-37tEdrUpirUKwqud2Ib7g/viewform?usp=sf_link

**Comment by chiaradiamarcelo** [comment]
> Hi, I am a new PM for the Connector SDK and I am looking at our feature backlog and getting things prioritized. I would appreciate if you can give your feedback for our product via this form. It should only take 2-5 mins but would be super valuable to our team. Thanks in advance!! https://docs.google.com/forms/d/e/1FAIpQLSfs5OreNsxnva_uTO2vTxnoF-oq-37tEdrUpirUKwqud2Ib7g/viewform?usp=sf_link

cc @redcatbear

**Comment by KazimM-BQ** [comment]
Hi... Wanted to check if there are any updates on this? I have the Tableau Server running on Linux. But still cannot find any instructions on running TDVT on it.

**Comment by saugatt** [comment]
Please look at [this documentation ](https://tableau.github.io/connector-plugin-sdk/docs/tdvt#running-tdvt-test-with-tabquerytoolsrv-in-linux-server)on running TDVT test in linux environment.

**Comment by saugatt** [comment]
Closed this as resolved.
