### ISSUE TITLE
[FEATURE] Allow for customization of "Enter database name" in <database>

### ISSUE THREAD

**Issue by alismess-db** [tableau/connector-plugin-sdk#788]
**Is your feature request related to a problem? Please describe.**
The <database> entry might semantically stand for something other than a database (e.g. a catalog). Yet, in the dropdown menu "Enter database name" is hardcoded.

**Describe the solution you'd like**
Allow for the customization of "Enter database name".

**Describe alternatives you've considered**
None

**About You**
Name: Ali Smesseim
Company: Databricks

**Comment by jainam1995** [comment]
internal tracking id : 1268963

**Comment by rosswbrown** [comment]
This will be resolved as a part of the future Tableau 2021.4 release.
