### ISSUE TITLE
[BUG] Validation rules are not evaluated for default/initial value

### ISSUE THREAD

**Issue by alismess-db** [tableau/connector-plugin-sdk#789]
**Describe the bug**
The `validation-rule`s are not evaluated for the default/initial value. The makes it possible that invalid default values can be submitted in the connection dialog.

**Screenshots**

**Desktop (please complete the following information):**
 - OS: macOS Catalina
 - Tableau Version: 2021.1.1

**About you:**
 Name: Ali Smesseim
 Company: Databricks

**Comment by jainam1995** [comment]
internal tracking id : 1268965

**Comment by sxlin** [comment]
The connection dialog is designed to only validate a fields after the user inputs to the field.

However, I see the problem that invalid value could be passed through without validation.  We have decided to address the issue by two means,
1) In Connector packager to make sure default value is valid against the validation rule;
2) When the user click "Sign In" button, we will validate the fields user has bot changed. 

I have created the above items in our backlog.

**Comment by sxlin** [comment]
If you are using default value as placeholder to provide a hint, we are going to support placeholder in connection fields.

**Comment by alismess-db** [comment]
@sxlin currently the Databricks connector (for Tableau 2021.3) uses an invalid default value as placeholder. Does this change need to be reverted?

**Comment by sxlin** [comment]
@alismess-db Yes, it should be reverted.  The default value should be a valid value.

**Comment by sxlin** [comment]
@alismess-db I have created a feature to support placeholder for fields in our backlog.  I am closing this issue.  Please reopen it or create another issue if you have further questions.
