### ISSUE TITLE
Is it possible to create your own TDVT tests?

### ISSUE THREAD

**Issue by jayhomn-bitquill** [tableau/connector-plugin-sdk#793]
Just wondering if it is possible to create your own TDVT tests to check against other tables other than Calcs and Staples?

**Comment by jainam1995** [comment]
Currently we only support running against Calcs and Staples. We have work on expanding TDVT to run against custom schema in our backlog and plan to work on it in future releases

**Comment by jainam1995** [comment]
Internal tracking Id for the backlog work: 1201497

**Comment by jainam1995** [comment]
When the work is completed and this capability is added we will update the page : https://tableau.github.io/connector-plugin-sdk/news/ with this information . Closing this issue. Feel free to re-open if you have any more questions
