### ISSUE TITLE
StaplesDataTest actual and expected values diff

### ISSUE THREAD

**Issue by jayhomn-bitquill** [tableau/connector-plugin-sdk#794]
So after running the StaplesDataTests for correctness, my tests fails but when I check the diff files, it seemed like it was the ordering that was the problem. Is there a way to fix this? or am I interpreting it wrong and the data is actually incorrect?[](url)
[actual.setup.staples_data.employee_name_diff.txt](https://github.com/tableau/connector-plugin-sdk/files/6556157/actual.setup.staples_data.employee_name_diff.txt)
[actual.setup.staples_data.product_name_diff.txt](https://github.com/tableau/connector-plugin-sdk/files/6556158/actual.setup.staples_data.product_name_diff.txt)

PS: The data correctness tests for calc is fine

**Comment by jainam1995** [comment]
Internal tracking Id : 1273107

**Comment by jayhomn-bitquill** [comment]
I will close this issue since I think my actual dataset is missing some rows. Sorry for the confusion
