### ISSUE TITLE
How to check if one argument is missing is dialect function

### ISSUE THREAD

**Issue by rhtpandeyIN** [tableau/connector-plugin-sdk#797]
**About You:**
Name: Rohit Pandey
Company: HCL Technologies

**Your question:**
Hi, I have this (below) dialect function in my Connectot's dialect file.

`
<function group='operator' name='!=' return-type='bool'>
      **<formula>(%1<>%2)</formula>**
      <argument type='int' />
      <argument type='int' />
</function>
`

The above function works fine if we have both the values passed, but as soon as the second argument is 0 we get a syntax error (as we do not support such things). The second arg is 0 in cases where we are having tests like -> int(true) or int(false)

And, this is how we are converting bool to int:

`
<function group='cast' name='INT' return-type='int'>
      <formula>(CASE&#10;&#9;**WHEN %1** THEN 1&#10;&#9;**WHEN NOT %1** THEN 0&#10;&#9;ELSE NULL END)</formula>
      <argument type='bool' />
</function>
`

From the above syntax, "**WHEN %1**" and "**WHEN NOT %1**" are calling "!= function" with two args (%1 <> 0)

Solution what we want is if we have two integers then (%1 <> %2) is fine, but if we have (%1 <> 0) {mostly boolean to int conversion case} then it should only take (%1).

Please let me know if this is clear to understand.

Regards:
Rohit

**Comment by jainam1995** [comment]
Hi,
Were you able to find a base class from the list given https://tableau.github.io/connector-plugin-sdk/docs/dialect , to inherit from and also find the answer in the section relating to function maps on that same page ?

**Comment by jainam1995** [comment]
Closing issue. Feel free to open of you have more questions . Thanks !
