### ISSUE TITLE
How does the Tableau SDK set the catalog when a Catalog via Metadata Enumeration is selected?

### ISSUE THREAD

**Issue by ray-dremio** [tableau/connector-plugin-sdk#801]
**About You:**
Name: Ray Lum
Company: Dremio

**Your question:**
The Tableau SDK support Metadata Enumeration including Catalog. When a Catalog is selected, how does Tableau use that selected catalog information?
1. USE <database>
2. setCatalog

**Comment by raymond-lum** [comment]
Hoping someone is able to clarify the behaviour of this. Curious also if all tables are subsequently qualified with the catalog name and/or other impacts of the underlying implementation associated with this. Any feedback would be greatly appreciated.

**Comment by rosswbrown** [comment]
Hi Ray,

Connectors built with the Tableau Connector SDK do not call setCatalog or send a `USE <Catalog>` query.  The current design is connectors take the user selected Catalog, [Database](https://tableau.github.io/connector-plugin-sdk/docs/mcd#the-connection-metadata-file) in Tableau terminology, and pass it on the ODBC connection string or JDBC url/properties as appropriate.

This value can be retrieved via the `connectionHelper.attributeDatabase` [key](https://tableau.github.io/connector-plugin-sdk/docs/api-reference#connection-helper) in the connection builder/properties builder step.  It is also important to include `dbname` in the [connection normalizer](https://tableau.github.io/connector-plugin-sdk/docs/api-reference#connection-normalizer) as well if Database (Catalog) is supported.

I'll open an enhancement internally to improve our documentation clarity around this topic as well.  Thanks.
