### ISSUE TITLE
Can we implement something like the dialog "Variables and Input Parameters" of the connector of HANA?

### ISSUE THREAD

**Issue by carlossc** [tableau/connector-plugin-sdk#804]
**About You:**
Name: Carlos Santos Canelles
Company: Denodo Technologies

**Your question:**

We are using this SDK to develop a connector for Denodo. 

Can we implement something like the dialog *Variables and Input Parameters* of the connector of HANA? 

When connecting Tableau Desktop to a HANA calculation view which includes variables or parameters, Tableau Desktop displays the dialog *Variables and Input Parameters*. In this dialog, the user provides the values of these variables/parameters and then, Tableau queries this calculation view.

From a client application, Denodo behaves as a relational database but you can also define views in which it is mandatory to indicate a value. This is useful to force users to provide a value (e.g. the name of the customer) when querying a table that holds a billion rows.

### More background information

Tableau already has a connector for Denodo, which uses the PostgreSQL ODBC driver to connect to Denodo. This connector was added to Tableau 6 years ago.
We are developing a new connector that uses the JDBC driver of Denodo, which performs better than the PostgreSQL ODBC driver. In addition, we will have more control of the SQL dialect the connector uses.

**Comment by carlossc** [comment]
If this not possible, I can close this and create an enhancement request and hopefully, it gets upvoted by more partners.

**Comment by rosswbrown** [comment]
Currently that feature is specific to the SAP HANA connector and not available via the Connector SDK.  Please open a feature request with the details about your scenario so it can be considered as a potential future enhancement to the SDK.  Thanks.

**Comment by carlossc** [comment]
Thank you @rosswbrown. We will do that.
