### ISSUE TITLE
Different logical query configs for each tds file

### ISSUE THREAD

**Issue by jayhomn-bitquill** [tableau/connector-plugin-sdk#805]
Is it possible to run the logicalquerytests on multiple tds files each with a different logicalqueryconfig?

**Comment by pvanderknyff** [comment]
The TDS files are tied to a single datasource in TDVT and a single INI config file (for example, mydb.ini). If you want to test a different TDS file and/or a different logical query config, you need a new config file for that test (for example, mydb_test2.ini), and to add that as a datasource using the instructions on the [TDVT doc page](https://tableau.github.io/connector-plugin-sdk/docs/tdvt#test-a-new-data-source). Multiple TDVT tests can test the same connector. Let me know if that covers your use case.

**Comment by pvanderknyff** [comment]
Closing issue. Feel free to open a new issue if you still have questions.
