### ISSUE TITLE
Connecting Tableau Desktop to Custom JDBC

### ISSUE THREAD

**Issue by CassidyMountjoy** [tableau/connector-plugin-sdk#807]
**About You:**
Name: Cassidy Mountjoy
Company: Blockpoint Systems

**Your question:**
I'm building a tableau connector to connect to my custom data source. I have also built a JDBC (com.blockpoint.jdbc) to connect to this source, the JDBC is of type 4.  I am getting a "java.sql.SQLException: No suitable driver installed, or the URL is incorrect".

my JDBC implements both: 
- java.sql.DriverManager.getConnection(String url) 
- java.sql.DriverManager.getConnection(String url, Properties info)

What I really need help on is how to debug this issue. I've been recently using the logs (log.txt and jprotocolserver.log) to track my progress. For some reason I'm not getting a tabprotosrv.txt log. Is this normal?

Something seems to be erroring in the loadDriver method. This is coming up in my jprotocolserver.log:

![image](https://user-images.githubusercontent.com/43921118/123330634-1d617600-d4f3-11eb-92be-73b7f2110d66.png)

My jdbc url looks correct as well from my log.txt:
JDBCProtocol::JDBCProtocol Connection URL: jdbc:mdb://0.0.0.0:8080/master?

Here are my log files for reference:
[Logs.zip](https://github.com/tableau/connector-plugin-sdk/files/6712103/Logs.zip)

Any suggestions on further debugging this issue, or various things I should check?

**Comment by jainam1995** [comment]
Internal tracking Id : 1282824

**Comment by jie-d** [comment]
Hi @CassidyMountjoy, it is normal that you don't get the tabprotosrv.txt logs in this case, they are for ODBC connections. It's expected to only see log.txt and jprotocolserver.log files when the connections are JDBC-based.

In `JDBCDriverManager.loadDriver(String url)`, we are calling `java.sql.Driver.acceptsURL(String url)` to verify that the connection url is accepted by the driver so make sure that method is implemented by your driver. The error message you see usually implies that your driver has thrown a `SQLException` with SQL state `08001`.

We actually only use DriverManager to load drivers and not to get connections directly from it. The method we call to get the Connection object is `java.sql.Driver.connect(String url, Properties info)`.

Let me know if that helps, or if you have any more question!

**Comment by jie-d** [comment]
Closing responded issue - if you have any more question regarding this, please feel free to open a new one.
