### ISSUE TITLE
[BUG] Reprompts for user credentials when using OAuth

### ISSUE THREAD

**Issue by DSPAnthony** [tableau/connector-plugin-sdk#826]
**Describe the bug**

- We are using Tableau Desktop with a custom connector we created using Keycloak as an Identity provider.
- When publishing a workbook with an Embedded DataSource and the Prompt User, the publish action works successfully.
- When opening the published workbook from the Tableau server, it redirects to a sign-in page.
- At the sign-in page, neither selecting the Username nor entering new credentials is working (it returns 401 in the console)
- We must go to the DataSource and edit the connection to embed the user credentials.
- When opening the workbook with a different user, Tableau will let the different user see the data as the embedded user as long as the embedded user has a valid token from our Authentication provider. If this token expires, then it will give the different user the chance to create new credentials.
.

**Screenshots**
N/A

**Desktop (please complete the following information):**
 - OS: AWS Workspace (Windows Server 2016 Datacenter )
 - Tableau Version:  Tableau Server Version: 2021.2.0 (20212.21.0610.0336) 64-bit Windows

**About you:**
 Name: Anthony Margaritondo
 Company: Data Street Partners

**Comment by jie-d** [comment]
Internal tracking ID: 1295977

**Comment by DSPAnthony** [comment]
I edited my initial bug as I had the last step wrong.  "Different user" was meant to be "embedded user".

**Comment by jinli-dev** [comment]
@DSPAnthony Could you please attach the workbook you use for the test? I try to reproduce the case in my local environment.

**Comment by rosswbrown** [comment]
Closing issue. Please re-open if you're still seeing this issue.
