### ISSUE TITLE
OAuth Attribute List

### ISSUE THREAD

**Issue by DSPAnthony** [tableau/connector-plugin-sdk#827]
**About You:**
Name: Anthony Margaritondo
Company: Data Street Partners

**Your question:**
Does the Tableau connector support using OAuth and OpenID to retrieve an ID Token?  We would like to pass custom attributes back in an ID Token.  Also, is there a list of accepted attributes to can be returned?
I wanted to include a little more detail.  In the connectionResolver.tdr file the following attributes are automatically included:  ACCESSTOKEN, REFRESHTOKEN, access-token-issue-time, access-token-expires-in, CLIENTID, CLIENTSECRET, oauth-client, id-token(if any), instanceurl(if any).  Do you have a list of attributes that are allowed to be added to <required-attributes><attribute-list> section?

**Comment by jie-d** [comment]
Internal tracking ID: 1295981

**Comment by jinli-dev** [comment]
> Does the Tableau connector support using OAuth and OpenID to retrieve an ID Token? We would like to pass custom attributes back in an ID Token. Also, is there a list of accepted attributes to can be returned?

Yes, if the OAuth provider supports openid. For example, you may add 'openid' to 'scopes' and map the id_token (the response from idp) to 'id-token' in oauthConfig.xml (please see the example below). What the connector does here is just to add the scope to the request and map the returned id_token to 'id-token' (Tableau attribute name).

```
<?xml version="1.0" encoding="utf-8"?>
<pluginOAuthConfig>	 
    <dbclass>you_db_class</dbclass>
......
    <scopes>openid</scopes>
    <scopes>other_scope</scopes>
......
    <accessTokenResponseMaps>
        <entry>
            <key>ACCESSTOKEN</key>
            <value>access_token</value>
        </entry>
......
        <entry>
            <key>id-token</key>
            <value>id_token</value>
        </entry>
    </accessTokenResponseMaps>
</pluginOAuthConfig>
```

Right now, we only support getting username from id_token. BTW, What custom attribute do you want to get from id_token?

> I wanted to include a little more detail. In the connectionResolver.tdr file the following attributes are automatically included: ACCESSTOKEN, REFRESHTOKEN, access-token-issue-time, access-token-expires-in, CLIENTID, CLIENTSECRET, oauth-client, id-token(if any), instanceurl(if any). Do you have a list of attributes that are allowed to be added to section?

For OAuth, this list basically includes all required attributes (I guess you refer to https://tableau.github.io/connector-plugin-sdk/docs/oauth). If you really want to add a custom one, you probably need to change connectionFields.xml and connectionResolver.tdr files. Here has an example, https://github.com/tableau/connector-plugin-sdk/tree/master/samples/scenarios/multi_auth (please refer to 'v-username')
