### ISSUE TITLE
Smoke test failed

### ISSUE THREAD

**Issue by WuYR123** [tableau/connector-plugin-sdk#830]
**About You:**
Name:WuYR123
Company:AAS

**Your question:**
Tableau desktop 2021.2 &  TDVT 2.3.5
I executed C: \ tdvt \ connector plugin SDK \ tdvt \ tdvt_ Workspace > py - M tdvt.tdvt run postredodbc -- generate. After that, it is found that the smoke test is unsuccessful, as shown in the following figure:
![image](https://user-images.githubusercontent.com/87626601/127843790-02c2f328-8853-42e6-bb08-feed0ef987cb.png)

My postgresodb.ini is shown in the following figure:
![image](https://user-images.githubusercontent.com/87626601/127844111-7017a00b-56da-4b8c-9b2d-d0d46c6f92a0.png)

File tdvt_ log_ The contents of combined.txt are shown in the following figure:
![image](https://user-images.githubusercontent.com/87626601/127844488-026d15f9-f330-490c-8cea-7342bca26e25.png)
![image](https://user-images.githubusercontent.com/87626601/127845143-8f117d60-24fc-4b78-9de7-ff276e1e18be.png)

I can't find the cause of the problem in the log. Please help me have a look. Where do I need to adjust?

**Comment by lukewrites** [comment]
Hi,

Looks like a licensing issue, as you highlighted in the first screenshot. The log file deletion errors in the second screen shot are non-issues. Can you confirm that your install of Tableau Desktop is licensed to connect to Postgres?

Thanks,
Luke

**Comment by rosswbrown** [comment]
Feel free to reopen if this issue is still occurring
