### ISSUE TITLE
Missing authentication types when publishing a data source

### ISSUE THREAD

**Issue by nineinchnick** [tableau/connector-plugin-sdk#846]
**About You:**
Name: Jan Waś
Company: Starburst Data Inc.

**Your question:**
When I'm trying to publish a data source (or a whole workbook) with our custom connector, I cannot set any authentication types. Tableau Server seems to be using `Run As` but I need to test other authentication types too. Are there any requirements for the connector itself or is it something that needs to be configured in Tableau Server?

I'm using the latest version for both Tableau Server and Tableau Desktop, 2021.2.1 on Windows Server 2019, with AD.

![image](https://user-images.githubusercontent.com/795177/131707803-d2acafc5-d3ce-4cc2-b52b-f8f0b28cf9f8.png)

**Comment by devanshsoni9** [comment]
Hi Jan

When using AD/Kerberos for authentication on Tableau Desktop, to see all available authentication options in the publish dialog (Server Runas and Viewer Credentials), you have to include the capability `<customization name="CAP_AUTH_KERBEROS_IMPERSONATE" value="yes"/>` in the manifest.xml. 
This [jdbc sample](https://github.com/tableau/connector-plugin-sdk/tree/master/samples/scenarios/jdbc_kerberos) should provide you ideas about configuration which may need to be done for Kerberos authentication on server, however the `connectionProperties.js` depend on the driver which you are using to connect so feel free to adapt accordingly.

**Comment by nineinchnick** [comment]
I do have this capability in the manifest file. I compared with that sample project and got everything the same.

**Comment by devanshsoni9** [comment]
Can you double check the authentication option value is using `<option value="auth-integrated" label="Kerberos" />`, label can be different.

**Comment by devanshsoni9** [comment]
Also, please double check you have set the tsm configurations as mentioned on this [page](https://help.tableau.com/current/server-linux/en-us/kerberos_delegation.htm)

**Comment by nineinchnick** [comment]
Kerberos auth works in Tableau Desktop and Tableau Server after publishing the data source so yeah, I'm sure the value is `auth-integrated`. I've set all the options in Tableau Server and verified that with `tsm configuration get -k <name>`
