### ISSUE TITLE
TDVT Testing with OAuth tds files

### ISSUE THREAD

**Issue by jayhomn-bitquill** [tableau/connector-plugin-sdk#848]
**About You:**
Name: Jay
Company: Dremio

**Your question:**

Is there a way to embed OAuth credentials within the tds files that are going to be used for TDVT?

**Comment by jie-d** [comment]
Hi Jay, you can find the detailed how-to in our document [here](https://tableau.github.io/connector-plugin-sdk/docs/tdvt.html) (see step 5 in section 'Test a new data source'). Please let us know if you have more questions.

**Comment by jayhomn-bitquill** [comment]
Yep thanks for the response! 

So just to clarify, what would the .password file look like?

Like this?

database_name;{“ACCESSTOKEN” : “your_access_token”, “REFRESHTOKEN” : “your_refresh_token”}

or

{“ACCESSTOKEN” : “your_access_token”, “REFRESHTOKEN” : “your_refresh_token”}

**Comment by wangxinlei** [comment]
You will just need the json string for the token, the database_name part should not belong to the password file but instead the twb file itself. so it should look like this: {“ACCESSTOKEN” : “your_access_token”, “REFRESHTOKEN” : “your_refresh_token”}.
Note this will always issue a refresh request first and get a new accessToken so make sure your refreshtoken works fine.

**Comment by jayhomn-bitquill** [comment]
Thank you will give that a try
