### ISSUE TITLE
TabQueryCLI and TDVT support for running LINUX/UBUNTU based environment

### ISSUE THREAD

**Issue by iqDF** [tableau/connector-plugin-sdk#861]
**About You:**
Name: Daniel Kurniadi
Company: Bytedance

**Your question:**

I want to automate the TDVT tests for a Linux environment because we are launching a live cloud data warehousing product and want to onboard Tableau in it. We are keen in ensuring quality of our product for our Tableau user as well. Hence we want to automate the test for Tableau integration with our cloud data warehouse.

The execution of the TDVT requires the tabquerytool.exe tool, that at the moment comes only with the Tableau Desktop installation and it seems to be only available for Windows and not for Linux. 

Describe the solution you'd like
I would like to be able to execute the TDVT in a Linux environment, thus an equivalent of the tabquerytool.exe should be available for Linux, ideally delivered with Tableau Server for Linux. Can Tableau team help with it? Perhaps any way around for Linux environment that we can achieve through partnership?

Describe alternatives you've considered
I have considered starting a Windows VM in Linux, but currently it adds more cost to license a Windows VM or MacOS test server.

**Comment by jie-d** [comment]
Internal tracking ID: 1318697

**Comment by rosswbrown** [comment]
This request is being tracked by #782
