### ISSUE TITLE
Customizations from manifest.xml not being used

### ISSUE THREAD

**Issue by neosujoy** [tableau/connector-plugin-sdk#867]
Name: Sujoy Neogi
Company: Innominds

I am using tdvt to test a new connector for druid, i created a named connector, my dialect files are being picked up correctly and it fixes lot of issues, but the customizations i mention in the manifest.xml are not reflecting during query generation.
Don't see any error messages also. This is how manifest.xml looks. is this correct or anything missing?

<?xml version='1.0' encoding='utf-8' ?>

<connector-plugin class='druid_jdbc' superclass='jdbc' plugin-version='0.0.0' name='Druid JDBC' version='18.1' min-version-tableau='2019.4'>
  <vendor-information>
      <company name="Inno****"/>
      <support-link url="https://example.com"/>
      <driver-download-link url="https://drivers.example.com"/>
  </vendor-information>
  <connection-customization class="druid_jdbc" enabled="true" version="10.0">
    <vendor name="druid_jdbc"/>
    <driver name="Druid JDBC"/>
    <customizations>
      <customization name="CAP_CONNECT_CUSTOM_SQL_WITHOUT_SCHEMA" value="no" />
      <customization name="CAP_SUPPRESS_DISCOVERY_QUERIES" value="no" />    </customizations>
  </connection-customization>
  <connection-dialog file='connection-dialog.tcd'/>
  <connection-resolver file="connectionResolver.tdr"/>
  <dialect file='dialect.tdd'/>
</connector-plugin>

**Comment by neosujoy** [comment]
Specifically i wanted to use limit in place of top

      <customization name="CAP_SELECT_INTO" value="no" />
      <customization name="CAP_SELECT_TOP_INTO" value="no" />
      <customization name="CAP_QUERY_TOPSTYLE_LIMIT" value="yes" />
      <customization name="CAP_QUERY_TOPSTYLE_ROWNUM" value="no" />
      <customization name="CAP_QUERY_TOPSTYLE_TOP" value="no" />
      <customization name="CAP_QUERY_TOP_0_METADATA" value="no" />
      <customization name="CAP_QUERY_TOP_N" value="yes" />

i still top queries being generated and somehow i feel manifest file is not being read for customization as changing it does not have any effect

**Comment by jie-d** [comment]
Internal tracking id: 1320705

**Comment by rosswbrown** [comment]
The `CAP_QUERY_TOPSTYLE_LIMIT`, `CAP_QUERY_TOPSTYLE_ROWNUM`, and `CAP_QUERY_TOPSTYLE_TOP` are only relevant to the [Other ODBC](https://help.tableau.com/current/pro/desktop/en-us/odbc_capabilities.htm) and [Other JDBC](https://help.tableau.com/current/pro/desktop/en-us/jdbc_capabilities.htm) connectors.  

For example if your database used LIMIT as the row-limiting clause in Generic ODBC `CAP_QUERY_TOPSTYLE_LIMIT` would be set.  In a connector developed with the SDK this customization would be made in the [dialect definition file](https://tableau.github.io/connector-plugin-sdk/docs/dialect).  Example:
```
    <format-select>
      <part name='Select' value='SELECT %1' />
      <part name='From' value='FROM %1' />
      <part name='Where' value='WHERE %1' />
      <part name='Group' value='GROUP BY %1' />
      <part name='Having' value='HAVING %1' />
      <part name='OrderBy' value='ORDER BY %1' />
      <part name='Top' value='LIMIT %1' />
      <part name='TopPercent' value='LIMIT %1 PERCENT' />
      <part name='TopSamplePercent' value='LIMIT %1 PERCENT' />
      <part name='TopSampleRecords' value='LIMIT %1' />
    </format-select> 
```

Connectors based on the Tableau Connector SDK should use [this page](https://tableau.github.io/connector-plugin-sdk/docs/capabilities) as reference for the supported capabilities documentation.

**Comment by neosujoy** [comment]
Thanks , this works perfectly fine, however the link you pointed to does not clearly specify which of the CAP_* properties are only valid for "other JDBC", the ones i added were under the Query sub-section.

**Comment by rosswbrown** [comment]
All capabilities listed on the [Capabilities page](https://tableau.github.io/connector-plugin-sdk/docs/capabilities) are supported by the Connector SDK, though some are specific to an ODBC or JDBC connector only.  In general the CAP_QUERY_* ones listed apply to either.

There is some additional details on the [Design Considerations page](https://tableau.github.io/connector-plugin-sdk/docs/design#set-connector-capabilities) to highlight the most important ones to evaluate initially.

To answer a question about a specific capability we'll need some more specifics around it, and which other ones are also being used.
