### ISSUE TITLE
[BUG] Current database not being set

### ISSUE THREAD

**Issue by bpintea** [tableau/connector-plugin-sdk#874]
**Describe the bug**
Tableau allows metadata discovery, listing available catalogs/databases and the tables  underneath these. User can change between databases and choose the tables to query. When sending a query to the data source however, Tableau neither embeds the database in the query (like `SELECT ... FROM database.table`, with `.` being the catalog separator), nor sets this value through dedicated driver API calls (JDBC's [Connection#setCatalog()](https://docs.oracle.com/en/java/javase/17/docs/api/java.sql/java/sql/Connection.html#setCatalog(java.lang.String)) or ODBC's [SQLSetConnectAttr()](https://docs.microsoft.com/en-us/sql/odbc/reference/syntax/sqlsetconnectattr-function)/SQL_ATTR_CURRENT_CATALOG).

Having the driver take a default database (through a URL or connection string) as described in the [Catalog Hierarchy](https://tableau.github.io/connector-plugin-sdk/docs/metadata-enumeration)
 can be an additional functionality, but doesn't substitute the above, since the user can change the database to query _past_ the initial connection.

**Screenshots**
1. Listing all and choosing a current database
![1 a  Databases listing](https://user-images.githubusercontent.com/1562801/138241566-3a3298ed-f600-4632-8181-9b7213c7a036.jpg)

2. Choosing table(s) to query from current database
<img width="512" alt="1 b  Tables listing" src="https://user-images.githubusercontent.com/1562801/138241701-68327088-8f65-47a5-8a71-3ccab8f1d1e3.png">

3. Failure cause by the current catalog not being set (chosen table isn't in the default catalog). Note: "index" is an SQL table in Elastic's terminology.
<img width="512" alt="1 c  Failed query" src="https://user-images.githubusercontent.com/1562801/138241923-6357e330-04dd-4654-a022-cdef6c1165f5.png">

**Desktop (please complete the following information):**
 - OS: Windows 10.
 - Tableau Version: 2021.1

**About you:**
 Company: Elastic

**Comment by nineinchnick** [comment]
@rosswbrown I'm having the same issue. From the logs, it looks like Tableau does not open up a new connection after selecting a database. I do have `dbname` in the normalizer section. Could enabling `CAP_JDBC_QUERY_ASYNC` affect this?

In `jprotocolserver.log` I see one entry without any catalog:
```
 Connecting to jdbc:trino://local-server:8080/?
```
Then a few entries like this:
```
Start local request 473 /enumerateNames.
```

And then immediately an entry for the table I drag from the list:
```
Running query 
```

**Comment by nineinchnick** [comment]
Should I report it as a new issue?

**Comment by rosswbrown** [comment]
Hi @nineinchnick, Yes please report as a new issue and include the information specified in our [Bug Artifacts](https://tableau.github.io/connector-plugin-sdk/docs/bug-artifacts) page. Thanks.
