### ISSUE TITLE
How do I implement datetime creation with a SQL datatype of time?

### ISSUE THREAD

**Issue by CassidyMountjoy** [tableau/connector-plugin-sdk#876]
**About You:**
Name: Cassidy
Company: Blockpoint Systems

**Your question:**
I am writing a custom connector and have written a dialect file. My data source for my live connection has a column of type `TIME`. I know that Tableau doesn't support a time datatype and instead computes a `DATETIME` from the time column by adding the date `1899-12-30`.

When reading from `calcs.time1` (a time column), my generated sql looks like:
```
 SELECT HOUR(DATE((CAST('1899-12-30' AS DATE) + calcs.time1))) AS hr_time1_ok
 FROM testv1.calcs calcs
 GROUP BY HOUR(DATE((CAST('1899-12-30' AS DATE) + calcs.time1)))
```

- The `HOUR(DATE(` portion is correct for casting. 
- I am having trouble overriding the `CAST('1899-12-30' AS DATE) + calcs.time1)` portion of the statement.

When casting the string '1899-12-30' to a date, I expect tableau to hit my specified method:
```
<function group='cast' name='DATE' return-type='date'>
      <formula>DATE(%1)</formula>
      <argument type='str' />
</function>
```
Additionally, when attempting to converting the two to a datetime, I expected Tableau to hit my `MAKEDATETIME` method, using a date and a datetime:
```
    <function group='cast' name='MAKEDATETIME' return-type='datetime'>
      <formula>MAKE_DATETIME(DATE(%1), TIME(%2))</formula>
      <argument type='date' />
      <argument type='datetime' />
    </function>
```
[dialect.zip](https://github.com/tableau/connector-plugin-sdk/files/7463942/dialect.zip)

Something is not being overridden, and the connector must be reverting to the base dialect. 

-Is there something I'm not overriding for this type of datetime creation in my dialect file?

I've attached my dialect file.

**Comment by rosswbrown** [comment]
I believe that part of the query generated comes from a system function `TIME1899` defined in the dialects by default.

It can be customized by overriding the function with this definition. Below is the default, which I think is what you are seeing.
```
    <function group='system' name='TIME1899' return-type='datetime'>
      <formula>(CAST('1899-12-30' AS DATE) + %1)</formula>
      <argument type='datetime' />
    </function>
```

I'll make a note to include this in our documentation of the [dialect defaults](https://github.com/tableau/connector-plugin-sdk/blob/master/samples/components/dialects/SQLDialect.tdd),

You may also want to experiment with `CAP_QUERY_TIME_REQUIRES_CAST` [capability](https://tableau.github.io/connector-plugin-sdk/docs/capabilities) to see if that changes any of the queries that aren't being generated correctly.

**Comment by CassidyMountjoy** [comment]
Thanks for the response! I would have gotten nowhere without the function definition, once implemented my dialect worked as expected. Are there any other 'system' functions I should know about to ease future complications?

**Comment by rosswbrown** [comment]
There is one more `SYS_NUMBIN` ([tests](https://github.com/tableau/connector-plugin-sdk/search?q=SYS_NUMBIN&type=code)) that is defined as below by default:

```
    <function group='system' name='SYS_NUMBIN' return-type='int'>
      <formula>FLOOR(%1 / %2)</formula>
      <argument type='real' />
      <argument type='real' />
    </function>
```

As a part of documenting `TIME1899` we will audit for any additional system functions that are implicitly defined and include those as well. Thanks for raising this gap.
