### ISSUE TITLE
Tableau Dialect Definition File // Mapping of a function dependent on the version of the Denodo server

### ISSUE THREAD

**Issue by carlossc** [tableau/connector-plugin-sdk#877]
**About You:**
 Name: Carlos Santos Canelles
Company: Denodo Technologies

**Your question:**

In the _Tableau Dialect Definition File_ (.tdd file), can I define the mapping of a function to depend on the version of the Denodo server I am connecting?

Or maybe, to include two .tdd files in the .taco and that the connector chooses one or the other depending on the version of Denodo that the user is connecting to. Is this currently possible (or in the roadmap)?

### Our goal

Due to customer request, we are considering adding a function like `split_part(string text, delimiter text, field int)` to support the Tableau feature [Split a Field into Multiple Fields](https://help.tableau.com/current/pro/desktop/en-us/split.htm). Currently, Denodo does not have any function like `split_part` so our connector cannot support the "split field into multiple fields". If we add the function "split_part", we will only add it to the latest major version of Denodo (v8.0) but not to the previous one (v7.0) but we still want the connector to be compatible with both version 8.0 and 7.0.

We have other similar use cases raised by customers where we would also need to do something like this.

### Background Information

Tableau already has a native connector for Denodo, which uses the PostgreSQL ODBC driver to connect to Denodo. This connector was added to Tableau 6 years ago.

We have developed a new connector that uses the JDBC driver of Denodo, which performs better than the PostgreSQL ODBC driver. This new connector is already in the Tableau Gallery, in beta.

**Comment by jie-d** [comment]
Internal tracking id: 1343832

**Comment by carlossc** [comment]
@jie-d, is this currently possible? By reading the documentation of the SDK, it seems this is not possible. I just want to confirm that I understood the documentation correctly.
It would be great if this is possible in the future but right now, I just want to know if it is possible or not.

**Comment by VasanthiNeelagiri** [comment]
Hi Carlos, 

I am a Product Manager in the Connectivity team. This functionality is currently not possible. You read the documentation correctly. 

Thanks & Regards,
Vasanthi Neelagiri
Product Manager, 
Connectivity
