### ISSUE TITLE
[BUG] Connector dialog requires entering password if a custom authentication type is used

### ISSUE THREAD

**Issue by Yury-Fridlyand** [tableau/connector-plugin-sdk#883]
**Describe the bug**
There is `connection-fields.xml` (connection dialog v2):
```
<connection-fields>
    <field name="authentication" label="Authentication" category="authentication" value-type="selection" default-value="auth-user-pass">
        <selection-group>
            <option value="auth-none" label="No authentication"/>
            <option value="auth-user-pass" label="Username and Password"/>
            <option value="AWS_SIGV4" label="AWS_SIGV4"/>
        </selection-group>
    </field>
    <field name="server" label="Server" value-type="string" category="endpoint" default-value="localhost">
    </field>
    <field name="port" label="Port" value-type="string" category="endpoint" default-value="9200">
    </field>
    <field name="username" label="Username" category="authentication" value-type="string">
        <conditions>
            <condition field="authentication" value="auth-user-pass"/>
        </conditions>
    </field>
    <field name="password" label="Password" category="authentication" value-type="string" secure="true">
        <conditions>
            <condition field="authentication" value="auth-user-pass"/>
        </conditions>
    </field>
</connection-fields>
```
Tableau Desktop requests entering password of `AWS_SIGV4` authentication method. Actually, the password field isn't show (that's correct).
![image](https://user-images.githubusercontent.com/88679692/141242540-fa03ca21-a7c0-4172-bbda-593c24734940.png)

I had the same trouble using connection dialog v1. Unfortunately, I didn't keep the screenshot. `connection-dialog.tcd` was:
```
<connection-dialog class='XXX'>
  <connection-config>  
    <authentication-mode value='ComboBoxIntegrated' />
        <authentication-options>
            <option name="None" value="NONE" default="true" />
            <option name="Integrated" value="AWS_SIGV4" />
            <option name="UsernameAndPassword" value="BASIC" />
        </authentication-options>
    <port-prompt value="Port: " default="9200" />
    <has-databases value="false" />
    <has-schemas value="false" />
  </connection-config>
</connection-dialog>
```

**Desktop (please complete the following information):**
 - OS: Win 10
 - Tableau Version: 2021.3

**About you:**
 Name: Yury Fridlyand
 Company: Bit Quill

**Comment by pvanderknyff** [comment]
` <option value="AWS_SIGV4" label="AWS_SIGV4"/>` does not contain a valid value for `authentication`. The `authentication` attribute has meaning to the Tableau platform, and it must match one of the valid auth modes that the Tableau platform recognizes. You can see a list of supported authentication modes here: https://tableau.github.io/connector-plugin-sdk/docs/auth-modes

Based on the other information you provided, it seems like you're trying to set up Integrated Auth. For that, the value of `authentication` should be `auth-integrated`. (The label would remain AWS_SIGV4, so users would see that on the UI.) There are a few other steps you need to take to enable integrated auth. We have a sample for JDBC Kerberos that has a readme that goes through the steps for enabling integrated auth for an SDK connector: https://github.com/tableau/connector-plugin-sdk/tree/master/samples/scenarios/jdbc_kerberos. 

Let me know if you have any questions about the above.

**Comment by Yury-Fridlyand** [comment]
`auth-integrated` is not listed on the [official website](https://tableau.github.io/connector-plugin-sdk/docs/mcd).
Thank you for your reply. I will try following your advice.
Could you, please, update the website page and give there a bit more information what is supported and what isn't?

**Comment by pvanderknyff** [comment]
Seems like the list of auth modes in the Connection Dialog V2 page is incomplete. I'll look at linking that instead to the Supported Authentication Mode list that's on the main [Authentication Modes](https://tableau.github.io/connector-plugin-sdk/docs/auth-modes) doc page, which includes `auth-integrated`.

**Comment by pvanderknyff** [comment]
Opened a story on our internal backlog to track documentation update: 1347319. Closing this issue, please open a new one if you encounter a problem with integrated authentication.
