### ISSUE TITLE
Unexpected behavior for Staples table and a custom LogicalConfig

### ISSUE THREAD

**Issue by CassidyMountjoy** [tableau/connector-plugin-sdk#889]
**About You:**
Name: Cassidy Mountjoy
Company: Blockpoint Systems

**Your question:**
When configuring my logical config I was having an issue with converting column names to lower case. I found myself needing to create a custom one, which I defined as  
```
[LogicalConfig]
Name = bsql_logical_query
fieldnameLower_underscore = True
tablename = $dsName
tablePrefix = [testv1].
```
This worked beautifully for the `calcs` table and I'm passing the majority of the tests... As far as the `staples` table, not so much. I can't get past the smoke tests because of a column name mismatch, due to upper case columns not matching my lower case in the database. It seems like my logical config is only being applied to `calcs`?
I only say this because I fixed this issue in calcs by adding the logical config but it didn't fix the issue in staples.

Here's my current smoke test error in `staples`, an upper/lowercase mismatch:
![image](https://user-images.githubusercontent.com/43921118/142509983-4ac3620b-80d7-48e6-84d9-e8b258fb18ae.png)

My tds file has lower case names as well:
![image](https://user-images.githubusercontent.com/43921118/142510494-2f25f011-9621-4983-a34a-b72a6009e046.png)

Any help or insight into this would be greatly appreciated, thanks!

**Comment by lukewrites** [comment]
Hi, @CassidyMountjoy, this is a known issue; I'll create a story to fix it.

**Comment by CassidyMountjoy** [comment]
Gotcha, @lukewrites, any temporary fix I can do to workaround this issue?

**Comment by lukewrites** [comment]
@CassidyMountjoy I don't think there is, unfortunately, but I took the story in the current sprint so I'm hoping to have a fix pushed soon.

**Comment by lukewrites** [comment]
@CassidyMountjoy Sorry I completely forgot to say in the above that you could just skip the smoke tests for now and look at how logical tests against `Staples` do.

**Comment by jie-d** [comment]
Internal tracking id: 1348597

**Comment by lukewrites** [comment]
Hey @CassidyMountjoy would you mind pulling down `master` and checking out to the `make-staples-smoke-logical` branch (I named it in a hurry 😬) to see if that will fix things? 

I'd recommend trying:

```
$ python -m tdvt.tdvt action --generate
$ python -m tdvt.tdvt run <your_ds> --verify
```

Thanks.

**Comment by CassidyMountjoy** [comment]
Thanks @lukewrites , after pulling and navigating to the `make-staples-smoke-logical` and running `python -m tdvt.tdvt --generate` I'm getting unexpected behavior. Looks like my `.ini` file is no longer valid, my console is relentlessly printing like some of the parameters in my logical config (I'm using the logical config I specified above) are no longer optional. I tried this on master as well and got the same response. Is this an update to the sdk that isn't in the docs yet?
![image](https://user-images.githubusercontent.com/43921118/144271834-611e2f3b-1453-4c8a-9902-f5827029c62c.png)

**Comment by CassidyMountjoy** [comment]
After further investigation, I had updated TDVT to version 2.4. After switching back to 2.3.1 and I was able to generate the tests, without the failing logical config.

**Comment by lukewrites** [comment]
That's a bug that has a PR (#893) that will merge today. 

It's actually lying to you - configs are fine, and tests _should_ run after it's done console logging a million lines of fake news. Apologies for the mess on the command line.

**Comment by lukewrites** [comment]
@CassidyMountjoy #893 merged and I pulled `master` into my branch, if you'd like to give it a try. Should no longer see that logging mess.

**Comment by CassidyMountjoy** [comment]
Thanks @lukewrites I just pulled from your branch got the updated changes, moved back on tdvt 2.4.0, but still having the same logging issue as before.

**Comment by lukewrites** [comment]
I merged commits to master (2.5.0) that I think will fix this for you. If they don't fix this please re-open.

**Comment by CassidyMountjoy** [comment]
Started using v2.5.0, also changed branches to the `make-staples-smoke-logical`. The logging issue was solved. As far as the smoke tests, I did have to add the following to my ini file to get the smoke tests to work `tablenameLower = True` but I was able to pass the smoke tests, thanks for the help.

**Comment by lukewrites** [comment]
Glad to hear it!
