### ISSUE TITLE
TDVT dialect 

### ISSUE THREAD

**Issue by yotams-commit** [tableau/connector-plugin-sdk#891]
Hi, 

I'm running TDVT and would like to modify some queries.
Can you please tell me where I can change the SQL statement of the tests?

**Comment by jie-d** [comment]
Internal tracking id: 1349240

**Comment by rosswbrown** [comment]
The SQL statements generated by the connector during the TDVT tests are a result of the connector definition. Please see the [Connector Design Considerations](https://tableau.github.io/connector-plugin-sdk/docs/design) and [Create a Tableau Dialect Definition File](https://tableau.github.io/connector-plugin-sdk/docs/dialect) for more information on how a connector is defined.

Feel free to open another issue if you have a question about a specific TDVT test or dialect function.  The type of information described [here](https://tableau.github.io/connector-plugin-sdk/docs/bug-artifacts) is helpful in prioritizing these issues. Thanks.
