### ISSUE TITLE
Date formats

### ISSUE THREAD

**Issue by guiangumpac** [tableau/connector-plugin-sdk#892]
Hi,

I am currently working on TDVT testing and there are test cases where the date format of the date is `m/d/y` which seems to get converted to `y-m-d` in the queries. I was hoping to use `CAST(DATE_FORMAT( %2, &apos;%Y-%m-%d 00:00:00&apos;) AS TIMESTAMP)` in the dialect for converting date to datetime. This would only work if we can assume that all date formats from Tableau will be converted to `y-m-d` for OpenSearch. Are there cases in which there will be a date where the format from Tableau would not be converted to `y-m-d`?

Test case:
![image](https://user-images.githubusercontent.com/90278068/143070842-1303f87a-a8b8-479f-9397-8d0e460aff3d.png)

Query:
![image](https://user-images.githubusercontent.com/90278068/143070944-a342e2df-3a2e-469b-90e2-2fe380d5444f.png)

**Comment by jie-d** [comment]
Internal tracking id: 1349241

**Comment by rosswbrown** [comment]
The test case described, `date0 == #7/4/1972#`, will invoke the [Date Literal Support](https://tableau.github.io/connector-plugin-sdk/docs/dialect#date-literal-support) within the dialect.

By default this is defined for Date and DateTime types:
```
<format-date-literal formula="%1" format='yyyy-MM-dd' />
<format-datetime-literal formula="%1" format='yyyy-MM-dd HH:mm:ss' />
```

> The `formula` attribute uses the token `%1` to insert the formatted date string. The `format` attribute describes the database’s accepted string format for date literals, using [ICU Date/Time format syntax](https://unicode-org.github.io/icu/userguide/format_parse/datetime/#datetime-format-syntax).


In one of the [example dialects](https://github.com/tableau/connector-plugin-sdk/blob/master/samples/components/dialects/SQLDialect.tdd#L145) a more advanced definition is shown:
```
<format-date-literal formula="TO_DATE('%1', '%2')" format='yyyy-MM-dd' />
<format-datetime-literal formula="TO_TIMESTAMP('%1', '%2')" format='yyyy-MM-dd HH:mm:ss' />
```

The `%2` argument will insert the database's accepted tokens as transformed from the ICU token definition in the `format` attribute. The transform is defined by the `icu-date-token-map` element ([example](https://github.com/tableau/connector-plugin-sdk/blob/master/samples/plugins/postgres_jdbc/dialect.tdd#L1145)).
```
<icu-date-token-map>
  ...
  <token key="yyyy" value="YYYY" /> <!-- year (1996) -->
  ...
  <token key="MM" value="MM" />     <!-- month in year (09) -->
  ...
</icu-date-token-map>
```

I would also recommend checking any Date or DateTime literals explicitly defined within the `<function>` element's `<formula>`s to ensure those meet the database's desired Date and DateTime format. Sometimes they are found in the `group='cast'` functions and [TIME1899](https://github.com/tableau/connector-plugin-sdk/blob/master/samples/components/dialects/SQLDialect.tdd#L51).

**Comment by rosswbrown** [comment]
Please reopen if this did no answer your question, thanks.

**Comment by BentsiLeviav** [comment]
Hi @rosswbrown 
I know this one is being closed, but I have a question related to this matter.
In my ClickHouse dialect, I have these settings configured:
```
<format-date-literal formula="DATE '%1'" format='yyyy-MM-dd' />
<format-datetime-literal formula="TIMESTAMP '%1'" format='yyyy-MM-dd HH:mm:ss' />
```
In the given test case, the passed date string is not being transformed correctly:

![image](https://github.com/tableau/connector-plugin-sdk/assets/46030906/cf533508-498d-4ae3-a1df-7c98db8b3209)

The test case includes this date `#4/12/2010#` with the format of `MM/dd/yyyy`, but the generated SQL creates the date `2010-12-04` with the format of `yyyy-dd-MM` even though `format-date-literal formula` is set to `'yyyy-MM-dd' `

Could you please advise on this? Did I miss something?
