### ISSUE TITLE
JDBC Athena + AzureAD not working after MFA

### ISSUE THREAD

**Issue by melquic** [tableau/connector-plugin-sdk#894]
Hi, I have a custom connector that uses Athena's JDBC driver to authenticate to AzureAD and assume a role in AWS Athena. Everything was working fine until the IT team enabled MFA in Azure AD.
Athena's JDBC driver supports MFA via browser authentication, but I understand this would not be an option as it would not work on Tableau Server.
I would like to know if anyone has already gone through this problem, and what was the solution adopted.
Thanks.

Name: Melqui de Carvalho
Company: Five Acts

**Comment by jie-d** [comment]
Internal tracking id: 1349942

**Comment by sidwray** [comment]
Correct.  On Server, the driver is not able to present the default browser window to the user (client).  Native Tableau connects that support OAuth use a native service. We are working on extending this to federated auth scenarios in AWS.  Would you mind sharing a link to the repo for your connector or send the files to us as an example to see what is working for some customers?

**Comment by jie-d** [comment]
Closing and please feel free to open a new one if you have any more questions.
