### ISSUE TITLE
Customized attributes do not wrok

### ISSUE THREAD

**Issue by OOOOOwenXu** [tableau/connector-plugin-sdk#904]
**About You:**
Name: Owen Xu
Company:Webank, shenzhen, China.

**Your question:**
I tried to develop my own Tableau connector following the instructions on https://tableau.github.io/connector-plugin-sdk/docs/ui. Everything works fine if I do not add customized vendor-attributes in connection-dialog.tcd. However, I want to show additional customized boxes and allow user to input value to these boxes. The following is the shortcut of my code.
![image](https://user-images.githubusercontent.com/25920664/145352594-86d16209-8a97-489c-a6ed-9a8fe8493064.png)

I am using the version of 2019.4 Tableau DeskTop.
[linkis_jdbc.zip](https://github.com/tableau/connector-plugin-sdk/files/7683050/linkis_jdbc.zip)

**Comment by pvanderknyff** [comment]
Hi Owen, it looks like you're using the Connection Dialog V1 framework. This framework does not allow for arbitrary custom attributes, we have three customizable attributes (vendor1, vendor2, and vendor3) that can have their name changed in the UI. This is documented here: https://tableau.github.io/connector-plugin-sdk/docs/ui#define-custom-vendor-attributes.

However, we recommend using [Connection Dialog V2](https://tableau.github.io/connector-plugin-sdk/docs/mcd). This framework allows for the creation of arbitrary custom attributes that appear on the UI, and gives the connector author a lot more control over what appears on the UI. [This section](https://tableau.github.io/connector-plugin-sdk/docs/mcd#vendor-defined) talks about adding custom attributes to Connection Dialogs V2. [Our sample connectors ](https://github.com/tableau/connector-plugin-sdk/tree/master/samples/plugins/postgres_jdbc) also use Connection Dialogs V2 and can be used as a starting point.

Connection Dialogs V2 was added in Tableau 2020.3, I see you're using 2019.4. That version of Tableau is fairly old at this point and is no longer receiving updates, it's highly recommended to upgrade to a later version for connector development.
