### ISSUE TITLE
Enable cross-join

### ISSUE THREAD

**Issue by eli-jethro** [tableau/connector-plugin-sdk#906]
**About You:**
Name: Eli Singer
Company: Jethro Data

**Your question:**
We're receiving queries in the format of:
... JOIN (select ....) ON 1 = 1;

This seems to be a workaround in case the target DB doesn't support CROSS JOIN.

As we do support CROSS K+JOIN, Is there a way to have the connector actually produce a CROSS JOIN syntax:
... CROSS JOIN (select ...) ;

Thanks, eli

**Comment by jie-d** [comment]
Internal tracking id: 1355164

**Comment by rosswbrown** [comment]
Validating `CROSS JOIN` is a scenario covered as a part of the [LODTests](https://tableau.github.io/connector-plugin-sdk/docs/tdvt#lodtests) TDVT test suite.

Running the [lod.1_Difference From with Cross Join](https://github.com/tableau/connector-plugin-sdk/blob/master/tdvt/tdvt/logicaltests/generate/input/lod/setup.lod.1_Difference%20From%20with%20Cross%20Join.xml) test with the [postgres_jdbc](https://github.com/tableau/connector-plugin-sdk/tree/master/samples/plugins/postgres_jdbc) sample connector I observe this query generated in the logs:

```
   SELECT "Staples"."Customer Name" AS "Customer Name",
     CAST( (12 * EXTRACT(YEAR FROM CAST("Staples"."Order Date" AS TIMESTAMP)) + EXTRACT(MONTH FROM CAST("Staples"."Order Date" AS TIMESTAMP))) - (12 * EXTRACT(YEAR FROM CAST("t0"."__measure__0" AS TIMESTAMP)) + EXTRACT(MONTH FROM CAST("t0"."__measure__0" AS TIMESTAMP))) AS BIGINT) AS "LOD - Fixed - 2 (copy)",
     SUM("Staples"."Sales Total") AS "sum:Sales Total:ok"
   FROM "Staples"
     CROSS JOIN (
     SELECT MIN("Staples"."Order Date") AS "__measure__0"
     FROM "Staples"
     HAVING (COUNT(1) > 0)
   ) "t0"
   GROUP BY 1,
     2
```

I don't see the `ON 1 = 1` being applied in this simple case. Perhaps you can provide more specifics to when you see this occur.

One way this could happen is if your connector's dialect is using one of the [built-in dialects](https://tableau.github.io/connector-plugin-sdk/docs/design#choose-a-dialect) as the `base` in the dialect definition. Its possible one of those is forcing that syntax in all cases.

**Comment by rosswbrown** [comment]
Please reopen if this did no answer your question, thanks.

**Comment by eli-jethro** [comment]
I'm unable to reopen, but below is an example of a query we're receiving.



SELECT 'Click here for books in Benchmarking' AS "Calculation_1117174228432035874",
       'Total Transfer-Out' AS "Time Window Count (copy 2)_1841690783775662081",
       IFNULL("t2"."usr:Benchmark Title (copy)_2015923792277975048:ok",0) AS "usr:Benchmark Title (copy)_2015923792277975048:ok"
FROM ((SELECT 1 AS "one"
       FROM ("def_schema"."_sec" AS "_sec"
         LEFT OUTER JOIN (SELECT COUNT(DISTINCT CASE WHEN CONCAT (CONCAT 
		                                                           (CASE WHEN "_data"."ALT_book_NAME" IS NULL 
																         THEN ' '  ELSE "_data"."ALT_book_NAME" END,'- '),
		                                                            CASE WHEN "_data"."xyz_TYPE" IS NULL THEN 'Keep Checked' 
																	     WHEN "_data"."xyz_TYPE" = 'Two-xyz' THEN 'Two xyz' 
																		 WHEN "_data"."xyz_TYPE" = 'Four-xyz' THEN 'Four xyz' 
																		 ELSE NULL END) != '' THEN "_data"."ALT_OPEID" ELSE NULL END) AS "__measure__0"
                          FROM ("rdm_pdp_rpt"."_data" AS "_data"
                            INNER JOIN "def_schema"."_sec" AS "_sec"
                                    ON ("_data"."book_CODE" = "_sec"."PSE_book_ORG_OPEID"
                                   AND "_data"."book_BRANCH" = "_sec"."PSE_ORG_BRANCH_CD"))
                          WHERE 'USGTEST' = "_sec"."USER_LOGIN"
                          HAVING COUNT(1) > 0) AS "t0" 
				ON 1 = 1
			)
       WHERE ('USGTEST' = "_sec"."USER_LOGIN" AND IFNULL("t0"."__measure__0",0) >= 5)
       HAVING COUNT(1) > 0
	   ) AS "t1" 
     LEFT OUTER JOIN (SELECT COUNT(DISTINCT CASE WHEN CONCAT (CONCAT (CASE WHEN "_data"."ALT_book_NAME" IS NULL 
	                                                                       THEN ' ' ELSE "_data"."ALT_book_NAME" END,'- '),
                                                                      CASE WHEN "_data"."xyz_TYPE" IS NULL THEN 'Keep Checked' 
			  													           WHEN "_data"."xyz_TYPE" = 'Two-xyz' THEN 'Two xyz' 
																	       WHEN "_data"."xyz_TYPE" = 'Four-xyz' THEN 'Four xyz' 
																	       ELSE NULL END)
  											   != '' THEN "_data"."ALT_OPEID" ELSE NULL END
								   ) AS "usr:Benchmark Title (copy)_2015923792277975048:ok"
                        FROM ("rdm_pdp_rpt"."_data" AS "_data"
                        INNER JOIN "def_schema"."_sec" AS "_sec"
                                ON ("_data"."book_CODE" = "_sec"."PSE_book_ORG_OPEID"
                                AND "_data"."book_BRANCH" = "_sec"."PSE_ORG_BRANCH_CD")
							  )
                       WHERE 'USGTEST' = "_sec"."USER_LOGIN"
                       HAVING COUNT(1) > 0
		  	         ) AS "t2" 
	ON 1 = 1)

**Comment by eli-jethro** [comment]
I was able to narrow down the issue and provide a step-by-step recreation. It seems to occur when the data source is not a single table but a relationship of two tables.

Please see the attached:
1. problem description and recreation
2. twb of a single table
3. twb of same report but with two tables

https://drive.google.com/drive/folders/14o5ZU4NnZgKPTis13FkHcW4-Lgi1-3q6?usp=sharing

Thanks, eli

**Comment by rosswbrown** [comment]
Thanks for the detailed write-up and repro steps. I'm able to observe the same behavior with the built-in Tableau PostgreSQL connector.  We'll be investigating to see what options there are for addressing this case.

**Comment by rosswbrown** [comment]
We have a [capability](https://tableau.github.io/connector-plugin-sdk/docs/capabilities#query) `CAP_QUERY_OUTER_JOIN_CONDITION_NO_TRIVIAL` that when enabled in our testing seems to address this use case.  It was added for connectors that aren't able to support trivial ON conditionals, like `1 = 1`, in OUTER JOIN scenarios.

It will not generate a CROSS JOIN like the single table LOD use case, but that aspect is by design since a [Relationship](https://help.tableau.com/current/server/en-us/datasource_relationships_learnmorepage.htm) between tables is defined.

When testing using a Join instead of a Relationship between two tables it does appear to generate the CROSS JOIN expected as well.

**Comment by rosswbrown** [comment]
Please add a note if you'd like to see this issue reopened, thanks.
