### ISSUE TITLE
Minimum requirements for custom connector submission

### ISSUE THREAD

**Issue by RafsanMazumder** [tableau/connector-plugin-sdk#915]
**About You:**
Name: Rafsan Mazumder
Company: ByteDance / Tiktok

**Your question:**
Currently our testcases passing rate for custom connector is > 90%. The failing testcases include required testcases, as our datasource does not support all the functionalities yet. 

According to this document, https://tableau.github.io/connector-plugin-sdk/docs/gallery-submission, we are supposed to pass >90% to be eligible for connector submission. Is there any additional requirement? (For example, do we need to pass all the required testcases?)

**Comment by VasanthiNeelagiri** [comment]
Hi Rafsan Mazumder,

I am the Product Manager on the Connectivity Team here at Tableau. Glad to hear that your test passing rate is >90%. If your datasource does not support certain functionality, thats okay. Our Dev team can review and decide on the next steps.

I would suggest your team to please fill this form - 
[Submit a Connector to Tableau Exchange via Google Tables](https://tables.area120.google.com/u/0/form/aazkn9dCirC305k3Czjkoa/t/aTDxX-eQDxddDrdwaKi4X18Wrn9R7TiQQ9mm_2PBJkUtb2RwGj3__s5bdc0rDX6_c0) or reach out to our Tech Partner Team - technologypartners@tableau.com regarding the next steps. 

Let me know if you have any other questions. 

Thanks & Regards,
Vasanthi Neelagiri,
Product Manager, Connectivity
