### ISSUE TITLE
Protocol [x] is unavailable 

### ISSUE THREAD

**Issue by AbdallaElabasery** [tableau/connector-plugin-sdk#931]
**About You:**
Name: Abdullah Elabasery
Company: Incorta

random error saw in the tdvt result  is protocol [x] is unavailable where x is the protocol number , so what does this error mean ?

**Comment by jie-d** [comment]
Hi @AbdallaElabasery,  can you share with us the log files where this error was seen? The files should contain names like jprotocolserver or stdout_jprotocolserver and [this article](https://kb.tableau.com/articles/howto/sending-desktop-logs) should be able to help you locate them. There are a few potential causes that can lead to this error and we will need the information from the logs to further identify.

**Comment by jie-d** [comment]
Hi @AbdallaElabasery, other than the page I linked above for log collection. It would greatly help us investigate if you can follow this [page](https://tableau.github.io/connector-plugin-sdk/docs/bug-artifacts) to share a few other artifacts with us. Thanks!

**Comment by jie-d** [comment]
Hi @AbdallaElabasery, just wanted to follow up and see if there might be any update on your end?

**Comment by jie-d** [comment]
Hi @AbdallaElabasery, just a kind note that I'll be closing this issue tomorrow if we haven't heard anything by then. If you have any further update feel free to comment on the issue and we can certainly look into it again. Thanks!

**Comment by jie-d** [comment]
Closing as no logs received.
