### ISSUE TITLE
Kerberos authentication Service Account Access issue in CentOS 7 

### ISSUE THREAD

**Issue by hovaesco** [tableau/connector-plugin-sdk#933]
**Describe the bug**
Trying to set up Kerberos Run as a Service Account in Tableau Server 2021.4.3 on CentOS 7. I'm using Starburst connector with Starburst ODBC driver. 

I followed the instruction from here: https://help.tableau.com/current/server-linux/en-us/kerberos_runas_linux.htm

Unfortunately, it fails during authentication phase. I'm getting below error from the driver: 
```
gss_init_sec_context() failed: SPNEGO cannot find mechanisms to negotiate.
Mar 21 16:12:44.836 ERROR 562018048 Simba::ODBC::Statement::SQLPrepareW: [Starburst][Trino] (2010) Authentication or authorization error occurred
```

It works well on Tableau Desktop, Tableau Server on Windows, unixODBC, using Service Account user in PyODBC and every other scenario other than on Tableau Server on CentOS 7. 

**Desktop (please complete the following information):**
 - OS: CentOS 7
 - Tableau Version: Tableau Server 2021.4.3 

**About you:**
 Name: Przemek Denkiewicz
 Company: Starburst

**Comment by VasanthiNeelagiri** [comment]
Hi Przemek,

Thanks for letting us know. Unfortunately, we are not supporting ODBC based Connectors. Connectors built using the ODBC Drivers will not be allowed into Tableau Exchange. Our docs also should reflect this soon.

Thanks & Regards,
Vasanthi Neelagiri,
Product Manager,
Tableau
