### ISSUE TITLE
[BUG] Can't run Prep flow on Tableau Server

### ISSUE THREAD

**Issue by artshevchenko** [tableau/connector-plugin-sdk#936]
When non-native connector used to retrieve data by Prep, Prep Conductor can't run flow. The error message is:

*Failed to connect to “”. Check that the connection is available or in the Connections tab, click Edit to check the required fields and credentials.*

<img width="960" alt="Screenshot 2022-03-23 at 16 05 04" src="https://user-images.githubusercontent.com/9002056/159707700-75af6d68-a71b-488f-8a87-7569593a1038.png">

In the "Edit Connection" window I can pass connection test successfully:
<img width="986" alt="Screenshot 2022-03-23 at 16 17 49" src="https://user-images.githubusercontent.com/9002056/159708706-ec4360c5-cbb6-4071-b248-45e326d9bbb0.png">

Connector works perfectly, I can see data preview when open flow in Web Edit on Tableau Server:
<img width="1432" alt="Screenshot 2022-03-23 at 16 09 38" src="https://user-images.githubusercontent.com/9002056/159709633-560d1d25-9034-40ea-8570-17b9b6f273b6.png">

You can get more info [here](https://github.com/analytikaplus/clickhouse-tableau-connector-jdbc/issues/29)

**Environment:**
 - OS: CentOS 7
 - Tableau Server Version:  2021.3.3 (20213.21.1018.0949) 64-bit Linux

**About you:**
 Name: Artem Shevchenko
 Company: ANALYTIKA PLUS

**Comment by PCbIX** [comment]
+1, we can't work propertly whithout clickhouse connector in our jobs

**Comment by pvanderknyff** [comment]
For Prep on Server, make sure the .taco file is added to the following directories:
- Tableau Prep Conductor: [Tableau_Server_Installation_Directory]/data/tabsvc/flowprocessor/Connectors
- Tableau Flow Web Authoring: [Tableau_Server_Installation_Directory]/data/tabsvc/flowqueryservice/Connectors

As well as the folder for general Tableau Server (though from the bug description you likely have that installed correctly):
- Tableau Server: [Tableau_Server_Installation_Directory]/data/tabsvc/vizqlserver/Connectors

Let me know if adding the taco to the above fixes the issue. I think our documentation in this area is incomplete, I'll update them accordingly.

**Comment by PCbIX** [comment]
```
root@tableau-b-1:/opt/tableau/tableau_connectors# ls -lh
total 24K
-rwxr-xr-x 1 root root 21K Feb  1 17:06 clickhouse_jdbc_0.2.2.taco
```
```
root@tableau-b-1:/opt/tableau/tableau_connectors# ls -lh /var/opt/tableau/tableau_server/data/tabsvc/vizqlserver/Connectors/
total 24K
-rwxr-xr-x 1 root root 21K Apr  4 08:45 clickhouse_jdbc_0.2.2.taco
```
```
root@tableau-b-1:/opt/tableau/tableau_connectors# ls -lh /var/opt/tableau/tableau_server/data/tabsvc/flowprocessor/Connectors/
total 24K
-rwxr-xr-x 1 root root 21K Apr  4 08:44 clickhouse_jdbc_0.2.2.taco
```
The same issue: `1 error
Failed to connect to “”. Check that the connection is available or in the Connections tab, click Edit to check the required fields and credentials.`

**Comment by pvanderknyff** [comment]
I'm not 100% sure that Prep honors the connect_plugins_path directory from the native api, that may be your issue. It's mainly intended for testing in-development connectors. There are 2 options for Server setup [here](https://tableau.github.io/connector-plugin-sdk/docs/run-taco), we prefer the first one, though it doesn't have the Prep folders at the moment. I have documentation changes in flight, for now try adding your connectors to the following directories and restart your server:
    - Tableau Server: `[Tableau_Server_Installation_Directory]/data/tabsvc/vizqlserver/Connectors`
    - Tableau Prep Conductor: `[Tableau_Server_Installation_Directory]/data/tabsvc/flowprocessor/Connectors`
    - Tableau Flow Web Authoring: `[Tableau_Server_Installation_Directory]/data/tabsvc/flowqueryservice/Connectors`

Let me know if the connector still has problems with Prep after adding the taco file to the above directories.

**Comment by artshevchenko** [comment]
@pvanderknyff Hi! It seems that the correct list of directories to install the connector is as follows:

- `[Tableau_Server_Installation_Directory]/data/tabsvc/vizqlserver/Connectors/`
- `[Tableau_Server_Installation_Directory]/data/tabsvc/flowprocessor/Connectors/`
- `[Tableau_Server_Installation_Directory]/data/tabsvc/flowqueryservice/Connectors/` *(if directory exists)*
- `[Tableau_Server_Installation_Directory]/data/tabsvc/flowminerva/Connectors/` *(if directory exists)*

Thank you for your help!

**Comment by pvanderknyff** [comment]
@artshevchenko I'm glad you were able to resolve your issues with Prep Conductor! I'll make sure the documentation is updated correctly with your findings. I'll do some testing on my side, but did you find that adding the taco file to flowminerva was necessary to unblock the Prep Conductor scenario, or was that to unblock a different scenario? Thanks!

**Comment by artshevchenko** [comment]
@pvanderknyff In version 2022.1 we did not find `flowqueryservice`. Obviously, the process could not evaporate, so we were looking for another process that has a Connectors directory. `flowminerva` turned out to be such a process. Apparently in new releases `flowminerva` performs `flowqueryservice` tasks. The author of the issue in our repository confirmed the operability of the solution described above

**Comment by pvanderknyff** [comment]
Thanks for confirming, that's helpful information. I'll continue working to fix/improve our documentation surrounding this scenario.

**Comment by PCbIX** [comment]
Hi. After removing native_api.connect_plugins_path, moving all taco files to directories listed above and restarting server all works perfect, Thanks.

**Comment by pvanderknyff** [comment]
@artshevchenko @PCbIX 

Just a heads up, spurred by this issue we're modifying our recommendations for installing tacos on server to use a previously undocumented option. The method you used is still an option and will continue to be supported, so no action is needed, but if you have troubles again you can add tacos to the following directory:
```
    - Windows: C:\Program Files\Tableau\Connectors
    - Linux: /opt/tableau/connectors
```
Tacos in this directory will be picked up by all Tableau Sever processes on that machine by design. It's more future-proofed than the other option, and simpler since it's just the one directory instead of three. I'll have the documentation on the SDK updated to reflect this today most likely and the documentation on the public facing user documentation shortly thereafter.
