### ISSUE TITLE
Upgrading to Connection Dialog v2 - problems with schema discovery

### ISSUE THREAD

**Issue by luigidellaquila** [tableau/connector-plugin-sdk#937]
**About You:**
Company: Elastic

**Your question:**
I'm trying to upgrade our connector to use Connection Dialog v2.

Since we do not have a Schema, our connector has `<customization name="CAP_JDBC_SUPPRESS_ENUMERATE_SCHEMAS" value="yes"/>`

With Dialog v1 everything works fine and when the user logs in and clicks on a database, the corresponding table names are loaded and displayed.
Migrating to Dialog v2, even after clicking on the database name, no tables are displayed. I tried to debug it on our end and I see that no queries are being performed to load the table names.

Further investigating the configuration, I found that I can make Tableau display the tables only by disabling "database" and "schema" in the connection metadata.
Unfortunately this is not a solution for us, since it would impact some of the functionalities we have today with v1.

Is this a known problem?

Thanks

Luigi

**Comment by pvanderknyff** [comment]
Added to internal backlog

**Comment by rosswbrown** [comment]
For the scenario you describe, Database and Table are supported, I think the connectionMetadata.xml file would look like this:
```
<connection-metadata>
  <database enabled='true' label="Database" />
  <schema enabled='false' />
  <table enabled='true' label="Table" />
</connection-metadata>
```
Depending on the design of the JDBC driver this usually is enough to prevent the `getSchemas` call without needing to also add `<customization name="CAP_JDBC_SUPPRESS_ENUMERATE_SCHEMAS" value="yes"/>`

It may be helpful to share the Connection Dialog V1 file as well if this doesn't resolve the issue.

For reference [The Connection Metadata File](https://tableau.github.io/connector-plugin-sdk/docs/mcd#the-connection-metadata-file) doc section and the [postgres_jdbc](https://github.com/tableau/connector-plugin-sdk/tree/master/samples/plugins/postgres_jdbc) sample with a `connectionMetadata.xml`.

**Comment by rosswbrown** [comment]
Please add a note if you'd like to see this issue reopened, thanks.
