### ISSUE TITLE
Can I use the SDK to change custom SQL naming conventions?

### ISSUE THREAD

**Issue by CassidyMountjoy** [tableau/connector-plugin-sdk#939]
**About You:**
Name: Cassidy Mountjoy
Company: Blockpoint Systems

**Your question:**
I was testing my custom connector and wrote some custom SQL to generate a table. The physical table name looks like `Custom SQL Query`. Is there any way for me to change the default name using the SDK? 

- In essence the database doesn't support multi-word table names and I'm receiving a query like `SELECT Custom SQL Query.custom.station_name AS custom_station_name FROM...`.
- Additionally database syntax doesn't allow `.` in a column name either, so `custom.station_id` throws it off as well.
- This could be related to my `LocalConfig` in the ini, which custom SQL doesn't seem to be following because tablenameLower should lower case the physical table name right?

```[LogicalConfig]
Name = bsql_logical_query
fieldnameLower_underscore = True
tablenameLower = True
tablename = $dsName
tablePrefix = [testv1].```

**Comment by rosswbrown** [comment]
The Physical Table name is hardcoded to `Custom SQL Query` as you've observed. The product does allow customers to rename the table friendly name, however this does not change the physical name.

The dialect does support customizing the allowed form of the table name with `id-allowed-characters`, `id-case`, and `id-max-length`. 

In this case try adding `id-allowed-characters` ([sample](https://github.com/tableau/connector-plugin-sdk/blob/master/samples/components/dialects/Annotated.tdd#L1441), [XSD](https://github.com/tableau/connector-plugin-sdk/blob/master/validation/tdd_latest.xsd#L649)) that doesn't allow ` `  (space). This will cause `_` to be inserted to replace any disallowed character. Example: 
```
<id-allowed-characters value='abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789_' />
```

I'll open something to include this detail [here](https://tableau.github.io/connector-plugin-sdk/docs/dialect) as well. Thanks.

**Comment by CassidyMountjoy** [comment]
@rosswbrown My `id-allowed-characters values` doesn't include a space, OR any upper case letters, `Custom SQL Query` doesn't seem to be following my dialect at all. I'm attaching my dialect file.
[dialect.zip](https://github.com/tableau/connector-plugin-sdk/files/8445157/dialect.zip)

**Comment by rosswbrown** [comment]
I've confirmed the Custom SQL scenario is not using the mangled table name correctly as defined by the dialect. I'll open a defect internally to track this issue. Thanks for reporting it.

**Comment by rosswbrown** [comment]
This issue has been resolved in the May maintenance [releases](https://www.tableau.com/support/releases). The dialect definition will now be used as expected for Custom SQL.

**Comment by CassidyMountjoy** [comment]
@rosswbrown I can create another thread but I'm back to being confused on the sql that's being produced. Now that the `id-allowed-characters` is being respected by the Custom SQL table name, I'm left with `Remote Field Name` containing `.`  like `zustom______uery.firm_id`. This results in SQL like 
```
SELECT zustom______uery.zustom______uery.firm_id AS id, zustom______uery.zustom______uery.city AS zustom______uery_city 
FROM ( SELECT office.address1 AS address1, office.address2 AS address2, office.city AS city, office.firm_id AS firm_id, office.id AS
 id, office.min_voucher_amount AS min_voucher_amount, office.state AS state, office.sys_timestamp AS sys_timestamp, 
office.sys_xact AS sys_xact, office.zip AS zip FROM main.office office WHERE office.firm_id = 1 ) zustom______uery INNER JOIN 
main.firm firm ON zustom______uery.zustom______uery.firm_id = firm.id GROUP BY zustom______uery.zustom______uery.firm_id, 
zustom______uery.zustom______uery.city
```
Shouldn't the projections be `zustom______uery.firm_id`?
