### ISSUE TITLE
[BUG] Windows Defender Credentials Guard prevents Tableau to access Kerberos ticket due to outdated JDK 11.

### ISSUE THREAD

**Issue by leniartek** [tableau/connector-plugin-sdk#957]
**Describe the bug:**
Windows Defender Credentials Guard doesn’t seem to allow Java Development Kit (JDK) v11 to access the Kerberos ticket in windows cache.
- This is a known issue in various old JDK versions [OpenJDK](https://bugs.openjdk.java.net/browse/JDK-8161921)  [Oracle](https://bugs.java.com/bugdatabase/view_bug.do?bug_id=8161921)
- JDK v11 (Long Time Support) was released in September 2018
- Tableau Desktop comes bundled with JDK v11

**Potential solution:**
Use newer JDK version.  JDK 17 will be recommended as it is the latest LTS version, released in Sep 2021

**Questions:**
When can we expect Tableau Desktop release that bundles a newer JDK version?
How to configure Tableau Desktop to use a local installed JDK 17 instead of the 11 bundled one?

**Screenshots**
When trying to configure `TABLEAU_JAVA_HOME` to point at Java version higher then 11:
<img width="504" alt="Screenshot 2022-04-22 at 09 59 57" src="https://user-images.githubusercontent.com/10237525/165178301-04f0ef4f-5901-417d-9bf1-e622dea7d91e.png">

**Desktop**
 - **OS:** 
    - Windows 10 Enterprise Version: 20H2 Build: 19042.1415
    - Windows 10 Enterprise Version: 21H2 Build: 19044.1526
    - Windows 10 Enterprise Version 21H2 Build: 19044.1526
 - **Tableau Version:**
    - Tableau Desktop 2021.4.2

**About you:**
 Name: Piotr Leniartek
 Company: The LEGO Group, Starburst Data

cc. @sidwray @wangxinlei

**Comment by sxlin** [comment]
@leniartek This is a Tableau product enhancement request, not a Tableau Connector SDK issue.  I will forward the request to Tableau develop group in charge of this feature.

[Tableau Community Forum](https://community.tableau.com/s/ideas) is a better place to submit product ideas or enhancement requests.

**Comment by sxlin** [comment]
tfs-1404659

**Comment by maxfomenko** [comment]
@sxlin
Thanks. For the ticket number you shared: "tfs-1404659" Is there a public facing page where I can see this issue thread to follow the discussion and progress?

**Comment by pvanderknyff** [comment]
The ticket number is internal. Closing this issue since it is not related to the Tableau Connector SDK.

**Comment by leniartek** [comment]
Thanks @sxlin @pvanderknyff.
Can someone from `Tableau develop group` answer these questions?

```
When can we expect Tableau Desktop release that bundles a newer JDK version?
How to configure Tableau Desktop to use a local installed JDK 17 instead of the 11 bundled one?
```
