### ISSUE TITLE
TDVT support for Custom SQL Query TDS files

### ISSUE THREAD

**Issue by jayhomn-bitquill** [tableau/connector-plugin-sdk#959]
**About You:**
Name: Jay Ho
Company: Dremio

**Your question:**

Does TDVT support running tds files generated through a custom SQL query? If so, how would I set up the logical config since the "tablename" attribute in the "relations" element doesn't exist anymore? This causes the Staples smoke and logical tests to not run since the Staples smoke test is a logical tests and outputs an error (ie. "[Tablename] not found")

**Comment by pvanderknyff** [comment]
Hi Jay,

Using custom sql datasources for TDVT is not a scenario we've tested or plan to support. For logical tests, TDVT relies on the tablename attribute in the relation.

Can you provide more details on what the goal is for running TDVT through a generated custom sql query? There may be other workarounds.
