### ISSUE TITLE
Database impersonation in ODBC for postgres based connectors

### ISSUE THREAD

**Issue by cshrauder** [tableau/connector-plugin-sdk#961]
Hello, 

A few questions after reading about database impersonation here: 
https://tableau.github.io/connector-plugin-sdk/docs/auth-modes

The documentation states "This applies to databases that support a user(authenticated_user) that can delegate requests to another user(delegated_user) by enabling the client to pass a DelegationUID(delegated_user) to the database server"

What method is used at the database level?  In postgres for instance this would done with "set role". 
(https://www.postgresql.org/docs/current/sql-set-role.html)

To clarify, in this scenario a workbook would be published with stored credentials and authenticated to the database with those same credentials.  When a user accesses the workbook the user's username (odbc/jdbc username) is passed as the delegated_user and runs a "set role <delegated_user>."

Are these assumptions correct for how database impersonation works with a database like postgres?  

thanks, 
-Christian

**Comment by devanshsoni9** [comment]
I think your understanding is correct about how database impersonation works. The exact JDBC driver property for passing DelegationUID could be different for different databases. This property will have to be specified in the connector plugin [properties file](https://github.com/tableau/connector-plugin-sdk/blob/master/samples/scenarios/templates/db_impersonation/connectionProperties.js#L14). I am sorry that the example link is broken in the auth-modes wiki page. I will fix it.

**Comment by devanshsoni9** [comment]
Hi Christian
Here’s where we mention JDBC only for new connectors in the Tableau Exchange. 

> Note: The Tableau Exchange no longer accepts submissions of ODBC connectors. Only JDBC connectors are accepted.


https://tableau.github.io/connector-plugin-sdk/docs/gallery-submission

For Postgres JDBC I think passing `user` should work instead of DelegationUID, although I haven't tested it so can't say for sure.

```
 if (attr[connectionHelper.attributeTableauServerAuthMode] == connectionHelper.valueAuthModeDBImpersonate) {
        var str = attr[connectionHelper.attributeTableauServerUser];
        
        if (!isEmpty(str)){
            props["user"] = str;
        }
        
}
```

**Comment by cshrauder** [comment]
Ok thanks for the confirmation.
