### ISSUE TITLE
TACO modifications for Database Impersonation

### ISSUE THREAD

**Issue by cshrauder** [tableau/connector-plugin-sdk#968]
Hello, 

I've been working with Tableau SE Nate Bernache. We've been trying to get database impersonation working for a common customer.  He's been troubleshooting this for a week on a Tableau server we gave him access to and has run out of ideas.  He said I should post this problem here. We've modified our TACO file according to your samples for Postgres with very little modification to establish a working baseline.  We can user a standard postgres connector with our product and routinely do with other products. 
We modified the standard postgres sample with the connectionproperties.js files here:
https://github.com/tableau/connector-plugin-sdk/blob/master/samples/scenarios/templates/db_impersonation/connectionProperties.js

When we try to use the connector the user name published with the connection/dashboard is used and the JDBC username isn't passed in for a 'set role' command as expected.  Please let me know what logs or other detail you need for help. 

For reference: https://github.com/tableau/connector-plugin-sdk/issues/961

**Comment by devanshsoni9** [comment]
Hi @cshrauder 

In case of db-impersonation, we do not explicitly run a `set role` command. It is for the database to make sure database impersonation is going through. I think it will be wise to first figure out if postgres supports database impersonation. If it does, then maybe figure out what driver property needs to be set in place of DelegationUID.

**Comment by cshrauder** [comment]
@devanshsoni9

It appears impersonation via the DelegationUID variable was ported from Hive; however, I believe Postgres JDBC implements a set_role command. 
- Does the SDK support a "set_role" command?
- If not, can you please provide guidance on how to leverage impersonation on other data sources besides Hive/Impala?
- Are there other options/workarounds that we can explore to enable impersonation using username and password based on Postgres? 

Thanks, 
-Christian

**Comment by devanshsoni9** [comment]
You may look into [enable](https://tableau.github.io/connector-plugin-sdk/docs/capabilities.html#initial-sql) Initial SQL capability and then use `set_role` in conjunction with [TableauServerUser] parameter as described in this [article](https://help.tableau.com/current/pro/desktop/en-us/connect_basic_initialsql.htm). I guess you may also want to defer execution to Tableau Server using the <ServerOnly></ServerOnly> defer tags.

Let us know if it's not working per your requirements.

**Comment by cshrauder** [comment]
Thanks!  Will be trying this out shortly.

**Comment by cshrauder** [comment]
Thanks, in our internal testing doing a SET ROLE [TableauServerUser]; Seems to work.  Will be testing this on the customer system but this appears to work.  Thanks for the guidance!

**Comment by devanshsoni9** [comment]
Thanks @cshrauder, Closing this out.
