### ISSUE TITLE
Issues with expected/actual of the TDVT

### ISSUE THREAD

**Issue by zachikochman** [tableau/connector-plugin-sdk#987]
**About You:**
Name: Zachi Kochman
Company: SQream

zachik@sqreamtech.com
yotams@sqreamtech.com

**Your question:**

After running the TDVT tests,
I saw that we have failures in the date test,
I investigate it, and this is my conclusions :

* The upload data does not match the expected results.
* Looks like there is a switch between the expected & actual results in the reported doc.

I will explain with example:

date0 column in the Calc table include only dates (without time), this is the upload data from the tableau git:

![image](https://user-images.githubusercontent.com/37074900/178133080-c592718d-8f2d-4da3-a106-658f12c0bfa8.png)

Test name: logical.calcs.SQreamDBJDBC
include the following query:

SELECT TRUNC(CAST([Calcs].[date0] AS DATE)::DATETIME, day) AS [tdy_Calculation_2683863928708153344_ok]
FROM [public].[Calcs] [Calcs]
WHERE (TRUNC(CAST([Calcs].[date0] AS DATE)::DATETIME, day) IN ({ts '1972-07-04 00:00:00'}, {ts '1975-11-12 00:00:00'}))
GROUP BY 1

Which mean looking for entries of : 1972-07-04 & 1975-11-12

When running it on the tables Got the following:

![image](https://user-images.githubusercontent.com/37074900/178133290-63abec69-83c4-42d9-bf7e-63ce61e00bb8.png)

Now in the report we can see:

![image](https://user-images.githubusercontent.com/37074900/178133302-784828c6-478d-4201-92d9-0be82278cc3b.png)

So:
1. In the running query we get the same response as mentioned in the expected column ... so I think there is switch between expected & actual
2. The actual contains the time 22:00:00 this does not come from our running query , so probably this is the expected is with wrong data ?
3. All the date tests having conflict of 1 days, so look like the expected results (that display under actual) is wrong
1972-07-03 against 1972-07-04
1975-11-11 against 1975-11-12

Second example :

Test = expression.standard.SQreamDBJDBC

![image](https://user-images.githubusercontent.com/37074900/178133312-557a110d-962a-408f-905d-087e45bfbf07.png)

1. We have diff of one day
1972-07-03 against 1972-07-04
1975-11-11 against 1975-11-12
2004-04-14 against 2004-04-15
etc.

Our query return :

![image](https://user-images.githubusercontent.com/37074900/178133323-fe8c6e33-4093-4e32-b243-7be0cb5dbe24.png)

Which is the same as in expected .. but I don't know where they took the actual (again switch between actual-expected?)
And this is similar to the upload data

Thanks

**Comment by lukewrites** [comment]
Tracking ID: W-12315369 assigned to @lukewrites

**Comment by lukewrites** [comment]
Hi @zachikochman I'm trying to repro this locally against the current `master` branch of the SDK. I've tried breaking some expected files and running tests against them (in the below I removed a tuple from `expected.setup.calcs_connection_test.txt`), and I'm seeing the Actual and Expected values in the correct columns. Can you please confirm if you're still seeing that in the csv after pulling in master?
<img width="1208" alt="Screen Shot 2023-06-30 at 2 10 16 PM" src="https://github.com/tableau/connector-plugin-sdk/assets/5643640/0b8b2c0c-b93d-46f4-b103-e3e4e6ea3137">
