### ISSUE TITLE
Is it possible to package node modules into the TACO?

### ISSUE THREAD

**Issue by TLarson-Tableau** [tableau/connector-plugin-sdk#998]
**About You:**
Name: Tim Larson
Company: Tableau

**Your question:**
I am a TAM for one of our Premium Strategic customers. They have built their own connector with the SDK. For part of their solution, they have built one or more node modules to do some work. They are wondering if it is possible to package their node.js modules into the TACO.

I hope I am asking this question correctly, I don't really know how node.js fits into the SDK, if at all.

**Comment by pvanderknyff** [comment]
Hi Tim, 

The Connector SDK currently only supports driver-based connectors, which do not support node,js files, or node modules at all. While the SDK does have some javascript components, they are heavily limited in what they can do and have only basic logic required.

From your question, I suspect your customer is building a Web Data Connector, which has its own [github page](https://github.com/tableau/webdataconnector/issues). Web Data Connectors 2.0 do not package as .taco files, which is what is currently publicly available, Web Data connectors 3.0 do package as .taco files but that project is still in development.
